### ISSUE TITLE
AutoConfigure: Does inquire.js give us any benefit over prompt?

### ISSUE THREAD

**Issue by mrjoelkemp** [jscs-dev/node-jscs#1000]
Problems with prompt:

* Screen resizing visually breaks the output. May or may not be attributed to the lib.

**Comment by zxqfox** [comment]
It can simplify work with user input in cli. Less imperative checks, cleaner code.

**Comment by mrjoelkemp** [comment]
I'm not particularly inclined to swap out the prompt-displaying library for little gain. No one has complained yet about auto-configure's prompts. Closing this for now until the code really does become messy because of prompt.
