### ISSUE TITLE
AutoConfigure: Make it work for an es6 codebase

### ISSUE THREAD

**Issue by mrjoelkemp** [jscs-dev/node-jscs#1001]
From https://github.com/jscs-dev/node-jscs/pull/1022:

> ask the user which dialect?: es(3), es(5), es(6)

Then modify the generator's internal checker configuration appropriately.

**Comment by hzoo** [comment]
Do we still need to do this?

**Comment by mrjoelkemp** [comment]
Yes. 

1. We either always provide `esnext: true` in the generated config as an easy fix, 
2. or ask the user for the dialect, 
3. or deduce the dialect.

I think solution 2 is fairly straightforward to put into the config generator.

**Comment by mrjoelkemp** [comment]
Of course, we have no insight into the use of autoconfig. We don't know how many users are giving up when trying to use the tool to configure an es6 codebase. It doesn't hurt to add this though.

**Comment by markelog** [comment]
So we decided to remove global lang option, and let rule decide for themselves
