### ISSUE TITLE
AutoConfigure: Handle erroneous input

### ISSUE THREAD

**Issue by mrjoelkemp** [jscs-dev/node-jscs#1002]
* A user inputs a number (or char) that doesn't correspond to a preset's index in the table.
* A user does not enter `e` or `f` when handling violated rules

Possibly related #1000

**Comment by zxqfox** [comment]
Can Inquirer help to solve this? ;-)

**Comment by mrjoelkemp** [comment]
@zxqfox Linked that issue in the description. Thanks!

**Comment by mrjoelkemp** [comment]
Haven't received any complaints about the lack of error handling. Inclined to close this until we get a report.
