### ISSUE TITLE
excludeFiles doesn't work on windows

### ISSUE THREAD

**Issue by aju** [jscs-dev/node-jscs#1007]
Running from cli from project directory:
"excludeFiles": ["public/js/views/subviews/**"] - doesn't work

"excludeFiles": ["C:/Projects/XXXXXXX/public/js/views/subviews/**"] - works

**Comment by markelog** [comment]
Where is your config located?

**Comment by aju** [comment]
I'm using .jshintrc file and its located in C:/Projects/XXXXXXX/

**Comment by markelog** [comment]
`.jshintrc`? Not `.jscsrc`?

**Comment by aju** [comment]
.jscsrc :) sorry for mistake

**Comment by mikesherov** [comment]
@aju have you tried `"excludeFiles": ["./public/js/views/subviews/**"]`, also did you install `jscs` globally, or locally to your project?

**Comment by aju** [comment]
I tired globally and locally (node node_modules/jscs/bin/jscs PATH). I tried with "./" at beginning no luck :(

**Comment by zxqfox** [comment]
@aju Please provide `jscs -v`, I can't repeat that with `v1.11.2`

**Comment by aju** [comment]
1.11.2 win7 :(
Same files and same command on linux works as expected :/

**Comment by zxqfox** [comment]
Thanks. Feels like it will be hard.
Can you provide some additional information? Maybe spaces in path or something else?

**Comment by aju** [comment]
Fixed. I was testing on node 0.11.X (unstable) updated to 0.12 (stable) and it works :)
Sorry for all the fuss.

**Comment by zxqfox** [comment]
Nice to know! Interesting bug.

**Comment by aju** [comment]
Yeah - I think it was something wrong with cwd but haven't checked in details

**Comment by zxqfox** [comment]
Yea, looks like. Anyway, thanks for details and contribution. ;-)
