### ISSUE TITLE
differentiation between "default" in export and switch

### ISSUE THREAD

**Issue by alawatthe** [jscs-dev/node-jscs#1011]
Currently, the ```default```keyword in switch statements and export declarations is treated the same, although they are completely different. This creates a problem, as I want to enforce a line break before the switch default (via ```requireKeywordsOnNewLine```), but I don't want to have a line break between ```export``` and ```default```.

My suggestion for (require|disallow)KeywordsOnNewLine is to have ```default```only check the switch case and and introduce something like ```exportDefault``` to check the ```default``` in export declarations. So for my use case I would write something like:
```
{
  "esnext": true,
  "requireKeywordsOnNewLine": ["default"],
  "disallowKeywordsOnNewLine": ["exportDefault"]
}
```
Thoughts?

---

Minimal example:
```js
export default function fn (arg) {
    return 42;
}

switch (str) {
    case 'foo':
        console.log('foo');
        break;
    default:
        console.log('default');
}
```

I am using version 1.11.0 of jscs. And here is my ```.jscsrc```:
```js
{
  "esnext": true,
  "requireKeywordsOnNewLine": ["default"]  // errors on the export default
  // or
  "disallowKeywordsOnNewLine": ["default"]  // errors on the switch default
}
```

**Comment by mikesherov** [comment]
@alawatthe yeah, there's more than a few cases in which keywords are insufficient to describe the rule you're trying to achieve. We're working on it.

/cc @markelog @mdevils another case of keyword confusion :-\

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed
