### ISSUE TITLE
Cannot read property '_tokenIndex' of undefined in v.1.11.0

### ISSUE THREAD

**Issue by lencioni** [jscs-dev/node-jscs#1013]
Thanks for all the great work on this tool and congrats on the latest release. However, I just upgraded from 1.10.0 to 1.11.0 and ran into this error:

```
TypeError: Cannot read property '_tokenIndex' of undefined
    at Object.JsFile.getNextToken (/Users/joe/brigade/node_modules/jscs/lib/js-file.js:265:26)
    at /Users/joe/brigade/node_modules/jscs/lib/rules/require-space-before-object-values.js:53:37
    at Array.forEach (native)
    at /Users/joe/brigade/node_modules/jscs/lib/rules/require-space-before-object-values.js:43:29
    at Array.forEach (native)
    at Object.JsFile.iterateNodesByType (/Users/joe/brigade/node_modules/jscs/lib/js-file.js:379:42)
    at Object.module.exports.check (/Users/joe/brigade/node_modules/jscs/lib/rules/require-space-before-object-values.js:42:14)
    at null.<anonymous> (/Users/joe/brigade/node_modules/jscs/lib/string-checker.js:157:22)
    at Array.forEach (native)
    at StringChecker.checkString (/Users/joe/brigade/node_modules/jscs/lib/string-checker.js:155:35)
```

Removing this line from my .jscsrc file makes the error go away:

```
"requireSpaceBeforeObjectValues": true,
```

Here's some of my config that might be interesting?

```
  "fileExtensions": [".js", ".jsx"],
  "esnext": true,
  "esprima": "./node_modules/esprima-fb",
```

Let me know if I can provide any more info, or if there is something that I am doing wrong here.

**Comment by mikesherov** [comment]
Thanks for contributing! Can you please:

1. Provide the offending source file.
2. Try not providing a custom esprima?
3. Try passing `tolerant: false` as the esprimaOptions in your config?

**Comment by lencioni** [comment]
I whittled it down to this case:

```javascript
var myobj = {
  myfunc() {
    return null;
  }
};
```

It seems to be related to the ES6 object literal property value shorthand syntax. Removing custom esprima and adding `"esprimaOptions": { "tolerant": false },` had no effect.

**Comment by zxqfox** [comment]
Looks like `myfunc` in `{ myfunc() { return null; } }` doesn't evaluated as `shorthand`. Imo it should be fixed in esprima.

**Comment by mikesherov** [comment]
@zxqfox, can you file an ESPrima bug? http://github.com/jquery/esprima

**Comment by zxqfox** [comment]
@mikesherov Thanks ;-) done.
