### ISSUE TITLE
requireSpaceBetweenArguments to strict in 1.11.0

### ISSUE THREAD

**Issue by doberkofler** [jscs-dev/node-jscs#1025]
With the update to 1.11.0 the rule requireSpaceBetweenArguments became stricter and now complains if there is more then one space after an argument.

This change does no longer allow to align argument in multiple lines:
```
f1(100,	1,	2);
f2(1,	2,	3);
```

**Comment by hzoo** [comment]
Yeah we will need a relax/strict option for some of the whitespace rules for alignment. So most likely 
requireSpaceBetweenArguments and validateParameterSeperator? Similar to #927

Right now errors.assert.whitespaceBetween with the `spaces: 1` option is strictly 1 space for some rules.
