### ISSUE TITLE
AssertionError: disallowSpacesInsideParentheses option requires true or object value with "all" or "only" properties

### ISSUE THREAD

**Issue by wvankuipers** [jscs-dev/node-jscs#1027]
Hello,

In the latest version of JSCS (1.11.0) there seems to be an issue with the following rule:

    "disallowSpacesInsideParentheses": { "all": true }

This results in the following error:

    AssertionError: disallowSpacesInsideParentheses option requires true or object value with "all" or "only" properties

Changing the rule to:

    "disallowSpacesInsideParentheses": { "all": true, "only": false }

Resolves the issue.

I checked the file `node_modules/jscs/lib/rules/disallow-spaces-inside-parentheses.js` and the issue seems to be on line 53:

    50 if (typeof option === 'boolean') {
    51        assert(option === true, error);
    52    } else if (isObject) {
    53        assert('only' in option, error);
    54    } else {
    55        assert(false, error);
    56    }

The "all" option seems to be missing.

**Comment by mikesherov** [comment]
@wvankuipers, thanks for contributing! Looks like you just want to use `true` instead of `{all: true}`. 

Did this used to work?

**Comment by wvankuipers** [comment]
@mikesherov Yep, worked fine in 1.10.0

Will try `disallowSpacesInsideParentheses: true`, thank you!
