### ISSUE TITLE
`.getReporter()` should require node_modules packages

### ISSUE THREAD

**Issue by UltCombo** [jscs-dev/node-jscs#1030]
Reference: https://github.com/jscs-dev/gulp-jscs/pull/66#discussion_r24322672

Also, perhaps `.getReporter()`'s `reporter` argument could accept a function (which simply returns the function)? Then we wouldn't need to wrap `.getReporter` in the plugins.

**Comment by UltCombo** [comment]
Though accepting the function as argument is not really necessary, a simple `typeof` check in the plugins would be enough.

**Comment by zxqfox** [comment]
Oops. Totally agreed here.

**Comment by UltCombo** [comment]
:+1:

**Comment by markelog** [comment]
Oh, well can do this only in 2.0, since https://github.com/jscs-dev/node-jscs/issues/1150 is a breaking change ((
