### ISSUE TITLE
JSCS v1.11.0 reporting false positives for "Multiple var declaration"

### ISSUE THREAD

**Issue by mattgrande** [jscs-dev/node-jscs#1032]
I'm using JSCS (through gulp-jscs) to run codestyle checks on my code. I have the following function:

    function( activities, includeNormalScans, includeEmergencies, securityReports ) {
      if ( includeNormalScans && includeEmergencies ) {
        return activities;
      }

      if ( !activities ) {
        return activities;
      }

      var copy = activities.slice(0),
          i;
      for (i = activities.length - 1; i >= 0; i--) {
        if ( includeNormalScans === false && activities[i].type === 'scan' ) {
          copy.splice( i, 1 );
        }
        else if ( includeEmergencies === false && activities[i].type === 'emergency' ) {
          copy.splice( i, 1 );
        }
        else if ( securityReports === false && activities[i].type === 'incident' ) {
          copy.splice( i, 1 );
        }
      }
      return copy;
    }

... and JSCS is reporting this:

    Multiple var declaration at filters/activityFilter.js :
        15 |      }
        16 |
        17 |      var copy = activities.slice(0),
    --------------^
        18 |          i;
        19 |      for (i = activities.length - 1; i >= 0; i--) {

If I rollback to 1.10.0, it (correctly) parses this fine, but when I switch back to 1.11.0, I get this again.

**Comment by mikesherov** [comment]
@mattgrande what configuration option are you using?

**Comment by mikesherov** [comment]
I don't believe that this is a false positive. We had a false negative in 1.10. disallowMultipleVarDecls is designed to behave this way.

Please let me know if I'm wrong, and we can reopen.

**Comment by mattgrande** [comment]
This is my current config:

    {
      "preset": "airbnb",
      "disallowSpacesInsideParentheses": null,
      "safeContextKeyword": ["me", "vm"]
    }

There is only one `var` declaration in the function I posted (and several others that are now getting this message), unless you're saying you can only define one variable per function...

**Comment by mikesherov** [comment]
@mattgrande yeah, airbnb changed their mind about multiple var declarations. We updated the preset accordingly. If you want to allow multiple declarators per declaration, add this to your config:

``
disallowMultipleVarDecl: null
```

Thanks!
