### ISSUE TITLE
False positives for "requireCapitalizedComments"

### ISSUE THREAD

**Issue by ashclarke** [jscs-dev/node-jscs#1039]
I have a couple of seemingly-false positives coming up when validating my code with this rule.

![image](https://cloud.githubusercontent.com/assets/963023/6125197/808a85d6-b10b-11e4-9f37-8c4e5e2d2b98.png)

In each case, the block is about two lines however, in the final example, it is two, two-line textblocks.

Here's a copy-past of the last one:

```
// Calculate the position of the price point as a proportion of
            // the range.
            // Adjust by 50% to accommodate 0% being the minimum left value
            // for the containing html element.
            pricePosition = MIDPOINT + (priceDifference / range) * 100;
```

Note: I'm running Windows 8.1.

**Comment by alawatthe** [comment]
I can reproduce the bug with version 1.11.1 using the following .jscsrc

```js
{
    "validateIndentation": 4,
    "requireCapitalizedComments": true
}
```
The bug does however not occur, if I use any of these rules alone...

We actually have a test for comments like this, see [require-capitalized-comments.js#L57-L61](https://github.com/jscs-dev/node-jscs/blob/master/test/rules/require-capitalized-comments.js#L57-L61). But the test only sets ```requireCapitalizedComments``` and not ```validateIndentation``` in the config.

**Comment by ashclarke** [comment]
Nice spot! I can confirm I use 4 spaces for indentation.

**Comment by mrjoelkemp** [comment]
@ashclarke thanks for reporting! 

@alawatthe would you like to look into it?

**Comment by mikesherov** [comment]
@alawatthe what's the actual repro case please?

**Comment by alawatthe** [comment]
@ashclarke You can (temporarily) fix the problem yourself, by placing the ```validateIndentation``` rule *after* the ```requireCapitalizedComments``` rule in your jscsrc.

I found the problem: The validate indentation rule reorders the lines of the comment. E.g.:
Consider the comment
```js
// A textblock may also have multiple lines.
// Those lines can be uppercase as well to support
// sentense breaks in textblocks
```
The file object, which goes into the  ```validateIndentation``` rule has a ```comments```property like this
```js
"comments": [
  {
    "type": "Line",
    "value": " A textblock may also have multiple lines.",
    "range": [
      // ...
    ],
    "loc": {
      // ...
    }
  },
  {
    "type": "Line",
    "value": " Those lines can be uppercase as well to support",
    "range": [
      // ...
    ],
    "loc": {
      // ...
    }
  },
  {
    "type": "Line",
    "value": " sentense breaks in textblock",
    "range": [
      // ...
    ],
    "loc": {
      // ...
    }
  }
],
```
It somehow modifies the object such that the object afterwards looks like this (the location and range info are still correct, just the ordering in the array is different):
```js
"comments": [
  {
    "type": "Line",
    "value": " sentense breaks in textblock",
    "range": [
      // ...
    ],
    "loc": {
      // ...
    }
  },
  {
    "type": "Line",
    "value": " Those lines can be uppercase as well to support",
    "range": [
      ..
    ],
    "loc": {
      // ...
    }
  },
  {
    "type": "Line",
    "value": " A textblock may also have multiple lines.",
    "range": [
      // ...
    ],
    "loc": {
      // ...
    }
  }
],
```
i.e. requireCapitalizedComments thinks the comment looks like this:
```js
// sentense breaks in textblocks
// A textblock may also have multiple lines.
// Those lines can be uppercase as well to support
```
which should throw an error.


@mikesherov you are the master of ```validateIndentation```, would you like to have a look at this?

**Comment by alawatthe** [comment]
@mikesherov The Repro case:
```js
// A textblock may also have multiple lines.
// Those lines can be uppercase as well to support
// sentense breaks in textblocks
```
with jscsrc:
```js
{
    "validateIndentation": 4, // or any other value here
    "requireCapitalizedComments": true
}
```

The ordering is important! The following jscsrc is working:
```js
{
    "requireCapitalizedComments": true,
    "validateIndentation": 4
}
```

**Comment by mikesherov** [comment]
OH, duh. `reverse` is in place. Fix coming in a minute.

**Comment by alawatthe** [comment]
That was quick, nice work :-D

Perhaps we should (deep) freeze the file object, to prevent modifications or check if rules modify the file object...

**Comment by ashclarke** [comment]
:smile: :+1:

**Comment by zxqfox** [comment]
@ashclarke There were 3 rules affected by this bug:
- disallow-mixed-spaces-and-tabs
- maximum-line-length
- validate-indentation

So probably you have some of them before `requireCapitalizedComments` ;-)

**Comment by ashclarke** [comment]
Disallow mixed spaces and tabs :)
