### ISSUE TITLE
Integrate Performance Monitoring

### ISSUE THREAD

**Issue by mikesherov** [jscs-dev/node-jscs#1043]
- [ ] Find benchmarking framework like bestie/benchmarkjs
- [ ] write bin script that runs benchmarks
  - [ ] should attempt to check a large file like the jquery source code
  - [ ] should compare the benchmark against an upper limit (our budget)
  - [ ] should exit with an error if over the limit
- [ ] integrate benchmark bin script with travis
- [ ] note process by which we update our budget periodically (perhaps as a pre-release task)

**Comment by zxqfox** [comment]
Guys from travis denied continous benchs: https://github.com/travis-ci/travis-ci/issues/352

Anyway, we can make a static script that will calculate a par of server's performance and then just normalize the result timings of bench via these values: timing s1 / performance s1 vs timing s2 / performance s2, etc.

We can run bench for many of our current tests, just we should mark them somehow.

If we go this way we need some script that fills a lot of key performance factors for js that can change with different hardware.

**Comment by mikesherov** [comment]
@zxqfox, perhaps the way forward is to install the previous minor version of jscs and compare the current codebase against the latest release. This is then relative and immune to the "different hardware" problem.

**Comment by zxqfox** [comment]
@mikesherov Some tagged version? Or just previous? I'm afraid of different set of functionality. Can be hard to compare. ;-(

**Comment by markelog** [comment]
It was optional thing to do anyway
