### ISSUE TITLE
Add `except` option for RequireCapitalizedComments

### ISSUE THREAD

**Issue by ashclarke** [jscs-dev/node-jscs#1045]
Hello again!

This is a suggested feature to allow for certain exclusions to this rule, e.g:

```
"requireCapitalizedComments": {
    "allExcept": ["istanbul", "jshint", "jscs"]
}
```

[istanbul](https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md) | [jshint](http://jshint.com/docs/) - see Inline Configuration section | [jscs](http://jscs.info/overview.html#error-suppression)

This allows hint comments to be ignored.

What do you think?

**Comment by mrjoelkemp** [comment]
Great catch @ashclarke! We should totally do this.

Would you like to give this a go?

**Comment by ashclarke** [comment]
Shall I make jscs and jshint default exceptions?

**Comment by alawatthe** [comment]
I reported this feature in the past https://github.com/jscs-dev/node-jscs/issues/837, but completely forgot about it :-/

I am against making jscs and jshint (or any other values) default exceptions. Why? Because I don't want use inline comments for these two tools and want to get notified, when I do.

**Comment by zxqfox** [comment]
@alawatthe I'd say no. It's a kind of sugar, atm we almost done #109 about presets, and I believe that it could helps a lot with sugar making in common. At other hand, I'm agree with @alawatthe about discouraging defaults.

**Comment by alawatthe** [comment]
@zxqfox I am probably not seeing something obvious, but what has this bug to do with presets?
> I'd say no.

"No" to what? I'm a bit confused :-/

**Comment by ashclarke** [comment]
I have created a PR with the change. This is one of my first contributions to an established repository, so please offer suggestions and advice if it is A) terrible or B) lacking something!

**Comment by zxqfox** [comment]
@alawatthe It was a message to @ashclarke sorry. ;-)

I'm talking about defaults, and presets can help with that.

**Comment by alawatthe** [comment]
@zxqfox Ah, now I get it. No problem :-D
