### ISSUE TITLE
add -l option. List violating files.

### ISSUE THREAD

**Issue by morenoh149** [jscs-dev/node-jscs#1047]
I'm currently trying to add jscs to an existing codebase. I'm fiddling with options and would really love to know which files are problematic.

Feature Request: `jscs . -l` prints out a list of violating files. The number of infringements could be listed next to the filename as well or be optional.

**Comment by mrjoelkemp** [comment]
Hey @morenoh149. Thanks for contributing! Interesting idea.

The closest we have is the first step in [`--auto-configure`](https://github.com/jscs-dev/node-jscs/blob/master/OVERVIEW.md#--auto-configure-experimental) that shows you the number of errors generated from the given path for every preset. It then tells you the number of violated rules. That's not quite what you're asking for.

Maybe a new cli option like `jscs --summarize path` would work. For now this would output a format like:

`filename #Errors #ViolatedRules`

I'm not particularly sold on showing the number of violated rules, but it could be helpful. If someone wanted to know the violated rules, they could just run jscs on that particular file.

Would you like to give the implementation a go? We could really use the help. If you have questions on how to approach this and where to look, we're happy to help.

**Comment by mikesherov** [comment]
This can be implemented as a reporter called the summary reporter. Until then, @morenoh149, you can do:

`jscs -r inline <path> | grep ".js" | cut -d':' -f1 | sort | uniq -c` which should get you the info you want ;)

**Comment by mrjoelkemp** [comment]
@mikesherov Woah.

**Comment by morenoh149** [comment]
@mikesherov that's some strong unix-fu 👾

**Comment by mikesherov** [comment]
@mrjoelkemp @morenoh149 "With enough pipes, everything is possible."
