### ISSUE TITLE
Rule to require a $ prefix on jQuery variables

### ISSUE THREAD

**Issue by TheSavior** [jscs-dev/node-jscs#1049]
Many style guides have this rule:

```javascript
/**
 * Require a $ before variable names that are jquery assignments.
 *
 * Type: `Boolean`
 *
 * Values: `true`
 *
 *
 * #### Example
 *
 * ```js
 * "requireDollarBeforejQueryAssignment": true
 * ```
 *
 * ##### Valid
 *
 * ```js
 * var $x = $(".foo");
 * ```
 *
 * ##### Invalid
 *
 * ```js
 * var x = $(".foo");
 * ```
 */
```

**Comment by msikma** [comment]
It might be good to generalize this rule a bit. jQuery is far from the only library that uses the $ sign for its objects, e.g. Zepto is an alternative. Maybe the rule should be that this covers variables that were set through a $ function call. Possibly with an extra related option to also cover instances like `var $el = jQuery("element");`
