### ISSUE TITLE
Is disallowSpacesInsideBrackets a combination of ... ?

### ISSUE THREAD

**Issue by Deathspike** [jscs-dev/node-jscs#1051]
Is `disallowSpacesInsideBrackets` a combination of `disallowSpacesInsideArrayBrackets` and `disallowSpacesInsideObjectBrackets`? According to the documentation it is effectively the same as `disallowSpacesInsideArrayBrackets`? If not, what is the point of this rule? What does it do?

**Comment by mikesherov** [comment]
@Deathspike thanks for contributing! There is docs for each of these rules at http://jscs.info and a google group where you can ask further questions like this: https://groups.google.com/forum/#!forum/jscs-dev 

With that said:

`disallowSpacesInsideObjectBrackets` is incorrectly named and should be `disallowSpacesInsideCurlyBraces`.

`disallowSpacesInsideArrayBrackets` only warns on array expressions: `var a = [ 1, 2, 3 ];` and not member expressions: `a[0]` or `a['b']`.

`disallowSpacesInsideBrackets`catches both array expressions and member expressions!

Thanks again!
