### ISSUE TITLE
Need to decide what asserts to use for boolean rules

### ISSUE THREAD

**Issue by zxqfox** [jscs-dev/node-jscs#1060]
We have a lot of rules with double assertion: first with `typeof`, and the second with `=== true`.
As mentioned in many PRs it's overkill to use `typeof x === 'boolean' and x === true`.

The last PRs with double check:
https://github.com/jscs-dev/node-jscs/pull/1023/files#diff-3c958cdc2aa18d8507669afbc4372ee5R76
https://github.com/jscs-dev/node-jscs/pull/1028/files#diff-eb24b2408e3575c79b3b3bd2a596f8aaR40
https://github.com/jscs-dev/node-jscs/pull/1059/files#diff-572c6f5a08392c7fff2ce006ebf948ebR34
etc.

I propose to drop `typeof === 'boolean'` asserts in all rules.

What you think?

/cc @markelog @mikesherov @mdevils @mrjoelkemp

**Comment by mikesherov** [comment]
Yes, do it. However, we should be working on the declarative options feature anyway so this becomes an unnecessary discussion.

**Comment by hzoo** [comment]
Oh I guess https://github.com/jscs-dev/node-jscs/commit/9f09ee0b5389e2f4db4fe83175653b8e9f5306cf closes this? Didn't see this before.

**Comment by mikesherov** [comment]
Yup. Thanks!
