### ISSUE TITLE
Use yeoman/insight to collect usage stats of rules and features

### ISSUE THREAD

**Issue by mrjoelkemp** [jscs-dev/node-jscs#1064]
We currently have some insight into preset popularity based on the github traffic, but no insight into other valuable data-points: rule/preset usage; runtime errors; esnext adoption; and the use of various, big-effort, cli options like autoconfigure and autofixing. 

Should we use a 3rd party library (ex: Mixpanel, https://www.npmjs.com/package/universal-analytics for Google analytics, or another) to determine rules/presets/features that should be moved out of core and give us insight as to where to best devote our dev time?

The stats that we currently have:
![screen shot 2015-02-14 at 1 12 42 pm](https://cloud.githubusercontent.com/assets/865203/6200549/3bb9d20c-b44b-11e4-9ecc-a31b88ddd845.png)

Google Analytics is probably the best bet to keep things free at JSCS' scale.

Is there any hesitation from the community on having usage tracked?

**Comment by hzoo** [comment]
I think would be also cool to somehow notify people of new rules/options they can add to their `.jscsrc` after updating jscs - like a cmd command prompt for them to fix errors/add the new rule or null the rule. Of course they can check the patch notes but this would be easier. 

So it would be similar to the auto-generation of a config file but this would be if they already have a config and want to easily see what new things they would add to it.

**Comment by zxqfox** [comment]
Afaik it's pretty easy to do and we can just ask about it on first use. I'd like to have it in JSCS.

e.g. https://github.com/bower/bower/blob/0ce7053598bf8b79f059c61bdd7afab08497868b/lib/util/analytics.js

**Comment by mikesherov** [comment]
Would be cool when someone uses autoconfigure to ask them to send the final config to us.

**Comment by mdevils** [comment]
Nice idea @mrjoelkemp!
+1 to @mikesherov

**Comment by mrjoelkemp** [comment]
As stated by @markelog outside of this thread, we should use https://www.npmjs.com/package/insight to collect usage data.
