### ISSUE TITLE
Add idiomatic preset [$15]

### ISSUE THREAD

**Issue by markelog** [jscs-dev/node-jscs#1065]
It seems it's one of popular javascript "code styles" out there. 
It could be easily extended from jquery preset.

https://github.com/rwaldron/idiomatic.js

**Comment by mdevils** [comment]
+1 to this preset

**Comment by hzoo** [comment]
I'l give it a shot - although it doesn't seem to have a preference over some things like spaces/tabs - just that it should be consistent.

**Comment by ehartford** [comment]
Please pull this!  Needed!

**Comment by serg-io** [comment]
+1

**Comment by markelog** [comment]
Since you dealt with the bounty ticket last time :-)

**Comment by mrjoelkemp** [comment]
Henry can do it. I'm out of the country at the moment. Cc @hzoo
