### ISSUE TITLE
Error for es6 class method's on a single line

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1066]
An error for `disallowSpacesInAnonymousFunctionExpression` for `"beforeOpeningRoundBrace": true` with es6 class.
So it's only when it's a single line. (with `esnext` and `esprima-fb`).
```
Component = class {
  render() { return <div />; }
------------^
};
Component = class {
  render() { return func(); }
};
```

This is fine
```
Component = class {
  render() {
    return <div />;
  }
};
```

**Comment by mikesherov** [comment]
Does this happen without esprima-FB? (If you replace the JSX portion with a string?

**Comment by hzoo** [comment]
Yeah this errors as well `"esnext": true,` and without `esprima-fb`

```
var Component = class {
  render() { return 'asdf'; }
};
new Component();
```

**Comment by hzoo** [comment]
This could be for all 3 functionExpression rules then (named, anon, both)
I looks like the FunctionExpression is `{ return 'asdf'; }`
so functionToken = `{` and file.getNextToken(functionToken) = `return`
So it's checking assert whitespace of `{ and return`

So I don't know if it means `return` if parent is MethodDefinition or something - or we need to get the prevTokens to get to `render() `
