### ISSUE TITLE
Include bin in coverage?

### ISSUE THREAD

**Issue by mrjoelkemp** [jscs-dev/node-jscs#1067]
Our coverage report isn't completely correct: it doesn't include the `bin` directory in the coverage report. That won't result in a bit dip in coverage, but it does indicate that we don't have coverage on the logic in our binary.

1. Do we care about testing the binary's logic?
2. If so, should we pull the binary's logic into `lib/bin`?

**Comment by zxqfox** [comment]
> If so, should we pull the binary's logic into lib/bin?

Why not? ;-)

**Comment by mdevils** [comment]
@markelog take a look, please

**Comment by markelog** [comment]
There is no logic there, bin is purely declarative

**Comment by mrjoelkemp** [comment]
I'd think a test that ensures that the cli module is being passed the appropriate args would prevent accidental breakages – especially since our cli tests use the cli module directly and bypass bin. 

There isn't much in the binary though, so I'm fine if we'd like to continue omitting it from the coverage report.
