### ISSUE TITLE
Bring JSCS to Gulp

### ISSUE THREAD

**Issue by mrjoelkemp** [jscs-dev/node-jscs#1070]
Relevant discussion: https://github.com/gulpjs/gulp/issues/904

Any community members interested in tackling this?

**Comment by hzoo** [comment]
Can help - Is there going to be a gulp preset or node-style-guide preset as well?

**Comment by mikesherov** [comment]
I think the node style guide would be a great preset to add.

**Comment by mikesherov** [comment]
And then, at that point, it's just running `jscs --autoconfigure` on the codebase ;-)

**Comment by mrjoelkemp** [comment]
New issue created for the https://github.com/felixge/node-style-guide preset. @markelog usually has opinions on new presets, so we can discuss is there/here.

@hzoo Thanks for continuing to help. You're doing great work!

**Comment by markelog** [comment]
Closing in favour of #1071
