### ISSUE TITLE
Add node-style-guide preset

### ISSUE THREAD

**Issue by mrjoelkemp** [jscs-dev/node-jscs#1071]
https://github.com/felixge/node-style-guide

Related #1070

**Comment by markelog** [comment]
I guess #1070 could be closed in favour of this issue.

@felixge what is you thoughts about this? Would it be cool for jscs to have this?

**Comment by hzoo** [comment]
Ok just wrote it up.

Node Style Guide | .jscsrc
------------- | -------------
2 Spaces for indention | "validateIndentation": 2,
never mix tabs and spaces | "disallowMixedSpacesAndTabs": true,
UNIX-style newlines | "validateLineBreaks": "LF"
No trailing whitespace | "disallowTrailingWhitespace": true,
Use Semicolons | "disallowSemicolons": null (or no rule)
80 characters per line | "maximumLineLength": 80 (any exceptions?)
Use single quotes (except JSON) | "validateQuoteMarks": "'",
Opening braces go on the same line | "disallowNewlineBeforeBlockStatements": true,
whitespace before and after the condition statement | requireSpaceAfterKeywords and "requireSpaceBeforeBlockStatements": true,
Method chaining (one per line, indent once) | validateIndentation? #511?
Declare one variable per var statement | "disallowMultipleVarDecl": true,
Use lowerCamelCase for variables, properties and function names | "requireCamelCaseOrUpperCaseIdentifiers": true,
Use UpperCamelCase for class names | "requireCapitalizedConstructors": true,
Use UPPERCASE for Constants | **new**: "requireUppercaseConstants"
Use trailing commas | "requireTrailingComma": { "ignoreSingleLine": true }
short declarations on a single line | [ ]
Only quote keys when your interpreter complains | "disallowQuotedKeysInObjects": true,
Use the === operator | *use jshint/eslint eqeqeq*
Use multi-line ternary operator | **new**: "requireMultiLineConditional"
if (a === '') | "disallowSpacesInsideParentheses": true
Any non-trivial conditions should be assigned to a var/func | **new**: "maxConditionalLength"
Write small functions | **new**: "maxFunctionLineLength": 15
Return early from functions | [ ]
Name your closures | "disallowAnonymousFunctions": true ?
No nested closures | 
Use slashes for both single line and multi line comments | **new**: "disallowMultiLineComments"
// This function has a .. | "requireCapitalizedComments": true
Don't use Object.freeze, Object.preventExtensions, Object.seal, with, eval | "disallowKeywords": ["with"]

**Comment by zxqfox** [comment]
wow.

**Comment by zxqfox** [comment]
wow.

-------------------------
| From code | JSCS |
-------------------------
| // This function has a .. | "disallowSpaceAfterLineComment": true |

**Comment by hzoo** [comment]
Oh ok. and for the table

```
First Header  | Second Header
------------- | -------------
Content Cell  | Content Cell
```

**Comment by zxqfox** [comment]
Yeah, sorry. Here time to sleep already...

Node Style Guide | ...
------------ | -----------
short declarations on a single line | "disallowMultipleVarDecl": "exceptUndefined" ?
Write small functions | I think it's not about code style, it's more about complexity
Return early from functions | This idea walking around about half of a year, I'm strongly for adding a rule for it.
Don't use Object.freeze, etc | It'd be great to have a check for that. But is this code style?

**Comment by hzoo** [comment]
We do have `disallowKeywords` so that's similar in some sense to "Don't use" - but yeah not really code style.

**Comment by felixge** [comment]
@markelog sure, it'd be cool :)

**Comment by callumacrae** [comment]
Does this issue also include stuff like checking for complexity, returning early from functions, and the other things mentioned in https://github.com/jscs-dev/node-jscs/issues/1071#issuecomment-74583649 ?

This would be great! I'm a fan of node-style-guide :smile:

**Comment by callumacrae** [comment]
I'm potentially throwing a spanner in the works in felixge/node-style-guide#56. Sorry about that.

**Comment by hzoo** [comment]
I don't think we will include complexity checks as that's that that much of a style thing - I think you'll have to go with JSHint or ESLint for that (like the maxstatements rule in JSHint). I think we could think about a rule for returning early.

Also you can always extend the preset yourself if rules aren't added

```js
{
    "preset": "node-style-guide",
    "other-rule": true
}

**Comment by callumacrae** [comment]
Ah, didn't know I could extend presets! (I've never used one before) Thanks :)

**Comment by hzoo** [comment]
Oh ok - yeah presets are meant to be a starting point for your own ruleset so you don't have to read through a bunch of rules. But you might change it to fit your or your team's style more. You can also disable a rule using `null`.

```
{
    "preset": "jquery",
    "requireCurlyBraces": null
}
```

You can even check the .jscsrc for the project: https://github.com/jscs-dev/node-jscs/blob/master/.jscsrc

**Comment by zxqfox** [comment]
@hzoo It would be great to note that in docs somehow. I suggest to make an issue with global docs updating to collect some ideas.
