### ISSUE TITLE
disallowPaddingNewLinesInObjects is "incorrect"

### ISSUE THREAD

**Issue by mikesherov** [jscs-dev/node-jscs#1074]
right now it disallows all new lines inside an object expression. It should instead disallow **2 new lines** inside of object expressions.

**Comment by angelsanz** [comment]
Does this still apply? I don't think that's what it does at the moment - currently, it's disallowing any number of newlines between the opening brace and the remaining chunk of the object literal, and also between the closing brace and the previous chunk of the object literal.

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed
