### ISSUE TITLE
disallowSpacesInsideParentheses incorrect error

### ISSUE THREAD

**Issue by jfelchner** [jscs-dev/node-jscs#1077]
[Here](https://gist.github.com/jfelchner/ed0a17c445af755e77c8) is the `jscsrc` I'm using.

This code is throwing an error and it should not:

```
disallowSpacesInsideParentheses: Illegal space after opening round bracket at tests/helpers/start-app.js :
     4 |import config      from '../../config/environment';
     5 |
     6 |export default function startApp(attrs) {
-----------------------------------------^
     7 |  var application;
     8 |
```

I'm running with the `--esnext` option.

**Comment by hzoo** [comment]
I can't reproduce this on master and can reproduce using 1.10.
Maybe try updating jscs to a later version or checkout the master branch.

**Comment by jfelchner** [comment]
@hzoo I'm on 1.11.3

**Comment by hzoo** [comment]
Hmm I see.. I just downloaded 1.11.3 zip and tried it with 

```

export default function startApp(attrs) {
  var application;
}
```
I did `./bin/jscs ./test.js --esnext` and got the error
but I added `"esnext": true` to your .jscsrc and got no error...?

**Comment by hzoo** [comment]
Oh also this is a duplicate of #947.

**Comment by jfelchner** [comment]
@hzoo confirmed!  Adding `"esnext": true` to the `.jscsrc` fixes the problem.

Thanks!
