### ISSUE TITLE
requirePaddingNewlinesBeforeKeywords incorrect error

### ISSUE THREAD

**Issue by jfelchner** [jscs-dev/node-jscs#1078]
[Here](https://gist.github.com/jfelchner/ed0a17c445af755e77c8) is the `jscsrc` I'm using.

This code is throwing an error and it should not:

```
requirePaddingNewlinesBeforeKeywords: Keyword `function` should have an empty line above it at tests/helpers/start-app.js :
     4 |import config      from '../../config/environment';
     5 |
     6 |export default function startApp(attrs) {
-----------------------^
     7 |  var application;
     8 |
```

I'm running with the `--esnext` option.

**Comment by hzoo** [comment]
Hmm yeah this rule needs an exception for `function` since the previous token is `default`, and previous to that is `export`.

**Comment by mikesherov** [comment]
@jfelchner, thanks for contributing! This is also a dupe, although I can't find it at the moment. This will be solved at some point soon. Thanks again.

**Comment by hzoo** [comment]
I think it's similar to #1035
