### ISSUE TITLE
New Rule: Disallow Identical Destructuring Names?

### ISSUE THREAD

**Issue by iamdanfox** [jscs-dev/node-jscs#1081]
ES2015's destructuring assignment has a [shorthand form][1] - it would be cool if JSCS could flag up code that could be shortened by using this syntax.

For example, the new rule would flag up this code:

    var {left: left, top: top} = this.refs.container.getDOMNode().getBoundingClientRect();

But allow the following lines:

    var {left, top} = this.refs.container.getDOMNode().getBoundingClientRect();
    var {left: someName, top: otherName} = this.refs.container.getDOMNode().getBoundingClientRect();

[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Simple_example_2

**Comment by mikesherov** [comment]
@iamdanfox great idea. Any interest in implementing this feature? The only caveat is that the rule itself needs to check if it's in ES6 mode using `file.getDialect`.

**Comment by iamdanfox** [comment]
I'm afraid I'm completely new to the codebase, but might be able to try implementing it.

From looking through `lib`, would you recommend using `file.iterateNodesByType` with `VariableDeclarator`/`FunctionDeclaration`?

Presumably we'd then need to go through tokens of `node.left`?

**Comment by mikesherov** [comment]
@iamdanfox I'd imagine you'd want this to apply to all `objectExpressions`, no? so `file.iterateNodesByType` would work. Also, you don't **need** to implement this if you'd rather wait for us to get around to it. We just like asking issue contributors if they'd like to become code contributors to. Thanks again for contributing!

**Comment by iamdanfox** [comment]
The [MDN article][1] shows a lot of different variants (e.g. nested destructuring, within `for of` loops, as function parameters and computed object property names).

Going for the simple assignment case sounds look a good place to start.  Would `ObjectExpression` catch things like:
    
    var obj = {x: 1, y: 2};
    var x, y;
    {x: x, y: y} = obj;

I was wondering whether `AssignmentExpression` might be appropriate?

(I think it's probably sensible for me to let a more experienced contributor implement this - I can't really commit the time to produce something good!)

[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Object_destructuring

**Comment by jasonkarns** [comment]
I would add that as a user, I would expect a configuration option to this rule that allowed or disallowed mixing. For instance:

`var {left, top: topper} = ...`

Having this rule play nicely so that different combinations of the rule don't result in impossible-to-fix lint errors is important.

**Comment by AiOO** [comment]
How is this going?
