### ISSUE TITLE
Unify and introduce polymorphic require of external plugins

### ISSUE THREAD

**Issue by markelog** [jscs-dev/node-jscs#1083]
Talking about these tickets - https://github.com/jscs-dev/node-jscs/issues/109, https://github.com/jscs-dev/node-jscs/issues/1030. I think, they all (and `additionalRules`), should follow same logic as `plugins` options does - i.e. take path or name of the potential package dependency.

**Comment by mikesherov** [comment]
Yes! Would love to see this done.

**Comment by zxqfox** [comment]
:+1: YES
