### ISSUE TITLE
Consider Errors and jsFile modules public interfaces

### ISSUE THREAD

**Issue by markelog** [jscs-dev/node-jscs#1084]
Since it used in rules, which could be third party rules, we need to document and correctly semver them.

**Comment by zxqfox** [comment]
Moreover these "modules" widely used in plugins. ;-)

**Comment by hzoo** [comment]
Added to 3.0 - should be close or leave this open?

**Comment by mrjoelkemp** [comment]
Can we reference this PR as being fixed from a commit in 3.0? Ideally, this
wouldn't be closed until 3.0 is merged to master

**Comment by hzoo** [comment]
Yeah it doesn't get closed until a ref commit is merged to master. This is just something to keep in mind when doing 3.0 for semver/adding docs for APIs so people can make rules more easily.
