### ISSUE TITLE
Make `preset` more useful

### ISSUE THREAD

**Issue by sindresorhus** [jscs-dev/node-jscs#109]
re #54 

As it stands now `preset` isn't very useful as it only has the `jquery` style. Seeing as the config is fairly verbose it would be nice to have some ways to reuse it.

Would be useful if `preset` could have a searchpath in this order:

1. Check it with fs.exists if it's a valid path to a preset file
2. Try to require a node module with that name. Super useful for being able to distribute presets. Since `"main"` in package.json can be a .json file it could be the preset and requiring the module, would give you the preset config object.
3. the built-in preset.

**Comment by mikesherov** [comment]
Can we get this done in 1.12? /cc @mdevils @zxqfox seems we just need to do the original suggestion and can defer the question of loading multiple presets together to a different issue at a different time.

I'll assign @zxqfox for now just so someone owns this.

**Comment by markelog** [comment]
Can take this one if @zxqfox don't mind

**Comment by zxqfox** [comment]
@markelog Feel free! I wanted to have deep extension here if possible: https://github.com/jscs-dev/jscs-jsdoc/issues/83 . There were idea to split google (with closurecompiler specific tags), wiki (with other set), etc.

**Comment by mikesherov** [comment]
Yeah, sounds good to me too. Just trying to get old issues addressed.

**Comment by zxqfox** [comment]
I agree that we can solve original issue (according to current roadmap) and make another issue for future. Just need to know what we can solve here.

**Comment by mikesherov** [comment]
Ability to load a preset by use of `require` so that presets can be distributed via npm.

**Comment by zxqfox** [comment]
@mikesherov We already have `plugins` functionality and it's pretty simple to make it: https://github.com/zxqfox/jscs-bem/blob/master/lib/index.js

I can suggest defining "jscs" or "jscs-plugin" right in package.json with "presets" section if we need something more but it looks pretty complex.
```
{
  "jscs-plugin": {
    "presets": ["hey-ho", "lets-go"]
  }
}
```

We already have package.json usage: https://github.com/jscs-dev/node-jscs/blob/master/test/data/configs/mixedWithPkg/package.json

**Comment by markelog** [comment]
@zxqfox preset option might be simple alternative to the plugin interface, so it would be easy to share such configs without digging into the API.

But i agree, it looks like creating plugin is easy too.

@mikesherov thoughts? 
@sindresorhus would love to hear your opinion about that too.

**Comment by zxqfox** [comment]
@markelog I'm not against some sugar for presets. Feels like it would be very helpful for preset makers.

**Comment by markelog** [comment]
> I'm not against some sugar for presets

It might be, or it might be duplicative. Not sure

**Comment by mikesherov** [comment]
My opinion is the same as before, making a preset should be as simple as creating json file and publishing it to NPM.

**Comment by zxqfox** [comment]
So... Consumer's config (`.jscsrc` file or something) will be the same as before:
```
{
  "preset": "somepreset"
}
```

And `"somepreset"` will be searched on:
1. Installed node_modules list;
2. Registered presets list (by plugins or core).

Publisher should name his NPM-package with `jscs-preset-` (or `jscs-` and special flag in package.json, to differentiate with usual plugins), create JSON, and publish these 2 files (package.json, and his somepreset.json).

@markelog @mikesherov Please correct me if I wrong.

@markelog And feel free to take this ;-) I'll be back in a couple days.

**Comment by mikesherov** [comment]
I would think the publisher would name her package `jscs-my-wonderful-preset` and in `.jscsrc` put:

```
{
  preset: "jscs-my-wonderful-preset"
}
```

This way, there is no magic. 

But I'm also fine if we want JSCS to assume `jscs-preset-` prepended to the name so that the publisher of package `jscs-preset-behance` could just put the following in `.jscsrc`:

```
{
  preset: "behance"
}
```

**Comment by mrjoelkemp** [comment]
I'd modify Mike's example to avoid mentioning jscs all together, just to show that the prefix is unimportant:

```
{
  preset: "my-npm-module-name"
}
```

Where `my-npm-module-name` could be whatever you'd `require` the module as (ex: `require('my-npm-module-name')`. We'll try to register the custom preset and if it doesn't adhere to the code standard for custom presets, then it'll fail. Otherwise, it should pass without a problem.

**Comment by mikesherov** [comment]
@mrjoelkemp yes, that's what I meant in my first example.

**Comment by zxqfox** [comment]
@mrjoelkemp In that case we require some jscs-preset/-plugin field in NPM `package.json` file as well as `main` field for main js file. Also we can use some default file name value like `jscs-preset.js` (like `index.js` for `main`). I just don't want to have inconsistencies in `package.json` usage, but I think we'll fix them at review state.

Okay. I think need to make something to make this talk subjective.

**Comment by markelog** [comment]
@zxqfox i'd like to take over this one with https://github.com/jscs-dev/node-jscs/issues/1083.

**Comment by phanect** [comment]
@markelog Is this function implemented?
And available on latest release?

**Comment by markelog** [comment]
Nope, proposed pull for it, considered as not back-compat, so only in 2.0 :-(

**Comment by phanect** [comment]
@markelog OK, thanks.
Then we can get this feature on next major release.
