### ISSUE TITLE
Treat do while loops special for requirePaddingNewlinesBeforeKeywords

### ISSUE THREAD

**Issue by sdepold** [jscs-dev/node-jscs#1092]
When I enable `requirePaddingNewlinesBeforeKeywords` for the while keyword that makes totally sense for the following case:

```
var a = true;

while (a) {
  something();
}
```

Where it make not really sense is in the do while case:

```
do {
  something();
} while (a);
```

Having this in place will make jscs complain about the fact that there is no newline before `while`.

It would be great to turn off that rule for a do while loop.

**Comment by oredi** [comment]
@mikesherov should I look into this as well?

**Comment by mikesherov** [comment]
@oredi yes please! Although I think we should include new names for `do while` and `export default` to disambiguate them from `while` and `switch default`. @markelog @mdevils @mrjoelkemp thoughts?

**Comment by oredi** [comment]
@mikesherov  Sorry I got held up by my main job lately. It might be a couple of weeks before I can look into this. If it is still open then I will pick it up.

**Comment by oredi** [comment]
@mikesherov I took a look into the code for this rule today and I not sure about using new names since that will involve using a method other that iterateTokensByTypeAndValue. But I am toying with an implementation along this lines.  Please let me know the thoughts on this?

Current
    check: function(file, errors) {
        var excludedTokens = [':', ',', '(', '='];

        file.iterateTokensByTypeAndValue('Keyword', this._keywords, function(token) {
                var prevToken = file.getPrevToken(token);

                // Handle special case of 'else if' construct.
                if (token.value === 'if' && prevToken && prevToken.value === 'else') {
                        return;
                // Handling for special cases.
                } else if (prevToken && excludedTokens.indexOf(prevToken.value) > -1) {
                        return;
                }

Proposed 
    check: function(file, errors) {
        var excludedTokens = [':', ',', '(', '='];
        var specialCases = {  'if': 'else', 'export': 'default' }

        file.iterateTokensByTypeAndValue('Keyword', this._keywords, function(token) {
                var prevToken = file.getPrevToken(token);

                // Handle special case constructs.
                if (specialCases[token.value] === prevToken) {
                        return;
                // Handling for do special cases.
                } else if (token.value === 'while' && file.getNodesByFirstToken(token).length === 0  && prevToken.value === '}') {
                    return;
                // Handling for special cases.
                } else if (prevToken && excludedTokens.indexOf(prevToken.value) > -1) {
                        return;
                }
