### ISSUE TITLE
JSCS: Cannot parse invalid JavaScript

### ISSUE THREAD

**Issue by PerseusTheGreat** [jscs-dev/node-jscs#1093]
Hello there.
I am not good in English, so, I apologize in advance.

When I am running JSCS, sometimes it shows [JSCS: Cannot parse invalid JavaScript] error message.
I found that happens when my JS file has assignment expression like this: 
<code>var someVariable = this;</code>

Now I want to know:
1. Is there a JSCS rule that I could set it Off/On or change it in my custom preset file?
2. If this was my fault, may I ask you to guide me to a correct situation, please.
3. If this situation is a bug of Node-JSCS, may I ask you fix it a.s.a.p., please.

I am using Microsoft Visual Studio 2013 + Update 4 and <a href='https://github.com/madskristensen/WebEssentials2013' target='_blank'>Web Essantials 2013 plugin</a> by <a href='https://github.com/madskristensen' target='_blank'>Mads Kristensen</a> that run Node-JSCS over JS files to correcting JS code style and increasing JS code quality (I think).

Thanks to your attentions.

**Comment by mikesherov** [comment]
@PerseusTheGreat thanks for contributing! We'll need exact reproduction steps to determine if this is a bug. The best place to ask for support is on our mailing list: https://groups.google.com/forum/#!forum/jscs-dev

My guess is that you are using `this` outside of a place where it is valid to do so, but I can't tell without a full repro case, including which version number of jscs you are running. Please ask for help on our mailing list, and if a bug is discovered, come back here to file a new one.

Closing this for now. Thanks again!

**Comment by mugenkanosei** [comment]
I'm experiencing the same issue using Visual Studio 2013 Update 4 with Web Essentials 2.5.4. It appears that the Web Essentials is using version 1.8.0 of JSCS. I was able to reproduce using this code:
```javascript
(function ()
{
    function AngularController() {
        var vm = this;
    }
}());
```
Commenting out the `var vm = this;` allows JSCS to work.

This is a recommended pattern when creating an AngularJS controller as noted in the [AngularJS Style Guide](https://github.com/johnpapa/angular-styleguide#style-y032) by John Papa.

**Comment by mrjoelkemp** [comment]
@mugenkanosei Great find. Glad to hear it's fixable via the config. Still odd that the error message states that it's invalid javascript.
