### ISSUE TITLE
Feature Request: placement of dot in member expressions

### ISSUE THREAD

**Issue by golyshevd** [jscs-dev/node-jscs#1094]
Hi JSCS team!

We need the rule that validates placement of  `.` in member expressions, if the members are not on same line

line of object

```js
promise.
    then().
    then().
    then();

very.
    very
    ['very-deep'].
    property;
```

line of property

```js
promise
    .then()
    .then()
    .then();

very
    .very
    ['very-deep']
    .property;
```

Our codestyle explicitly describes the requirement of writing dot on new line (the second example), but we can't control it using jscs.

Are there any plans to make such rule?

/cc @markelog

**Comment by hzoo** [comment]
Is this is the same as https://github.com/jscs-dev/node-jscs/issues/511?

**Comment by golyshevd** [comment]
Yep, this is the same. Sorry for duplicate

> If so, there are plans!

Good news! =)

**Comment by duncanbeevers** [comment]
Is there an inverse of this rule? If I want to enforce the trailing-dot notation, I try using

```json
"requireOperatorBeforeLineBreak": true
```

But this generates no warnings for either of these code blocks.

```javascript
this.
  then(that);
```

```javascript
this
  .then(that);
```

Likewise, I get the same results when explicitly specifying the dot operator in the configuration.

```json
"requireOperatorBeforeLineBreak": ["."]
```

**Comment by hzoo** [comment]
I don't think we are regarding `.` as a operator the rule?
Related to #511: https://github.com/jscs-dev/node-jscs/issues/511#issuecomment-48851189

**Comment by duncanbeevers** [comment]
Yes, it appears not. I'll keep an eye on #511 for an eventual solution. Thanks.
