### ISSUE TITLE
WordPress VIP preset

### ISSUE THREAD

**Issue by paulschreiber** [jscs-dev/node-jscs#1099]
It would be helpful to have a WordPress VIP preset. Their style rules — based on jQuery — are here:
https://make.wordpress.org/core/handbook/coding-standards/javascript/

**Comment by hzoo** [comment]
Right now the Idiomatic (referenced in the wordpress style guide) preset i'm working on is also based on jquery. Shouldn't be too hard to add if we want to do this.

**Comment by hzoo** [comment]
WIP

Wordpress | JSCS
---------------|---------
base styles | jquery preset
indentation with tabs | `"validateIndentation": "\t"`
single quotes | `"validateQuoteMarks": "'"`
100 char limit is not strictly enforced | `"maximumLineLength": null`?
Any ! negation operator should have a following space | `requireSpaceAfterPrefixUnaryOperators: ['!']`

**Comment by paulschreiber** [comment]
@hzoo Thanks! I'm happy to help with this — let me know if I should start a new branch or if you have one already.

**Comment by hzoo** [comment]
Yeah I'l begin a PR soon so we can start adding rules

**Comment by markelog** [comment]
VIP?

**Comment by paulschreiber** [comment]
@markelog WordPress VIP is the paid-hosting version of WordPress. For PHP, the WordPress VIP coding standards add some additional rules to the WordPress coding standards. 
https://vip.wordpress.com/documentation/code-review-what-we-look-for/
https://vip.wordpress.com/documentation/code-and-theme-review-process/
https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards

For JavaScript, I don't think there are additional rules; we can refer to this as the "WordPress" preset.

@westonruter and/or @joshbetz can confirm if this is the case.

**Comment by westonruter** [comment]
> It would be helpful to have a WordPress VIP preset. Their style rules — based on jQuery — are here:
https://make.wordpress.org/core/handbook/coding-standards/javascript/

Note that these aren't WordPress.com VIP standards. They are *WordPress Core* standards. So the JSCS naming standard should reflect that. For PHP_CodeSniffer we have a “WordPress” superset standard library with all of the sniffs, and then we have subset standards for “WordPress-Core”, “WordPress-VIP”, and “WordPress-Extra”.

Just wanted to note as well that PHP_CodeSniffer supports tokenizing and applying sniffs to JS as well as PHP. Some of the sniffs in the WordPress-Coding-Standards project apply to JS files as well, though PHP has been the exclusive focus for that project thus far.

See also: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/39

**Comment by hzoo** [comment]
@westonruter Should this preset be `wordpress-core`, `wordpress`, or something else?

**Comment by westonruter** [comment]
Depends on how many rules you come up with. If you're specifically targeting the standards in the Core handbook, then `wordpress-core`

**Comment by hzoo** [comment]
Right now I've only started with https://make.wordpress.org/core/handbook/coding-standards/javascript/ since that was the original link that was given. I think we're open to whatever is needed - although I guess `wordpress-core` since it applies to more people?

**Comment by westonruter** [comment]
:+1:

**Comment by mrjoelkemp** [comment]
For the record, if this preset will only be used within wordpress core, then the jscsrc (i.e., wordpress preset) should live in that project – not maintained by jscs core.

Similar to `grunt`, if this preset will be used to enforce the wordpress style across all wordpress plugins, then the preset will be widely used and is a great candidate for inclusion in jscs core.

**Comment by paulschreiber** [comment]
@mrjoelkemp The preset would be useful to all WordPress theme and plugin developers, not just folks who work on WordPress core, and would be a great addition to jscs core.

**Comment by westonruter** [comment]
:+1: The WordPress Core coding standards should be used by themes and plugins as well, so it wouldn't be limited to the Core project itself: so yes should be used across all WordPress projects.

BTW, there is a `.jshintrc` in Core: https://core.trac.wordpress.org/browser/trunk/.jshintrc

**Comment by mrjoelkemp** [comment]
Sweet. +1 to this

**Comment by hzoo** [comment]
Great! I started a PR: #1105.

**Comment by westonruter** [comment]
Opened Trac ticket to get this added to WordPress Core: https://core.trac.wordpress.org/ticket/31823

**Comment by westonruter** [comment]
Also opened PR to add it to VIP Quickstart, as referenced above: https://github.com/Automattic/vip-quickstart/issues/414

**Comment by hzoo** [comment]
If you guys do add it to wordpress core (or even just run it on the codebase) - there will probably be a lot of changes needed to the preset (added and removed). Like https://github.com/jscs-dev/node-jscs/issues/1187 already.

So you can create an issue/PR about it so we can get it in - if there's differences because of jquery changes we could move the original jquery rules into wordpress so it doesn't depend on another preset if needed. (remove `"preset": "jquery"`).

Maybe it would be interesting to somehow not have to depend on jscs for the preset definitions (but that's probably a different thing altogether and maybe already discussed?).
