### ISSUE TITLE
Couple of outdated dependencies

### ISSUE THREAD

**Issue by cvrebert** [jscs-dev/node-jscs#1104]
* xmlbuilder
  * Currently using: `~2.5.0`
  * Latest: `2.6.1`
* glob
  * Currently using: `~4.3.5`
  * Latest: `4.4.0`

**Comment by mikesherov** [comment]
PR please! Thanks as always @cvrebert for contributing!

**Comment by hzoo** [comment]
This is fixed now from https://github.com/jscs-dev/node-jscs/commit/7d5696af9114db1dcd45585f0b559c3614f231b9
