### ISSUE TITLE
Request: disallowExtraNewLinesInsideObjectLiteral

### ISSUE THREAD

**Issue by yaycmyk** [jscs-dev/node-jscs#1108]
Valid:

````javascript
var a = {
    b: 'c',
    c: 'd'
};
````

Invalid:

````javascript
var a = {

    b: 'c',

    c: 'd'

};
````

Ideally, this would have an optional setting to only prevent extra newlines at the beginning and end of the object like this, perhaps `onlyStartEnd`:

Valid:

````javascript
var a = {
    b: 'c',
    c: 'd',

    d: {
        e: 'f'
    }
};
````

Invalid:

````javascript
var a = {

    b: 'c',
    c: 'd',

    d: {
        e: 'f'
    }

};
````

**Comment by mikesherov** [comment]
Yeah, we need this rule. Thanks for contributing!

**Comment by hzoo** [comment]
Going to be closing older/inactive issues and labeling with `orphaned` to track anything we might want to reopen again later (if we want to add it again or something has a PR). Thanks :smiley: !
