### ISSUE TITLE
Request: requirePaddingNewlinesAfterKeywords

### ISSUE THREAD

**Issue by yaycmyk** [jscs-dev/node-jscs#1109]
Valid:
````javascript
function() {
    var a = 'b';

    if (a === 'b') {
         // do something
    }

    a = 'c';
}
````
````javascript
function() {
    var a = 'b';

    if (a === 'b') {
         // do something
    }
}
````

Invalid:
````javascript
function() {
    var a = 'b';

    if (a === 'b') {
         // do something
    }
    a = 'c';
}
````

Same general options as `requirePaddingNewlinesBeforeKeywords`, but it would suppress the warning if the block was the last thing in the scope.

**Comment by mikesherov** [comment]
This is `requirePaddingNewlinesAfterBlocks`, which is an existing rule. If I've misunderstood the request, feel free to respond, but closing this for now.

**Comment by yaycmyk** [comment]
@mikesherov That one is not documented on http://jscs.info/rules.html, thanks for the heads up :)

**Comment by hzoo** [comment]
I think it's not on the website since there hasn't been a release (the rule is only in master now)
