### ISSUE TITLE
Request: requireSafeContextKeyword

### ISSUE THREAD

**Issue by yaycmyk** [jscs-dev/node-jscs#1110]
This would accept either `true` or an integer, with the integer being the number of uses of `this` before requiring use of the alias variable.

Valid:
````javascript
function x() {
    var that = this;

    that.x();
}
````
````javascript
// set to 2

function x() {
    this.x();
}

function x() {
    var that = this;

    that.x();
    that.y();
}
````

Invalid:
````javascript
function x() {
    this.x();
}
````
````javascript
// set to 2
function x() {
    this.x();
    this.y();
}
````

**Comment by mikesherov** [comment]
Thanks, we already have safeContextKeyword. Although, no option for number of uses, but we're not likely going to add that option, so I'm going to close this for now. Thanks again!

**Comment by yaycmyk** [comment]
@mikesherov Sure, this was more of a reach anyway :) I thought it would be a good addition, since it's a common pattern to use a `this` alias after more than one use to take advantage of minification. `this` can't really be minified on its own after all.

**Comment by mikesherov** [comment]
@yaycmyk, the advantage for minification typical goes away after gzipping though, considering how much gzip loves repetition. 

The use case for aliasing `this` is not for minification but rather for usage in other contexts without the use of bind.

**Comment by yaycmyk** [comment]
@mikesherov Valid. Thanks :)
