### ISSUE TITLE
Request: disallowSwitchCaseIndentation

### ISSUE THREAD

**Issue by yaycmyk** [jscs-dev/node-jscs#1111]
If this flag is true, then `case` statements should live at the same indentation level as their parent `switch`, a'la Crockford style.

Valid:
````javascript
switch (x) {
case 'b':
    break;
}
````

Invalid:
````javascript
switch (x) {
    case 'b':
        break;
}
````

**Comment by mikesherov** [comment]
The `validateIndentation` rule already tracks which style you use and then enforces future usages to be consistent with the first one, so I'm going to close this for now. Thanks again, and please explore the docs at http://JSCS.info

**Comment by yaycmyk** [comment]
@mikesherov Hmm, but what if the first instance it picks up is not the desired one?

**Comment by mikesherov** [comment]
@yaycmyk then you'll get a ton of errors in your codebase. I suppose we can always make this an explicit option too. Care to work on it?

**Comment by yaycmyk** [comment]
Sure, happy to!
