### ISSUE TITLE
Fix field in rule declaration

### ISSUE THREAD

**Issue by markelog** [jscs-dev/node-jscs#1113]
See discussion in https://github.com/jscs-dev/node-jscs/pull/1087#issuecomment-75753478

**Comment by markelog** [comment]
@mrjoelkemp @zxqfox @mikesherov @mdevils would like some reaction to this, there is some rules that could not be used with basic assertions without bloating amount of functions for this module.

**Comment by mikesherov** [comment]
@markelog want to talk about it after 1.12 is out. Sorry for delaying discussion, just have lots going on.

**Comment by zxqfox** [comment]
Sorry for delay, guys.

> But there doesn't seem to be many other needs for additional assertions, and I think the fear of an overblown is just that, fear.

:+1: 

> even if we add assertions to every rule in our codebase it wouldn't mean any external rule could use it. Which would mean auto-fixing wouldn't possible for the them.

:+1: 

> On the other hand, give users API to change your code is dangerous.

:+1:, but it's a fear ;-) If you using a plugin — ask plugin developer why it fails.

If you using JSCS as a plugin to IDE or Some smart editor — usually you have a choice to not save file and, moreover, cancel changes with Ctrl+Z/Cmd+Z.

What you think about Assertion API. Is it ready to be public?
