### ISSUE TITLE
[BUG] Allow for ES6 Destructuring in function arguments

### ISSUE THREAD

**Issue by NickPresta** [jscs-dev/node-jscs#1116]
Hello,

I'm writing some code that looks like this:

```js
class Foobar {
  myFunction({ body=null, method='GET', headers={} }) {
    console.log(body);
  }
}
```

But when I run `jscs` with the following `.jscsrc`:

```
{
    "preset": "grunt",
    "esnext": true,
    "esprima": "esprima-fb",
    "fileExtensions": [".js", ".jsx"]
}
```

I get the following:

```
Unexpected token = at src/javascript/myFile.js :
    36 |
    37 |  myMethod({
    38 |    body=null,
-----------------^
    39 |    method=null,
    40 |    headers={},


1 code style error found.
```

This feature is [valid ES6](http://babeljs.io/repl/#?experimental=true&playground=false&evaluate=true&loose=false&spec=false&code=class%20Foobar%20%7B%0A%20%20myFunction(%7B%20body%3Dnull%2C%20method%3D'GET'%2C%20headers%3D%7B%7D%20%7D)%20%7B%0A%20%20%20%20console.log(body)%3B%0A%20%20%7D%0A%7D) so I'm not sure what Rule or `esprima` options to apply to get this to pass.

This is especially frustrating because `jscs` doesn't seem to be following the `//jscs:disable` pragma so I can't wrap that line to ignore errors for now.

Any help is much appreciated. Thanks!

**Comment by hzoo** [comment]
JSCS does have inline comments http://jscs.info/overview.html#inline-comments - don't know if it's not working in that case. We're still adding support for ES6 so it might be a bug in the rule. Although if it says unexpected token then it's probable esprima doesn't support it yet.

**Comment by NickPresta** [comment]
@hzoo thank you for digging into this. I will watch the esprima ticket for a resolution. Feel free to close this ticket.
