### ISSUE TITLE
Ability to disable/suppress unexpected token errors altogether?

### ISSUE THREAD

**Issue by gsklee** [jscs-dev/node-jscs#1117]
Is it possible at all to disable/suppress unexpected token errors, so that JSCS can coexist with Babel's playground mode?

**Comment by gsklee** [comment]
Something other than magic comments, please.

**Comment by mikesherov** [comment]
@gsklee JSCS is beholden to the parser, which provides the AST to JSCS. In the case that the parser can't recover from an unexpected token, there is nothing JSCS can do here.

However, JSCS allows you to provide any esprima derative you want, like esprima-fb, the esprima harmony branch, espree, etc....

Find a parser that parses your code and JSCS can support it.

Thanks again!
