### ISSUE TITLE
Bug with indentation for multiline comments

### ISSUE THREAD

**Issue by royerboat** [jscs-dev/node-jscs#1121]
Getting a strange indentation error inside of a multi-line comment.

The following code that triggers the warning:
```js
/*
# this is a line
# this is another line
*/
var hello = "World";
```

Actual warning result:
```
validateIndentation: Multiline comments should not have tokens on its ending line at jscs-bug.js :
     1 |/*
     2 |# this is a line
----------^
     3 |# this is another line
     4 |*/


1 code style error found.
```
The validate config I'm using:
"validateIndentation": 4

**Comment by mikesherov** [comment]
@royerboat this will be fixed in the next release. Thanks for contributing!

**Comment by royerboat** [comment]
Glad to hear it! Thanks for responding so quickly!

**Comment by mikesherov** [comment]
This no longer triggers an error once 1.12 goes out, but we're still doing unsafe manipulations to the code when a `#` appears inside a multiline token like:

```
/*
#
*/
```

or 

```
var a = "\
#\
";
```

cc @markelog or @zxqfox  or @mdevils

**Comment by Reinmar** [comment]
Another test case:

```
   345 |  );
Multiline comments should not have tokens on its ending line at core/loader.js :
   227 |/*
   228 |foo
   229 |*/ // %REMOVE_LINE%
----------^
   230 |
```

Passes on master, throws on v1.11.3.

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
