### ISSUE TITLE
Add tests to verify whitespace fixes for rules

### ISSUE THREAD

**Issue by TheSavior** [jscs-dev/node-jscs#1127]
I have identified the following rules to need tests that verify whitespace fixes. 

 - [x] DisallowCommaBeforeLineBreak
 - [x] DisallowKeywordsOnNewLine
 - [ ] DisallowMixedSpacesAndTabs
 - [ ] DisallowMultipleLineBreaks
 - [x] DisallowNewLineBeforeBlockStatement
 - [x] DisallowObjectKeysOnNewLine
 - [ ] DisallowOperatorBeforeLineBreak
 - [x] DisallowPaddingNewLinesAfterBlocks
 - [x] DisallowPaddingNewLinesAfterUseStrict
 - [ ] DisallowPaddingNewLinesBeforeKeywords
 - [ ] DisallowPaddingNewLinesBeforeLineComments
 - [ ] DisallowPaddingNewLinesInBlocks
 - [ ] DisallowPaddingNewLinesInObjects
 - [ ] DisallowRightStickiedOperators
 - [ ] DisallowSpaceAfterBinaryOperators
 - [ ] DisallowSpaceAfterKeywords
 - [ ] DisallowSpaceAfterLineComments
 - [ ] DisallowSpaceAfterObjectKeysColons
 - [ ] DisallowSpaceAfterObjectKeys
 - [ ] DisallowSpaceAfterPrefixUnaryOperators
 - [ ] DisallowSpaceBeforeBinaryOperators
 - [ ] DisallowSpaceBeforeBlockStatements
 - [ ] DisallowSpaceBeforeKeywords
 - [ ] DisallowSpaceBeforeObjectValues
 - [ ] DisallowSpaceBeforePostfixUnaryOperators
 - [ ] DisallowSpaceBeforeArguments
 - [ ] DisallowSpacesInAnonymousFunctions
 - [x] DisallowSpacesInAnonymousFunctionExpression
 - [ ] DisallowSpacesInCallExpression
 - [ ] DisallowSpacesInConditionalExpression
 - [ ] DisallowSpacesInForStatement
 - [ ] DisallowSpacesInFunctionDeclaration
 - [ ] DisallowSpacesInFunctionExpression
 - [ ] DisallowSpacesInFunction
 - [ ] DisallowSpacesInNamedFunctionExpression
 - [ ] DisallowSpacesInsideArrayBrackets
 - [ ] DisallowSpacesInsideBrackets
 - [ ] DisallowSpacesInsideObjectBrackets
 - [ ] DisallowSpacesInsideParentheses
 - [x] DisallowTrailingComma
 - [x] DisallowTrailingWhitespace
 - [x] RequireAlignedObjectValues
 - [ ] RequireBlocksOnNewLine
 - [ ] RequireCommaBeforeLineBreak
 - [ ] RequireKeywordsOnNewLine
 - [ ] RequireLeftStickiedOperators
 - [ ] RequireLineBreakAfterVariableAssignment
 - [ ] RequireLineFeedAtFileEnd
 - [ ] RequireNewLineBeforeBlockStatements
 - [x] RequireObjectKeysOnNewLine
 - [x] RequireOperatorBeforeLineBreak
 - [x] RequirePaddingNewLinesAfterBlocks
 - [x] RequirePaddingNewLinesAfterUseStrict
 - [ ] RequirePaddingNewLinesBeforeKeywords
 - [ ] RequirePaddingNewLinesBeforeLineComments
 - [ ] RequirePaddingNewLinesInBlocks
 - [ ] RequirePaddingNewLinesInObjects
 - [ ] RequireRightStickiedOperators
 - [ ] RequireSpaceAfterBinaryOperators
 - [ ] RequireSpaceAfterKeywords
 - [ ] RequireSpaceAfterLineComment
 - [ ] RequireSpaceAfterObjectKeys
 - [ ] RequireSpaceAfterPrefixUnaryOperators
 - [ ] RequireSpaceBeforeBinaryOperators
 - [ ] RequireSpaceBeforeBlockOperators
 - [ ] RequireSpaceBeforeKeywords
 - [ ] RequireSpaceBeforeObjectValues
 - [ ] RequireSpaceBeforePostfixUnaryOperators
 - [ ] RequireSpaceBeforeBetweenArguments
 - [ ] RequireSpaceBeforeObjectValues
 - [ ] RequireSpaceBeforePostfixUnaryOperators
 - [ ] RequireSpaceBetweenArguments
 - [x] RequireSpacesInAnonymousFunctionExpression
 - [ ] RequireSpacesInCallExpression
 - [ ] RequireSpacesInConditionalExpression
 - [ ] RequireSpacesInForStatement
 - [ ] RequireSpacesInFunctionDeclaration
 - [ ] RequireSpacesInFunctionExpression
 - [ ] RequireSpacesInFunction
 - [ ] RequireSpacesInNamedFunctionExpression
 - [ ] RequireSpacesInsideArrayBrackets
 - [ ] RequireSpacesInsideBrackets
 - [ ] RequireSpacesInObjectBrackets
 - [ ] RequireSpacesInsideParentheses
 - [x] RequireTrailingComma
 - [ ] ValidateLineBreaks
 - [ ] ValidateParameterSeparator
 - [x] ValidateQuoteMarks

**Comment by zxqfox** [comment]
God! How you did this? ;-D

**Comment by TheSavior** [comment]
*sigh*...manually. 

I didn't think it would be that many so I kept being like...oh, I'm almost done. And then I got from disallow to require, and was like "shit, guess I can't stop here".

**Comment by mrjoelkemp** [comment]
Nice work!

**Comment by mdevils** [comment]
Wow)

**Comment by hzoo** [comment]
I guess you can check the 3 you finished in #1128!

**Comment by TheSavior** [comment]
Good call! Look at that progress! ;)

**Comment by hzoo** [comment]
Updated with more rules

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
