### ISSUE TITLE
Error when handling object destructuring + parameter default

### ISSUE THREAD

**Issue by gsklee** [jscs-dev/node-jscs#1130]
```javascript
function foo({opt1 = 100, opt2 = 200} = {}) {}
```

This is [valid ES6 syntax](http://babeljs.io/repl/#?experimental=true&playground=false&evaluate=true&loose=false&spec=false&code=function%20foo(%7Bopt1%20%3D%20100%2C%20opt2%20%3D%20200%7D%20%3D%20%7B%7D)%20%7B%7D) yet it throws the following error even with `"esnext": true`:

```
Error: Unexpected token = at es6.js :
     4 |    BaseClass;
     5 |
     6 |    function foo({opt1 = 100, opt2 = 200} = {}) {
--------------------------------^
     7 |    }
     8 |

```

**Comment by hzoo** [comment]
This is similar to #1116. From the research I did at the time, it seems like it's an issue with esprima not supporting the syntax at the moment.
