### ISSUE TITLE
False positive in # stripper cause weird artifact

### ISSUE THREAD

**Issue by Raynos** [jscs-dev/node-jscs#1137]
I have the following comment

```js
/*

## Section 1

Some text

## Section 2

Some more text

*/
```

jscs has a regex `source = source.replace(/^#!?[^\n]+\n/gm, function(str, pos) {` that strips my markdown header lines.

This causes an unexpected "multiple line break" error.

We should change the regex to support markdown headers.

**Comment by zxqfox** [comment]
I'm not sure how you can get `This causes an unexpected "multiple line break" error.` but agree with fixing this regex.

**Comment by zxqfox** [comment]
Unfinished test case that doesn't fail:
```js
it('should not report lines with #! at begin inside comments', function() {
    checker.configure({ disallowMultipleLineBreaks: true });
    assert(checker.checkString(
        '/*\n\n' +
        '## Section 1\n\n' +
        'Some text\n\n' +
        '## Section 2\n\n' +
        'Some more text\n\n' +
        '*/\n'
    ).isEmpty());
});
```

**Comment by Ppchiu** [comment]
can someone tell me why a '#!' would occur in a js file?

**Comment by zxqfox** [comment]
`#!/usr/bin/env node` at the first line to force a file to be called itself as a node argument.

**Comment by Ppchiu** [comment]
ohh, right. Thanks for the quick response!

**Comment by markelog** [comment]
Since we can't repro it, i'm closing this
