### ISSUE TITLE
requireLineBreakAfterVariableAssignment should have exception for declarations in for loops

### ISSUE THREAD

**Issue by blazarus** [jscs-dev/node-jscs#1157]
Currently the following code causes requireLineBreakAfterVariableAssignment to complain:
```
for (var i = 0, length = myArray.length; i < length; i++) {
...
}
```
I think it would make more sense if this style rule ignored variable declarations in the "init" portion of the for loop.

**Comment by mrjoelkemp** [comment]
Hi @blazarus. Thanks for contributing. 

This could be achieved by extending the rule with a value like `allExcept: ['ForStatement']`. Though, I'm not particularly sold on including the node type in the value. Any other suggestions using `allExcept`?

**Comment by zxqfox** [comment]
@mrjoelkemp I think we should handle this as special case since I can't remember what other keywords can contains `var`:
```
while (var i = 5) { break; }; // fail
do { break; } while (var i = 5); // fail
```

Do you?
As I see it's only allowed in `for`.

**Comment by blazarus** [comment]
Yeah, I agree with @zxqfox that it makes sense to handle this as a special case. Looking through [Mozilla's Parser API](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Parser_API), the node types we should be concerned about are ForStatement, ForInStatement, and ForOfStatement.

**Comment by mrjoelkemp** [comment]
What about users who want the current, strict version of the rule? We'd have to revert the special case and go with allExcept anyway. 

Is there any other valid configuration that avoids users having to type the 3 for loop node types?

**Comment by zxqfox** [comment]
@mrjoelkemp As far as I see it's a rare case. But this rule forces to make code like that (if I'm not wrong):
```
for (var i = 0, length = myArray.length; i < length; i++) {

  // ...
}
```

This is strange at least.

**Comment by mrjoelkemp** [comment]
I'm having a hard time discerning whether we're fixing a bug in the rule or creating an exception.

I only hesitate to avoid imposing our sense of style on users. 

@mikesherov or @markelog can you make the call?

**Comment by zxqfox** [comment]
Totally agreed.

**Comment by mikesherov** [comment]
Only an insane person wants a newline inside a for loop. Make it automatic, like we do in lots of other cases (e.g. we don't warn about missing curly in an else if). 



Mike Sherov
