### ISSUE TITLE
Checklist for things we are hoping to land before 1.12?

### ISSUE THREAD

**Issue by TheSavior** [jscs-dev/node-jscs#1158]
I've seen from other PRs some confusion from people outside of the core contributors what is on people's mind before releasing a new version and I know I'm having the same question. Is there any way we can get some more transparency into this? It definitely seems like we are getting close.

**Comment by mrjoelkemp** [comment]
Hey @TheSavior. Thanks for asking. This is a question better suited for the mailing list though. That said, we maintain a set of milestones: https://github.com/jscs-dev/node-jscs/milestones. We may not always hit every single item, but the milestones list the core team's priorities. 

We typically hold release-centric discussions transparently on the mailing list. There's very little non-public communication amongst the maintainers.

Hope that sheds more light. Feel free to repost on the mailing list.

**Comment by mrjoelkemp** [comment]
I should also add that we'd love help for the issues in the 1.12 milestone and any future milestones. Any help is appreciated. Thanks again for asking.

**Comment by TheSavior** [comment]
So...there is a mailing list? :P

**Comment by mrjoelkemp** [comment]
![screen shot 2015-03-10 at 11 03 40 pm](https://cloud.githubusercontent.com/assets/865203/6589670/bb0b166a-c779-11e4-9093-a2042b6191ea.png)

Yeah, the button on jscs.info is preeeeetty tiny :) Perhaps we should also add it to https://github.com/jscs-dev/node-jscs/#more-about-jscs? Mind fixing that or suggesting a better place?

**Comment by hzoo** [comment]
Adding it to `more-about-jscs` sounds good to me since it'll be in the repo readme if no one see's it on the website.
