### ISSUE TITLE
Test targets explicitly provided which are listed in `.jscsignore`

### ISSUE THREAD

**Issue by zxqfox** [jscs-dev/node-jscs#1159]
1. `git` doesn't add files by default even if they targeted explicitly, paths to which are listed in `.gitignore`: `echo 'something' >> .gitignore; git add something`;
2. `jshint` (more importantly) act the same as git and doesn't check explicitly provided targets if they are listed in `.jshintignore`;
3. `jscs` atm has `excludedFiles` (as analogue `.jshintignore`/`.gitignore`), but it checks explicit targets since `v1.5.6` — inconsistency at my pov.

Can we rethink that and go `jshint`/`git` way?

/cc @markelog @mikesherov @mdevils @mrjoelkemp @hzoo @indexzero

**Comment by hzoo** [comment]
Sounds good to me - JSHint also lets you do `jshint . --exclude-path .gitignore`
