### ISSUE TITLE
requireSpacesInConditionalExpression should not prohibit using new lines around "?" and ":"

### ISSUE THREAD

**Issue by Reinmar** [jscs-dev/node-jscs#1160]
We use the following setting:

```
	"requireSpacesInConditionalExpression": {
		"afterTest": true,
		"beforeConsequent": true,
		"afterConsequent": true,
		"beforeAlternate": true
	},
```

In previous JSCS versions the following code was correct, but now JSCS throws errors.

```
prop: test ?
		foo
	:
		bar
```

In my opinion new lines should count as spaces or should prevent spaces validation at all. Now it's inconsistent, because rules like "requireSpacesInsideArrayBrackets" do not throw when new lines were used inside array brackets.

**Comment by zxqfox** [comment]
Thanks for contribution. :+1: for not reporting this as an error.

**Comment by Reinmar** [comment]
So you don't find the inconsistency between rules like "requireSpacesInsideArrayBrackets" and "requireSpacesInConditionalExpression" to be a bug?

**Comment by hzoo** [comment]
This is really old now, but I can't reproduce on jscs 2.2.1 with the rule/snippet anymore. Going to close - let me know if you can still reproduce @Reinmar
