### ISSUE TITLE
"requireSpacesInsideArrayBrackets" fails to notice a comment

### ISSUE THREAD

**Issue by Reinmar** [jscs-dev/node-jscs#1161]
We use:

```
"requireSpacesInsideArrayBrackets": "all",
```

In JSCS 1.10.0 the following code started throwing errors:

```
var keystrokes = [ CKEDITOR.CTRL + 90 /*Z*/, CKEDITOR.CTRL + 89 /*Y*/, CKEDITOR.CTRL + CKEDITOR.SHIFT + 90 /*Z*/ ]
```

The error:

```
One space required before closing bracket at plugins/undo/plugin.js :
    12 |
    13 |( function() {
    14 | var keystrokes = [ CKEDITOR.CTRL + 90 /*Z*/, CKEDITOR.CTRL + 89 /*Y*/, CKEDITOR.CTRL + CKEDITOR.SHIFT + 90 /*Z*/ ],
-------------------------------------------------------------------------------------------------------------------^
    15 |  backspaceOrDelete = { 8: 1, 46: 1 };
```

I understand that it's a tricky case, but for some reason it worked before, so perhaps it could work again.

**Comment by zxqfox** [comment]
Seems like this space doesn't checked in 1.10, because comments wasn't tokens.

It looks false positive because there are spaces in array brackets.

@hzoo Am I right?

/cc @mikesherov

**Comment by hzoo** [comment]
Yeah it's ignoring the comment so the whitespace > 1.

if we do
```js
var beforeClose = file.getPrevToken(closeBracket);
// to
var beforeClose = file.getPrevToken(closeBracket, {includeComments: true});
```
beforeClose will be a comment with type Block it that case and it passes.

**Comment by zxqfox** [comment]
Ah, :+1: for adding `includeComments`.
