### ISSUE TITLE
Multi-line function declaration parameters

### ISSUE THREAD

**Issue by bramcordie** [jscs-dev/node-jscs#1164]
Jetbrians' IDE have the following options for function declaration parameters:
- align when multi-line
- new line after __(__
- place __)__  on new line

When all set to true it  gives me the formatting I'm looking for:
```javascript
function someFunctionDeclaration(
  aBunch,
  ofArguments,
  thatDontGo,
  onOneLine
) {
}
```
Is there a similar rule for jscs to format my code this way?

**Comment by hzoo** [comment]
I don't think there's currently anything like that so it would be a new rule. We don't currently have a lot of alignment rules yet - I think the only one so far is `requireAlignedObjectValues`.

so maybe the name could be `requireAlignedFunctionParameters`? and probably an option for the minimum number of parameters to check for alignment (maybe you think its ok to have < 2 parameters on a single line so

```js
// good
function(a, b)
function(
  a,
  b,
  c
)
// bad
function(a, b, c)
```

**Comment by bramcordie** [comment]
My use-case is not so much about the number of parameters but more so the length when you line them all up. Lining them up or going multi-line (when you exceed your line limit) is by choice and should both be possible. If you go multi-line you do have to be consistent and put new lines after and before your round brackets.
```javascript
// good
function(short, and, sweet) {}
function (
  thisIs,
  theLongestList,
  ofParametersEverWritten
) {}
// bad
function (thisIs,
          theLongestList,
          ofParametersEverWritten) {}
```

**Comment by hzoo** [comment]
Yeah ok an option for the `maximumLineLength` (or using the value from the `maximumLineLength` rule itself if that's possible) could be used instead.

**Comment by zxqfox** [comment]
My 5 cents:
```
requireAlignedFunctionParameters: {
  alignment: "indent"|"firstParameter",
  multiline: <boolean>,
  maximumLineLength: <number>
}
```

I'm not sure about names but I think different styles has different rules for this case.

`alignment` will rule:
```js
function (
  thisIs,
  theLongestList
) {}
// vs
function (thisIs,
          theLongestList) {}
```

`multitline` will rule:
```js
function (thisIs, theLongestList) {
}
// vs
function (
  thisIs,
  theLongestList
) {}
```

And I think we need also a some `sticky` flag to rule newlines about parentheses.
```
function (thisIs,
  theLongestList) {}
// vs
function (
  thisIs, theLongestList
) {
}
```

**Comment by bramcordie** [comment]
@zxqfox Aligning parameters is only relevant when you multi-line. You can either be a little more verbose and explicitly mention this in the rule name or just assume it, e.g.: `requireAlignedMultilineFunctionParameters` or `requireAlignedFunctionParameters`

For your second example, a separate rule to disallow multi-lining might be more appropriate: `disallowMultilineFunctionParameters` (this may create awkward situations when you exceed your line length)

You always align if the rule is set so I would replace the `alignment` option with `lineBreakAfterOpeningBraces` to accommodate your first example.

My proposition:
```javascript
requireAlignedFunctionParameters: {
  lineBreakAfterOpeningBraces: <boolean>,
  lineBreakBeforeClosingBraces: <boolean>
}
```

**Comment by zxqfox** [comment]
Yeah, probably you're right. To decide wisely we need to know about real use cases.

**Comment by TheSavior** [comment]
This rule needs tests that verify that it fixes properly. Using `assertHelpers.reportAndFix` is probably the best choice.
