### ISSUE TITLE
In esprima tolerant mode, display all esprima tolerant errors as JSCS errors

### ISSUE THREAD

**Issue by mikesherov** [jscs-dev/node-jscs#1165]
Right now, we only log parse errors from Esprima, when we should be logging all errors from esprima when in tolerant mode, including strict violations.

**Comment by schempy** [comment]
If nobody is working on this I'd like to give it a try. If it's available could you provide an example where Esprima is giving an error that's not from parsing?

Thanks!

**Comment by schempy** [comment]
The following will produce an error 'Octal literals are not allowed in strict mode.'  

```js
function f() {
  var a = 021;
}
```
The error is only in the tree object during the call to [parseJavaScriptSource](https://github.com/jscs-dev/node-jscs/blob/master/lib/js-file.js#L1052).

Is that the type of error you'd like to log?

Thanks!

**Comment by markelog** [comment]
In 3.0 esprima will not gonna be used anymore
