### ISSUE TITLE
ES6 Template Literals And "require-spaces-inside-object-brackets"

### ISSUE THREAD

**Issue by chadhietala** [jscs-dev/node-jscs#1171]
I ran into an interesting issue with the "require-spaces-inside-object-brackets" rule when using ES6 template literals.

For example this will cause a JSCS error:

```
var id = 1;
var url = `www.example.com/${id}/profile`
```

It seems like this rule should not be applied within strings.

For more detail about the specific error see https://github.com/emberjs/ember.js/pull/10637

**Comment by hzoo** [comment]
Hmm this shouldn't be an issue since the rule is checking for an `ObjectExpression`. If `esnext` is enabled esprima should parse it as a `TemplateLiteral` (and I see it is enabled in the ember `.jscsrc`. Can you try testing on master or a later release of jscs?

Going to look into it more.

**Comment by mikesherov** [comment]
@chadhietala what version of JSCS are you using? 1.11 correctly only does Objects, where as 1.10.* did all curlies.

**Comment by mikesherov** [comment]
Also, this is dependent on a bug in esprima which will be fixed in the next release.

**Comment by chadhietala** [comment]
@mikesherov Yea Ember is using an older version. Will bump and report back.

**Comment by chadhietala** [comment]
@mikesherov Yes this appears to be effected by the Esprima bug. I bumped everything up to the latest and I still get the error.

**Comment by nevir** [comment]
You can work around it by depending on his pull request branch on esprima,
and setting "esprima": "node_modules/esprima" in your jscsrc

**Comment by hzoo** [comment]
yeah as per @nevir
package.json
```js
"esprima": "mikesherov/esprima#templateStrings"
```
.jscsrc
```js
"esprima": "node_modules/esprima"
```
but I dono if that works that easily since its broccoli-jscs?

**Comment by hzoo** [comment]
Can close this now?

**Comment by mikesherov** [comment]
Yes @hzoo thanks!
