### ISSUE TITLE
Spaces in generator declarations/expressions

### ISSUE THREAD

**Issue by geigerzaehler** [jscs-dev/node-jscs#1175]
If you use generators and JSCS’s `esnext` option, the behaviour is counter-intuitive.

~~~json
{
  "esnext": true,
  "requireSpacesInAnonymousFunctionExpression": {
    "beforeOpeningRoundBrace": true
  }
}
~~~

~~~js
var f = function* () {}
~~~
This shows the “Missing space before opening round brace“ error. The following doesn’t.

~~~js
var f = function *() {}
~~~

Moreover, with the `requireSpaceAfterKeyword` option set to true, the following is also an error.
~~~js
function* f () {}
~~~

**Comment by zxqfox** [comment]
Yeah, nice idea! Thanks for contributing

**Comment by hzoo** [comment]
Should this be a bunch of new rules like `requireSpacesInGeneratorFunctionExpression`? Something similar would be to check the location of the `*` for
```
function * ()
function* ()
function *()
function*()
```

**Comment by mikesherov** [comment]
right, seperate rule for generator `*` because they can show up in a few unexpected places.

**Comment by zxqfox** [comment]
For me it's pretty close to `requireSpacesInConditionalExpression` with their `afterTest`/`beforeConsequent`.

But if we look further and reach ES7's `async function * name ()` we can also try to group up all of them to `requireSpacesInFunctionExpression` options. Just a thought.

**Comment by hzoo** [comment]
Going to at least fix the function spacing rules - we can add the generator spacing rule later.

I guess it since we check beforeRoundBrace then instead of checking `function(` vs `function (` we check `*(` vs `* (`
