### ISSUE TITLE
Parse error on const in switch

### ISSUE THREAD

**Issue by mzgol** [jscs-dev/node-jscs#1176]
```js
const x = 3;

switch (x) {
  case 1:
    const a = x;
    break;
}
```
Error: `Unexpected token const`, points at the `const` declaration inside of switch. Checked on the playground: http://jscs.info/demo.html

**Comment by zxqfox** [comment]
I'm afraid that it's from esprima; not sure but don't see `Unexpected token` in code base.
https://github.com/jquery/esprima/blob/0b3658b7fddd05b4140fcbeacca56b2c6d7596e2/esprima.js#L168

**Comment by hzoo** [comment]
If its the playground - it's probably because the playground doesn't have an option for esnext. With `esnext": true` it looks like it works fine locally.

**Comment by mikesherov** [comment]
Agreed. @mzgol, let me know if you're experiencing otherwise and I'll reopen.

**Comment by mzgol** [comment]
OK, I got confused as I knew we used `const` inside `switch` blocks even without enabling `esnext`. Turns out we had it wrapped in curlies which makes the error go away:
```js
switch (x) {
  case 1: {
    const a = 2;
    break;
  }
  default:
    break;
}
```
Is this an intended behavior with `esnext` disabled? Seems weird.

**Comment by mikesherov** [comment]
@mzgol, `let` and `const` aren't completely baked in Esprima `1.*`, which is what we use when `esnext` is not `true`.
