### ISSUE TITLE
Unexpected token :  for json files

### ISSUE THREAD

**Issue by malsup** [jscs-dev/node-jscs#1177]
I see this error for every json file I test.  Even for a simple file:

    { "jscs": "test" }

**Comment by zxqfox** [comment]
Emh, as far as I know JSON is not valid JS (except empty ones: `{}`, `[]`).

Can I ask why you need to check JSON files with JSCS?

**Comment by malsup** [comment]
I don't really.  I just assumed it would work without really thinking to hard about it.  :-)

**Comment by zxqfox** [comment]
@malsup Np. If you using it with explicit call on target you can take a look at #1159
Each vote counts! ;-)

**Comment by adambuczynski** [comment]
Stumbled upon this as well... You'd expect the linter to be able to handle JSON files as well, like jshint does. In my gulp process, I just lint all JS and JSON files in one stream. Had to add `"**/*.json"` to my excludeFiles in .jscsrc to prevent this error.

**Comment by hzoo** [comment]
Thanks for the feedback @adambuczynski - maybe we can just exclude `.json` by default then?

**Comment by adambuczynski** [comment]
I think so, since it's causing errors anyway, might as well.
