### ISSUE TITLE
Add icons/logos of JSCS users to main page

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1178]
(Because the list is getting long)

Previous discussion: https://github.com/jscs-dev/node-jscs/pull/1149

**Comment by hzoo** [comment]
Should we close this and move this issue to the website repo?

**Comment by mdevils** [comment]
I think we can have the logo at README as well

**Comment by hzoo** [comment]
Or we can do it like Babel https://babeljs.io/users/

**Comment by markelog** [comment]
I guess we just need to do it and improve iteratively. Any takers?

**Comment by hzoo** [comment]
http://eslint.org/ has a cool/similar thing to babel as well - Can just make an issue asking for company/project name, homepage, license, logo (svg?) and broadcast it.

**Comment by markelog** [comment]
> Can just make an issue asking for company/project name, homepage, license, logo (svg?) and broadcast it

Ask who? Most of those logos are in public domain and accessible, i guess google search should do the trick 

@escaton Do you want to take this one?

**Comment by hzoo** [comment]
This could be moved to the website repo

**Comment by markelog** [comment]
Most of it should

**Comment by hzoo** [comment]
Ok moving to the other repo: https://github.com/jscs-dev/jscs-dev.github.io/issues/44
