### ISSUE TITLE
New rule: maximumNumberOfLines

### ISSUE THREAD

**Issue by alawatthe** [jscs-dev/node-jscs#1181]
Since I really dislike files with several thousand lines of code, I'd like to have a rule in which I can specify the maximal number of lines a file can have. 

Maybe this rule should have an option to not count empty lines or comments. 

Any opinions?

**Comment by zxqfox** [comment]
5 cents: It's very close to limiting cyclomatic complexity or nesting conditional blocks. Should we? Or better to move this to jshint?

I mean it's not really stylistic thing. But I'm not against.

**Comment by alawatthe** [comment]
Good point @zxqfox. However the related rules in jshint and eslint act on a function basis, meaning, a very long file with lots of simple functions would pass the check. Which is not really what I want.

**Comment by zxqfox** [comment]
@alawatthe Yep! That's why I'm not against ;-)
