### ISSUE TITLE
disallowSpaceBeforeBinaryOperators doesn't alow , but it is used in Crockford preset

### ISSUE THREAD

**Issue by SteveALee** [jscs-dev/node-jscs#1185]
The Crockford preset contains the lines

```json
"disallowSpaceBeforeBinaryOperators": [
        ","
    ],
```

(see https://github.com/jscs-dev/node-jscs/blob/master/presets/crockford.json#L44-L46)
which causes this error

> The value of property "disallowSpaceBeforeBinaryOperators" was "," but must be one of the following values: "?", "+", "-", "/", "*", "=", "==", "===", "!=", "!==", ">", ">=", "<", "<=", null

This is slightly confusing as the listed operators are not "binary" as defined in the ECMAScript spec. (eg &&). Even more confusing the documentation includes the comma operator "'," in the example (see http://jscs.info/rules.html#disallowspaceafterbinaryoperators).

I tested by copying the raw preset contents to a .jscsrc file used by WebEssentials in VisualStudio

**Comment by SteveALee** [comment]
If the message means option means a Mathematical 'binary operator" (see http://en.wikipedia.org/wiki/Binary_operation) as it appears to then I think comma be included in the set .

**Comment by SteveALee** [comment]
Actually I then get a bunch of unsupported rule errors

JSCS: Unsupported rule: requireSpaceBetweenArguments
JSCS: Unsupported rule:  disallowSpaceBeforeBinaryOperators
JSCS: Unsupported rule: requireSpacesInForStatement

So I conclude that either the Crockford preset is out of date OR the WebEssentials implementation is.

**Comment by zxqfox** [comment]
Well:
https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/require-space-between-arguments.js
https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/require-spaces-in-for-statement.js

I really don't know what is wrong there but rules are in place and crockford preset looks fine.

Can you look at version you using? These rules are pretty fresh (3 dec '14, and 15 jan '15).

**Comment by zxqfox** [comment]
Oh. Probably you just trying to use rules that weren't published at the moment. If so it's ok ;-) And thanks for contribution!

**Comment by SteveALee** [comment]
Surely in theory it would only be used the settings from the Crockford template in the project .jscsrc?

**Comment by zxqfox** [comment]
Summoning @markelog as the great master of presets.

Btw. @SteveALee how you using presets? Via `preset` option or by manual copying it to `.jscsrc`? I still can't get how you've got these errors.

**Comment by SteveALee** [comment]
Copy and pasted into the new file in VS13 from 
https://raw.githubusercontent.com/jscs-dev/node-jscs/master/presets/crockford.json

**Comment by SteveALee** [comment]
I created a downstream issue too - 
https://github.com/madskristensen/WebEssentials2013/issues/1816

**Comment by zxqfox** [comment]
Yeah, okay. That's why you have these errors. Some of rules in master doesn't exist in JSCS bundled with VS13 (or WebEssentials).

For further usage: `{ "preset" : "crockford" }`. It will load this file for ya and won't fail because we synchronising presets and rules.

**Comment by SteveALee** [comment]
Ah, yes that makes sense. Can you the add extra rules in the file after that "preset".

Can I suggest that  you add a note to
http://jscs.info/overview.html#presets

Thanks very much

**Comment by zxqfox** [comment]
Yeah, we need to do something with this.

http://jscs.info/overview.html#presets vs http://jscs.info/overview.html#preset

**Comment by SteveALee** [comment]
Almost but not quite. There are still some version dependencies you can;t quite escape. I'll stick to by patched version of crockford preset for now. heh

> The value of property "preset" was "crockford" but must be one of the following values: "jquery", "google"

**Comment by SteveALee** [comment]
Almost but not quite. There are still some version dependencies you can;t quite escape. I'll stick to by patched version of crockford preset for now. heh

 > The value of property "preset" was "crockford" but must be one of the following values: "jquery", "google"

**Comment by SteveALee** [comment]
I looked at submitting a pull request for jscs-dev.github.io but have got a little lost.
It seems the dev branch creates master, from MD source files in a folder /jcsc but i cannot find those.
Strangely they DO seem to exist in he root this repo. files.

Do I just submit a PR for the OVERVIEW.md in this repo?

**Comment by markelog** [comment]
> Do I just submit a PR for the OVERVIEW.md in this repo?

Yep
