### ISSUE TITLE
WordPress: disable requirePaddingNewLinesBeforeLineComments

### ISSUE THREAD

**Issue by paulschreiber** [jscs-dev/node-jscs#1187]
Disable the requirePaddingNewLinesBeforeLineComments rule for the WordPress preset.

**Comment by paulschreiber** [comment]
@hzoo

**Comment by hzoo** [comment]
Oh is `requirePaddingNewLinesBeforeLineComments` from jquery? I can do a PR to null it (or you can go ahead of you want). Don't know when it be available unless we do a 0.12.1 to fix presets? Otherwise users would need to tag to the specific commit.

**Comment by mrjoelkemp** [comment]
Seems patch worthy.

**Comment by hzoo** [comment]
@paulschreiber Ok did the PR, although I was looking at the wordpress handbook - https://make.wordpress.org/core/handbook/coding-standards/javascript/#comments. In the comments section - it says `Comments come before the code to which they refer, and should always be preceded by a blank line.`

**Comment by paulschreiber** [comment]
Hmm. Maybe this is a (different) JSCS bug, then. The problem I had was lines with trailing comments:
```
$foo = 1; // comment
```
...would have their comments moved elsewhere.

**Comment by hzoo** [comment]
Is this an autofix issue? Or if its a rule - then you can use `--verbose` to check the rule name and we can look at it.

**Comment by paulschreiber** [comment]
Yes — autofix (`-x`) was causing this.

**Comment by hzoo** [comment]
Ok great our first auto fix issue! We will need to figure out a minimal test case (which could be difficult). Maybe some of the rules are having issues with not taking into account comments?

**Comment by TheSavior** [comment]
It sounds like this is #1194

**Comment by paulschreiber** [comment]
@TheSavior That does sound right.

**Comment by markelog** [comment]
Okay, so not disabling it, but fixing `requirePaddingNewLinesBeforeLineComments` rule.

Although i would consider changing the example in the doc from

```js
function foo( types, selector, data, fn, /* INTERNAL */ one ) {
    // Do stuff
}
```
to 
```js
function foo( types, selector, data, fn, /* INTERNAL */ one ) {
    
   // Do stuff
}
```
Just like it was done in jQuery code-style, or changing this rule value to `"allExcept": "firstAfterCurly"`
