### ISSUE TITLE
requireLineBreakAfterVariableAssignment doesn't handle 'let' or 'const'

### ISSUE THREAD

**Issue by blazarus** [jscs-dev/node-jscs#1190]
When running with `esnext` set to true, `let a = 'b', c = 'c';` and `const a = 'b', c = 'c';` are not caught, while `var a = 'b', c = 'c';` is correctly caught.

Looking at the code for the rule, it is explicitly checking for `var`:
```
if (thisDeclaration.parentNode.kind === 'var') { ... }
```
Seems like `let` and `const` need to be added to this if statement.

**Comment by hzoo** [comment]
Yeah sounds good to me. Also any other rules if they are checking `kind === 'var'`.

**Comment by blazarus** [comment]
Thanks for addressing this so quickly!

Quickly grepping through the code, it looks like require-multiple-var-decl specifically has checks for 'var' and 'const' but not 'let'. Not sure if that's intentional or not, though.
