### ISSUE TITLE
Document "-x" and "-auto-configure" options

### ISSUE THREAD

**Issue by markelog** [jscs-dev/node-jscs#1192]
They might deserve additional sections even.

/cc @mdevils, @mrjoelkemp, @mrjoelkemp, @zxqfox 

No ones like to write docs :-)

**Comment by hzoo** [comment]
`--auto-configure` is kind of documented already in OVERVIEW.md - probably need a longer explanation of what it does. http://jscs.info/overview.html#cli. And we can remove the (experimental) part.

**Comment by markelog** [comment]
Yeah, you right
