### ISSUE TITLE
requirePaddingNewLinesBeforeLineComments should not consider code and comment on the same line

### ISSUE THREAD

**Issue by TheSavior** [jscs-dev/node-jscs#1194]
There should be an option to allow this to be valid:

```javascript
var x = 'foo'; // jshint ignore:line
```

Right now it will complain that it needs to be preceeded by a new line.

There is already a configuration for an allExcept:

```
"requirePaddingNewLinesBeforeLineComments": {
  "allExcept": "firstAfterCurly"
}
```

allExcept should probably be an array. 

```
"requirePaddingNewLinesBeforeLineComments": {
  "allExcept": ["firstAfterCurly", "inlineComments"]
}
```

Thoughts?

**Comment by mikesherov** [comment]
I think we can just say that if the line comment isn't the first token on the line, no error. No need for a new option here. Thanks for reporting @TheSavior !

**Comment by TheSavior** [comment]
I figured that is how I would check if `allExcept: "inlineComments"` was set. You are saying that we should just change the default behavior?

I could see changing the default being okay if used in conjunction with a rule like ` `requireLineCommentsOnNewLine`. Do we have a rule like that?

**Comment by hzoo** [comment]
There's https://github.com/jscs-dev/node-jscs/issues/651 `validateCommentPosition`

**Comment by markelog** [comment]
Okay, so #651 is our guy then

**Comment by TheSavior** [comment]
I believe this should still be open. The default for this rule should be changed so that it doesn't error on any line comment that isn't on it's own line. 

This can then be used in conjunction with #651

**Comment by markelog** [comment]
Oh, all right, thanks for the clarification
