### ISSUE TITLE
Difference between disallowSpacesInsideArrayBrackets and disallowSpacesInsideBrackets?

### ISSUE THREAD

**Issue by TheSavior** [jscs-dev/node-jscs#1198]
I can't tell the difference between these two rules. `arrayBrackets` seems to comment on a rule that is deprecated that `brackets` still uses. Does that imply that the rule was renamed and we somehow ended up with a copy?

**Comment by hzoo** [comment]
I think this was part of this discussion: https://github.com/jscs-dev/node-jscs/issues/923. I think `requireSpacesInsideArrayBrackets` is only on arrays and disallowSpacesInsideBrackets is for all `[]`?

**Comment by fluidsonic** [comment]
These rules seem to be broken at the moment.

We use the configuration below to require this format:
```js
var a = [ 1, 2 ]  // spaces required in array creation
var b = a[0]      // spaces forbidden for array/object access
```
In the first line, jscs both requires and forbids the use of spaces so there's no way to validate the code.

`.jscsrc`:
```json
{
	"disallowSpacesInsideBrackets": true,
	"requireSpacesInsideArrayBrackets": "all"
}
```

`test.js`:
```js
'use strict'

var a = [ 1, 2 ]
var b = [1, 2]
```

Output:
```
Illegal space after opening bracket at test.js :
     3 |var a = [ 1, 2 ]
-----------------^
     4 |var b = [1, 2]

Illegal space before closing bracket at test.js :
     3 |var a = [ 1, 2 ]
----------------------^
     4 |var b = [1, 2]

One space required after opening bracket at test.js :
     3 |var a = [ 1, 2 ]
     4 |var b = [1, 2]
-----------------^

One space required before closing bracket at test.js :
     3 |var a = [ 1, 2 ]
     4 |var b = [1, 2]
---------------------^
```

**Comment by markelog** [comment]
@fluidsonic we will try to release a patch with a fix for this bug soon, let's move this discussion in https://github.com/jscs-dev/node-jscs/issues/1319
