### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by jacksonrayhamilton** [jscs-dev/node-jscs#1199]
Abbreviations can be troublesome.

- They can make code harder to understand.
- When abbreviations intersect, they can be ambiguous.
  - "element" can be shortened to "elem", "elm", "el" or "e", and "error" can be shortened to "err" or "e". Which "e" are we talking about? When we say "elm" are we talking about elm trees, or even [Professor Elm](http://bulbapedia.bulbagarden.net/wiki/Professor_Elm)?
  - "directory" can be shortened to "dir", but "direction" can also be shortened to "dir". I have written games in JS where this abbreviation collision actually became an issue.
- It can be exhausting to try to think up new abbreviations, and the decision to choose one over another is rather arbitrary.
- An abbreviation can't be distinguished from a misspelling, and as we all know, misspellings are sources of errors.
- Abbreviations take about half a second less time to type. But with the word auto-completion plugins that modern IDE's are outfitted with, writing long identifiers usually only takes 2-3 characters plus tab. And we are no longer limited to 80-character displays / punchcards, like in the early days of programming; we have word wrap, if newlines can't keep our lines short enough. So there is no practical advantage to abbreviating words.

The simple solution to these issues is to require that all words used in source text be real words. I think it would be valuable for JSCS to validate the spelling of identifiers.

Acronyms like HTTP, URL, etc, can be permitted, because acronyms have defined meanings, whereas abbreviations are only sometimes defined, or only known colloquially.

It is always within a developer's power to properly spell a variable or function parameter correctly. Sometimes he may need to interface with 3rd-party API's that don't spell words correctly, in which case it should be possible define spelling exceptions for certain property names.

You could use wordlists from [SCOWL](http://wordlist.aspell.net/) or some other dictionary. When the dictionary falls short, it should be possible to extend it with new words (which could be used as identifiers AND properties). This is especially important for domain-specific acronyms.

"Words" can be derived from identifiers according to casing; so `theQuickBrownFox` and `jumps_over_the_lazy_dog` could both have their words parsed. If you decide to capitalize your acronyms, like `appURL` vs `appUrl`, then parsing could be tricky when single-letter words like "I" or "a" (as in `beAGreatPerson`) are encountered. JSCS might want to enforce (or assume) that acronyms not be capitalized so that they can be identified as "words."

I recommend against adding common programming-isms like "app", "dir", "config", "src" et al to the default dictionary. By default, the dictionary should enforce the same English that we were taught in elem school... I mean, elementary school. If a team wants to add those programming-isms to their dictionary, then they can, but to the detriment of their style guide's consistency.

What do you guys think? Is this feasible? Does anyone else think it's worthwhile? Thanks.

**Comment by mrjoelkemp** [comment]
+1 for the idea. I need to sit on the proposed implementation though.

**Comment by jacksonrayhamilton** [comment]
Looks like the Lodash authors (or someone else) already came up with a good word regex:

```js
var reWords = (function() {
    var upper = '[A-Z\\xc0-\\xd6\\xd8-\\xde]',
        lower = '[a-z\\xdf-\\xf6\\xf8-\\xff]+';

    return RegExp(upper + '+(?=' + upper + lower + ')|' + upper + '?' + lower + '|' + upper + '+|[0-9]+', 'g');
}());

'fooBar'.match(reWords);
// => ["foo", "Bar"]

'fooBarFoo'.match(reWords);
// => ["foo", "Bar", "Foo"]

'fooBARFoo'.match(reWords);
// => ["foo", "BAR", "Foo"]

'foo_bar_foo'.match(reWords);
// => ["foo", "bar", "foo"]
```

So no need to settle on camel-cased acronym capitalization.

**Comment by alawatthe** [comment]
I agree, that abbreviations are a common source of errors and confusing code. However I don't think that checking the spelling of identifiers will work, because:

* There are identifier names I what to disallow, although they are English words. For example ```bar```, ```temp```, ...
* Sometimes I really want to use a identifier name, which isn't a real English word.
  * For example, when using lodash, I want to call the variable ```lodash```, but that's not an English word.
  * An other example are ```for``` loops, where ```i```, ```j```, ```k```, ... are more or less the standard variable names:

    ```js
    for (let i = 0; i < 4; i++)  {
      for (let j = 0; j < 5; j++)  {
        doSomething();
      }
   }
    ```

* Often you don't have control over the identifier names. For example in configuration objects for third-party libraries. E.g.: I the case of jscs there are ```esnext```, ```esprimaOptions```, ...
* Internationalisation: Why should this be restricted to English? Why shouldn't I be allowed to use Russian, German or Greek for my variable names? Yes, the following is valid JavaScript:
```js
var μεταβλητός = 'variable';
```
* It's a configuration nightmare. What word list should be used? This gets even more complicated if more than one language is used. What is done with false positives and false negatives?
* Using several word lists will increase the download size of jscs a lot.
* I doubt, that this can be implemented in an easy, performant way. We had a big performance problem  https://github.com/jscs-dev/node-jscs/pull/861 when doing something similar.

---

I think normally it is enough, to black list identifier names which shouldn't be used. That's why I implemented disallow-identifier-names (https://github.com/jscs-dev/node-jscs/pull/960) some time ago. It is available in 1.12.0, however, due to a bug https://github.com/jscs-dev/node-jscs/issues/1203 you probably have to wait until 1.12.1 to use it.

@jacksonrayhamilton: In your case, you can add something like 
```js
"disallowIdentifierNames": [ "elem", "elm", "el", "err", "e", "dir"]
```
to your ```.jscsrc```.

**Comment by mrjoelkemp** [comment]
Great points @alawatthe! I'd love to see something like this on comments, but you'd run into similar issues as what @alawatthe described when it comes to docblocks or comments that mention var names.

**Comment by jacksonrayhamilton** [comment]
Yes, it should be possible to allow words not in the dictionary, and to disallow words in the dictionary, at your discretion.

We could create node packages providing dictionaries and the user could optionally install 1 or more of them if he wanted to use spellcheck. Then he could use whichever language(s) he wanted, and the download size of JSCS wouldn't necessarily need to be affected. (Though I don't see download size as much of an issue; you don't install packages often. I think it would be convenient and worthwhile to have some English dictionary bundled.) I don't know how to split words in non-Latin languages, but special support can be added for them if it is needed and desired.

This feature is optional, so it wouldn't really matter if it was slow. But it probably doesn't have to be. I expect we can use some well-known searching algorithm to find words quickly. It appears that checking for the existence of a word is fast:

```js
'use strict';

// v3.6.0
var _ = require('lodash'),

    // JSON array of 33,000 words (SCOWL English list size 70)
    words = require('../english-words.json');

suite('wordlist', function () {
    var subjectWords = _.times(10, function () {
        return words[_.random(words.length)];
    });
    _.forEach(subjectWords, function (word) {
        bench(word, function () {
            _.indexOf(words, word, true);
        });
    });
});
```

When I run the above benchmark with `matcha` I get

```
~/projects/wordlist λ ./node_modules/.bin/matcha 

                      wordlist
       1,352,018 op/s » hatcher
       1,400,212 op/s » millruns
       1,468,260 op/s » tentation
       1,434,476 op/s » humoresques
       1,383,501 op/s » unscaled
       1,368,811 op/s » importuner
       1,267,606 op/s » complotting
       1,351,163 op/s » neonatologist
       1,349,367 op/s » soymilks
       1,302,093 op/s » subordinary


  Suites:  1
  Benches: 10
  Elapsed: 17,507.54 ms
```

as `_.indexOf` is doing a binary search on a pre-sorted wordlist. 0.0000007 seconds per word lookup seems pretty snappy.

`disallowIdentifierNames` helps a little bit, but not enough. There are many ways to misspell most words. I can try to cover all the cases I can think of, but the maintainers of the code will likely imagine new abbreviations, and the tool won't notice them until they are too deeply embedded in the codebase. The same could apply to false positives like "temp", though I imagine there are fewer false positives than there are possible contractions.

If there is configuration overhead, I imagine most of it will be paid early in a project's lifetime when most of its domain-specific words are discovered and added to the list. You will only have to add more exceptions as you bring in more 3rd-party libraries, which probably shouldn't happen often. Contrast this to relying solely on `disallowIdentifierNames`, which will be an endless battle between you and your co-workers as week after week you suck their programmer vocabulary dry. Better to do it all at once.

**Comment by jacksonrayhamilton** [comment]
Took a stab at implementing this for [#1217](https://github.com/jscs-dev/node-jscs/pull/1217).

**Comment by jacksonrayhamilton** [comment]
[Implemented.](https://github.com/jscs-dev/jscs-spellcheck)
