### ISSUE TITLE
Unexpected location listed for disallowPaddingNewlinesInBlocks

### ISSUE THREAD

**Issue by TheSavior** [jscs-dev/node-jscs#1200]
With `"disallowPaddingNewlinesInBlocks": true`

This code:
```javascript
(function () {
 
 var a = 2;

})();
```

highlights the opening bracket with the warning that there shouldn't be padding at the beginning of the block.

It also highlights the space after the semicolon on 2 saying that there shouldn't be padding at the end of the block. I'd imagine the error for no padding at the end should be on the closing bracket.

**Comment by hzoo** [comment]
This would be fixed with CST as well?

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
