### ISSUE TITLE
Autoformat: validateQuoteMark

### ISSUE THREAD

**Issue by indexzero** [jscs-dev/node-jscs#1201]
Should be a straight-forward enough rule to fix tokens on. PR coming shortly.

**Comment by TheSavior** [comment]
This is something that should definitely have a lot of tests. I could see it running into issues with strings with/without escape chars for the opposite quote type. I could also see it being an issue with multiple concatenated strings with different quote types. Multi line strings would be another good thing to check.

**Comment by p3k** [comment]
:+1:
