### ISSUE TITLE
New Rule: disallowNotOperatorsInConditionals

### ISSUE THREAD

**Issue by SimenB** [jscs-dev/node-jscs#1205]
Sorta confusing title. Also, sorry if this is already a rule.

I'd like the following code to to throw
```javascript
if (!clause) {
    // Do something crazy
} else {
    // Do something really crazy
}
```
The correct way would be
```javascript
if (clause) {
    // Do something really crazy
} else {
    // Do something crazy
}
```

If no else is present, no error.

Does this make sense?

**Comment by TheSavior** [comment]
When I was at Google, this was ingrained into my coding habits. I would love a rule for this.

**Comment by hzoo** [comment]
So this would just check for the presence of the not operator in an if with an else?

**Comment by SimenB** [comment]
Yeah, either just negating, or ``==!``.

**Comment by hzoo** [comment]
And only with a single boolean? What if it's (a &&!b)?

**Comment by SimenB** [comment]
In my mind, if you have a single wrapped expression, that you then negate, it should throw.

So from your last 2 examples, the first is fine, the second should throw.

If you think of it as if you removed the negation, and could then just switch the bodies of the ``if`` and the ``else`` and have the same result, then it should throw.

**Comment by hzoo** [comment]
Ok cool. I'm not sure about a good rule name... `disallowNegation...` or `disallowFalsyCheckInIfStatement`..

Unrelated: It might be interesting to check if a expression can be simplified `!(!a || !b)` -> `a && b`

**Comment by TheSavior** [comment]
@mkanat: IIRC, you had a name for this.

**Comment by SimenB** [comment]
(related to boolean-expressions)

What about a rule about maximum number of expressions? Like if you have maximum 2, then ``(a || b)`` is fine, but ``(a || b || c)`` would throw, and you should split it and extract it to a variable or something.
Or what about missing clarifying parentheses? e.g. ``(a && b || c && b)`` can be confusing. It's much easier to read and reason about if it's written as ``((a && b) || (c && d))``

**Comment by TheSavior** [comment]
I could imagine a rule that requires parenthesis for any expression with more than one operator of different importances. That would encompass `var a = 2 + 4 / 8 > 6 && 2 - 4 * 2 < 3` as well as requiring parens for boolean conditionals. Can you make a new issue describing that?

**Comment by hzoo** [comment]
Can work on a PR for this.

**Comment by TheSavior** [comment]
`disallowInvertedConditionalsWithElse`?

**Comment by TheSavior** [comment]
I would imagine this should be okay:
```javascript
if (!foo || bar) {
} else {
}
```

What about:
```javascript
if (!foo) {
} else if (bar) {
}
```

**Comment by hzoo** [comment]
Just picked a name for now.

**Comment by zxqfox** [comment]
It would be great partner to `requireEarlyReturn`

**Comment by zxqfox** [comment]
What about `if (!(a && b))` vs `if (!a || !b)`? Logically it's the same. But should we handle this as negate?

**Comment by SimenB** [comment]
@somebody this was closed in today's release

**Comment by hzoo** [comment]
I think you can @jscs-dev

**Comment by markelog** [comment]
Right, let's have commit ref, for good record keeping - https://github.com/jscs-dev/node-jscs/commit/52083ffde676fa4ca35c7203d0284f3939dcf970

**Comment by jasonkarns** [comment]
looks like i missed the naming discussion but I would have preferred to see the term 'negation' used instead of 'not'.  IME, `negation` is the more language-agnostic (computer-sciency) term for the operator.

My vote is for `disallowNegationOperatorsInConditionals`
