### ISSUE TITLE
New Rule: (disallow|require)MultiLineTernary

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1206]
For node-style-guide: https://github.com/felixge/node-style-guide#use-multi-line-ternary-operator

```js
var foo = (a === b)
  ? 1
  : 2;
```

**Comment by bjdixon** [comment]
I'd like to implement this one please.

**Comment by hzoo** [comment]
Go for it! Let us you if you need help suggestions - you can always do a wip PR for feedback
