### ISSUE TITLE
requirePaddingNewLineAfterVariableDeclaration in for loop

### ISSUE THREAD

**Issue by SimenB** [jscs-dev/node-jscs#1207]
The following line throws 
``for (var i = 0; i < 60; i++) {``

It wants newlines after ``var i = 0;``. I "fixed" it by moving the declaration to the top of the function, but I still think this should be accepted.

**Comment by hzoo** [comment]
Sounds similar to the for loop exception for `requireLineBreakAfterVariableAssignment` https://github.com/jscs-dev/node-jscs/issues/1157. I can take this.
