### ISSUE TITLE
Wrong location listed for disallowMultipleLineBreaks

### ISSUE THREAD

**Issue by TheSavior** [jscs-dev/node-jscs#1209]
This code:

```javascript
function foo() {
  var a = 2;


}
```

Reports that there shouldn't be at most two lines between the semicolon and the curly brace on the space after the semicolon. I would expect it to highlight the closing curly brace instead.

**Comment by zxqfox** [comment]
https://github.com/jscs-dev/jscs-jsdoc/issues/89 lol. It shows jsdoc comment as the second token.

**Comment by markelog** [comment]
<pre>
disallowMultipleLineBreaks: } and ; should have at most 2 line(s) between them at test.js :
     3 |
     4 |
     5 |}
---------^
     6 |
</pre>

I don't know, does it looks better?

**Comment by zxqfox** [comment]
Hm, not sure why `}` placed as the first token.

@TheSavior Why you think the closing brace should be marked instead of opening one?

@markelog I'm missing a lot location range here.

**Comment by markelog** [comment]
@zxqfox now it looks like this - 
```js
disallowMultipleLineBreaks: ; and } should have at most 2 line(s) between them at test.js :
     1 |function foo() {
     2 |  var a = 2;
--------------------^
     3 |
     4 |
```

**Comment by zxqfox** [comment]
Check this ;-)
```js
function foo() {
  var a = 2;


  /**
    * @something
    */
}
```

I think @TheSavior meant that it should looks like:
```
disallowMultipleLineBreaks: ; and } should have at most 2 line(s) between them at test.js :
     3 |
     4 |
     5 |}
--------^
     6 |
```
But I'm not sure why.

**Comment by TheSavior** [comment]
@markelog exactly.
@zxqfox exactly.

The reason I think it should look like your second example is because there is no error on the line with `var a = 2;` The error is that the semicolon has too many blank lines above it. You could also say that there are too many blank lines (and that those lines themselves are the error). 

Either way though, there is nothing wrong on line 2 IMO. :P

**Comment by mikesherov** [comment]
Assertions need to be able to specify which of the tokens is in error. I'll work on this soon.

**Comment by hzoo** [comment]
Will this be fixed when we integrate CST?

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
