### ISSUE TITLE
an option to ignore indentation validation for comments

### ISSUE THREAD

**Issue by jakutis** [jscs-dev/node-jscs#1215]
This feature should be able to silence the error on the bottom:

```
$ cat a.js 
var a = Math.random();
if (a < 0.5) {
  // testing jscs comment indentation
  a = 0;
//  a = 0.5;
}
$ cat cfg.json 
{
  "validateIndentation": 2
}
$ ./node_modules/.bin/jscs -c cfg.json a.js 
Expected indentation of 2 characters at a.js :
     3 |  // testing jscs comment indentation
     4 |  a = 0;
     5 |//  a = 0.5;
----------^
     6 |}
     7 |


1 code style error found.
```

**Comment by david-gang** [comment]
:+1: 
This is especially annoying with multiline comments like in ngdoc

>←[1mExpected indentation of 1 characters←[22m at ←[32mils\ils.directive.js←[39m :
 ←[90m   18 |←[39m
 ←[90m   19 |←[39m
 ←[90m   20 |←[39m    /**
←[90m---------^←[39m
 ←[90m   21 |←[39m     * @ngdoc directive
 ←[90m   22 |←[39m     * @name x.directive: y

**Comment by boldt** [comment]
:+1: 

I do not use jscs until now, because of plenty of single line comments as shown above.

**Comment by zxqfox** [comment]
@boldt Why not to disable this specifique rule?

**Comment by boldt** [comment]
@zxqfox I guess your talking about the rule `validateIndentation`?

**Comment by JetFault** [comment]
This is pretty useful

**Comment by ppcano** [comment]
:+1:

**Comment by langdonx** [comment]
Just updated JSCS and encountered this.

>> 231 code style errors found!

A lot of IDE shortcuts (WebStorm in particular) throw comments at the beginning of the line, which is why this has become an issue for me.

**Comment by neagle** [comment]
This is a problem for me, too. I'm using `validateIndentation: "\t"` which is really useful, but it's reporting errors for commented-out blocks of code like this:

```
	//User.findById(new ObjectId(userId), function (err, user) {
		//if (err) {
			//return next(new Error('Failed to load User'));
		//}
		//...
	//});
```

```
Expected indentation of 1 characters at controllers/users.js :
```

Would it make sense to have an option along the lines of `allowArbitrarilyIndentedComments`? (Name mostly for humor value.)

**Comment by mrjoelkemp** [comment]
What about allExcept: ['comments']?

**Comment by neagle** [comment]
:+1: That sounds great to me.

**Comment by blah238** [comment]
:+1:

**Comment by markelog** [comment]
So does anyone want to tackle this? I guess @mikesherov currently overwhelmed with `validateIndentation` issues

**Comment by neagle** [comment]
Thanks a lot! :smile:
