### ISSUE TITLE
Unnamed functions block verification

### ISSUE THREAD

**Issue by Ynk33** [jscs-dev/node-jscs#1218]
Hi,
I wrote a really simple function to test jscs, with some mistakes written on purpose :
```javascript
function() {
    var MY_Test = 'hello';
    return MY_Test;
}
```

Then, I used the command
```bat
jscs $MY_WORKSPACE --preset=node-style-guide
```
to see how the mistakes are displayed, with the Node Style Guide preset.

Normally, 2 errors would have been displayed : unnamed function, and not camelcase name for the variable. But only the first one is displayed with the error "Unexpected token (".
So I changed the function to see if this is the node-style-guide which is not complete : 
```javascript
function test() {
    var MY_Test = 'hello';
    return MY_Test;
}
```

But in that case, the not camelcase error is displayed properly.
So I guess that this is the unnamed function which is blocking the validation.

Is it some kind of a bug, or am I misunderstanding something ?
Thanks for your help.

**Comment by hzoo** [comment]
In the first example, you can't make a function declaration with naming it.
So there is an error because it isn't valid js.
```js
function() {
    var MY_Test = 'hello';
    return MY_Test;
}
```

You could do `var a = function() {}`.

**Comment by mikesherov** [comment]
Thanks for contributing. The problem is as @hzoo described. Please repsond if you feel like this is an error. Thanks again!
