### ISSUE TITLE
Support for spread attributes

### ISSUE THREAD

**Issue by globexdesigns** [jscs-dev/node-jscs#1219]
JSCS is having a lot of issues with spread attributes. Obviously, they can't be parsed with regular settings. I then tried enabling `"esnext": true`, but that didn't help either.

```
Unexpected token ... at components/js/layout/Test.js :
    36 | render () {
    37 |  var { className, fixedHeight, fixedWidth, height, width, ...other } = this.props;
--------------------------------------------------------------------^
```

Even wrapping it in a  `//jscs:disable` didn't seem to help.

```
Unexpected token ... at components/js/layout/Test.js :
    36 | render () {
    37 |  //jscs:disable
    38 |  var { className, fixedHeight, fixedWidth, height, width, ...other } = this.props;
--------------------------------------------------------------------^
    39 |  //jscs:enable
```

**Comment by hzoo** [comment]
`Unexpected token` usually means that esprima doesn't currently support spread or destructuring in that way yet. Yeah `esnext` would be required as well.
You can try `esprima-fb` maybe? `npm install` it and either do `--esprima=esprima-fb_path` or add it to your .jscsrc with `"esprima": "path_to_esprima-fb"`

**Comment by mikesherov** [comment]
@globexdesigns using esprima-fb for the time being is your best option. Going to close this for now, as it can only be fixed by Esprima.
