### ISSUE TITLE
New Rule: Blank line after 'use strict', New Rule: Blank line before module.exports

### ISSUE THREAD

**Issue by TheSavior** [jscs-dev/node-jscs#1220]
I've been working on a style guide for CommonJS specific things and it has brought to light a few things that would be good JSCS rules.

The style guide:
https://gist.github.com/TheSavior/af94986da0ecef32e310

The examples:

## Leave a blank line after strict mode declaration
**Good**
```javascript
'use strict';

// code
```

**Bad**
```javascript
'use strict';
// code
```

## Always put a blank line before your export statement
**Good**
```javascript
// code

module.exports = {};
```

**Bad**
```javascript
// code
module.exports = {};
```

**Comment by zxqfox** [comment]
Look like a rule of `requireNewLineBefore*` group. :+1: to have it!
