### ISSUE TITLE
New Rule: requireEarlyReturn

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1223]
From https://github.com/jscs-dev/node-jscs/issues/1071#issuecomment-74583649 (node-style-guide and idiomatic preset).

Right:
```js
function isPercentage(val) {
  if (val < 0) {
    return false;
  }

  if (val > 100) {
    return false;
  }

  return true;
}
```
Wrong:

```js
function isPercentage(val) {
  if (val >= 0) {
    if (val < 100) {
      return true;
    } else {
      return false;
    }
  } else {
    return false;
  }
}
```

Name? Maybe `requireEarlyReturnFromFunctions`?
Not sure how we would go about doing this? Checking for return's in else statements?

**Comment by zxqfox** [comment]
:+1: for this.

`requireEarlyReturn` is fine for me. I think `FromFunctions` not needed because returns used in functions only and made for functions.

**Comment by hzoo** [comment]
Oh haha good point.

**Comment by markelog** [comment]
That one would be cool to have

**Comment by hzoo** [comment]
Going to close for now.

**Comment by markelog** [comment]
Okay, reopening, since it is needed for couple presets
