### ISSUE TITLE
New Rule: Disallow ByteOrderMark

### ISSUE THREAD

**Issue by Krinkle** [jscs-dev/node-jscs#1225]
Downstream: https://phabricator.wikimedia.org/T40233

PHPCS equivalent: [Sniffs/Generic.Files.ByteOrderMark](https://github.com/squizlabs/PHP_CodeSniffer/blob/2.3.0/CodeSniffer/Standards/Generic/Sniffs/Files/ByteOrderMarkSniff.php)

**Comment by zxqfox** [comment]
I'm not sure that this is about code style and should be implemented in `jscs`.

**Comment by Krinkle** [comment]
Perhaps it's more suitable for JSHint?

**Comment by zxqfox** [comment]
I thought about it. But still not sure ;-) At least, jshint works with file itself and not js code. So it's definitely closer to the BOM problem.

/cc @mikesherov @mrjoelkemp @markelog

**Comment by mikesherov** [comment]
Yeah, this is definitely JSHint territory. We don't work with the file itself. @Krinkle report this to them instead. Closing for now!
