### ISSUE TITLE
API syntax with require?

### ISSUE THREAD

**Issue by aogilvie** [jscs-dev/node-jscs#1230]
```
var jscs = require('jscs');
...
jscs(['/a/path?'], { preset: 'whatever'});
```

What's the expected API syntax?

**Comment by markelog** [comment]
For example in grunt plugin - https://github.com/jscs-dev/grunt-jscs/blob/bb98fca2c6184e4cc9963cdab7e4f2613701a38f/tasks/lib/jscs.js#L54-L55

Then use `checkString`, `checkPath` methods or <a href="https://github.com/jscs-dev/node-jscs/blob/c668ff1be0b1cfa058866048944bad3df7ff7cbc/lib/checker.js">etc</a>, we will create documentation for this interface, would you like to help?

**Comment by aogilvie** [comment]
Cheers. Yeah sure, I'll just have a wee play and push something to say, overview.html?

**Comment by aogilvie** [comment]
Is there a sync API for either checkPath() or checkString()?

```
var checker = jscs.checkPath(path);

if (!checker) {
    console.error(checker.failMsg);
}
```

Here is what I use for JSHint:

```
fileContent = fs.readFileSync(filePath, 'utf8');

// Run the linter
isSuccess = jshint(fileContent, jshintrc);

// Report the test
if (!isSuccess) {
    jshint.errors.forEach(function (err) {
        .... // output error
    }
}
```

**Comment by markelog** [comment]
Nope those are very different APIs
