### ISSUE TITLE
requirePaddingNewLinesAfterBlocks seems overly strict

### ISSUE THREAD

**Issue by tomekwi** [jscs-dev/node-jscs#1232]
```js
callingAFunction(
  with,
  another,
  function() {
    // ...
  }
);

// more code
```

This results in `Missing newline after closing curly brace`. IMO the function call is a block in itself, so the newline should be required after it. Not after the nested anonymous function.

But JSCS prefers this – which should IMHO be wrong:

```js
callingAFunction(
  with,
  another,
  function() {
    // ...
  }

);
// more code
```

**Comment by Ky6uk** [comment]
Also, I can't set exceptions on this rule? Like a all blocks except `else`.

**Comment by TheSavior** [comment]
I agree, here is another case that occurs pretty often:

```
fun(
  arr.map(function() {
  })
);
```

**Comment by hzoo** [comment]
Looks like https://github.com/jscs-dev/node-jscs/issues/1237 is a similar issue?

We are checking for `nextToken.value ===` `} and )` so what about `,` for multiple function calls in a list?
