### ISSUE TITLE
Unexpected token * with yield

### ISSUE THREAD

**Issue by arthurmuchir** [jscs-dev/node-jscs#1234]
I got an ```Unexpected token *``` when I declare function like this :
```
app.use(function* (next) {
...
}
```

Using jshint, esnext option allow me to bypass warning but I don't find any equivalent in jscs.

Is there any ?

Thanks

**Comment by mrjoelkemp** [comment]
We have the `esnext` option as well. See if that works: http://jscs.info/overview.html#esnext. If that doesn't work, then it's an esprima bug and we can proceed accordingly.

**Comment by arthurmuchir** [comment]
ok, so it's an esprima bug.

Thanks !
