### ISSUE TITLE
disallowMultipleSpaces matches tabs too

### ISSUE THREAD

**Issue by globexdesigns** [jscs-dev/node-jscs#1240]
I was hoping to use the `disallowMultipleSpaces` rule to check against multiple spaces only, but it seems to check for multiple tabs too (which is undesirable to me since that's our method of indentation).

If this is the indented behaviour for this rule, can you please update the documentation to say:

`Disallows multiple INDENTATION CHARACTERS between identifiers, keywords, and any other token`

Here is an example of some code which fails when this rule is enabled:

```
// All spaces here are tab characters
component: {
	register:		createActionCreator('COMPONENT_REGISTER'),
	unregister:		createActionCreator('COMPONENT_UNREGISTER')
},
```

**Comment by mikesherov** [comment]
Yes, this is a documentation issue. This rule is behaving exactly as intended. If you are using alignment, this rule is not for you.
