### ISSUE TITLE
Errors should indicate which rule is causing them

### ISSUE THREAD

**Issue by SteveALee** [jscs-dev/node-jscs#1241]
The errors message requires some guess work.

For example ```Var declarations should be joined``` I eventually figured out this was the problem due to the old airbnb preset in Visual Studio Web Essentials (#822) 

And while ```Invalid Line break``` can also be narrowed down by a little searching it would be great if either

1) the option causing the error was listed
2) The docs included the error message.

**Comment by mikesherov** [comment]
@SteveALee that's the `--verbose` option, which will become the default in 2.0. Thanks for contributing!

**Comment by SteveALee** [comment]
COol. I just have to figure how to turn it on in VS Web Essentials then :)
