### ISSUE TITLE
Existing rule for only allowing one key definition in object declaration per line?

### ISSUE THREAD

**Issue by TheSavior** [jscs-dev/node-jscs#1249]
I just added `  "requirePaddingNewLinesInObjects": true` to our projects configuration and formatted:

```javascript
var a = {b: 1, c: 2}
```

Which turned into

```javascript
var a = {
    b: 1, c: 2
};
```

I was looking for an additional rule to add that would require it to be like this:

```javascript
var a = {
    b: 1, 
    c: 2
};
```

but didn't see anything in the docs that would do that. Is there a rule for this yet? It looks like the closest I can find is `requireLineBreakAfterVariableAssignment` but that seems to only care about `var` statements, and not object declarations.

**Comment by markelog** [comment]
It seems like auto-fixing bug, which relates to https://github.com/jscs-dev/node-jscs/commit/5f20bf884ff9a6b77d0cbbffd4ef1054b866deb7

**Comment by TheSavior** [comment]
I don't think this is an autofix bug. 
```
var a = {
    b: 1, c: 2
};
```
still passes JSCS, which means I am just missing an additional rule to put each key on its own line.

**Comment by hzoo** [comment]
Yeah ok basically #317, `validateNewlineAfterArrayElements` for objects. I'm also suggesting it for destructuring/module imports.

Looking at the rule, `requirePaddingNewLinesInObjects` actually only checks for the first/last newline in an object - not for each object key.

**Comment by markelog** [comment]
It makes more sense to put them in separate lines, but i agree - additional rule would be better

**Comment by hzoo** [comment]
So the label for this should be `new rule` instead of `bug`?
