### ISSUE TITLE
requireSpaceAfterLineComment doesn't autofix

### ISSUE THREAD

**Issue by TheSavior** [jscs-dev/node-jscs#1250]
See title

**Comment by TheSavior** [comment]
This rule doesn't use the assertions because it is manually parsing the comment string which includes the `//` since `//` isn't a token on its own. 

It manually calls `errors.add` which can't specify that the error is fixed. 

@markelog, this seems like a space where our assertions and errors library are lacking. How do you recommend we progress on this issue?

**Comment by zxqfox** [comment]
We definitely should rethink default behaviour of esprima for our needs.

**Comment by zxqfox** [comment]
I suggest to implement 3 additional tokens: `//`, `/*`, `*/`.

Related #1242

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
