### ISSUE TITLE
conflict: jQuery variables requiring $, private variables using _

### ISSUE THREAD

**Issue by TheSavior** [jscs-dev/node-jscs#1251]
I have some private state that would normally be:

```javascript
this._element = $('.element');
```

with `requireDollarBeforejQueryAssignment: true`, I'd want it to be

```javascript
this._$element = $('.element');
```

but then that fails having the dollar at the beginning. So if I switch it around:

```javascript
this.$_element = $('.element');
```

Then `requireCamelCaseOrUpperCaseIdentifiers` complains.

How should this be resolved such that it is possible to do:

```javascript
this._$element = $('.element');
```

An option to the jquery rule?

**Comment by mrjoelkemp** [comment]
Seems like an exception that should be built in. The first char in the property or identifier. Patch release worthy.

**Comment by markelog** [comment]
An edge case, but yeah, we could build that in, does anyone want to take that in?

**Comment by TheSavior** [comment]
What do we want the solution to look like? Always allow `_` before the `$`? Have a config option of allowed prefixes for jquery elements that defaults to `$` but can be specified: `['_$', $']`?

**Comment by markelog** [comment]
> Always allow _ before the $?

Would that be enough?

**Comment by TheSavior** [comment]
It would be enough for me, but I could imagine it not being expected for other people.

Since requireCamelCaseOrUpperCaseIdentifiers always allows leading underscores, it would be fine to do the same here. So yeah, lets roll with `Always allow _ before the $`.
