### ISSUE TITLE
inconsistent naming: disallowPaddingNewlinesInBlocks

### ISSUE THREAD

**Issue by jeremymoritz** [jscs-dev/node-jscs#1255]
On the same page, you have this named two ways:

disallowPaddingNewlinesInBlocks
disallowPaddingNewlinesInBlock

http://grab.by/GkBK

![screen shot 2015-04-10 at 11 23 54 am](https://cloud.githubusercontent.com/assets/2779583/7092035/3504e1aa-df74-11e4-8147-d1f8191375ae.png)

**Comment by hzoo** [comment]
This is from http://catatron.com/node-jscs/rules/disallow-padding-newlines-in-blocks/?

If you go to http://jscs.info/rules.html it doesn't seem to have this issue (jscs.info is the official site).
