### ISSUE TITLE
verbose option only shows the plugin name

### ISSUE THREAD

**Issue by alawatthe** [jscs-dev/node-jscs#1257]
When using the ```--verbose``` with a plugin, only the name of the plugin is displayed and not the rule in the plugin. For example:

```
->jscs test.js --verbose
jsDoc: Missing param name at test.js :
     1 |/**
     2 | * @param {Object}
-----------^
     3 | */
     4 |var f = function(param) {}


1 code style error found.
```

I'd like to have something like:

```
->jscs test.js --verbose
jsDoc.checkParamNames: Missing param name at test.js :
     1 |/**
     2 | * @param {Object}
-----------^
     3 | */
     4 |var f = function(param) {}


1 code style error found.
```

**Comment by zxqfox** [comment]
@alawatthe Thanks for the report ;-)

That's related to #739

**Comment by zxqfox** [comment]
@mikesherov @markelog Please correct me (and milestone) if we can make it earlier than 2.0.

**Comment by hzoo** [comment]
We should get this in if it's simple to do

**Comment by zxqfox** [comment]
`eslint` using slash for separating: `jsdoc/checkParamNames`

@hzoo It's not so simple. Here are few proposed solutions:
- Via sharing data between rules and remaking rules in jsdoc plugin;
- Via plugins for parser: to parse jsdoc comment blocks before executing checkers;
- Via nested rules support in core: just to support better reporting for rules like that.

Not sure what is better here atm. Earlier I though we should go for #698

**Comment by zxqfox** [comment]
@markelog :+1: Thanks! If you'll find some other related issues — please push it me too. :smirk_cat:

**Comment by markelog** [comment]
Okay :-)

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
