### ISSUE TITLE
jQuery identifiers must start with a $ - failing for object properties

### ISSUE THREAD

**Issue by viveleroi** [jscs-dev/node-jscs#1266]
Using JSCS/gulp on a project which assigns a jquery object to an object property triggers the `jQuery identifiers must start with a $` error. However, the property is part of a configuration object for another javascript in bower, and outside our control.

```
jQuery identifiers must start with a $ at assets/js/controllers/project/fields.js :
    24 |        $scope.initFormBuilder = function() {
    25 |            $scope.formbuilder = new Formbuilder({
    26 |                targets: $('.formbuilder'),
------------------------^
```

Assigning it to a variable first solves the issue, but is unnecessary in this specific case.

Using gulp-jscs 1.4.0 on Mac OS X 10.10.2.

**Comment by TheSavior** [comment]
Unfortunately we are unable to know whether you are passing it to an object that you control or a 3rd party library. This seems like a case where you use a `jscs disable` flag to ignore the line.

**Comment by mikesherov** [comment]
@TheSavior we should introduce an `ignoreProperties` option the same as `requireCamelCaseorUppercaseIdentifiers`. Thanks for contributing @viveleroi

**Comment by viveleroi** [comment]
I was going to suggest the same. It's not a critical issue, I can use a variable or use an ignore flag, it just feels a little inconsistent.
