### ISSUE TITLE
ignoreProperties for requireCamelCaseOrUpperCaseIdentifiers falsely catches getters

### ISSUE THREAD

**Issue by Aintaer** [jscs-dev/node-jscs#1269]
If I have an object like
```js
{
  get some_url() {
    return url;
  }
}
```

`some_url` is flagged as failing `requireCamelCaseOrUpperCaseIdentifiers`, even though it is only a property of the object.

**Comment by zxqfox** [comment]
Object keys are identifiers too (as well as variables, function names, etc).

What did you expect?

**Comment by mikesherov** [comment]
@zxqfox we have ignoreProperties for this exact reason though.

**Comment by zxqfox** [comment]
@mikesherov Yes, sure. I'm just afraid that I didn't understand the question.

**Comment by zxqfox** [comment]
Oh, sorry. So while you using
```
  requireCamelCaseOrUpperCaseIdentifiers: "some_url"
```
JSCS still reporting `get some_url`? Ok.

**Comment by zxqfox** [comment]
@Aintaer Thanks for reporting ;-)

**Comment by zxqfox** [comment]
Landed, thanks!
