### ISSUE TITLE
Can we catch exceptions and dump inner state of checker?

### ISSUE THREAD

**Issue by zxqfox** [jscs-dev/node-jscs#1271]
```
$ node_modules/.bin/jscs .
TypeError: Cannot read property 'type' of undefined
    at /Users/remnev/stat-counters/node_modules/jscs/lib/rules/require-multiple-var-decl.js:41:24
    at Array.forEach (native)
    at Object.JsFile.iterateNodesByType (/Users/remnev/stat-counters/node_modules/jscs/lib/js-file.js:406:42)
...
```

Case for test:
```js
switch (ab.nodeType) {
    case 1:
        var ad = ab.nodeName;
        break;
}
```
To have some additional info about checking file, etc.

**Comment by TheSavior** [comment]
IIRC, there is a fix out for the specific issue mentioned.

However, I totally agree that we should never be throwing errors to the user from inside the Java code base. Hopefully unit tests avoid these cases but this is a good example of where that was not the case.

It's a fine line though. From the users side, we should wrap JSCS completely in a try catch to be able to say "an error occurred when running JSCS". However, we would then lose all of the debugging information. Perhaps the debugging information would be printed as part of a verbose flag that was mentioned in another issue.

**Comment by zxqfox** [comment]
:+1: Agreed. But we shouldn't stop checking file on exceptions imho. One rule's fail shouldn't ruin all the rest.

And yes, `--verbose` should definitely expose this information to user. It helps a lot for debugging and bug reporting.

**Comment by zxqfox** [comment]
Related issues: #916, #1163

**Comment by TheSavior** [comment]
That is a great point about disabling the rule and continuing running with the others.

**Comment by zxqfox** [comment]
I'm gonna land this if nobody against. Take one more look please.

/cc @mikesherov @TheSavior @hzoo

**Comment by hzoo** [comment]
Looks good?

**Comment by zxqfox** [comment]
@hzoo For me? Seems like. ;-) Is it a question?
