### ISSUE TITLE
requireSpacesInsideObjectBrackets not working for empty declarations

### ISSUE THREAD

**Issue by dominik0711** [jscs-dev/node-jscs#1275]
Using `requireSpacesInsideObjectBrackets: "all"` does not alert for following code:

```
var x = {};
```

Should be with space: 

```
var x = { };
```

**Comment by markelog** [comment]
This is by design, most users wouldn't want to show error for this particular case, i'd say it's a plugin job.

**Comment by dominik0711** [comment]
Generally blanks after curly brackets can't be forced to be alerted even for following case:

```
function x () {return 123; }
```

Should be:

```
function x () { return 123; }
```

**Comment by markelog** [comment]
Well, yeah, since this rule called "requireSpacesInside**Object**Brackets", but i can understand the confusion, we will change rule names in 2.0 to make them more appropriate.

As far as i can see, we don't have the rule that would enforce spaces in your case, you're welcome to submit one, or add additional values for the `requireSpacesIn*` rules.

**Comment by dominik0711** [comment]
Thanks for your fast answer. We suspected that already. We'll have a closer look how to submit a rule for these cases.

**Comment by dominik0711** [comment]
@markelog Right now, I have my own custom rules implemented. Following the wiki documentation [Plugin-API](https://github.com/jscs-dev/node-jscs/wiki/Plugin-API) is it right that I have to manipulate `lib/config/configuration.js` to register my plugins??? If yes, what will happen after `npm update`? With every new `jscs` version, my changes in `lib/config/configuration.js` will be deleted. I won't check in `lib/config/configuration.js` in my `git repository`. What about my `plugin.js`? Is it necessary to save them inside `rules folder`???

**Comment by zxqfox** [comment]
@dominik0711

> is it right that I have to manipulate lib/config/configuration.js to register my plugins???

no ;-)

> Cannot find module 'require-spaces-inside-curly-braces'

You need to put your plugin into a npm module (or some subpath).

E.g.:
```
your-jscs-plugin/
  index.js
  lib/
    rules/
      require-spaces-inside-curly-braces.js
```

in `your-jscs-plugin/index.js`:
```
module.exports = function (conf) {
  // plugin loading:
  conf.registerRule(require('../lib/rules/require-spaces-inside-curly-braces.js'));
};
```

In `.jscsrc`:
```
  "plugins": ["./your-jscs-plugin"],
  "requireSpacesInsideCurlyBraces": true
```

You need `./` before plugin name because of local nature of it. If you'll put into npm module you could install it and use without `./`.

I hope it'll help you ;-)

**Comment by zxqfox** [comment]
> How do I enable then the rule as well for Sublime Text 3 SublimeLinter?

It should works right after you put `"plugins"...` configuration into your `.jscsrc` (and install your plugin if npm). At least I don't have any troubles with it (except global jscs installation).

**Comment by dominik0711** [comment]
Thank you guys for your help! Now it seems to be clear for me. 
Maybe this help could help other guys too? At least for me this is a much better description compared to the [Wiki](https://github.com/jscs-dev/node-jscs/wiki/Plugin-API)

**Comment by zxqfox** [comment]
@dominik0711 I definitely should update Wiki ;-) Thanks!

**Comment by zxqfox** [comment]
Updated. @dominik0711 Can you please take a look at new version? https://github.com/jscs-dev/node-jscs/wiki/Plugin-API

**Comment by dominik0711** [comment]
@zxqfox In my opinion it's now better described and more comprehensible. Thanks!

**Comment by zxqfox** [comment]
@dominik0711 Good to hear ;-) Thanks for review.
