### ISSUE TITLE
New rule: disallowPaddingNewlinesInArrayDeclaration

### ISSUE THREAD

**Issue by SimenB** [jscs-dev/node-jscs#1280]
I'd like a rule to dissalow padding newlines in multiline array-declarations

Invalid

```js
[
    'app',
    'underscore',
    'backbone',
    'jquery',
    'hbs!templates/base'

]
```
```js
[
    'app',
    'underscore',
    'backbone',

    'jquery',
    'hbs!templates/base'
]
```

Valid would be without padding :smile:

**Comment by zxqfox** [comment]
It can be an option to `validateNewlineAfterArrayElements`. I don't see how we can make `requirePaddingNewlinesInArrayDeclaration`.

**Comment by hzoo** [comment]
Going to be closing older/inactive issues and labeling with `orphaned` to track anything we might want to reopen again later (if we want to add it again or something has a PR). Thanks :smiley: !
