### ISSUE TITLE
Illegal keyword: continue

### ISSUE THREAD

**Issue by fishbar** [jscs-dev/node-jscs#1283]
with this code， jscs will throw en Error ： Illegal keyword: continue
```
for (var i = 0; i < 1; i++) {
  if (bool) {
    continue;
  }
}
```

but this block is working fine, is this a bug ?

**Comment by zxqfox** [comment]
Looks like. Thanks for a report but I can't repeat it.
Can you provide your `.jscsrc` or find a rule that throw it?

**Comment by markelog** [comment]
You have enabled <a href="http://jscs.info/rules.html#disallowkeywords">disallowKeywords</a> rule, probably through `crockford` preset.

You can null it out, or redefine it -
```js
{	
	"preset": "crockford",
	"disallowKeywords": [
		"with"
	],

	// Or
	// "disallowKeywords": null
}
```

If there problem is somewhere else, please let us know, and i will re-open it
