### ISSUE TITLE
New Rule: enforceBracesPosition

### ISSUE THREAD

**Issue by stephencookdev** [jscs-dev/node-jscs#1284]
I was hoping to be able to use JSCS to check for the position of the opening brace (i.e. braces on new line, or same line).
As a rule, I imagine it might look something like the following:

With the configuration:

    "enforceBracesPosition": {
        "style": "sameLine"
    }

Wrong:

    if(x)
    {
        // code
    }

Right:

    if(x) {
        // code
    }

With configuration:

    "enforceBracesPosition": {
        "style": "newLine",
        "exceptions": [ "return" ]
    }

Wrong:

    if(x) {
        return {
            // code
        }
    }

Right:

    if(x)
    {
        return {
            // code
        }
    }

**Comment by zxqfox** [comment]
Did you see `disallowNewlineBeforeBlockStatements` and `requireNewlineBeforeBlockStatements`?

**Comment by stephencookdev** [comment]
I did not! Definitely seems to do what I described.

I should have looked a bit harder through the existing rules. Thanks!

**Comment by zxqfox** [comment]
Np ;-) Thanks for your question.
