### ISSUE TITLE
requireSpacesInAnonymousFunctionExpression does not override defaults

### ISSUE THREAD

**Issue by KaoruDev** [jscs-dev/node-jscs#1285]
my `.jscsrc`:
```
{
  "preset": "airbnb",
  "requireCamelCaseOrUpperCaseIdentifiers": "ignoreProperties",
  "requireSpacesInAnonymousFunctionExpression": {
    "beforeOpeningRoundBrace": true,
    "beforeOpeningCurlyBrace": true
  }
}
```

example code:
```
var stuff = function () {};
```
error: Illegal space before opening round brace

so then i change to:
```
var stuff = function(){};
```
error: Missing space before opening round brace

seems like i can't override the `airbnb` defaults =(

**Comment by hzoo** [comment]
So the way you can override the default is by nulling the preset's rule. Looking at the [airbnb preset](https://github.com/jscs-dev/node-jscs/blob/master/presets/airbnb.json#L8) the rule is actually disallowing. So you would do in your `.jscsrc`

```js
{
  disallowSpacesInAnonymousFunctionExpression: null
}

And if you want to require it as well then add `requireSpacesInAnonymousFunctionExpression` as well

**Comment by zxqfox** [comment]
@hzoo :+1: But where?

**Comment by hzoo** [comment]
Ok I will just make a separate issue for this.

**Comment by KaoruDev** [comment]
thx for the quick response!
this is now my `.jscsrc`
```
{
  "preset": "airbnb",
  "requireCamelCaseOrUpperCaseIdentifiers": "ignoreProperties",
  "requireSpacesInAnonymousFunctionExpression": {
    "beforeOpeningRoundBrace": true,
    "beforeOpeningCurlyBrace": true
  },
  "disallowSpacesInAnonymousFunctionExpression": null
}
```
still no dice =(
I even tried:
```
  "disallowSpacesInAnonymousFunctionExpression": {
    "beforeOpeningRoundBrace": null,
    "beforeOpeningCurlyBrace": null
  },
```
thinking that might be it according to the docs, and it's not =( I just get an error saying the values can ONLY be true

**Comment by zxqfox** [comment]
try to run JSCS with `--versbose` flag.

I've ran your example and it showed me:
```
disallowSpacesInFunctionExpression: Illegal space before opening round brace at ...
```

So you need to nullify "disallowSpacesInFunctionExpression" rule.

**Comment by KaoruDev** [comment]
@zxqfox huzzah that did the trick! many thanks!
Sorry i couldn't figure out the rule causing the break. I'm using `jscs` in vim =/

**Comment by zxqfox** [comment]
@KaoruDev Np ;-) Thanks for your question. Hope we'll find a place in docs for notice that ;-)

@hzoo Perhaps we need troubleshooting section or something?

**Comment by hzoo** [comment]
Ok I just assumed what the rule was. Yeah I think we could add something like that. And I think we said `--verbose` should be default in 2.0.
