### ISSUE TITLE
Docs: Show what JSCS does on home page

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1286]
~~Clarify being able to null/extend presets #1285.~~
~~One would be under the `--preset` option in http://jscs.info/overview.html#cli.~~
~~Another might be a small note under the [preset section](http://jscs.info/overview.html#presets) - I would mention being able to extend presets as well as disable rules and link to the preset section.~~
~~So I guess just link to the section about being able to null/extend presets in other places.~~

----

Also I think it would be nice to give an example of what jscs does in the about/home page. config/install info - So maybe an example .jscs config that shows off the common features (preset + extend) + autofix.

**Comment by hzoo** [comment]
Ok nulling rules was also in #971.

**Comment by hzoo** [comment]
Changed issue to be about the 2nd issue if we want to do something like that.

**Comment by markelog** [comment]
:thumbsup:

**Comment by zxqfox** [comment]
:+1:

**Comment by hzoo** [comment]
Although I guess this could be an issue in the website repo instead?

**Comment by markelog** [comment]
Yep - https://github.com/jscs-dev/jscs-dev.github.io/issues/24
