### ISSUE TITLE
indentation in functions not reported correctly

### ISSUE THREAD

**Issue by nicks** [jscs-dev/node-jscs#1287]
```js
goog.scope(function() {

  goog.foo = function() {
  alert(1)
}

})
```

Run:
jscs --preset=google test.js

Expected:
I would expect the indentation of `alert` to be flagged

Actual:
No error

This is particularly painful when running the auto-formatter because it will auto-format the `goog.foo = ...` line to the correct indentation, but format everything relative to it incorrectly

**Comment by TheSavior** [comment]
Duplicate of #1144

**Comment by nicks** [comment]
great, thanks!
