### ISSUE TITLE
autofix creates long lines

### ISSUE THREAD

**Issue by nicks** [jscs-dev/node-jscs#1288]
```js
if (thisIsAReallyLongNameOhYesItIs
    && thisIsAReallyLongNameOhYesItIs2
    && thisIsAReallyLongNameOhYesItIs3
    && thisIsAReallyLongNameOhYesItIs4) {
  alert(1)
}
```

Run:
```jscs --preset=google -x test.js```

Expected:
jscs will put the operator on the previous line

Actual:
jscs merges all the lines together, creating one really long line and creating a new warning

```js
if (thisIsAReallyLongNameOhYesItIs && thisIsAReallyLongNameOhYesItIs2 && thisIsAReallyLongNameOhYesItIs3 && thisIsAReallyLongNameOhYesItIs4) {
  alert(1)
}
```

**Comment by markelog** [comment]
google preset has <a href="http://jscs.info/rules.html#requireoperatorbeforelinebreak">this</a> enabled rule - which requires `&&` to be on the same line.

Not sure if this incorrect, but it certainly could done better

**Comment by nicks** [comment]
would you accept a pr that just moved the operator instead of the whole line?

**Comment by markelog** [comment]
yeah
