### ISSUE TITLE
unexpected identifier : "of"

### ISSUE THREAD

**Issue by run1t** [jscs-dev/node-jscs#1289]
Hi, 
when i want to use the identifier 'of',like that : 
```for(item of list){
}```
I have a error on the 'of' , have you add forgot the identifier 'of' or is just an error with my configuration.

Regard,

**Comment by hzoo** [comment]
Did you run jscs with the `esnext` flag? you can either do `jscs --esnext` or put `{ esnext: true }` in your `.jscsrc`

**Comment by run1t** [comment]
Thank you ! It works perfectly !
Sorry for the inconvenience.
