### ISSUE TITLE
Add an error message about using ES6 option when encountering specific ES6 'unexpected identifier'

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1290]
I think a lot of people know about it, but I was thinking we could mention using the `esnext` option in a message when users encounter `unexpected identifier : "of"` (when it's easy to identify their intent is to use ES6 and they don't have the option turned on already. And then if it still has `unexpected token` that it probably is an esprima issue. #1289, #1077

for of loop - `of`,
generator function - `*`,
arrow function - `=>`,
classes - `class`
template strings - `` ` ``
modules - `export, import`

**Comment by mrjoelkemp** [comment]
:+1:

**Comment by zxqfox** [comment]
We need a note, but actually we almost got Esprima 2.x. And esnext flag will be removed.

@markelog @mikesherov Guys, what you decide?

**Comment by hzoo** [comment]
Yeah it's true we wouldn't need it when we add it to be the default.

**Comment by mikesherov** [comment]
I'd like to focus on Esprima 2.3, and getting feature complete there rather than fixing this issue.

**Comment by hzoo** [comment]
Should we close this then?

**Comment by markelog** [comment]
I think we could integrate this error message if you up for it

**Comment by hzoo** [comment]
I was! But now if were just going to remove it anyway a bit later probably better to just to add some more es6 rules.
