### ISSUE TITLE
JSX should be enabled by default

### ISSUE THREAD

**Issue by markelog** [jscs-dev/node-jscs#1294]
This is very common request, es6 too, waiting on es6 though, but i don't want to wait long.

This might require switching parsers, since i don't know any esprima "plugins" or forks that supports jsx.

There is https://github.com/eslint/espree and https://github.com/marijnh/acorn (with jsx plugin).

**Comment by mikesherov** [comment]
There is no need to switch away from Esprima. Full ES6 coming very soon and JSX plugin ability right after that. Espree folks are participating in Esprima meetings about possibilities of unforking and @nzakas has said several times the goal is to make Esprima unnecessary.

If you want to help make JSX in Esprima a reality, come to the Esprima team meeting at 2PM EST today in #esprima-meeting on freenode.

**Comment by mikesherov** [comment]
Sorry, I meant to say the goal is to make Espree unnecessary.

**Comment by Slayer95** [comment]
From <code>README.md</code>

`JSCS — <b>JavaScript</b> Code Style.`

JSX is not JavaScript :| If anything, it should be supported under a flag, not by default.

**Comment by markelog** [comment]
I wonder, what do you think "JS" in "JSX" stands for? JSX is popular extension of ECMAScript, a lot of people use it, a lot of people request it.

We go where the community wants to go.

**Comment by Slayer95** [comment]
In that case, JS is Java o:

Do we have actual numbers? As in relative to the total JSCS userbase?

**Comment by markelog** [comment]
> In that case, JS is Java o:

Link?

> Do we have actual numbers? As in relative to the total JSCS userbase?

I don't know who you would collect these numbers, we have a lot of request for it, in fact, it's one of the most popular request we have.

**Comment by zxqfox** [comment]
:-1: for this because it can be solved via plugins easily.
But :+1: for make it as easy as possible (e.g. `npm i jscs-jsx`).

**Comment by markelog** [comment]
Now you can use `esnext:true` and jsx would work so it seems that logic is enough for everyone
