### ISSUE TITLE
validateIndentation does not work for arrays

### ISSUE THREAD

**Issue by simonauner** [jscs-dev/node-jscs#1295]
The rule `validateIndentation` does not seem to complain about incorrectly indented array items.

.jscsrc:
```
"validateIndentation": 4
```

code:
```
angular.amd.module('app', [
'ui.router',
    'ngAnimate',
    'ngCookies',
   ...
]);
```

I would expect JSCS to complain about indentation of the first array item based on the comment https://github.com/jscs-dev/node-jscs/issues/424#issuecomment-45290926

Yes, no?

Using gulp-jscs 1.6.0 running JSCS 1.12.0 on Mac OSX Yosemite.

**Comment by mikesherov** [comment]
There is currently no canonical indentation style, which is why it's absent from the validateIndentation rule. There are open feature requests for this already, and I'll be tackling it soon! Thanks for contributing!
