### ISSUE TITLE
a `--quiet` option (for use with `--fix`)

### ISSUE THREAD

**Issue by joeybaker** [jscs-dev/node-jscs#1297]
It would be nice to be able to suppress output when running jscs on the command line. This would be useful if you only need to know pass/fail or if you just want to run the `--fix` option but not see any errors.

**Comment by zxqfox** [comment]
Thanks for suggestion. But it looks like a dup.

Related: #425 #962

Planned on 2.0

**Comment by joeybaker** [comment]
wow, sorry, issue search failed me there.

**Comment by zxqfox** [comment]
@joeybaker Np :smirk_cat:
