### ISSUE TITLE
requirePaddingNewLinesAfterBlocks: ignore "});" case

### ISSUE THREAD

**Issue by mnaughto** [jscs-dev/node-jscs#1298]
Just one little annoyance with this rule. Often times, I write code like this:

```js
_.each(items, function(item){
    // do something
});
```

Right now, this results in a style violation, but I don't think it should. To fix the violation, I have to change the code to this:

```js
_.each(items, function(item){
    // do something
}

);
```

And that looks terrible! Can this rule be revised to "pass" a block followed by a closing parent followed by punctuation?

**Comment by hzoo** [comment]
Thanks for contributing! This should be fixed in master already (https://github.com/jscs-dev/node-jscs/commit/ec2f2a24fecf32a97b950ccbc97501bbe353bab0). There hasn't been another release yet though so if you want you can add the commit to your package.json or wait.
