### ISSUE TITLE
Option to ignore new lines after blocks when they're inside object literals

### ISSUE THREAD

**Issue by viveleroi** [jscs-dev/node-jscs#1301]
We require new lines after code blocks, yet we very often describe default options for a class (then merge the user-provided object with these). This means we usually have empty functions as defaults but the jscs check flags them, requiring following new lines.

In order to satisfy the style check, it must look like:

    var configSchema = {
      yes: function() {},

      no: function() {}
    }

This is fairly common in our code, I'd really rather not have to add disable comments each time. It would be nice if there was some sort of `ignoreProperties` option for this too.

I'd like the code to look like this

    var configSchema = {
      yes: function() {},
      no: function() {}
    }

**Comment by markelog** [comment]
Feel free to send us a PR.

cool avatar btw.

**Comment by TheSavior** [comment]
This was added in #1239 I believe.

**Comment by viveleroi** [comment]
We're using v1.12.0. Is that commit included? If so it's either not working or doesn't address this issue. If not, we can update to `#latest`

**Comment by hzoo** [comment]
Looks like it was added 11 hours ago so you'll need to update to `#ab17e8` or `#latest` like you said

**Comment by viveleroi** [comment]
Oops, was looking at when the pr was opened and the first commit happened - not when it merged. My mistake, thanks

**Comment by hzoo** [comment]
Looks like this was added and we never closed this?
