### ISSUE TITLE
variable named async causes problems

### ISSUE THREAD

**Issue by respectTheCode** [jscs-dev/node-jscs#1306]
This appears to be relate to the new es7 `async`.

This is fails "Operator , should stick to previous expression"

```javascript
var async = require("async");

module.exports = async.each.bind(async, values, function (key, cb) {
...
```

But this does not

```javascript
var async = require("async");
var asyncFix = async;
module.exports = async.each.bind(asyncFix, values, function (key, cb) {
...
```

**Comment by hzoo** [comment]
Are you using not esnext and what version of jscs?
Can you run with `--verbose` to get the exact rule?
I don't think the parser supports `async/es7` yet so it probably isn't an issue with that.

**Comment by respectTheCode** [comment]
I am using linter-jscs in atom and it looks like it is using 1.12.0 of jscs. Im not sure how to get it in verbose mode though.

I don't have `esnext: true`.

**Comment by hzoo** [comment]
Oh ok. We just added `verbose: true` in the config in master (so for now you would need to run it from cli), but looking at the message I assume the rule is for `disallowSpaceBeforeBinaryOperators`?

**Comment by respectTheCode** [comment]
It is the `disallowSpaceBeforeBinaryOperators` rule, but it also happens without a `.jscsrc` file.

When I run the cli it doesn't find the error though. So it might be a linter-jscs issue.

**Comment by markelog** [comment]
As far as i can see this code example could be very well be a es3 code, if cli tool doesn't throw for you, then, as you said it, it is a linter issue

**Comment by hzoo** [comment]
@respectTheCode this still an issue?
