### ISSUE TITLE
New Rules: (require|disallow)ObjectShorthand (ES6)

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1308]
[airbnb/javascript#3.5](https://github.com/airbnb/javascript/tree/master#3.5)

I don't know if anyone would want disallowObjectShorthand but we can add that too.

```js
// require
var obj = {
    a,
    handler,
    toString() {},
    *g() {}
};
// disallow
var obj = {
    a: a,
    handler: handler,
    toString: function() {},
    g: function*() {}
};
```

Can have options for methods, properties, or both.

---

Related rule: `requireObjectShorthandFirst`?

> Group your shorthand properties at the beginning of your object declaration.
> Why? It's easier to tell which properties are using the shorthand.

```js
// good
{
  a,
  handler,
  abc: xyz,
  test: test2
}
```

Implementation from dockyard/ember-suave: https://github.com/dockyard/ember-suave/pull/13

**Comment by hzoo** [comment]
@jscs-dev Should I keep adding more ES6 rules as seperate issues or make a issue for ES6 in general so we can discuss and eventually make separate ones?

**Comment by markelog** [comment]
> Should I keep adding more ES6 rules as seperate issues or make a issue for ES6 in general so we can discuss and eventually make separate ones?

Sure thing, we can filter them out with `esnext` label, so separate issues might be overkill, although i would stick to rules that are needed for the presets only.

> Also do we have a roadmap for what we want to do next?

Yeah, that is a pain, basically we need to increase amount of fixable rules, change config in back-compat way and make es6 and jsx to be enabled by default.

/cc @mdevils, @mikesherov, @zxqfox, @mrjoelkemp

**Comment by markelog** [comment]
I would even would go so far and would start using babel and make es6 a primary language of jscs code-base

**Comment by hzoo** [comment]
Ok most of these are from airbnb - any other rules are just potential styles I notice from looking at the es6 features. Yeah it would be cool to use es6 features in jscs (template strings for tests instead of string concat and newlines).

**Comment by markelog** [comment]
> any other rules are just potential styles

be careful, if people don't need it, no need to spend time on it

**Comment by hzoo** [comment]
Yeah I'l keep it in mind - I thought of `validateNewlineInModuleImports` because it was similar to another rule already.

**Comment by zxqfox** [comment]
Not sure why you shouldn't ;-)

**Comment by mdevils** [comment]
+1 for label `esnext`

**Comment by hzoo** [comment]
Moved to https://github.com/jscs-dev/node-jscs/issues/1390
