### ISSUE TITLE
New Rule: disallowVar (ES6)

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1309]
https://github.com/airbnb/javascript/tree/es6#references. Probably would go in a few ES6 presets (when that happens).

- Use `const` for all of your references; avoid using `var`.

> Why? This ensures that you can't reassign your references (mutation), which can lead to bugs and difficult to comprehend code.

```javascript
// bad
var a = 1;
var b = 2;

// good
const a = 1;
const b = 2;
```

- If you must mutate references, use `let` instead of `var`.

> Why? `let` is block-scoped rather than function-scoped like `var`.

```javascript
// bad
var count = 1;
if (true) {
  count += 1;
}

// good, use the let.
let count = 1;
if (true) {
  count += 1;
}
```

**Comment by markelog** [comment]
Well, that is keyword, you know where i'm going with this right :-)

**Comment by hzoo** [comment]
Haha good point. Then

```js
disallowKeywords: {
  es6: ['var']
}
```

**Comment by lukeapage** [comment]
FYI: jshint has implemented this as the (currently undocumented) `varstmt: true` option

**Comment by hzoo** [comment]
Thanks for the info - in this case we aren't making any new rules since `disallowKeywords` and `disallowIdentifiers` already covers those kinds of cases.

**Comment by mrjoelkemp** [comment]
Safe to close then?

**Comment by hzoo** [comment]
I think we were going to add a `new rule option` for `disallowKeywords` and `disallowIdentifiers` (#1305) but we could make a new issue for that.

**Comment by mrjoelkemp** [comment]
Will take that as a yes :) ping to reopen if needed
