### ISSUE TITLE
Create a roadmap

### ISSUE THREAD

**Issue by markelog** [jscs-dev/node-jscs#1318]
It seems we need one, i guess it's on me, would love to anyone to pitch in though.

**Comment by mrjoelkemp** [comment]
Milestones don't suffice?

**Comment by markelog** [comment]
I guess not, there is a lot of confusion around it, even between us.

@mdevils what do you say?

/cc @mikesherov, @zxqfox

**Comment by mikesherov** [comment]
I think we should put out a patch release addressing autofixing issues, then get to work on 2.0.

**Comment by mikesherov** [comment]
I think it's a good idea to have a team meeting in irc for this.

**Comment by zxqfox** [comment]
:+1: Agree.

Also would be nice to have a label to mark candidates for 2.0 before meeting.

**Comment by markelog** [comment]
Sure, need to choose on day & time, i can do it whenever

**Comment by mrjoelkemp** [comment]
@mikesherov can you set something up for this week? Probably during our lunch 12pm EST on Wednesday?

**Comment by mdevils** [comment]
I don't think live chat will work for us as we have different time zones. Maybe let's consider Gitter or something like that?

**Comment by hzoo** [comment]
Should this be closed then?

**Comment by zxqfox** [comment]
@hzoo No, we still don't have roadmap ;-)

**Comment by hzoo** [comment]
Ok since I wasn't sure if we wanted one anymore since there's 2.0 issues and milestones already. (But I would like one anyway)

**Comment by markelog** [comment]
https://github.com/jscs-dev/node-jscs/wiki/Roadmap

If someone wants to add something to that list, please be sure to assignee yourself to that item and be ready to do it in the next week
