### ISSUE TITLE
jscs v1.13.0 reports "Unexpected reserved word" for "import" keyword.

### ISSUE THREAD

**Issue by akash1810** [jscs-dev/node-jscs#1321]
Contents of `.jscsrc` file is:
```json
{}
```
(empty for simplicity of example)

Have a file `test.js` with:
```javascript
import angular from 'angular';
```

`./node_modules/.bin/jscs --esnext test.js` reports:

```bash
Unexpected reserved word at test.js :
     1 |import angular from 'angular';
---------^
     2 |
```

My current fix/workaround is to freeze on version 1.12.0.

**Comment by markelog** [comment]
This is justifies a patch version, you could use <a href="http://jscs.info/overview.html#-esprima-s-">workaround</a> for now 

@mikesherov i remember you said you have couple bugs you want to fix too? Does tomorrow sounds good?

**Comment by markelog** [comment]
@akash1810 or even easier use `esnext` option in the config

**Comment by hzoo** [comment]
I think it's an issue with `esnext` as a cli option. I tested with the config and it works.

**Comment by akash1810** [comment]
@hzoo nice! Thanks all.

**Comment by hzoo** [comment]
Great! And using `--esnext` in cli will be fixed in the next release as well.

**Comment by mikesherov** [comment]
`it.only` was commited accidentally.

**Comment by markelog** [comment]
@mikesherov, please see the full history
