### ISSUE TITLE
No way to combine ignoreFunction and ignoreLineBreak in requireAlignedObjectValues

### ISSUE THREAD

**Issue by adrianheine** [jscs-dev/node-jscs#1324]
While working on [jscsrc-guesser](https://github.com/adrianheine/jscsrc-guesser), I found out that there's no way to combine `ignoreFunction` and `ignoreLineBreak` options for the `requireAlignedObjectValues` rule. That seems to be an arbitrary limitation.

**Comment by hzoo** [comment]
Yeah looking at [it](https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/require-aligned-object-values.js) it only accepts a single string. We could allow it to accept an array or an object with both of those as properties.
```js
requireAlignedObjectValues: {
  "ignoreFunction": true,
  "ignoreLineBreak": true
}
```
Would you like to take this? Should be a few examples from the other rules that allow something like this.

**Comment by markelog** [comment]
Relates to https://github.com/jscs-dev/node-jscs/issues/1303

"requireAlignedObjectValues": {
  "allExcept": [ "function", "lineBreak" ]
}

might be better choice, while conserving back-compat

**Comment by zxqfox** [comment]
@markelog :+1:

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
