### ISSUE TITLE
New rule suggestion: disallowVariableNames

### ISSUE THREAD

**Issue by mzgol** [jscs-dev/node-jscs#1334]
Now that a lot of people are transpiling their code, it'd be useful to be able to blacklist the use of specific variable names.

For example, if a project relies on rest parameters it might be useful to blacklist the `arguments` variable name from even being used so that the following code prints a linting error:
```js
function f() {
    for (let i = 0; i < arguments.length; i++) {
        console.log(arguments[i]);
    }
}
```

Another example is `require`. If someone transpiles their code via Babel, they might want to use ES6 modules everywhere so the following code:
```js
const koa = require('koa');
```
throws as one is expected to write:
```js
import koa from 'koa';
```

This could be handled by a config:
```js
"disallowVariableNames": ["arguments", "require"]
```

**Comment by alawatthe** [comment]
I think we already have what you want. See http://jscs.info/rules.html#disallowidentifiernames. (It is called disallowIdentifierNames and not disallowVariableNames, because it also checks the properties in objects.)

**Comment by mzgol** [comment]
Indeed, thanks!

**Comment by hzoo** [comment]
@mzgol It's a good suggestion - I made an issue for disallowing `arguments` in favor for rest in #1305 and `.apply` for spread in #1326 and the suggestion is the same as here - except to possibly make an option for es6/es5.
