### ISSUE TITLE
Is .es6 files supported? 

### ISSUE THREAD

**Issue by montogeek** [jscs-dev/node-jscs#1338]
I am getting this error when running jscs agains a .es6 file:
```bash
→ jscs --esnext index.es6
No configuration found. Add a .jscsrc file to your project root or use the -c option.
→ jscs -c --esnext index.es6
Config source is corrupted - TypeError: Arguments to path.resolve must be strings
```

Thanks!

**Comment by hzoo** [comment]
Yeah it should be. Add `fileExtensions: true` in your config. http://jscs.info/overview.html#fileextensions

Also `-c` is the config option so you need to pass a path for that. http://jscs.info/overview.html#cli

**Comment by montogeek** [comment]
Actually, it should be an array ```"fileExtensions": [".js", ".jsx"]```
Thanks!
