### ISSUE TITLE
Disable rules with `false` value

### ISSUE THREAD

**Issue by adrianheine** [jscs-dev/node-jscs#1342]
Note that `validateIndentation.includeEmptyLines` accepts `true` and `false`.

**Comment by zxqfox** [comment]
@markelog I'm not sure how we'll resolve this to new format ;-\

**Comment by markelog** [comment]
@zxqfox there is a lot of things to consider in the new format

**Comment by zxqfox** [comment]
@markelog I mean just suboptions for rules. Should we allow `false` for them?

**Comment by adrianheine** [comment]
The funny thing about this is that the rule alters the input and actually sets `includeEmptyLines` to `false` if unset.

**Comment by zxqfox** [comment]
@adrianheine Well, looks like we should drop that assert and allow `false` value.

**Comment by hzoo** [comment]
I don't remember if I made an issue for `false` already. I think we should rename this issue to be general or make a new one if we are going to allow false instead of nulling the options.
