### ISSUE TITLE
requirePaddingNewLinesAfterBlocks uses global state

### ISSUE THREAD

**Issue by adrianheine** [jscs-dev/node-jscs#1343]
`requirePaddingNewLinesAfterBlocks` uses global state for the exceptions, which means you cannot have multiple instances with different settings. Moreover, when `requirePaddingNewLinesAfterBlocks` is configured with `true`, it does not overwrite the exceptions, so you cannot run with `true` after you ran with exceptions in one nodejs run. **Edit:** It actually never resets exceptions.

**Comment by hzoo** [comment]
@TheSavior

**Comment by TheSavior** [comment]
Does this issue come up when you ignore the rule in line in a file? Can you create a test case that fails? I understand that the usage of global state in the rule is likely bad, I just can't think of an example of how you'd be running different configurations on a single nodejs run.

**Comment by adrianheine** [comment]
I'm doing that in [jscsrc-guesser](https://github.com/adrianheine/jscsrc-guesser), which is not the main use case for the rules, obviously. I'll check the inline config thing, though.

**Comment by zxqfox** [comment]
@adrianheine Just interesting: why not `--auto-configure`? http://jscs.info/overview.html#-auto-configure-

**Comment by TheSavior** [comment]
I believe auto-configure only chooses the preset that matches best, not individual rules which it looks like jscsrc-guesser does.

**Comment by adrianheine** [comment]
That's right. I think presets are fine if you actually decided to follow the coding style the preset tries to represent. I don't think it makes too much sense using a preset just because it happens to correspond roughly to what you are doing. Also, I plan on introducing a diff feature, which would allow you to check which rules you follow but have not configured – for example freshly introduced rules. That could also help in updating presets quickly.

**Comment by adrianheine** [comment]
Inline configuration does not run into this issue, since it does not allow you to change the configuration of a rule, it just allows you to disable and enable them. That happens by suppressing error output.

**Comment by hzoo** [comment]
I would like something to help add new rules to your `.jscsrc`. http://csscomb.com/config is pretty cool (although it doesn't allow an existing config and you can't go back).

**Comment by markelog** [comment]
> Also, I plan on introducing a diff feature, which would allow you to check which rules you follow but have not configured – for example freshly introduced rules

That would be awesome! We always have this problems with updating presets.

> I would like something to help add new rules to your .jscsrc. http://csscomb.com/config is pretty cool 

People ask for this, but, personally, i don't see the point, "auto-configure" feature is enough, which probably mean we aren't good of promoting it.

**Comment by hzoo** [comment]
I think anyone would appreciate something to help adding new rules/options whenever there is a new version?

**Comment by TheSavior** [comment]
Can you guys take the conversation about the validity of his tool out of this issue? This is a real bug. I'd love for ideas as to how to write a failing test though.
