### ISSUE TITLE
"disallowSpaceAfterKeywords" rule does not distinguish between 'else' and 'else if'

### ISSUE THREAD

**Issue by samfb** [jscs-dev/node-jscs#1346]
I have this jscs rule:
`disallowSpaceAfterKeywords: ["if", "else", "for", "while", "do", "switch", "try", "catch"]`

An error this produces is:
`Unexpected whitespace between else and if`

That error is incorrect - there *must* be a space between else and if for an 'else if' condition.
There should be an exception added for 'else if'.

**Comment by zxqfox** [comment]
Thanks for a report

**Comment by samfb** [comment]
Normally the 'if' keyword will catch the 'else if' case, but I actually want to use the 'else' case.
There is a rule for disallowSpaceBeforeBlockStatements that accomplishes that case, but the documentation clearly shows 'else' as a valid keyword.

**Comment by markelog** [comment]
@samfb You saying you seeing warning for the:

```js
...
else if(
```
when 
```js
"disallowSpaceAfterKeywords": [ "else" ]
```
? Could you provide the code-example otherwise?

**Comment by samfb** [comment]
I'm seeing the warning with this code:
```
...
}else if(...){
...
}else{
...
```

**Comment by hzoo** [comment]
Did a PR - Ok so

```js
if(x){} else if(x){} else{}
```

is giving an error for `"disallowSpaceAfterKeywords": [ "else" ]` right?

**Comment by samfb** [comment]
That is correct. That code would produce the "Unexpected whitespace between else and if" error.
