### ISSUE TITLE
Update dependencies?

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1347]
`estraverse		^1.9.3	4.1.0` and some others (commander, lodash.assign, browserify, jshint).

**Comment by markelog** [comment]
Yep

**Comment by alawatthe** [comment]
Do we have any policy on when to update dependencies? (E.g. every four weeks, before we release, on minor/major releases of dependencies, ...)

**Comment by mrjoelkemp** [comment]
No policy. Happy to merge PRs with bumped versions and passing tests.

**Comment by hzoo** [comment]
I forgot what we said about `esprima` - I'm assuming leave it for now?

**Comment by mikesherov** [comment]
Leave esprima for now.

**Comment by mikesherov** [comment]
Also, don't bump major versions for now.
