### ISSUE TITLE
Preset definition for 'crockford' coding style should include requireSpacesInAnonymousFunctionExpression

### ISSUE THREAD

**Issue by rjmackay** [jscs-dev/node-jscs#1351]
From http://javascript.crockford.com/code.html:
`If a function literal is anonymous, there should be one space between the word function and the ( (left parenthesis).`

**Comment by markelog** [comment]
Sure thing, would you like to send us a PR?

**Comment by markelog** [comment]
I'd say it more a enhancement then a bug :-)

**Comment by zxqfox** [comment]
Okey! ;-)
