### ISSUE TITLE
Support decorators +  other ES2006 syntax

### ISSUE THREAD

**Issue by olanod** [jscs-dev/node-jscs#1352]
Many people are already using babel and since it now supports decorators, class properties and more it would be great to support that.

**Comment by hzoo** [comment]
Thanks for the request - this is similar to #1344. #1270. I got it working with babel by passing a version of it (modified `babel-eslint`) into the `esprima` option but it still has errors from what I've found so maybe soon.

**Comment by markelog** [comment]
See the <a href="http://jscs.info/overview.html#esnext">esnext</a>

**Comment by olanod** [comment]
Last time I checked, `esnext` option didn't include the ES2016 (ES7) new features like decorators or class properties.

**Comment by markelog** [comment]
If esprima doesn't support it, we can't too.

@hzoo could create a specific issue for your work?

**Comment by hzoo** [comment]
Ok #1353
