### ISSUE TITLE
Supporting ES7/Babel

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1353]
For #1352, #1344, #1270.

My plan is to make `babel` a possible parser to use in the `esprima` option.
I could do a repo for this so you can do `"esprima": "babel-jscs"` or something like that.
Nothing would need to be changed in `jscs` itself.
`babel-jscs` would modify the acorn parser to output into an esprima format and patch `estraverse` (just modifying `babel-eslint` somewhat).

I got it working on an es7 code snippet (the issues linked) and a small project but running it with more rules leads to some errors that still need to be fixed.

**Comment by markelog** [comment]
Created - https://github.com/jscs-dev/babel-jscs

**Comment by hzoo** [comment]
Almost ready to do an initial version - can someone give thoughts on the change in https://github.com/jscs-dev/node-jscs/pull/1369?

**Comment by hzoo** [comment]
@moroshko, @olanod, @ben-ng - If you want to try it out, I created https://github.com/hzoo/babel-jscs for testing (no npm package yet). Will wait and then move to https://github.com/jscs-dev/babel-jscs. You'll need to update `package.json` and your `.jscsrc` to ` "esprima": "./node_modules/babel-jscs"`

```js
{
  "node-jscs": "jscs-dev/node-jscs#master",
  "babel-jscs": "hzoo/babel-jscs#master"
}
```

**Comment by markelog** [comment]
Does it with our tests? We intergrate this in our CI-runs, if it pass, i think we could do the npm package and push to jscs-dev org repo

**Comment by hzoo** [comment]
I still have to figure out how to run the tests (git submodule?) not sure yet. I ran it manually before and got a few issues regarding cli, and quotes (babel infers the quotes will always output the same one).

**Comment by markelog** [comment]
It seems babel-jscs has support for jsx?

**Comment by hzoo** [comment]
Yeah it will parse anything babel supports itself since it will be an option for esprima - `"esprima": "babel-jscs"` (es6, es7, jsx, flow) - mostly through `acorn-to-esprima` transformation and some other stuff

**Comment by markelog** [comment]
So is there anything preventing us from dropping `esprima-harmony-jscs` dep and using `babel-jscs` for `esnext` option?

**Comment by hzoo** [comment]
For me it would be that it hasn't been tested as much yet and not all the tests pass (at the moment) but that shouldn't be too hard to fix.

**Comment by markelog** [comment]
Well, we described this `esnext` option as experimental, although, i fear about `esprimaOptions` param though.

Otherwise jsx and more extensive es6 supports does it for me.

@mikesherov, @zxqfox, @mrjoelkemp, @mdevils thoughts?

**Comment by zxqfox** [comment]
@markelog :+1: for jsx as a plugin for esprima ast. And I'm not sure we need this when we'll support esprima 2.x. Since there I'm not against using it for another library. But it's a revolution, and need to hear @mikesherov about it.

**Comment by rorysaur** [comment]
@hzoo thank you!! :pray: I was trying to set up jscs on a project that uses babel (es6) + flow, and couldn't find any parser that could accommodate both. your package made everything magically work. hope you keep developing it :+1:

**Comment by markelog** [comment]
Just added this feature to 2.0 roadmap

**Comment by mdevils** [comment]
As for me, around Esprima there is a strange situation right now.
* `esprima` supports `ES6`, but it does not support `ES5` without `ES6` (it does not support enabling/disabling features). It also does not support `JSX` and doesn't have plugin interface to write a `JSX` plugin. `esprima-fb` is not planned to be supported.
* `estraverse` supports both `ES5` and `ES6`. And it can be configured to support `JSX`.
* `escodegen` only supports `ES5` (no `ES6` and `JSX` support).
* `escope` supports both `ES5` and `ES6`, but does not support `JSX`.

**Comment by mdevils** [comment]
I hope someone can share his picture on `acorn/babel`.

**Comment by markelog** [comment]
Nice list

> esprima supports ES6

Not fully, plugin interface will come right after full support of the ES6

>  but it does not support ES5 without ES6

ES6 is back-compat, so i don't see an issue there.

Acorn supports es6 and written on es6-dialect also has plugin for jsx, you forgot the estree btw :-). 

Answer for `babel` is kinda obvious :-), but it also has support for ES7 features, like if someone mention possible extension on TC-meeting. But not proposed but only mentioned! It probably be added into the babel for the community response, which scary cool and dangerous at the same time.

In any case, i put all my money on `babel-jscs` here.

**Comment by markelog** [comment]
Hey @hzoo, would you have time to provide pr for this?

**Comment by hzoo** [comment]
What would I need to do for the pr?

**Comment by markelog** [comment]
Basically, pr that proposes to use `babel-jscs` instead of `esprima-fb`

**Comment by deezahyn** [comment]
@hzoo where should I file issues? here:
https://github.com/hzoo/babel-jscs
I tried your branch seems buggy on the validatequotemarks. Its changing my single quotes to double quotes when I use `-f`

**Comment by hzoo** [comment]
@deezahyn Um yeah just file it at https://github.com/hzoo/babel-jscs there until I move it to https://github.com/jscs-dev/babel-jscs. I guess we can just do it whenever.

However for that particular issue about quote marks I documented in the readme already. Not sure what we can do about it @sebmck?

> Rules related to quotes won't work: validateQuoteMarks (Babel infers and transforms quotes to be consistent so you'll need to find another way to enforce this or turn off the parser and run it.)

**Comment by sebmck** [comment]
@hzoo 

> Babel infers and transforms quotes to be consistent so you'll need to find another way to enforce this or turn off the parser and run it.

This is completely unrelated to the parser and is done in the code generator (which `babel-jscs` and `babel-eslint` **don't** use) so this isn't the cause of the issue.

**Comment by hzoo** [comment]
@sebmck Ah ok. I didn't do enough research then.

@deezahyn Yeah you can make an issue for it in the repo or I'l do it later.

@markelog Ok shouldn't be too hard to just replace the parser for esnext.

Seems like it's just
```js
this._esprima = options.esprima || (options.esnext ? babelJscs : defaultEsprima);
```

**Comment by markelog** [comment]
Yeah :-)

**Comment by shepherdwind** [comment]
Why not publish an beta version(`npm publish . --tag beta`), so that we can install with a beta tag.

Install from github, sometimes will be too slow.

**Comment by hzoo** [comment]
Sounds like a good idea (would be good so people can test and find any big issues). I think we're going to release "soon" though :smile:

**Comment by shepherdwind** [comment]
@hzoo That great. Waiting for you beta release.

**Comment by timini** [comment]
I'm trying to enable es7 decorator rules in jscs. Will this help me out?

**Comment by markelog** [comment]
Now you just need to use `esnext: true`
