### ISSUE TITLE
'destructuring expression', `Unexpected token {`

### ISSUE THREAD

**Issue by nschloe** [jscs-dev/node-jscs#1355]
I'm trying to use jscs for a Firefox Add-on project in which I use
```
var { ToggleButton } = require('sdk/ui/button/toggle');
```
The _destructuring expression_ on the left-hand side is recognized by _jshint_ as
```
'destructuring expression' is available in ES6 (use esnext option) or Mozilla JS extensions (use moz).
```
Adding either of the two jshint options suffices.

_jscs_ on the other hand will continue to complain with
```
 Unexpected token {
```
What to do about this?

**Comment by hzoo** [comment]
Similarly to jshint you can use the `esnext` option as well! you can either pass `--esnext` in the cli or put `"esnext": true` in your `.jscsrc` config file. Otherwise you can pass a specific parser (different esprima like `esprima-fb`)

**Comment by nschloe** [comment]
Perfect, thanks.
