### ISSUE TITLE
Style issues

### ISSUE THREAD

**Issue by markelog** [jscs-dev/node-jscs#1358]
> expects valid type instead of Promise * Error[] at lib/checker.js :
   138 | * @param {String} path
   139 | * @param {Function} fileHandler
   140 | * @returns {Promise * Error[]}
---------------------^
   141 | */
   142 |Checker.prototype._processPath = function(path, fileHandler) {

/cc @zxqfox

**Comment by zxqfox** [comment]
`Promise * Error[]` is not valid jsdoc afaik. 
https://github.com/jsdoc3/jsdoc/issues/509

**Comment by markelog** [comment]
Yeah, i read it, as i understand this is not part of the "standart" yet?

**Comment by mrjoelkemp** [comment]
What's the best way to handle this via the jscs-jsdoc plugin? Ignore that style of type or disable specific instances? Or do we have to change them until the spec is updated?

**Comment by markelog** [comment]
I'd say we need understand if "jsdoc" plugin is correct here, if it is, then we should fix the issues, if not, we should correct the check.

**Comment by zxqfox** [comment]
@markelog Yep, there is no standard. If we parsing it — we can stick to something parsable.

Tell me what it means and I tell you if it doesn`t correct.

Personally, I don't see why `*` (star) should be a sign to use for promises when Google Closer and jsdoc3 standard uses `<...>` for that.

Promise is an Object that contains Result or Reject reason, several callbacks and internal state. So why we can't use a standard: `Promise.<?Result, ?Reject>`?

**Comment by mrjoelkemp** [comment]
I'm fine with something like `Promise.<String>` if that's standard. To be clear, this implies that the promise resolves with a string, correct?

**Comment by zxqfox** [comment]
@mrjoelkemp Yep. Just there is a standard for *any* generic objects like `Array.<Object.<String, function(Array.<String>)>>` driven by Google Closure and integrated to jsdoc toolkit 3. But there is no something specific for Promises right now.

btw, I'm using online tool that parses jsdoc: http://kuniwak.github.io/jsdoctypeparser/ and since 1.2.0 it uses PEG, but `*` is still unknown thing. We can shut this exception in our jsdoc plugin, but still it's invalid (or unknown).

**Comment by zxqfox** [comment]
I'd say `{Promise * Error[]}` should be a `Promise.<Error[]>` for a while.

**Comment by markelog** [comment]
> driven by Google Closure and integrated to jsdoc toolkit 3

Enough for me, could you send a PR?
