### ISSUE TITLE
Make jsDoc plugin part of the jscs dist

### ISSUE THREAD

**Issue by markelog** [jscs-dev/node-jscs#1359]
It could be in another repo, but a dependency of jscs.

/cc @zxqfox

**Comment by zxqfox** [comment]
Mmm?

**Comment by markelog** [comment]
Purpose of this ticket is to discuss inclusion of jsdoc rules to the jscs distribution

**Comment by mrjoelkemp** [comment]
"new rule"? Can you further describe what the inclusion entails? Is this for the website?

**Comment by markelog** [comment]
"new rule" in sense of lack of such rule(s) in the current jscs distro

**Comment by mrjoelkemp** [comment]
So you want users to be able to use jscs-jsdoc from jscs directly. Got it. 

What is painful about the current solution of it being an external plugin? i.e. What are the benefits? The separation of concern is clear as it stands.

**Comment by markelog** [comment]
> What is painful about the current solution of it being an external plugin?

Nothing painful, it would improve convenience though, and improve popularity of such rule(s), since we would document it on the site and could use them in the presets.

> The separation of concern is clear as it stands.

Separation would stay, since rule(s) would be in another repo.

**Comment by zxqfox** [comment]
> since we would document it on the site and could use them in the presets.

Mmm, but we can document them without inclusion into jscs dist, no?
I'm just trying to find a way to write other plugins with documenting at jscs.info.

**Comment by markelog** [comment]
> Mmm, but we can document them without inclusion into jscs dist, no?

That would be a complicated task.

> I'm just trying to find a way to write other plugins with documenting at jscs.info.

That might be unnecessary

**Comment by mrjoelkemp** [comment]
Plugins are in dedicated repos though, so they could also have dedicated github pages that we could link to within our overview.

What we're saying, in a more general sense, is that org-owned plugins are likely to be brought into the core (unifying the config, not the code). 

Do we intend on keeping the `jsDoc` key as part of the configuration or flattening it to the main jscsrc level with this integration?

**Comment by zxqfox** [comment]
I'd say, if we want to show docs on jscs.info and/or build dist with it we should be sure in
- rules inside plugin are the first class rules (there are some dirty things that couldn't be done without changes in jscs core. e.g. jscs-dev/jscs-jsdoc#61);
- docs formatted as well as in core;
- the same support as in core.

E.g. atm it's not easy to use plugins for projects via samba/afp. IDE plugins looking for a global jscs and failing on searching project plugins. And also it's hard to use different versions of jscs for different projects. Etc.

So I'm not sure that I've completely got what you suggesting to do.

**Comment by zxqfox** [comment]
About formatting docs: we just need a convention for that.

> Do we intend on keeping the jsDoc key as part of the configuration or flattening it to the main jscsrc level with this integration?

@mrjoelkemp Better to have namespaces for them because rule names can conflict. But I'm still waiting for new config format, and hope that it will reduce the count of possible (wrong) ways.

**Comment by markelog** [comment]
Just added this feature to 2.0 roadmap

**Comment by markelog** [comment]
@zxqfox do you have time to provide pr for this?
