### ISSUE TITLE
Aggregate and simplify rules

### ISSUE THREAD

**Issue by markelog** [jscs-dev/node-jscs#136]
Currently, jscs has 49 rules (not counting non-esprima options) and will have more i suspect, much more, most of these rules are pretty simple and can take only one or two possible values like `true/false`, some rules are complete opposite of each other, for example `requireSpaceAfterKeywords`, `disallowSpaceAfterKeywords`, some does not have their significant other, like `disallowSpacesInsideParentheses` doesn't have `requireSpacesInsideParentheses` some complement each other, eg `disallowSpacesInsideArrayBrackets`, `disallowSpacesInsideParentheses`, and so forth...

This amount of rules, their incompleteness could be overwhelming to set up, change and support.

At the beginning, when amount of rules was low, it was simpler and faster to add more features then try to unify them, i think now or in the <a href="https://github.com/mdevils/node-jscs/issues/102">near future</a> it would makes sense to give them more structure.

This –

```js
"requireSpaceAfterKeywords": ["if"],
"disallowSpaceAfterKeywords": ["else"],
"requireSpacesInFunctionExpression": { "beforeOpeningRoundBrace": true, "beforeOpeningCurlyBrace": false },
"disallowMultipleVarDecl": true,
```

could become 

```js
"space after keywords": {
	"require": ["if"],
	"disallow": ["else"]
},
"spaces in function expression": {
	"require": "before opening brace",
	"disallow": "before opening curly brace"
},
"multiple var decl": false

```
or 

```js
"require": {
	"space after keywords": ["if"],
	"spaces in function expression": "before opening brace"
}
"disallow": {
	"space after keywords": ["else"],
	"spaces in function expression": "before opening curly brace",
	"multiple var decl": true,
}
```
or
```js
"require": [
	{ "space after keywords": ["if"] },
	{ "spaces in function expression": "before opening brace" }
],
"disallow": [
	{ "space after keywords": ["else"] }, 
	{ "spaces in function expression": "before opening curly brace" },
	"multiple var decl"
]
```

Or other formats could be adopted, goal is to make rules consistent with each other, if something is allowing something, something could declare the opposite.
If this idea is acceptable, i propose to figure out the new format and what rules are missing.

Although this is pretty big change, but of course, current format should be supported too.

**Comment by hzoo** [comment]
Yeah I'm forgetting to update all the function rules - there's `(require|disallow)spacesIn` `functionExpression`, `anonymousFunctionExpression`, `namedFunctionExpression`, `functionDeclaration`, `function`

`functionExpression`, `anonymousFunctionExpression`, `namedFunctionExpression` are basically the same code except for the `node.id` check

**Comment by hzoo** [comment]
We can close this or #698 right?

**Comment by hzoo** [comment]
Just closing this in favor of #698 for less duplication.
