### ISSUE TITLE
  [feature request] disallow-multiple-spaces - but ignore inline comments

### ISSUE THREAD

**Issue by bigmonkeyboy** [jscs-dev/node-jscs#1360]
Issue #1059 introduced disallow-multiple-spaces .... could there be an option to allow multiple space if the rest of a line is a comment ?  EG - allow this
    
       var foo = "bar";                // I want to
       var bar = "something else";     // keep comments aligned
       var other = "and again";        // and away from the code

while still enforcing the single space rule in the code

**Comment by bigmonkeyboy** [comment]
Found there is an allowEOLComments option....  not mentioned in the docs at all...
So Issue is now - can it be added to the docs ?

**Comment by markelog** [comment]
Would you like to do that?
