### ISSUE TITLE
junit reporter generates empty xml file

### ISSUE THREAD

**Issue by btilford** [jscs-dev/node-jscs#1368]
When all rules pass the junit reporter is generating an empty file. Either it should output a valid xml file or not create the file. Tools like Jenkins that would try to read this file will fail the build if the file is 0 bytes.

**Comment by markelog** [comment]
Sorry, for responding so, so late, i see this result for empty results - 

```xml
<?xml version="1.0"?>
<testsuite name="JSCS" tests="1" failures="0">
  <testcase name="input" failures="0"/>
</testsuite>
```

Do you see a different picture?

**Comment by btilford** [comment]
Yeah we had 0 byte files. We do use concurrent so if the file is created before it's used and some other parallel task fails the build that might explain it.

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
