### ISSUE TITLE
Support ignoring of a single line with a trailing comment

### ISSUE THREAD

**Issue by lpil** [jscs-dev/node-jscs#1372]
Hello!

The main thing that prevents us from being able to use jscs at work is that jscs doesn't have the ability to ignore a single line with a trailing comment, like jshint does:

```javascript
var x = 1
var y = 2 // jshint ignore:line
var z = 3
```

Here the missing semicolon on the first and third line will be reported, but the second will not.

It would be great to have the same feature in jscs.

Thanks,
Louis

**Comment by SimenB** [comment]
I agree that single line exclusion would be sweet, but you can almost achieve this now.

```js
var x = 1
// jscs:disable requireSemicolons
var y = 2
// jscs:enable requireSemicolons
var z = 3
```

Or just `// jscs:disable/enable` to hit all rules

**Comment by markelog** [comment]
@lpil would you like to tackle this one?

**Comment by lpil** [comment]
@jonnyarnold Shall we have a look?
