### ISSUE TITLE
Internal error in requireDollarBeforejQueryAssignment

### ISSUE THREAD

**Issue by aknuds1** [jscs-dev/node-jscs#1373]
```
[info] jscs results in errors
[info]   requireDollarBeforejQueryAssignment @ line 1 char 0
[info]     Error running rule requireDollarBeforejQueryAssignment: This is an issue with JSCS and not your codebase.
[info] Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
[info] TypeError: Cannot read property 'indexOf' of undefined
[info]     at /Users/arve/Projects/gradlehub/portal/node_modules/jscs/lib/rules/require-dollar-before-jquery-assignment.js:112:24
[info]     at Array.forEach (native)
[info]     at Object.JsFile.iterateNodesByType (/Users/arve/Projects/gradlehub/portal/node_modules/jscs/lib/js-file.js:426:42)
[info]     at Object.module.exports.check (/Users/arve/Projects/gradlehub/portal/node_modules/jscs/lib/rules/require-dollar-before-jquery-assignment.js:72:14)
[info]     at null.<anonymous> (/Users/arve/Projects/gradlehub/portal/node_modules/jscs/lib/string-checker.js:141:22)
[info]     at Array.forEach (native)
[info]     at StringChecker._checkJsFile (/Users/arve/Projects/gradlehub/portal/node_modules/jscs/lib/string-checker.js:137:31)
[info]     at StringChecker.checkString (/Users/arve/Projects/gradlehub/portal/node_modules/jscs/lib/string-checker.js:117:14)
[info]     at Object.checkSource (/Users/arve/Projects/gradlehub/portal/node_modules/jscs-loader/index.js:88:24)
[info]     at Object.<anonymous> (/Users/arve/Projects/gradlehub/portal/node_modules/jscs-loader/index.js:137:19)```

**Comment by hzoo** [comment]
Could you also post a code snippet and jscs version? From the stack trace the rule is `requireDollarBeforejQueryAssignment` and `varName` is `undefined`.

**Comment by aknuds1** [comment]
Hm, I've tried running jscs by itself on the file, then the bug isn't triggered, maybe there's a bug in jscs-loader. Will try to find out...

The jscs version is 1.13.1 btw.

**Comment by aknuds1** [comment]
@hzoo I've traced it to line 80 of rules/require-dollar-before-jquery-assignment.js. Problem is that `left.name` is undefined, any idea why this might be? My log of the value of `left`:
```
[info] left:  { type: 'ObjectPattern',
[info]   properties:
[info]    [ { type: 'Property',
[info]        key: [Object],
[info]        value: [Object],
[info]        kind: 'init',
[info]        method: false,
[info]        shorthand: true,
[info]        computed: false,
[info]        range: [Object],
[info]        loc: [Object],
[info]        parentNode: [Circular],
[info]        parentCollection: [Circular] },
[info]      { type: 'Property',
[info]        key: [Object],
[info]        value: [Object],
[info]        kind: 'init',
[info]        method: false,
[info]        shorthand: true,
[info]        computed: false,
[info]        range: [Object],
[info]        loc: [Object],
[info]        parentNode: [Circular],
[info]        parentCollection: [Circular] } ],
[info]   range: [ 1164, 1181 ],
[info]   loc:
[info]    { start: { line: 35, column: 10 },
[info]      end: { line: 35, column: 27 } },
[info]   parentNode:
[info]    { type: 'VariableDeclarator',
[info]      id: [Circular],
[info]      init:
[info]       { type: 'Identifier',
[info]         name: 'value',
[info]         range: [Object],
[info]         loc: [Object],
[info]         parentNode: [Circular],
[info]         parentCollection: [Object] },
[info]      range: [ 1164, 1189 ],
[info]      loc: { start: [Object], end: [Object] },
[info]      parentNode:
[info]       { type: 'VariableDeclaration',
[info]         declarations: [Object],
[info]         kind: 'let',
[info]         range: [Object],
[info]         loc: [Object],
[info]         parentNode: [Object],
[info]         parentCollection: [Object] },
[info]      parentCollection: [ [Circular] ] },
[info]   parentCollection: [ [Circular] ] }
```

**Comment by hzoo** [comment]
Could you post the actual code that leads to the error if possible? Based on `ObjectPattern` it looks like you are using es6? It's possible this rule doesn't account for that so we'll have to change it.

**Comment by aknuds1** [comment]
@hzoo I got it now, I had to get hold of the transpiled code since this is what jscs runs agains:
```
let Receipt = () => {
  Promise.all(R.map((subsystem) => loadData(subsystem, token, uuid), ['vcs']))
    .then((values) => R.forEach((value) => {
      let {subsystem, data} = value;
    }));
};
```

This reproduces the error for me.

**Comment by aknuds1** [comment]
I think I was confusing originally which code was triggering the error, sorry.

**Comment by hzoo** [comment]
Ok great it's probably `let {subsystem, data} = value;` then.

Since this code isn't really related to jQuery at all - maybe it would be better to check the presence of the `$` token before the other checks? We need to handle this case anyway but yeah that could be useful too. @TheSavior

**Comment by TheSavior** [comment]
It looks like we should add above this line: https://github.com/jscs-dev/node-jscs/blob/8cc2ba0b33175132ca83b3aa3d95be385805eadc/lib/rules/require-dollar-before-jquery-assignment.js#L79

A check for `token.id.type` which would branch as it is now for `identifier` and add a new branch for `ObjectPattern`. Happy to receive pull requests. :)

**Comment by zxqfox** [comment]
![image](https://cloud.githubusercontent.com/assets/677518/7616983/02800744-f9b1-11e4-887a-31a6468f71a7.png)

I feel that error is everywhere.

**Comment by tsteuwer** [comment]
I am also having this issue. If no one grabs it I'll make @TheSavior 's change and submit a PR.

**Comment by mrjoelkemp** [comment]
@tsteuwer A PR is very welcome. Let us know if you have any questions.

**Comment by markelog** [comment]
@tsteuwer still interested?

**Comment by tsteuwer** [comment]
@markelog yes, ty for reminding me. I'll do it when I get home tonight

**Comment by tsteuwer** [comment]
So I messed with this last night and was unable to remember how I got it to happen (almost 30 days ago). I tried using the code above but it doesn't cause the issue for me.

**Comment by tsteuwer** [comment]
Arg, didn't mean to hit save. I'll mess with it at work tomorrow and see if I can get it to happen somewhere

**Comment by SimenB** [comment]
I threw together #1636 real quick. Doesn't do anything except add a failing test for now, but you know... :laughing:
