### ISSUE TITLE
Document Migration guide from JSHint

### ISSUE THREAD

**Issue by mikesherov** [jscs-dev/node-jscs#138]
Since #102 is now completed, we should document a migration guide from JSHint. This probably depends on figuring out some better documentation too, as outlined in: https://github.com/mdevils/node-jscs/issues/129

**Comment by markelog** [comment]
Because:
1. jshint is pretty slow of removing style related options, 
2. no ones likes to document things and because 
3. this open for a year now,

I think it safe to say this will never be documented. Plus footnotes at the rules page http://jscs.info/rules.html is more or less enough

**Comment by mikesherov** [comment]
Yeah, Agreed.
