### ISSUE TITLE
Update esprima / use esprima 2.x

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1382]
Since we have esprima, and custom esprima-harmony - I think we are planning on updating when `esprima@2.3.0` comes out?

Also related: if we update esprima - what will we do with `esnext: true`?

Related: #1376, #1377, #1290

**Comment by markelog** [comment]
I'd say `esnext: true` should have ability to parse babel code :-). 

The bigger problem is to support `jsx` by default, which probably not gonna happen soon.

**Comment by hzoo** [comment]
I'm ok with pushing an initial version of `babel-jscs` after https://github.com/jscs-dev/node-jscs/pull/1369 gets merged/released - I suppose 1.14.0 then?
