### ISSUE TITLE
New Rule: disallowNodeTypes

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1389]
Ref https://github.com/jscs-dev/node-jscs/issues/1385#issuecomment-102881542.
> Maybe we should have a disallowLabelStatements rule

So instead of a one off rule (`disallowLabelStatements`), we can do the same as `disallowIdentifierNames`, and `disallowKeywords`? Although I don't know what other statements we would want to disallow that is like this (since most would be keywords)

Need a better name - @ljharb?

Would take an array of strings from: https://github.com/jquery/esprima/blob/master/esprima.js#L108-169

`"disallowASTStatements": ["LabelStatement"]`
`"disallowNodeTypes": ["LabelStatement"]`

**Comment by ljharb** [comment]
Sure, I like that.

**Comment by mikesherov** [comment]
`disallowNodeTypes`
