### ISSUE TITLE
Spacing for comments

### ISSUE THREAD

**Issue by Famlam** [jscs-dev/node-jscs#139]
[feature request]

It would be nice to have options to enforce the spacing of comments in code. E.g.,
```javascript
var a = b; // does not stick to the code
var a = b;// sticks to the code
var a = function(b /* comment sticks right */, c /* comment sticks right */) {}
var a = function(b/*comment sticks left*/ , c/* comment sticks left*/ ) {}
var a = function(b/* comment sticks left & right */, c/* comment sticks left & right */) {}
var a = function(b /* comment doesn't stick */ , c /* comment doesn't stick */ ) {}
// newline comments are always valid on the left side
/* newline comments are always valid on the left side*/
var a = b; /* comments followed by a newline are always valid on the right side */ 

```

This request has two reasons:
1. nice, consistent styling
2. to fix issues with `Illegal space before closing round bracket at input` if `"disallowSpacesInsideParentheses": true`  is used, for code like `function(el /* comment */, i /* comment */) {}` or `if (this /*strict mode unsupported*/) {}`

**Comment by markelog** [comment]
This issue has been open more than a month without supported PR for it. 

Unfortunately, we don't have the resources to implement rules that could not be included in any of the supported [presets](https://github.com/jscs-dev/node-jscs/tree/master/presets) (if it could be, please point that out).

However, if you or anybody else submit PR for it, we will gladly consider it.
