### ISSUE TITLE
New Rules: port rules from dockyard/ember-suave (ES6)

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1390]
We can port over some rules created by awesome folks from `dockyard/ember-suave`.

https://github.com/dockyard/ember-suave/pull/10#issuecomment-101069954

@rwjblue
> Would love to move the custom rules upstream.

----

Rules: https://github.com/dockyard/ember-suave/tree/master/lib/rules

- [ ] `requireArrayDestructuring`: https://github.com/dockyard/ember-suave/commit/5db73305cfa05b4856f89db6bb4fb1480ac9a665

```js
// bad
const colors = ['red', 'green', 'blue'];
const first = colors[0];

// good
const colors = ['red', 'green', 'blue'];
const [first] = colors;
const [red, green] = colors;
const [, , blue] = colors;
```

- [ ] `requireObjectDestructuring`: https://github.com/dockyard/ember-suave/commit/9b975e68f1c52aeda1848cba857b94a726e2e1a7

https://github.com/dockyard/ember-suave/issues/35

```js
"requireObjectDestructuring": {
  "allExcept": ["get", "set"]
}
```

```js
// bad
let foo = SomeThing.foo;
let bar = SomeThing.Baz.bar;

// good
let { foo } = SomeThing;
let { bar } = SomeThing.Baz;

let someVariableName = SomeThing.propertyWithDifferentName;

const get = SomeThing.get;
const set = SomeThing.set;
```

https://github.com/dockyard/ember-suave/blob/master/lib/rules/require-enhanced-object-literals.js

- [ ] `requireEnhancedObjectLiterals`, `requireObjectShorthand`, `requireShorthandObjectMethods`, `requireShorthandObjectProperties` (can change the name)

```javascript
let bar = "adsf";

// bad
let foo = {
 bar: bar
};

// bad
let foo = {
  bar: function() {}
};

// good
let foo = {
  bar() {}
};
```

- [ ] `requireObjectShorthandFirst`

> Group your shorthand properties at the beginning of your object declaration.
> Why? It's easier to tell which properties are using the shorthand.

```js
// good
{
  a,
  handler,
  abc: xyz,
  test: test2
}
```

**Comment by markelog** [comment]
It seems it was done already
