### ISSUE TITLE
Unexpected behavior of validateIndentation on object with function in property

### ISSUE THREAD

**Issue by irnc** [jscs-dev/node-jscs#1391]
Given the rules:

```json
{
  "validateIndentation": 2
}

```

Following code passes validation, while it is expected to not.

```js
a({
    b: function () {
    return 1;
  }
  });

```

This specific case might be fixed by issue #806. But if `b` symbol is placed at anything other than 2 or 4 position, jscs will complain about `Expected indentation of 2 characters [...]` at this line. Which suggests that objects are checked by `validateIndentation` rule.

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
