### ISSUE TITLE
"fileExtensions" ignored for certain file.

### ISSUE THREAD

**Issue by aliosv** [jscs-dev/node-jscs#1394]
"fileExtensions": [".js"]
````
jscs test.css  // will lint
````
i try to add in "excludeFiles" pattern ````"**/!(*.js)"```` but it not match correct(example: test.json - true).

**Comment by mrjoelkemp** [comment]
Hey @aliosv. Thanks for reporting. Is there an existing  test for this? If not, would you be open to submitting a failing test or a PR to fix this?

**Comment by aliosv** [comment]
@mrjoelkemp, #1405

**Comment by zxqfox** [comment]
@aliosv Looks like solution ;-)
