### ISSUE TITLE
letter case question for 'l' in 'requirePaddingNewlinesBeforeKeywords'

### ISSUE THREAD

**Issue by ZuBB** [jscs-dev/node-jscs#1399]
What was the reason for lowercase 'l' (..newline..) in this option?

**Comment by hzoo** [comment]
I don't think there's any reason - we just didn't catch that. we're planning on fixing these consistency issues in 2.0

**Comment by ZuBB** [comment]
thanks for info. Do you have any rough assumption when 2.0 will will be ready/shipped? (I saw in milestones page that for now it does not have that date)

**Comment by hzoo** [comment]
We can also change it to be consistent now if its still backwards compatible but we'll have to do cleanup in 2.0. And I don't think we know about the 2.0 release yet - at least one more release before that?

**Comment by ZuBB** [comment]
I think we can wait for new name till 2.0 whenever it will happen.

thanks again for info
