### ISSUE TITLE
AlignedObjectValues does not work with ComputedPropertyName

### ISSUE THREAD

**Issue by jfelchner** [jscs-dev/node-jscs#1404]
ES6 has the ability to use computed property names in object literals.

https://people.mozilla.org/~jorendorff/es6-draft.html#sec-object-initializer

Example:

```javascript
myKey = 'myKeyName';

myObject = {
  [myKey]  : 'myKeyValue',
  otherKey : 'myOtherValue',
};
```

Results in `myObject` having a value of:

```javascript
{
  myKeyName : 'myKeyValue',
  otherKey  : 'myOtherValue',
}
```

Unfortunately the alignment check considers the above code to be out of alignment.  Presumably due to the fact that it's ignoring the `[]`.

**Comment by jfelchner** [comment]
Additionally the check that verifies whether there's a space after the object literal key also throws an error because it sees the `]`.  Not sure if you want me to open up another ticket for that one.

**Comment by hzoo** [comment]
Thanks for the report! Yeah a lot of rules haven't been remade to account for ES6 yet (working on a lot of them now). Yeah you can do a separate issue for the other rule.
