### ISSUE TITLE
Ensure consistency of all rules using atLeast/Exactly/atMost for tokenAssert

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1409]
Ref https://github.com/jscs-dev/node-jscs/pull/1380#issuecomment-102521538

Some rules may assert **exactly** a single space, and others assert **at least** a single space

**Comment by zxqfox** [comment]
Just thought: why not to check this automatically with our custom rules for jscs?

**Comment by hzoo** [comment]
@zxqfox what do you mean by our custom rules?

**Comment by zxqfox** [comment]
@hzoo I mean to make an internal plugin or just a set of rules to check subject of the issue.

**Comment by markelog** [comment]
It seems it was already been done
