### ISSUE TITLE
new maximumLineLength option

### ISSUE THREAD

**Issue by clayreimann** [jscs-dev/node-jscs#1412]
It would be nice if [maximumLineLength](http://jscs.info/rule/maximumLineLength.html) had an option `allowMethodDeclarations` which would exempt lines like the following. It would default to `false` for backwards compatibility.

```
function myCoolFunctionWith(descriptiveArgumentName1, descriptiveArgumentName2, descriptiveArgumentName3) {
```
or
```
  _removeSingleLeaf(rootModel, rootProp, rootInstance, leafModel, leafProp, leafInstance, watcher) {
```

I can take a pass at this in the near future.

**Comment by zxqfox** [comment]
@clayreimann :+1: would be nice, thanks!

**Comment by mrjoelkemp** [comment]
The value of allExcept: 'parameters' seems applicable. For this rule, however, we'd need to also pass a line length value. @markelog how would that work in the new format?

**Comment by zxqfox** [comment]
Looks like `{ value: \d+ }` or something

**Comment by markelog** [comment]
it seems

```js
maximumLineLength: {
  value: 40,
  tabSize: 1,
  allExcept: [ ... ]
}
```

**Comment by markelog** [comment]
And obviously deprecate `allow` values

**Comment by clayreimann** [comment]
@mrjoelkemp what do you mean by `allExcept: 'parameters'`. Is your thought that we wouldn't exempt the length of the parameters, just exempting the length of the method name? Because that doesn't seem too useful to me.

**Comment by zxqfox** [comment]
@clayreimann It's just about naming, all the rest is what you described above.

**Comment by markelog** [comment]
@clayreimann is this common situation in your code?

**Comment by clayreimann** [comment]
The long method definition lines? Yes, once you get more than a couple parameters. Perhaps it's my Obj-C verbosity creeping in though. I just really don't like adding line breaks to my method definitions. And to add insult to injury jscs requires that the enable/disable don't have matching indentation if you just want to wrap the method definition line.

**Comment by markelog** [comment]
:-), i just afraid we end up adding exceptions for every possible language construction.

**Comment by mrjoelkemp** [comment]
I'd prefer to call it allExcept: 'functionSignature' but that seems overly
wordy (though the most accurate).

**Comment by markelog** [comment]
@clayreimann would you like to implement aforementioned logic?

**Comment by clayreimann** [comment]
I was planning on doing it this weekend 

—Clay

On May 30, 2015, at 12:07 AM, Oleg Gaidarenko <notifications@github.com> wrote:

@clayreimann would you like to implement aforementioned logic?

**Comment by markelog** [comment]
Coolballs!

**Comment by mikesherov** [comment]
FWIW, I'm against adding this option. The current options for this rule are for unavoidable situations.

The point of this rule is to force contributors to introduce line breaks in these situations.

Anyway, that's my two cents. We'll see what happens if there's a pull request.

**Comment by clayreimann** [comment]
@mikesherov All the current options for this rule are avoidable by wrapping the line in question with `// jscs:maximumLineLength:disable/enable`, which is what I'm doing now with my method definitions. 

That being said, if this option doesn't jibe with the direction/style that the project espouses then feel free not to accept #1418.

**Comment by markelog** [comment]
I would let people to add everything they want in that exception list :-)
