### ISSUE TITLE
requireArrowFunctions: create more exceptions

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1413]
Ref original: https://github.com/jscs-dev/node-jscs/issues/1383

In es6 strict mode/babel, Arrow functions refer to the outer level `this`. 

In ES6 modules the top level this is `undefined`.  If you want a function with its own this value, you cannot use an arrow function. (maybe that could even be a rule? can't use arrow function with `this` on top level scope)

Two issues for this (I think)?

- shouldn't error when setting prototype or method (not an issue I suppose if you only use classes)

```js
function MyFunc(a) {
  this.a = a;
}
MyFunc.prototype.methodHere = function(a) {};
MyFunc.method2 = function(a) {}
```

- shouldn't error in object literal (should use method shorthand syntax instead, because otherwise this becomes undefined)
```js
var a = {
  b: 1,
  normalFunction: function() { return this.b; },
  arrowFunc: () => { return this.b; },  // undefined.b;
  methodShorthand() { return this.b; }
};
var a.arrow = () => { return this.b }; // undefined.b;
```

So really this rule would allow you to replace all function expressions that don't have this as well as whenever you are using .bind(this) or var x = this?

https://goo.gl/sOxDk1

**Comment by hzoo** [comment]
Not sure if this is a new rule value or just a bug and should be added in by default? And thanks for adding the shortlink.

**Comment by markelog** [comment]
I'd say it should default behaviour

**Comment by hzoo** [comment]
I think it might be too complicated to search for `this` in a function so maybe it should just skip all `Properties` and `AssignmentExpressions`?
