### ISSUE TITLE
requireTemplateStrings: add more checks

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1416]
Right now we check for `Identifier` and `BinaryExpression`

There might be more based on these?

```js
this.toIcon(suit) + ' Card-suit'; // node.left.type === 'CallExpression'
card.value + ' is a point card'; // node.left.type === 'MemberExpression'
```

Ref original: https://github.com/jscs-dev/node-jscs/issues/1330

**Comment by mikesherov** [comment]
Why do we check for anything other than binary expression? Seems like unnecessary complication of this rule. If we're concerned about false positive on string + string, then we should at most make it be string + !string rather than a list of node types being added.

**Comment by hzoo** [comment]
Maybe we can check string + string as well then? 'a' + 'b'  -> `ab`

**Comment by michelle** [comment]
@hzoo, a case against checking string + string: https://github.com/jscs-dev/node-jscs/pull/1610

**Comment by brzpegasus** [comment]
You could still check for string + string, but make an exception for string concatenations that span multiple lines; perhaps something along these [lines](https://github.com/dockyard/ember-suave/blob/master/lib/rules/require-template-strings-for-concatenation.js#L23-L27)?

Basically, this is not okay:

```js
const value = 'a' + 'b';
```

but this is:

```js
const value = 'JavaScript Code Style JSCS is a code style linter for ' +
  'programmatically enforcing your style guide.';
```

**Comment by mrjoelkemp** [comment]
@brzpegasus Thanks for the suggestion. This seems like another possible value: `allExcept: ['multiLineStrings']`. It's a stricter form of `allExcept: ['stringConcatenation']`

**Comment by mikesherov** [comment]
Hmm... I think we can take @brzpegasus 's suggestion without having to introduce a new option.
