### ISSUE TITLE
autofix allows edge case to be on one line even if requireBlocksOnNewline is set to true

### ISSUE THREAD

**Issue by AurelioDeRosa** [jscs-dev/node-jscs#1417]
Hi.

I know the issue I'm reporting is a bit of an edge case and maybe it'll be eventually labelled as "wontfix". However, I was playing with a few weird conditions to test the autofix feature. I set the `requireBlocksOnNewline` to `true` and tested the following code:

```js
if (prop) { /* Do something here with prop... */ } else { return; }
```

I'd expect the code to be formatted as follows:

```js
if (prop) {
   /* Do something here with prop... */
} else {
   return;
}
```

However, this is how it's actually formatted:

```js
if (prop) { /* Do something here with prop... */ } else {
   return;
}
```

The reason is, of course, that a comment is not considered as a block, but it still feels weird.

**Comment by mikesherov** [comment]
Thanks for contributing! We'd be glad to accept a patch for this!

**Comment by oredi** [comment]
@mikesherov 

I was trying out the implementation for this and I found that once implemented it will break the string-checker test for the crockford. I extracted a portion of the crockford code below that fail the tests. For backward compatibility I was wondering if it might be a better idea to add a third option for this rule that takes an object with the a boolean flag property to indicate checking comments and an integer value for specifying the min statements

    obj = {
        method: function () { // requireSpaceBeforeObjectValues
            return this.datum; // requireDotNotation
        },
        datum: 0
    };
