### ISSUE TITLE
Wrong expected indentation with an arrow function

### ISSUE THREAD

**Issue by pgilad** [jscs-dev/node-jscs#1419]
I get wrong expected indentation on this code:
```js
$elm.one('hidden.bs.modal', () => {
        let model = slaveForm.model;
        if (isSaved) {
            model = model.clone();
        }
        slaveForm.close();
        this.model.set('test', model);
        slaveForm.remove();
        $elm.remove();
        this.render();
    })
    .find('.modal-body')
    .html(slaveForm.render().el);
```

But the same exact code, but with a regular function instead of an arrow function is deemed correct:
```js
$elm.one('hidden.bs.modal', function () {
        let model = slaveForm.model;
        if (isSaved) {
            model = model.clone();
        }
        slaveForm.close();
        this.model.set('test', model);
        slaveForm.remove();
        $elm.remove();
        this.render();
    })
    .find('.modal-body')
    .html(slaveForm.render().el);
```

Running with minimal `.jscsrc`:
```json
{
    "validateIndentation": 4,
    "esnext": true
}
```

**Comment by zxqfox** [comment]
@mikesherov What you think about trying to move out `validateIndentation` core to separate module or bunch of them?
It looks like a huge code base already that needs a lot of tests. Also it'd be nice to have some abstraction layer between AST and rule itself. I believe we can drastically reduce amount or errors with that.

**Comment by mikesherov** [comment]
The validateIndentation code doesn't consider arrow functions yet. I'll fix this.

**Comment by mikesherov** [comment]
@zxqfox, yes it can be done but I don't think it's necessary for this issue. Something like adding validation for call expressions or arrays are more appropriate for that though.

**Comment by talamaska** [comment]
Any news about this?

**Comment by markelog** [comment]
No, @mikesherov seems busy with outer stuff, you welcome to tackle though

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
