### ISSUE TITLE
No space before colon for requireAlignedObjectValues if disallowSpaceAfterObjectKeys is set

### ISSUE THREAD

**Issue by dreef3** [jscs-dev/node-jscs#1420]
Hi,

I'm wondering is there a way to implement such behavior. Looks like this change would require to pass current configuration (or just a list of rules) to the rule's `configure` method. Is it a bad thing to do?

Example configuration:
```javascript
"requireAlignedObjectValues": "all"
```
##### Invalid
```js
var x = {
    a : 1,
    bcd : 2,
    ef : 'str'
};
```

Without `"disallowSpaceAfterObjectKeys": true` (current behavior):

##### Valid
```javascript
var x = {
    a   : 1,
    bcd : 2,
    ef  : 'str'
};
```

With `"disallowSpaceAfterObjectKeys": true`:
##### Valid
```js
var x = {
    a  : 1,
    bcd: 2,
    ef : 'str'
};
```

Here's the relevant piece of code from the `requireAlignedObjectValues` rule:
```javascript
errors.assert.spacesBetween({
    token: keyToken,
    nextToken: colon,
    // + 1 is responsible for this extra space
    exactly: maxKeyEndPos - keyToken.loc.end.column + 1,
    message: 'Alignment required'
});
```

The reasoning behind that may seem to be a local issue: I'm trying to configure JSCS plugin to work with built-in Intellij IDEA formatter and there's no option to allow space before the colon only for multiline-aligned objects and not inline.

**Comment by hzoo** [comment]
I think it's better for most if not all rules to be independent of each other.

I'm not sure I understand what you're asking for - do you just want the last code snippet when both rules are true? Although maybe we could just change `requireAlignedObjectValues` to have that last version by default (a more stricter check)?

**Comment by mikesherov** [comment]
Thanks for contributing! Yes, it's possible for these two rules to exist together by having the requireAligned rule to only verify alignment and not location of the colon.

**Comment by dreef3** [comment]
@mikesherov , @hzoo 

Please see my attempt to solve this under #1428.
