### ISSUE TITLE
An option to allow keywords on new line if there are comments when disallowKeywordsOnNewLine is true

### ISSUE THREAD

**Issue by stevemao** [jscs-dev/node-jscs#1421]
Valid
```js
if (x < 0) {
    x++;
} else {
    x--;
}

if (x < 0) {
    x++;
} 
// comments
else {
    x--;
}
```

Invalid
```js
if (x < 0) {
    x++;
}
else {
    x--;
}
```

**Comment by hzoo** [comment]
I think we can make an exception for if/else and I guess do/while as well (without a new option).

**Comment by mrjoelkemp** [comment]
@hzoo sounds good

**Comment by stevemao** [comment]
Glad to know that you guys think this is a good idea :smile:

**Comment by oredi** [comment]
If no one is looking at this, I am taking it up :)

**Comment by stevemao** [comment]
Hey guys, did you treat this as a bug? So we can't enforce 
```js
if (x < 0) {
    x++;
} 
// comments
else {
    x--;
}
```
as invalid like the old behaviour?

**Comment by oredi** [comment]
@stevemao  The PR that was merged included the exception that allows you to place comments between the if closing brace and the else keyword. So the code that you listed is now allowed even if you activated the disallowKeywordsOnNewLine for the "else" keyword

**Comment by stevemao** [comment]
@oredi i know :D But I'm asking if there's a way to enforce 

```js
if (x < 0) {
    x++;
} 
// comments
else {
    x--;
}
```
invalid? My original proposal was to add another option.

**Comment by oredi** [comment]
@stevemao oh sorry I misunderstood your message. The new implementation create an exception on the current option rather create a new one. So there is no way to enforce the code segment you listed as an error now.

**Comment by stevemao** [comment]
If fine if this is by design :)

**Comment by oredi** [comment]
So the preferred implementation will be a new option and remove the exception on the original implementation? I can work on that if it is preferred

**Comment by stevemao** [comment]
@markelog why is this reopened?

**Comment by markelog** [comment]
hmm, okay, if everybody is cool with it :-)

**Comment by stevemao** [comment]
I asked because I wan't not sure. I guess it's not hard to implement it if anyone asks for it :)
