### ISSUE TITLE
Add a rule to validate filenames?

### ISSUE THREAD

**Issue by lukeapage** [jscs-dev/node-jscs#1424]
It would be useful to force the casing of the javascript filenames themselves e.g.
```
requireFilenameCasing: "pascal"
// driveService.js
requireFilenameCasing: "lowercase-dashed"
// drive-service.js
```

with options pascal, camel, lowercase-dashed (better name?), lowercase underscored etc.

**Comment by mrjoelkemp** [comment]
Thanks for contributing. I've wanted this for a while too. 

All of our rules are for linting the contents of a file, not its filename. However, I believe it's possible to attach the filename as part of the JsFile object and assert properties about that filename in a new rule. 

Would you like to give it a go? We could use the help. Feel free to ask questions on this issue thread if you need help.

**Comment by hzoo** [comment]
I don't know if we wanted this as part of JSCS but it would be awesome to have! And an easy rule name - could also do `validateFilenames` since we have a few of those. Would be nice to do it for different file types to be general but kind of outside our scope? If we only need one option then it can just be different strings like suggested above.

**Comment by lukeapage** [comment]
I might get round to it, but I already do quite a bit of open sourced contributions and I have a backlog of own time work for that

**Comment by mikesherov** [comment]
We'd also need the ability to specify the name of a file if it's received as stdin or as a temp file (which some linters do... most notably sublimeLinter.

**Comment by ShashankaNataraj** [comment]
Additionally can we have this option also check for specific file name patterns under specific directories?

For example. if I wanted all scripts under controllers directory to have camel case, and all scripts under services directory to have pascal case?

**Comment by markelog** [comment]
> For example. if I wanted all scripts under controllers directory to have camel case, and all scripts under services directory to have pascal case?

It seems as a task for the config finder

**Comment by hzoo** [comment]
This would be so awesome to have :smile:!
