### ISSUE TITLE
disallowKeywordsOnNewLine doesn't disallow line after keyword

### ISSUE THREAD

**Issue by TheSavior** [jscs-dev/node-jscs#1429]
`"disallowKeywordsOnNewLine": ["else"]`

current lists in the documentation:

Valid
```
if (x < 0) {
    x++;
} else {
    x--;
}
```

Invalid
```
if (x < 0) {
    x++;
}
else {
    x--;
}
```

**However**
It also allows

```
if (x < 0) {
    x++;
} else 
{
    x--;
}
```

Which I want to be invalid.

**Comment by mrjoelkemp** [comment]
Sounds like `disallowKeywordsOnNewLine` is doing the right thing. Perhaps an additional brace-centric rule is necessary for the example you want to be invalid?

**Comment by TheSavior** [comment]
Agreed. :)

**Comment by mrjoelkemp** [comment]
Sounds like it's safe to close. Happy to reopen if I'm wrong.
