### ISSUE TITLE
feature request: naming convention checks

### ISSUE THREAD

**Issue by pohutukawa** [jscs-dev/node-jscs#1431]
I've used in the past `checkstyle` for Java, and I quite liked the way it could be used to report on naming convention violations. For that different categories are suitable:

* `variableNamingRegex`
* `functionNamingRegex`
* `constantNamingRegex`
* `namespaceNamingRegex`
* `classNamingRegex` (or `(type|constructor)NamingRegex`)

Regexes can contain indicators for length, so that we can also catch too short identifiers (such as single-letter variable names). Which is quite good.

However, we do probably also want some e. g. `variableNamingExceptions` containing an array, which can hold things like `e` (for an exception in a `catch` block), `i` and `j` for loop variables, or whatever somebody needs (e. g. `x` and `y` for coordinates).

Unfortunately I haven't been able to find any tool for JavaScript that can check for these, but I believe it would fit best into JSCS and can make a big difference in ensuring code style/quality.

**Comment by hzoo** [comment]
Just so you know, right now we have the `disallowIdentifierNames` rule and also https://github.com/jscs-dev/jscs-spellcheck now (for rules related to naming).

I guess what you're asking for is more of a `validate/requireIdentifierForX` for different types of things. I think we'll have to see some examples of regexes to see how this would work in practice?

**Comment by mrjoelkemp** [comment]
Hey @pohutukawa. Thanks for contributing. Similar to @hzoo's point, examples of what you want to be valid/invalid would be really helpful. It sounds like you do want either `disallowIdentifierNames` or [requireCamelCaseOrUpperCaseIdentifiers](http://jscs.info/rule/requireCamelCaseOrUpperCaseIdentifiers.html).

Please let me know if we're missing something. Otherwise, it seems we have rules that suffice. Happy to reopen with more details provided.

**Comment by pohutukawa** [comment]
Too bad this has been closed. I have just sussed out some regexes:

What I'd use for naming of ...
* variables and functions: `new RegExp('^_?[a-z][a-zA-Z0-9]{2,}$')`
  This will allow only stuff that starts with a lower case letter, and is at least three characters long, with an optional leading underscore `_` (e. g. to indicate "private" attributes)

* classes and types: `new RegExp('^_?[A-Z][a-zA-Z0-9]{2,}$')`
  Similar as above, only starting with an upper case letter.

* constants: `new RegExp('^_?[A-Z][A-Z0-9_]{2,}$')`
  All upper-snake case, optional leading underscore `_`

* namespaces: `new RegExp('^_?[a-z][a-z0-9]{2,}$')`
  All lower-case, optional leading underscore

I'd guess the rules would need some further tweaking over time, but this should give you already a general idea on what I'm looking for.

The option `requireCamelCaseOrUpperCaseIdentifiers` is too coarsely granular, and doesn't prevent our devs to enforce the rules, e. g. towards using single letter variables, or correct naming schemes specific for different "things". The dictionary option mentioned by @hzoo seems quite interesting, but strictly speaking only complementary to my desired outcome. So, still thanks for pointing that out, as that would be good to enable for sane naming as well (I know of sombody who's named a class in a technical application `BrigitteBardot`, which is not helpful ...).

**Comment by alawatthe** [comment]
@pohutukawa like @mrjoelkemp said, it would be helpful to see some examples  what should be valid or invalid. Just looking at the RegExps I have a lot of questions: 

* What do you mean with "types"?
* What do you mean with "namespaces"? Objects? Aren't they also variables?
* What's about constant variables? (I assume with constants you mean variables declared with ```const```) Are they validated with the constants RegExp or the variable RegExp?
* Classes only in the ES6 way, or constructor functions as well? Then, what is with functions which act as normal functions and constructor functions?

Furthermore I see a few problems with your approach:
JSCS however uses static code analysis, to analyze the code. This means, that it is difficult to impossible to identify the type of a variable. Just consider:

```js
var variableName = Math.random() < 0.5 ? 'the answer' : 42;
// We only know at runtime,
// whether variableName will be a string or or a number...
```

Even, if we leave such things away, we have problems like
* Some variables are coming from external libraries, which then need to be checked, too.
* We need to store the return types of all the functions implemented in all browsers/node.js/... 
* As far as I know none of this stuff is implemented in JSCS, which means there would be a lot to do.

That said, I like the idea of restricting the set of variable names (I built ```disallowIdentifierNames```), however I don't think that your approach is easy to implement :-/

**Comment by pohutukawa** [comment]
@alawatthe & @mrjoelkemp You're probably right, it'll be hard to do for JavaScript. I must admit, I'm not the biggest fan of JavaScript, due to the fact that many things can be achieved, but one has to circumnavigate the absence of language features/keywords to achieve them, whereas it's simpler in other languages (even if they're dynamically -- but strictly -- typed like Python).

Anyway, to get back to the questions:

* With "types" I'm talking about things like classes through prototypes only (so far), that then can be used to create object instances (e. g. for declaring that something takes an object of a particular type with particular properties, as opposed to any object).
* Strictly speaking "namespaces" in JavaScript are plain old objects as well, but they're used for scoping/segmenting code. I like this to be made clear through variable naming.
* Constants through `const` seem to be an ES6 construct not available in browsers, yet. So for us, we're still using `var` for declaring them. However, (just like with the namespaces), we're indicating them by convention through variable naming.

I know that some of these things are not clearly distinguishable in vanilla JavaScript code. So my initial question was more aiming at an ideal, however, I'd be fully satisfied with some kind of sub-set of this. I find it particularly important to have some way to keep the naming scheme consistent and to prohibit single-letter variables (besides the common exceptions as stated above).

I'll certainly have a look at the suggestion from @hzoo on `jscs-spellcheck`, which will give me quite some mileage as well as complementary benefits already. But it just doesn't go far enough ... :-|

**Comment by pohutukawa** [comment]
@alawatthe I've had a look at the source of `disallowIdentifierNames`. Maybe I can use this to come up with an easy implementation of a rule like `restrictIdentifierNames` only allowing for "clean" names that fit the naming scheme outlined above (configurable via `RegExp`s). So it won't be necessarily possible to distinguish from context between the different identifier cases, but at least I can prevent them from being "mix mashed" and restricted from e. g. being single-letter.

**Comment by markelog** [comment]
Sounds like https://github.com/jscs-dev/node-jscs/issues/612? Still interested?

**Comment by markelog** [comment]
Ping us up if you change your mind
