### ISSUE TITLE
JSFile and Configuration Proposal: Support custom code and tree transforms

### ISSUE THREAD

**Issue by mrjoelkemp** [jscs-dev/node-jscs#1434]
In the same vein as #1433, and with the pending inclusion of #1427, I fear the unnecessary bloat of the `JSFile#parse` method.

Proposal: Support a pre-parse code transform and a post-parse tree transform via config (`codeTransform` and `treeTransform` attributes that accept a module path) similar to errorFilters. 

* The code transform module would take in the source code and return the modified source code
* The tree transform module would take in a tree and return a modified tree.

We'd move hashbang, IOS instrumentation, and grit processing logic to their respective code transform and tree transform files that are referenced within our `.jscsrc` using the above-specific transform keys of the config.

* To avoid supporting all future custom include syntax or other funky js pragmas, we may also consider (though up for debate) only keeping node-specific pragma support in the core – removing support for IOS instrumentation and moving it to an optionally used transform module in the jscs-dev org.

To demonstrate the pattern:

**Hashbang**

Code transform: https://github.com/jscs-dev/node-jscs/blob/f963cd496d4e5d89bb8ffee9abc1c8114b69f41f/lib/js-file.js#L826-L832

Tree transform: https://github.com/jscs-dev/node-jscs/blob/f963cd496d4e5d89bb8ffee9abc1c8114b69f41f/lib/js-file.js#L845-L849

**IOS Instrumentation**

Code transform: https://github.com/jscs-dev/node-jscs/blob/f963cd496d4e5d89bb8ffee9abc1c8114b69f41f/lib/js-file.js#L834-L841

Tree transform: https://github.com/jscs-dev/node-jscs/blob/f963cd496d4e5d89bb8ffee9abc1c8114b69f41f/lib/js-file.js#L851-L859

**Grit processing**

Code transform: https://github.com/tonyganch/node-jscs/blob/1374-grit-tags/lib/js-file.js#L843-L851

Tree Transform: https://github.com/tonyganch/node-jscs/blob/1374-grit-tags/lib/js-file.js#L871-L879

**Comment by mdevils** [comment]
It is hard to disagree with idea. I did propose dialects earlier. Looks like it is still a wanted feature. I think I will be able to make a prototype implementation for this.
