### ISSUE TITLE
ignoreProperties does not work

### ISSUE THREAD

**Issue by chasm** [jscs-dev/node-jscs#1436]
This:

```javascript
if (fields.hostName) { party.host_name = fields.hostName }
```

gets flagged for non-camelcased property *despite* having the following set both in Sublime Text and in a .jscsrc file:

```json
"requireCamelCaseOrUpperCaseIdentifiers": "ignoreProperties"
```

Am I missing something here? `host_name` is clearly a property of the party object.

**Comment by markelog** [comment]
Hm, can't reproduce it, are you sure you using latest version of jscs?

Could you execute the `jscs --version` and `jscs <problematic file> --verbose` and post the output?

**Comment by chasm** [comment]
1.13.1

Thanks! I didn't know about that command (only used it via Sublime).  I was able to find an error in my .jscsrc file (a stray =) -- ran it through JSONLint and now everything works beautifully. Sorry for the error on my part -- guess I *was* missing something.

**Comment by markelog** [comment]
np :-)
