### ISSUE TITLE
requireOperatorBeforeLineBreak: doesn't work well for CallExpressions

### ISSUE THREAD

**Issue by mrjoelkemp** [jscs-dev/node-jscs#1437]
See https://github.com/jscs-dev/node-jscs/issues/511#issuecomment-66161341.

Requires investigation. Check out the failing test: https://github.com/jdlrobson/node-jscs/commit/08f440372fb75e81ea6efb9d26a72a35fd5a5678.

**Comment by hzoo** [comment]
`.` was removed as a binary operator so `var defaultOperators = require('../utils').binaryOperators.slice();` doesn't include it in the rule

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
