### ISSUE TITLE
ExportNamedDeclaration/ExportDefaultDeclaration exception for disallowFunctionDeclarations

### ISSUE THREAD

**Issue by alawatthe** [jscs-dev/node-jscs#1440]
I'd like to use function declarations in export statements but disallow them everywhere else.
I.e. a ```.jscsrc``` file like:

```json
{
  "disallowFunctionDeclarations": {
    "allExcept": ["ExportNamedDeclaration", "ExportNamedDeclaration"]
  }
}
```
should allow the usage of function declarations in the following two situations (and disallow them everywhere else):

```js
// ExportDefaultDeclaration
export default function id (x) {
  return x;
}

// ExportNamedDeclaration
export function square (x) {
  return x * x;
}
```

I think, this only affects the ```disallowFunctionDeclarations``` rule and not the dual rule ```requireFunctionDeclarations```.

Any opinions?

**Comment by hzoo** [comment]
I was just thinking `disallowFunctionDeclarations` could be covered by `disallowNodeTypes`, but if we want exceptions/options then that fails. Sounds ok

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
