### ISSUE TITLE
Destructuring default values

### ISSUE THREAD

**Issue by nicolo-ribaudo** [jscs-dev/node-jscs#1441]
```js
function x({ a = 1 }) {}
```
```json
{
  "esnext": true
}
```

Reports `Unexpected token = [parseError]`

Esprima supports destructuring default values v2.2.0
https://github.com/jquery/esprima/pull/1128

**Comment by zxqfox** [comment]
Yeah, but we still using 1.x branch ;-( Upgrade were planned.

**Comment by hzoo** [comment]
@nicolo-ribaudo 

Add the `esprima` option to your `.jscsrc` and choose a different parser (esprima, esprima-fb, babel-jscs)
(you will need to npm install it)
```js
//.jscsrc
{
    "esprima": "./node_modules/esprima",
    "esprima": "./node_modules/esprima-fb",
    "esprima": "./node_modules/babel-jscs",
    ...
}
```

**Comment by hzoo** [comment]
Yeah update is tracked in #1382, #1353

**Comment by hzoo** [comment]
We can close this then right?
