### ISSUE TITLE
New rule to disallow block comments?

### ISSUE THREAD

**Issue by ShashankaNataraj** [jscs-dev/node-jscs#1443]
There are code styles out there which disallow block comments and prefer single line comments.

https://github.com/h5bp/Effeckt.css/wiki/Code-Style-Guide

**Comment by hzoo** [comment]
If we think this could be a rule - what would the name be: `requireBlockComments`? I guess there could be the opposite rule as well.

**Comment by ShashankaNataraj** [comment]
+1 Yes, I would think `requireBlockComments` and `disallowBlockComments` could be appropriate names for the new rules.

**Comment by mrjoelkemp** [comment]
Keep in mind requireBlockComments will need to respect `// jscs: disable` comments.

**Comment by markelog** [comment]
jQuery preset could benefit from that rule too - https://contribute.jquery.org/style-guide/js/#comments
But with exception for the parameter list.

@ShashankaNataraj  would you like to do it?

**Comment by ShashankaNataraj** [comment]
@markelog Sure would! I will take this up! :+1:

**Comment by mrjoelkemp** [comment]
Hey @ShashankaNataraj still interested?

**Comment by ShashankaNataraj** [comment]
@mrjoelkemp Definitely, sorry got caught up in some other things. Will be making a PR soon.
