### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by kover** [jscs-dev/node-jscs#1444]
TypeError: Cannot read property 'type' of undefined
    at /usr/local/lib/node_modules/jscs/lib/rules/require-padding-newlines-before-line-comments.js:100:26
    at /usr/local/lib/node_modules/jscs/lib/js-file.js:445:17
    at Array.forEach (native)
    at Object.JsFile.iterateTokensByType (/usr/local/lib/node_modules/jscs/lib/js-file.js:443:26)
    at Object.module.exports.check (/usr/local/lib/node_modules/jscs/lib/rules/require-padding-newlines-before-line-comments.js:86:14)
    at null.<anonymous> (/usr/local/lib/node_modules/jscs/lib/string-checker.js:141:22)
    at Array.forEach (native)
    at StringChecker._checkJsFile (/usr/local/lib/node_modules/jscs/lib/string-checker.js:137:31)
    at StringChecker.checkString (/usr/local/lib/node_modules/jscs/lib/string-checker.js:117:14)
    at null.<anonymous> (/usr/local/lib/node_modules/jscs/lib/checker.js:43:21)

**Comment by mrjoelkemp** [comment]
Hi @kover. Thanks for contributing. Any chance you could supply a code sample that reproduces the error? It would greatly help us track down the issue.

**Comment by zxqfox** [comment]
Hm. Why it doesn't catched by https://github.com/jscs-dev/node-jscs/blob/master/lib/string-checker.js#L134 ?

**Comment by hzoo** [comment]
There isn't that much info - like what version of jscs (maybe older than when you added that @zxqfox)

**Comment by zxqfox** [comment]
@hzoo lol ;-) Right!

@kover Please, provide your config and used version or jscs.

**Comment by kover** [comment]
Hi,

ok, of course

command line: jscs cc_integration_mon.js --preset=jquery

**Comment by kover** [comment]
Hi,

I use jquery preset

jscs --version
1.13.1

**Comment by kover** [comment]
Well, I’ll try to use provided solution and let you know, if this will fix.

**Comment by markelog** [comment]
> Well, I’ll try to use provided solution and let you know, if this will fix.

What solution? We didn't introduce any, we need a code sample, jscs config or just output of `jscs --verbose`

**Comment by hzoo** [comment]
@kover If you don't want to show the whole file then we just need a minimal code snippet that causes the error you mentioned (that would be better).

**Comment by kover** [comment]
Hi,

I attach file in previous email, but if you don’t receive it, here is the content:


//CORIS added

var calling_number;
//переменная для отслеживания сосстояния HOLD
var hold_flag; 
//CORIS end

// MMK-Informservice
var isCallMissed;
// MMK-Informservice
// Methods
function connect(serverIP, serverPort, domain, userId, userPassword, agentId, agentPassword) {
    var params = { 
        method: "connect",
        serverip: serverIP,
        serverport: serverPort,
        domain: domain,
        userid: userId,
        userpassword: userPassword,
        agentid: agentId,
        agentpassword: agentPassword
    };
    var result = call_avayacc_method(params);
    if (result.code == 200) {
        _id = result.reason;
        setAgentId(_id);
        bind(MAX_WAIT_TIME);
    }
    return result;
}

function disconnect() {
    var params = { method: "disconnect" };
    return call_avayacc_method(params);
}

function setReady() {
    var params = { method: "setready" };
    return call_avayacc_method(params);
}

function setNotReady(status) {
    var params = {
        method: "setnotready",
        status: status 
    };
    return call_avayacc_method(params);    
}

function acceptCall() {
    var params = { method: "acceptcall" };

    return call_avayacc_method(params);    
}

function hangupCall() {
    var params = { method: "hangupcall" };
    return call_avayacc_method(params);
}

function holdCall() {
    var params = { method: "holdcall" };
    return call_avayacc_method(params);
}

function resumeCall() {
    var params = { method: "resumecall" };
    return call_avayacc_method(params);
}

function transferCall(number) {
    var params = {
        method: "transfercall",
        number: number
    };
    return call_avayacc_method(params);
}

function sendDTMF(dtmf) {
    var new_dtmf = dtmf.replace("#", "A");
    var params = {
        method: "senddtmf",
        dtmf: new_dtmf
    };
    return call_avayacc_method(params);
}

function makeCall(number) {
    var params = {
        method: "makecall",
        number: number
    };
    return call_avayacc_method(params);
}

function acceptIM(hello_msg) {
    var params = { 
        method: "acceptim",
        msg: hello_msg
    };
    return call_avayacc_method(params);
}

function discardIM() {
    var params = { method: "discardim" };
    return call_avayacc_method(params);
}

function sendIM(im) {
    var params = {
        method: "sendim",
        msg: im
    };
    return call_avayacc_method(params);
}
 
function replyEmail(to, subject, msg) {
}

// Events
function onDisconnect() {
    Log('onDisconnect');

    document.getElementsByName("ConnectBtn")[0].disabled = false;
    document.getElementsByName("DisconnectBtn")[0].disabled = true;
    document.getElementsByName("SetReadyBtn")[0].disabled = true;
    document.getElementsByName("SetNotReadyBtn")[0].disabled = true;

    document.getElementsByName("AcceptCallBtn")[0].disabled = true;
    document.getElementsByName("HangupCallBtn")[0].disabled = true;
    document.getElementsByName("HoldCallBtn")[0].disabled = true;
    document.getElementsByName("ResumeCallBtn")[0].disabled = true;
    document.getElementsByName("SendDTMFBtn")[0].disabled = true;
    document.getElementById("dtmf").disabled = true;
    document.getElementsByName("TransferCallBtn")[0].disabled = true;
    document.getElementById("TransferNumber").disabled = true;
    document.getElementsByName("MakeCallBtn")[0].disabled = true;
    document.getElementById("CallNumber").disabled = true;
}

function showAlert (phone_number) {
    $.getJSON("/phone/callerinfo.cshtml?phone=" + phone_number, function(data) {
        var showInfo = "<p><b>Телефон:</b> " + data.phone + "</p>";
        showInfo += "<p><b>Ф.И.О.:</b> " + data.caller_name + "</p>";
        showInfo += "<p><b>Расположение:</b> " + data.address + "</p>";
        $("#alert-placeholder").toggleClass('top-block').append("<div class='alert alert-info fade in'>" + showInfo + "</div>");
        setTimeout(function() {
            $('.alert').alert('close');
            $("#alert-placeholder").toggleClass('top-block');
        }, 20000);
    });
}

function onCallIncoming(skillset, a_number, ivr) {
    Log('onCallIncoming: a_number=' + a_number + ' skillset=' + skillset + ' ivr=' + ivr);
	//CORIS added
	calling_number = a_number;
	//CORIS END

    // MMK-InformService log calling number and current analyst ID
    // var userLogin = document.getElementById("ServiceDeskUser").value;
    showAlert(calling_number);
    // $.get("/phone/logrecord.cshtml?phone=" + calling_number + "&userid=" + userLogin);
    document.getElementsByName("AcceptCallBtn")[0].disabled = false;
    document.getElementsByName("HangupCallBtn")[0].disabled = false;
}

function onCallNotify(callState, callId, calledAddress, callingAddress) {
    Log('onCallNotify: callState=' + callState + 
                     " callId=" + callId +
                     " calledAddress=" + calledAddress +
                     " callingAddress=" + callingAddress);

    var userLogin = document.getElementById("ServiceDeskUser").value;

	if (callState == "ringing") {
        document.getElementsByName("AcceptCallBtn")[0].disabled = false;
        document.getElementsByName("HangupCallBtn")[0].disabled = false;
        
		//CORIS
		hold_flag = 0;
		//CORIS end

        // MMK-Informservice
        isCallMissed = true;
        // MMK-Informservice
    } else if (callState == "active") {
        document.getElementsByName("AcceptCallBtn")[0].disabled = true;
        document.getElementsByName("HangupCallBtn")[0].disabled = false;
        document.getElementsByName("HoldCallBtn")[0].disabled = false;
        document.getElementsByName("ResumeCallBtn")[0].disabled = true;
        document.getElementsByName("SendDTMFBtn")[0].disabled = false;
        document.getElementById("dtmf").disabled = false;
        document.getElementsByName("TransferCallBtn")[0].disabled = false;
        document.getElementById("TransferNumber").disabled = false;
		//CORIS added
		//Сравниваем номер телефона под которым пользователь залогинился в систему, с номером телефона с которого звонят
		var myreq=/(\d{1,11})/;
		var myArrey=myreq.exec(callingAddress);
		Log('callingAddress=' +myArrey[0] + " AgentID=" + document.getElementById("AgentId").value);
		if ((document.getElementById("AgentId").value != myArrey[0]) && (hold_flag != "1")) {
		//Если номера различаются создаем обращение
			// createReqAndOpenWindow(document.getElementById("ServiceDeskUser").value, document.getElementById("ServiceDeskPassword").value, calling_number);
            document.getElementsByName("CreateIncident")[0].disabled = false;
		}
		//CORIS ended

        // MMK-Informservice
        isCallMissed = false;
        $.get("/phone/logrecord.cshtml?phone=" + calling_number + "&userid=" + userLogin + "&callstatus=1");
        // MMK-Informservice
    } else if (callState == "disconnected") {
        document.getElementsByName("AcceptCallBtn")[0].disabled = true;
        document.getElementsByName("HangupCallBtn")[0].disabled = true;
        document.getElementsByName("HoldCallBtn")[0].disabled = true;
        document.getElementsByName("ResumeCallBtn")[0].disabled = true;
        document.getElementsByName("SendDTMFBtn")[0].disabled = true;
        document.getElementById("dtmf").disabled = true;
        document.getElementsByName("TransferCallBtn")[0].disabled = true;
        document.getElementById("TransferNumber").disabled = true;
        document.getElementsByName("CreateIncident")[0].disabled = true;
		//CORIS
		hold_flag = 0;
		//CORIS end

        if (isCallMissed) {
            $.get("/phone/logrecord.cshtml?phone=" + calling_number + "&userid=" + userLogin + "&callstatus=0");
        }

    } else if (callState == "held") {
		//CORIS
		hold_flag = 1;
		//CORIS end
        document.getElementsByName("HoldCallBtn")[0].disabled = true;
        document.getElementsByName("ResumeCallBtn")[0].disabled = false;
    } 
}

function onIncomingIM(name, phone, email, subject) {
    var logMsg = 'onIncomingIM: ';
    if (name != null) {
        logMsg += 'name=' + name;
    }
    if (phone != null) {
        logMsg += ' phone=' + phone;
    }
    if (email != null) {
        logMsg += ' email=' + email;
    }
    if (subject != null) {
        logMsg += ' subject=' + subject;
    }
    Log(logMsg);

    document.getElementsByName("AcceptIMBtn")[0].disabled = false;
    document.getElementsByName("DiscardIMBtn")[0].disabled = false;
    document.getElementById("im").disabled = true;
    document.getElementsByName("SendIMBtn")[0].disabled = true;
}

function onIM(msg) {
    Log('onIM: ' + msg);
}

function onIMClose() {
    Log('onIMClose');
}

function onEmail(from, subject, msg) {
}

function onSystemError(state, errorMsg) {
    Log('onSystemError: state=' + state + ' errorMsg=' + errorMsg);
}

**Comment by markelog** [comment]
Can't reproduce the error with

```js
"requirePaddingNewLinesBeforeLineComments": { "allExcept": "firstAfterCurly" }
```
or 

```js
"requirePaddingNewLinesBeforeLineComments": true
```

What version of jscs do you use?

**Comment by kover** [comment]
Hi,

i use version 1.13.1

**Comment by markelog** [comment]
That is weird, as @zxqfox said, this error should be catched and re-throw it in more friendly manner by jscs internal logic that was introduced some time back.

I'm afraid you need to provide a repo with this error, otherwise, if someone else couldn't reproduce it, we're out of options.
