### ISSUE TITLE
New rule for , and ; to not have preceding space?

### ISSUE THREAD

**Issue by ShashankaNataraj** [jscs-dev/node-jscs#1447]

**Comment by markelog** [comment]
Would be very interesting rule, would you like to tackle this one?

**Comment by markelog** [comment]
You also already can do that for the comma btw - http://jscs.info/rule/disallowSpaceAfterBinaryOperators.html

But we would rather move it to it own rule(s), see discussion in https://github.com/jscs-dev/node-jscs/issues/845#issuecomment-111121060

**Comment by hzoo** [comment]
`dockyard/ember-suave` has the semicolon one done. https://github.com/dockyard/ember-suave/blob/master/lib/rules/disallow-space-before-semicolon.js if we want to use that. And regarding commas I think there was an issue about that

**Comment by markelog** [comment]
Cool, if only it would use `assert` module and no regexps

**Comment by markelog** [comment]
Okay, we landed semicolon rule, should be pretty easy to create rule for the comma

**Comment by markelog** [comment]
@ShashankaNataraj would you like to tackle this?

**Comment by ShashankaNataraj** [comment]
@markelog SUre would! Will raise a PR.

**Comment by markelog** [comment]
@ShashankaNataraj it seems you almost finish with it?

**Comment by ShashankaNataraj** [comment]
@markelog yeah, but I'd like to test it a couple of times before submitting.
