### ISSUE TITLE
New rule for variable names to contain $ if the RHS of the equation has a $

### ISSUE THREAD

**Issue by ShashankaNataraj** [jscs-dev/node-jscs#1449]
Some code styles read: `Use $ in front of a variable if it's a jquery object.` which should be possible to enforce from JSCS.

**Valid**
`var $abc = $("#abc");`

**Invalid**
`var abc = $("#abc");`

This can also be extended for other special characters such as `_` but `$` is the most common one being used in libraries such as angular.

**Comment by hzoo** [comment]
This should be covered with `requireDollarBeforejQueryAssignment` now http://jscs.info/rule/requireDollarBeforejQueryAssignment.html
