### ISSUE TITLE
Would love to see Beginner or Easy labels on issues

### ISSUE THREAD

**Issue by lpommers** [jscs-dev/node-jscs#1450]
As someone who is new to JSCS and wants to start contributing, it would be extremely helpful if issues had the label `beginner` or `easy` where applicable.  

I think it would provide a good entry point to the project and give people a good way to explore the code base with having a goal, but not one that is too over their head.

**Comment by hzoo** [comment]
@lpommers Sounds good!

For now, I would check out previous PRs (commit's start with `New Rule: x`) or current rules/tests to see what is needed. we have labels for `new rule` and `new rule option` (difficulty varies though). Also https://github.com/jscs-dev/node-jscs/blob/master/CONTRIBUTING.md

**Comment by mrjoelkemp** [comment]
Great suggestion. We have the [help-wanted label](https://github.com/jscs-dev/node-jscs/labels/help-wanted) for that purpose. We should likely change the label name to 'beginner-friendly' so it's clearer.

**Comment by lpommers** [comment]
I think that would be a good idea because help-wanted can be misleading. help-wanted because it's a difficult task? or help wanted because trying to solicit people get involved?

**Comment by hzoo** [comment]
Yeah it could imply it's difficult to do

**Comment by markelog** [comment]
Most changes are related to JSCS code-base are related to the new rule, new option rule, or bug fixes for existing ones, maybe presets changes too. Those are easy changes, any of those issues could be a good start for the beginner.

I think we could add some helpful notes for the beginners to the contribution guide though and mention it on the main readme.
