### ISSUE TITLE
Docs: Document that error suppression only holds for the current file

### ISSUE THREAD

**Issue by mrjoelkemp** [jscs-dev/node-jscs#1451]
If you want to ignore the entire file, just do:

```js
// jscs: disable
```

No need to add `// jscs: enable` at the end of the file.

**Comment by oredi** [comment]
@mrjoelkemp related to this I think the description for "Disabling All Rules" is misleading. I would think the following might be a little clearer

#### Disabling All Rules

The placement of the special comments `// jscs:disable` and `// jscs:enable` will disable or enable the checking of all rules against the code that appears the comment

**Comment by mrjoelkemp** [comment]
Agreed, @oredi. Sounds like you want to submit a PR :) :)

**Comment by oredi** [comment]
Sure I will put in one tomorrow with the Doc change for the entire file as well.

**Comment by markelog** [comment]
I would remove or replace everything between `// jscs: disable` and `// jscs: enable`, would help in cases like this - https://github.com/jscs-dev/node-jscs/issues/1156
