### ISSUE TITLE
requireSpaceAfterObjectKeys not working as expected

### ISSUE THREAD

**Issue by ShashankaNataraj** [jscs-dev/node-jscs#1454]
![image](https://cloud.githubusercontent.com/assets/650317/8148602/616ec25c-12c2-11e5-8ec0-3818e3954930.png)

**Comment by mrjoelkemp** [comment]
Thanks for reporting @ShashankaNataraj. Which jscs version are you using?

**Comment by ShashankaNataraj** [comment]
JSCS version: 1.13.1
"grunt-jscs": "^1.8.0"

I get the same error on both. Im using webstorm which integrates JSCS, I get the error within the IDE as well as when using grunt-jscs from the command line.

**Comment by TheSavior** [comment]
Same

**Comment by hzoo** [comment]
Unless I'm mistaken isn't this working as intended? Do you need the opposite rule `disallowSpaceAfterObjectKeys`?

http://jscs.info/rule/requireSpaceAfterObjectKeys.html

```js
// Valid
var x = {a : 1};

// Invalid
var x = {a: 1};
```

**Comment by ShashankaNataraj** [comment]
@hzoo I see your point. I was expecting `pkg: ` to be valid since there is already a space after `:`. Now I RTFM'd and saw my expectation was wrong. Closing this issue, thanks!

**Comment by hzoo** [comment]
Ah yeah http://jscs.info/rule/requireSpaceAfterObjectKeys.html

**Comment by hzoo** [comment]
Oops put the same thing - it's http://jscs.info/rule/rule/requireSpaceBeforeObjectValues.html

**Comment by ShashankaNataraj** [comment]
@hzoo Thanks a ton!
