### ISSUE TITLE
exclude files via command line?

### ISSUE THREAD

**Issue by saitheexplorer** [jscs-dev/node-jscs#1458]
Is there a way to exclude paths and files via a command line option? I know it's possible via config file.

JSHint has the option to exclude:

```
--exclude

Allows you to specify directories which you DON'T want to be linted.
```

I'm trying to avoid having to create a new ignore file in each of our projects and instead just include in my package.json as an npm script. Looking through `bin/jscs` leads me to believe this is not possible today. Is this correct?

**Comment by mrjoelkemp** [comment]
Yes, there's `excludeFiles`: https://github.com/jscs-dev/node-jscs/blob/master/OVERVIEW.md#excludefiles.

Feel free to ask questions like this on the gitter channel: https://gitter.im/jscs-dev/node-jscs

**Comment by saitheexplorer** [comment]
This lets me ignore using a config file, but this option doesn't exist using the command line tool (as far as I can tell).

I will take my question to gitter - thanks for the heads up.

**Comment by mrjoelkemp** [comment]
Actually, you're right. This doesn't exist. I assume we'd accept a comma-sep list of dir-names and split that to form the excludeFiles config value.

**Comment by markelog** [comment]
PR welcome!

**Comment by saitheexplorer** [comment]
Forked the project - will give it a shot!

**Comment by michieldewilde** [comment]
Working on this

**Comment by michieldewilde** [comment]
Wouldn't it be better to exclude mutiple files by using this:
`jscs lib/config/configuration.js --exclude lib/config/configuration.js,lib/config/blabla.js`
instead of this:
`jscs lib/config/configuration.js --exclude lib/config/configuration.js --exclude lib/config/blabla.js`

**Comment by golyshevd** [comment]
> Yes, there's excludeFiles: https://github.com/jscs-dev/node-jscs/blob/master/OVERVIEW.md#excludefiles.

Think that excludeFiles should not be a part of `.jscsrc`. It causes some issues when copying/pasting `.jscsrc` from project to project. excludeFiles should be an argument of some internal `checkFileList` function, which should filter the list IMHO

**Comment by markelog** [comment]
Yeah, we agree, feel free to implement

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
