### ISSUE TITLE
excludeFiles: add "node_modules/**" by default

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1461]
So people don't need to add `node_modules/**` every time (or forget and freeze their cli).

Similar argument could be made for `bower_components` (@zxqfox)

Should be able to include again by using `!node_modules` already I think?

**Comment by markelog** [comment]
Now `excludeFiles` has default value of `[]` we could define this value as `[ "node_modules/**" ]`

**Comment by markelog** [comment]
@TheSavior you had idea about additional paths?

**Comment by TheSavior** [comment]
I would think we should ignore everything in the .gitignore by default as well. Users don't want to check those files in, are not part of their project, and most likely vendor files.

**Comment by mrjoelkemp** [comment]
I'd like to land https://github.com/jscs-dev/node-jscs/pull/1467 and then open up the gitignore file inclusion as a follow up PR. Sound good?

**Comment by markelog** [comment]
yep
