### ISSUE TITLE
Misc: add a message suggesting to use autofix when running jscs (and autoconfigure)

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1462]
Show the message explaining to use `jscs -x` to autofix issues when there are greater than a certain amount of issues (say 100, 500, 1000 - don't know)?

**Comment by markelog** [comment]
More then `maxError`?

**Comment by hzoo** [comment]
Ok but it looks like the default for `maxErrors` is `Infinity`, so otherwise we need a number if they don't specify it.

**Comment by markelog** [comment]
https://github.com/jscs-dev/node-jscs/issues/681 also mentioned on our roadmap :-)

**Comment by hzoo** [comment]
This is similar to #1471 so we can close one of them

**Comment by mrjoelkemp** [comment]
True. The integration of fixing is more useful than a meesage suggesting to use it.
