### ISSUE TITLE
feat: Support Typescript

### ISSUE THREAD

**Issue by btesser** [jscs-dev/node-jscs#1463]
It would really be great if support could be added to jscs for typescript.  If you don't have time to implement, guidance on doing this would be great

**Comment by markelog** [comment]
This is out of scope, but check this out - https://github.com/palantir/tslint

**Comment by hzoo** [comment]
Only way would be if you could plug in parser for it for the `esprima` option or `babel-jscs` just happens to support the typescript features being used.

**Comment by markelog** [comment]
Okay, re-open for the consideration then

**Comment by hzoo** [comment]
Well I don't know haha - I'm not sure if we would want to support it in that way. Might have to modify a lot of stuff if there are any typescript specific features used.

**Comment by zxqfox** [comment]
Even if TS parser will return the same AST as we await for usual JS, it can require additional rules for type checking. Not sure it's possible to parse it right in JSCS, but I see it can be easily made with some plugin. ;-) Just an idea.

**Comment by milkisevil** [comment]
+1

**Comment by hzoo** [comment]
For now I would say try https://github.com/jscs-dev/babel-jscs (but don't expect too much).

**Comment by kobezzza** [comment]
+1

**Comment by RehanSaeed** [comment]
+1

**Comment by hzoo** [comment]
Not really sure how this would work at the moment since all our stuff is the esprima/ESTree format. I don't know enough about typescript to say so if it works now it is because the features are the same as the ones supported by babel. Going to close for now.

**Comment by rokerkony** [comment]
+1

**Comment by hzoo** [comment]
Can probably try using https://github.com/eslint/typescript-eslint-parser at some point similar to babel-eslint/babel-jscs since it will be compatible with estree - @nzakas.

**Comment by eriadam** [comment]
+1 Angular 2 is coming.

**Comment by mikaturunen** [comment]
+1. For general TypeScript work and Angular 2.

**Comment by GauSim** [comment]
+1
