### ISSUE TITLE
README Demo link 404

### ISSUE THREAD

**Issue by austinkelleher** [jscs-dev/node-jscs#1464]
The demo link on the node-jscs README points to a page that no longer exists [jscs.info/demo](http://jscs.info/demo.html)

**Comment by hzoo** [comment]
Thanks for the contribution! Yeah it's a known issue (hasn't been ported over to the new site yet, PR welcome)

Similar to #1370. We should remove it (or better just put a message to explain)

**Comment by markelog** [comment]
Okay, closing as dup
