### ISSUE TITLE
Toggling all rules for a single line with a trailing comment reenabled previously disabled rules

### ISSUE THREAD

**Issue by lpil** [jscs-dev/node-jscs#1466]
> If we have 1 rule turned off, and then want to toggle on and off all
> rules, how do we do this? When we toggle back on all rules after the
> single line trailing comment we will override the previously turned
> off rule as there's no good way to identify it was already on, and
> that it needs to be disabled again on the same line we enable all
> rules.

> The intended behaviour is slightly unclear, and implementing this
> feature will take a sizeable refactoring of the disabled rule index
> system, which my colleagues and I did not feel comfortable
> undertaking.

See further conversation here: https://github.com/jscs-dev/node-jscs/pull/1432#discussion_r32442520

**Comment by markelog** [comment]
You didn't forget :-), thanks!

**Comment by lpil** [comment]
:D

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.

**Comment by lpil** [comment]
Oh! I didn't realise it was merged into eslint. Wonderful :)
