### ISSUE TITLE
Indentation incorrectly validated for commented out code.

### ISSUE THREAD

**Issue by kirilloid** [jscs-dev/node-jscs#1468]
rule `validateIndentation`
It says, that the first line of commented code has incorrect indentation.
Why in the world does it check indentation for commented code?

##### CODE SAMPLE

```javascript
function someFn(mod) {
    'use strict';
    mod.init = null; // small memory clean-up
/*    if (mod.instance == null) {
    this._warn('You should return instance from the module `%s`', name);
    }*/
    return mod.instance;
}
```

##### OUTPUT

from grunt-jscs
```
Expected indentation of 4 characters at src/... :
   220 |    'use strict';
   221 |    mod.init = null; // small memory clean-up
   222 |/*    if (mod.instance == null) {
------------^
   223 |    this._warn('You should return instance from the module `%s`', name);
   224 |    }*/
>> 1 code style errors found!
```

##### VERSIONS

1.11.0 - **not** reproduced
1.12.0 - reproduced
1.13.0 - reproduced

##### ENV INFO
node v0.10.33
npm v1.4.28
win7 x64

**Comment by hzoo** [comment]
Hey thanks for contributing - I think your request is covered with https://github.com/jscs-dev/node-jscs/issues/1215.

**Comment by kirilloid** [comment]
Thanks for the reference. It's essentially the same. The only difference is that author of that issue consider it OK with possibility to turn off and I consider such behavior as a bug.

**Comment by mrjoelkemp** [comment]
Closing due to dupe.
