### ISSUE TITLE
Fix issues for rules about function spacing (ES6)

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1470]
https://github.com/jscs-dev/babel-jscs/issues/4 was about shorthand methods erroring but it probably affects more than just `requireSpacesInAnonymousFunctionExpression`.

We probably need to check getters, setters, class methods, and object shorthand for all the function spacing rules (similar to the checks in `requireArrowFunctions`).

Similar to #1066

**Comment by mrjoelkemp** [comment]
+1 for a fix

**Comment by hzoo** [comment]
Should probably fix this..

@jscs-dev/owners So do we want to ignore shorthand methods for `requireSpacesInAnonymousFunctionExpression`? @mzgol is saying we should since it's not an anon function. However in the parser all of these are anonymous because they are `FunctionExpression` with no `node.id`

**Comment by mrjoelkemp** [comment]
Gonna move my comment to this thread:

In the following code:

```js
var o = {
  f() {},
};
```

`f() {}` is sugar for `f: function() {}`. `f()` is part of the function signature (as you'd define params like `f(foo, bar)`), so it should adhere to the rules.

**Comment by mzgol** [comment]
> `f() {}` is sugar for `f: function() {}`. `f()` is part of the function signature (as you'd define params like `f(foo, bar)`), so it should adhere to the rules.

I disagree. While it's true desugaring happens as you described, for me the rules was always about two things:

1. Do I want a space before `(` in `function ()`?
2. Do I want a space before `(` in `function f()`?

In my projects I'm answering "yes" to (1) and "no" to (2). The rule for me is - always a space between the `function` keyword and a paren, never a space between a name and a paren, no matter if the function is anonymous or not. So this:
```js
const o = {
    f() {},
};
```
is for me closer (spacing-wise) to:
```js
function f() {}
```
than to:
```js
const f = function () {};
```
After 1662163 I'm unable to enforce this; to not get linting errors I'd have to drop the `disallowSpacesInAnonymousFunctionExpression` rule completely.

If you want to treat named function expressions and method shorthand separately (which I can understand), please treat method shorthands and anonymous function expressions separately as well. Or at least add an option that allows such a treatment.

As it stands, I'm no longer able to update JSCS in my projects.

**Comment by hzoo** [comment]
I guess it's true we were already ignoring getters/setters (so the spacing for that wasn't enforced) https://github.com/hzoo/node-jscs/blob/b4084d7d4e1fbcb2033aa0c0bcb584fa839434df/lib/rules/disallow-spaces-in-anonymous-function-expression.js#L88

Ok so we would need to add `requireSpacesInClassMethod`, `requireSpacesInGetter`, `requireSpacesInSetter`, `requireSpacesInMethodShorthand` or something (seems like too many if it's separate rules) - and when we change the config make a single rule for all function types with options?

**Comment by mrjoelkemp** [comment]
For this particular request, sounds like we only need to support allExcept:
['shorthandMethod'].

**Comment by mzgol** [comment]
> For this particular request, sounds like we only need to support allExcept:
> ['shorthandMethod'].

That would work for me.

**Comment by mrjoelkemp** [comment]
@mzgol Added a ticket for this: https://github.com/jscs-dev/node-jscs/issues/1513.
