### ISSUE TITLE
requireSpread: doesn't error for a.prototype.b.apply(this, arguments)

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1482]
Was testing some of the rules on babel

These should error

```js
DefaultFormatter.prototype.transform.apply(this, arguments);
Node[key].apply(null, args);
```

@mikesherov

**Comment by mikesherov** [comment]
@hzoo thanks for the ping! How can I help?

**Comment by hzoo** [comment]
Just making sure the examples should error? And actually the other comment I made isn't there (about how to detect).

We want to make sure `a.apply(a, args)` - a and a are the same?

The code now is `callee.object && callee.object.name === firstParameter.name` was based on just `a.apply` and not for `a.b.apply`

**Comment by mikesherov** [comment]
I'm curious as to why we check the first parameter *at all*. This should still be caught by the rule:

```
function foo() {
  a.apply(d, arguments);
}
```

because it can always be changed into

```
function foo(...args) {
  a.call(d, ..args);
}
```

**Comment by hzoo** [comment]
Initially just tried implementing what you commented - https://github.com/jscs-dev/node-jscs/issues/1326#issuecomment-98174053 (why I pinged you as well :smile:)

**Comment by mikesherov** [comment]
I see... former me was only partially right :-)

**Comment by mikesherov** [comment]
because my former comment: 

> // good, we can't be certain that apply is Function.prototype.apply
> g.apply(arguments);

is an OK heuristic, but we can be *fairly* certain that:

> g.apply(b, arguments);

is `Function.prototype.apply`

**Comment by xtian** [comment]
Not sure if this is the same issue or not, but `instance.method.apply(instance, args);` as listed in the invalid examples for `requireSpread` does not trigger a failure either.

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
