### ISSUE TITLE
New rule to avoid 3 consecutive newlines

### ISSUE THREAD

**Issue by kilianc** [jscs-dev/node-jscs#1486]
bad
```js
let a = 'a'


if ('b' === a) ...
```

good

```js
let a = 'a'

if ('b' === a) ...
```

**Comment by mikesherov** [comment]
Thanks for contributing! This rule exists and is called `disallowMultipleLineBreaks` http://jscs.info/rule/disallowMultipleLineBreaks.html :-)

**Comment by kilianc** [comment]
Thanks @mikesherov ! I am not sure how did I miss that O_O
