### ISSUE TITLE
validateIndentation does not work with ES6 class methods

### ISSUE THREAD

**Issue by priyatham-aps** [jscs-dev/node-jscs#1497]
I have been trying out jscs on ES6 codebase with --fix option and I have noticed that validateIndentation rule does not work on ES6 class methods. Meaning it does not indent or throw an error when class methods are wrongly indented.

For example, consider the following code. I have set validateIndentation rule to tab (\t).
```javascript
class test {
f1() {
  var a;
var b
		var c;
  	var d;
}
	f2() {
  var a;
var b
		var c;
  	var d;
	}
}
```
After I run jscs on this code with --fix option, it is transformed to the following:
```javascript
class test {
f1() {
	var a;
	var b
	var c;
	var d;
}
	f2() {
		var a;
		var b
		var c;
		var d;
	}
}
```
This looks like validateIndentation rule is not being applied to class method declaration line, but it is being applied to the method body relative to the declaration.

Comparing this behavior with a similarly structured function, lets say we have the following code:
```javascript
function test1() {
function f1() {
  var a;
var b
		var c;
  	var d;
}
	function f2() {
  var a;
var b
		var c;
  	var d;
	}
}
```
This gets transformed to the following, which is as one would expect:
```javascript
function test1() {
	function f1() {
		var a;
		var b
		var c;
		var d;
	}
	function f2() {
		var a;
		var b
		var c;
		var d;
	}
}
```
I have gone through the list of issues reported on esnext and found that this issue is not reported so far, which left me a bit confused as despite what looked like a significant number of people working with jscs on ES6 codebase no body seemed to run into this issue. So, I am wondering if this is a genuine issue or if I am missing something. Can somebody shed some light on this, please?

**Comment by mikesherov** [comment]
On it.

**Comment by priyatham-aps** [comment]
@mikesherov 
Do you need anything from my side to help track down the issue? Happy to help in anyway I can.

**Comment by jamietre** [comment]
+1 but I'm having a different effect - perhaps because of the time passed since the original bug report & newer version?

    class test {
        constructor(options) {
            this.options = options
        }
        method() {
            this.doSomething(err, function() {
                if (err) throw err
            })
        }
    }

with `validateIndentation` this gets formatted as:

    class test {
        constructor(options) {
        this.options = options
        }
        method() {
        this.doSomething(err, function() {
            if (err) throw err
        })
        }
    }

That is, the inner scope of the class method is not accounted for.

**Comment by danbucholtz** [comment]
I am seeing the same issue that @jamietre is seeing.  Anyone have a fix?

**Comment by tconroy** [comment]
+1, facing the same problem as @danbucholtz -- auto fix keeps flattening our classes requiring manual fixing. Anyone have a solution?

**Comment by laurent-news** [comment]
+1 Facing this problem

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
