### ISSUE TITLE
Docs: Document how to programmatically invoke jscs

### ISSUE THREAD

**Issue by mrjoelkemp** [jscs-dev/node-jscs#1509]
Carry over from the gitter discussion: https://gitter.im/jscs-dev/node-jscs?at=5596c81ff1ed8771684fcd9c

```
var checker = require('jscs');
checker.configure(mySweetConfig);
var errors = checker.checkString(mySweetCodeString);
```

From @hzoo:

```
yeah would be good although it wouldn't go specifically in the readme - I think overview.md
maybe even it's own section?
```

/cc @kadamwhite

**Comment by kadamwhite** [comment]
Awesome! I started a first pass at this on Friday, and will push it up as a PR once I'm back from the weekend.
