### ISSUE TITLE
Impossible to override presets if rule property `requires true value or should be removed`.

### ISSUE THREAD

**Issue by jamestalmage** [jscs-dev/node-jscs#1520]
The following construct is all over the codebase, in many rules:

```js
if ('beforeOpeningRoundBrace' in options) {
  assert(
    options.beforeOpeningRoundBrace === true,
    this.getOptionName() + '.beforeOpeningRoundBrace ' +
    'property requires true value or should be removed'
  );
}
```

The issue arises when a preset (google in my case) sets one of those options to `true`, and I wish to override it and make it`false`. It's just not possible, or the above assertion fails.

**Comment by Slayer95** [comment]
You should make it ``null``

**Comment by jamestalmage** [comment]
Umm...
The code snippet above will pretty obviously throw if the value is null.

```js
var opts = {a: null}

'a' in null; //true

assert(opts.a === true); // throws AssertionError
```

**Comment by zxqfox** [comment]
@jamestalmage Actually, when you nullify rule in your config it won't load nor execute these (nullified) rules at all.

If you want to test it:
```js
var opts = {a: null}

if (opts.a != null) {
  assert(opts.a === true);
}
```

**Comment by mrjoelkemp** [comment]
@zxqfox is correct. The rules with a value of null are never executed. Happy to reopen if you find that to not be the case.

**Comment by jamestalmage** [comment]
I'd be happy if that were true, but you're both wrong, and I tested before replying to @Slayer95 (even though it's plain from reading the code that it wasn't going to work).

```json
{
    "preset": "google",
    "disallowSpacesInFunctionExpression": {
        "beforeOpeningRoundBrace": null
    },
    "disallowSpacesInFunctionDeclaration": {
        "beforeOpeningRoundBrace": null
    },
}
```

throws

```
disallowSpacesInFunctionExpression.beforeOpeningRoundBrace property requires true value or should be removed.
```

The offending code [is here](https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/disallow-spaces-in-function-expression.js#L42).

**Comment by zxqfox** [comment]
@jamestalmage It looks like a bug ;-\ But you can nullify the whole rule:
```
{
  "disallowSpacesInFunctionExpression": null
}
```

@mrjoelkemp What we decided about rule's properties?

**Comment by hzoo** [comment]
@jamestalmage Yeah like @zxqfox said you can nullify the whole rule. It's only plain from the code snippet you posted that it wouldn't work. However if you know about the internals there's a check for null to not load the rule.

https://github.com/jscs-dev/node-jscs/blob/master/lib/config/configuration.js#L490-L495

**Comment by mrjoelkemp** [comment]
@zxqfox not sure i understand the need for allExcept in the context of this issue. We don't nullify parts of a rule's configuration. 

Nullifying the whole rule is the way to go. We should have been more clear when suggesting null.

**Comment by jamestalmage** [comment]
You would still run in to problems if you wanted to toggle both child values (unsetting one and setting the other):
```json
 "disallowSpacesInFunctionExpression": {
    "beforeOpeningRoundBrace": null,
    "beforeOpeningCurlyBrace": true
 }
```
```
disallowSpacesInFunctionExpression.beforeOpeningRoundBrace property requires true value or should be removed
```

Doing this:

```json
 "disallowSpacesInFunctionExpression": null
```

Gets me where I want, but I would hardly call it "closed".

**Comment by markelog** [comment]
If you want to make it better we would appreciate your PR on the matter

**Comment by mikesherov** [comment]
We should probably change our `in` checks to `!= null` checks.

**Comment by guy-mograbi-at-gigaspaces** [comment]
+1 

reached here after using `google` preset and want to override `disallowSpacesInAnonymousFunctionExpression`.. setting null does not resolve this issue for me, tried different versions, nothing works. 

this makes preset practically unusable

**Comment by markelog** [comment]
would you mind posting you config?

**Comment by guy-mograbi-at-gigaspaces** [comment]
```  
jscs: {
            files: lintFiles,
            options: {
                preset: 'google',
                config: 'src/.jscsrc' // tweak for intellij's default
            }
        }

```

```
{
    "validateIndentation": 4,
    "disallowSpacesInAnonymousFunctionExpression": ???
}
```

**Comment by guy-mograbi-at-gigaspaces** [comment]
Just found out that 2 rules affect `function ()` - space before bracket in anonymous function. 

this rule also enforces it

```
    "disallowSpacesInFunctionExpression": {
        "beforeOpeningRoundBrace": true
    },
```

I guess if I override it, then it will go away.
