### ISSUE TITLE
Verbose should provide more information

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1522]
(2.0) We will need to change the docs for this since it's already going to be on right? And the options will have to change to turn it off instead of on?

**Comment by markelog** [comment]
Did we discuss this?

**Comment by hzoo** [comment]
I have to find it but I remember talking about it

**Comment by markelog** [comment]
I'd say you need to know rule name only if want to disable it which seems as a rare case, otherwise you just need to fix the error.

Plus no other linter does it.

**Comment by hzoo** [comment]
Oh it was a comment from @mikesherov so don't know if we did then https://github.com/jscs-dev/node-jscs/issues/1241#issuecomment-90202014

**Comment by mikesherov** [comment]
Yes, I thought we should do verbose by default because new users when configuring need this info.

**Comment by hzoo** [comment]
Oh and the other reason is when reporting a bug for a rule

**Comment by hzoo** [comment]
Let's do this

**Comment by zxqfox** [comment]
:+1:

**Comment by markelog** [comment]
Well, that would practically eliminate this flag and it would be major change, so in any case it would have to wait for 3.0.

To prove these hypothesises we would need to fix https://github.com/jscs-dev/node-jscs/issues/1064, since we didn't received actual opinion from users.

**Comment by markelog** [comment]
Hm, after some thought, i think we should do that, even without #1064, what we want to do with `--verbose` flag though? remove it?

**Comment by hzoo** [comment]
We could make it not do anything? Is there other information we could be telling the user?
