### ISSUE TITLE
Rename esprima and esprimaOptions

### ISSUE THREAD

**Issue by mrjoelkemp** [jscs-dev/node-jscs#1523]
Should be parser and parserOptions, respectively.

**Comment by mikesherov** [comment]
The parser must still produce Esprima output as of the moment. This seems more suitable of a change once parsers output a common CST.

**Comment by hzoo** [comment]
If we do this - 3.0 change?

**Comment by mrjoelkemp** [comment]
Or support both but update our docs to only use parserOptions. This is not
a big win though and I agree that we only work with esprima-like parsers,
so the semantics are currently upheld.

Closable imo
