### ISSUE TITLE
requireSpacesInsideObjectBrackets ignores es6 destructed objects

### ISSUE THREAD

**Issue by oluckyman** [jscs-dev/node-jscs#1524]
test file:
```
import { Map } from 'immutable';
import {List} from 'immutable';

let {z} = obj;
let { x } = obj;
```
.jscsrc
```
{
  "esnext": true,
  "esprima": "esprima-fb",
  "requireSpacesInsideObjectBrackets": "all"
}
```
`$ jscs test.js`
```
No code style errors found.
```
`$ jscs --version`
```
1.13.1
```

**Comment by markelog** [comment]
Added check for destructive assignments, but import statements are more tricky, so i also added tests for it too - https://github.com/jscs-dev/node-jscs/blob/bc90c56791e9a552e2fa8293e9bd0d9e0af768e0/test/specs/rules/require-spaces-inside-object-brackets.js#L68

If you would like to give it try.

**Comment by oluckyman** [comment]
Thanks for quick fix!⚡️

seems you have duplicated assertion here https://github.com/jscs-dev/node-jscs/blob/bc90c56791e9a552e2fa8293e9bd0d9e0af768e0/test/specs/rules/require-spaces-inside-object-brackets.js#L83-L85

**Comment by hzoo** [comment]
Imports are really different from objects, destructuring (although they are all using `{}`)

We should either split into different rules, or have options for each (probably better)

**Comment by hzoo** [comment]
We can cover imports with https://github.com/jscs-dev/node-jscs/issues/2151, https://github.com/jscs-dev/node-jscs/issues/2151

@markelog then we can remove `describe.skip('import (#1524)', function() {`

**Comment by markelog** [comment]
Sounds good to me

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
