### ISSUE TITLE
Spread must be the final element of an element list

### ISSUE THREAD

**Issue by itsjamie** [jscs-dev/node-jscs#1525]
With the javascript below, I receive the error ```Spread must be the final element of an element list```

```javascript
let values = [
  5,
  3
];

Producer.create(window.session, ...values, session => {
  return this;
}
```

Have I missed a configuration option?

Thanks!

**Comment by markelog** [comment]
This issues shouldn't exist in current master, i will close this, but ping us up if it does happen with the latest commits

**Comment by itsjamie** [comment]
"Doh!"

My global JSCS was out of date, I was wondering why SublimeLinter wasn't showing the error but the cli `jscs .` was. 

Thanks!
