### ISSUE TITLE
How to Support Presets for both Airbnb Style Guides

### ISSUE THREAD

**Issue by destroyerofbuilds** [jscs-dev/node-jscs#1529]
Airbnb publishes two style guides, their [ES6 Style Guide](https://github.com/airbnb/javascript), and their [ES5 Style Guide](https://github.com/airbnb/javascript/tree/master/es5).

One example of these guides not agreeing with one another is the ES5 guide which states that trailing commas are not allowed, while the ES6 guide requires trailing commas.

At this time node-jscs only has a single preset for Airbnb, which, as of (jscs-dev/node-jscs@9339ec4) requires trailing commas. That's a change that will break any teams following the ES5 rules.

**Comment by mikesherov** [comment]
Thanks for contributing, @destroyerofbuilds . Seems we should publish a `airbnb-es5` preset. Thoughts /cc @markelog @hzoo @mrjoelkemp

**Comment by hzoo** [comment]
That sounds good to me. Do we want to continue maintaining presets or allow certain orgs to maintain them as well - like for airbnb?

**Comment by mrjoelkemp** [comment]
+1 for a separate preset. Maintenance is pretty low for the preset itself - it's just a collection of rules. The rules are the where most of the maintenance is.

**Comment by defli** [comment]
+1

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
