### ISSUE TITLE
Unsupported rule: validateJSDoc [javascript/jscs]

### ISSUE THREAD

**Issue by jameswomack** [jscs-dev/node-jscs#1533]
I am getting this error even though that rule is not used.

I'm using the latest dev version and this is the config: https://gist.github.com/jameswomack/f779b1dad706398d73a0

**Comment by MarkitoMagic** [comment]
Hi James, how did you resolve this issue?

**Comment by jameswomack** [comment]
@MarkitoMagic I discovered that Syntastic (a vim plugin) was actually pointing to an earlier version of JSCS. I was mistaken in claiming I was using the latest dev version.
