### ISSUE TITLE
Wrong warning with requireSemilicons: false

### ISSUE THREAD

**Issue by Andre-487** [jscs-dev/node-jscs#1534]
Put into jscs.json rule `requireSemilicons: false` with a some preset using:
```
{
  "preset": "yandex",
  "requireSemicolons": false,
  "disallowSemicolons": true
}
```
Get warning: `requireSemicolons option requires a true value or should be removed`

But it's not error. The `requireSemilicons` rule in this case reloads value from preset.

**Comment by hzoo** [comment]
@Andre-487 you want to null a preset rule http://jscs.info/overview.html#presets

`"requireSemicolons": null`

**Comment by Andre-487** [comment]
It works, thanks
