### ISSUE TITLE
disallowImplicitTypeConversion triggered improperly

### ISSUE THREAD

**Issue by adambuczynski** [jscs-dev/node-jscs#1538]
disallowImplicitTypeConversion is triggered for the following code:

```js
return '' +
    '\'use strict\';+\n\n' +
    '/**\n' +
    ' * Environment configuration (' + envName + ')\n' +
    ' */\n' +
    'module.exports = {\n' +
    '  //Your configuration here\n' +
    '};\n';
```

This is because of the `'' +`, but there is clearly no type conversion going on in the code block.

**Comment by mrjoelkemp** [comment]
What about the concat of envName? That's an implicit conversion.

**Comment by adambuczynski** [comment]
By that logic:

```js
return '\'use strict\';+\n\n' +
    '/**\n' +
    ' * Environment configuration (' + envName + ')\n' +
    ' */\n' +
    'module.exports = {\n' +
    '  //Your configuration here\n' +
    '};\n';
```

could also be considered an implicit conversion, because you can never know what's inside `envName`.. But it's not, because `envName` can be assumed to be a string in this case.

I think the rule should be limited to finding occurrences of `'' + var;`, which is an obvious implicit conversion to a string.
