### ISSUE TITLE
Require 1 statement per line

### ISSUE THREAD

**Issue by Famlam** [jscs-dev/node-jscs#154]
valid:
```javascript
c();
d++;
```
invalid:
```javascript
c(); d++;
```

(The following should of course be valid):
```javascript
for (var i=0; i<10; i++) {
  // for loops may contain ; without newlines between the ( and )
}

// Objects don't need { and }
var j = {};

var k = true; //comments are allowed
```

**Comment by markelog** [comment]
This issue has been open more than a month without supported PR for it. 

Unfortunately, we don't have the resources to implement rules that could not be included in any of the supported [presets](https://github.com/jscs-dev/node-jscs/tree/master/presets) (if it could be, please point that out).

However, if you or anybody else submit PR for it, we will gladly consider it.
