### ISSUE TITLE
Should we rename "var" and "decl" rules to "variable" and "declaration" for consistency?

### ISSUE THREAD

**Issue by jacksonrayhamilton** [jscs-dev/node-jscs#1549]
In the following rules, "variable" is spelled correctly:

- `requireLineBreakAfterVariableAssignment`
- `requirePaddingNewLineAfterVariableDeclaration`

In the following rules, "declaration" is spelled correctly:

- `disallowFunctionDeclarations`
- `disallowSpacesInFunctionDeclaration`
- `requireFunctionDeclarations`
- `requirePaddingNewLineAfterVariableDeclaration`
- `requireSpacesInFunctionDeclaration`

But inconsistently, "variable" and "declaration" are misspelled as "var" and "decl" in the following rules:

- `disallowMultipleVarDecl`
- `requireMultipleVarDecl`

And the new rule `requireVarDeclFirst` carries this inconsistency forward.

Perusing the rules reveals that all other rule names are also spelled correctly. You should maintain this consistency by renaming the following rules:

- `disallowMultipleVarDecl` becomes `disallowMultipleVariableDeclarations`, with the old name as an obsolete alias
- `requireMultipleVarDecl` becomes `requireMultipleVariableDeclarations`, with the old name as an obsolete alias
- `requireVarDeclFirst` becomes `requireVariableDeclarationFirst`

**Comment by mrjoelkemp** [comment]
Thanks for contributing @jacksonrayhamilton. It's a good point. We spoke about renaming `disallowMultipleVarDecl` and `requireMultipleVarDecl` for clarity, but didn't really touch on the shortening of `Variable` and `Declaration`. 

Would you like to submit a PR that renames the rules? I'm not sure we have a lot of breaking, rule renaming going on in 2.0. @markelog, do you think we should maintain backCompat for this even if the rename lands in 2.0?

**Comment by mikesherov** [comment]
Yes, we should leave shell copies of the old rules that throw one error: `this rule has been renamed to ...` so that users can migrate easily, with full removal in 3.0

**Comment by mikesherov** [comment]
But there was also a whole lot more renaming we were going to do for 2.0, but now that we haven't released in so long, I fear its counterproductive to do this now as it'll delay a 2.0 for longer than it's already been delayed. This is at least one reason I wanted a 1.14

**Comment by markelog** [comment]
Me and @mdevils thinking of providing new cli flag which we enable config autoformat and if jscs would executed with old config then show those errors with suggestion of using that flag.

That should be pretty easy if we would just map the old config to the new one.

**Comment by mikesherov** [comment]
:+1: to @markelog 's last comment. `jscs --upgrade-config` ?

**Comment by jacksonrayhamilton** [comment]
Upgrades sound awesome. It's only slightly complicated by the fact that comments are allowed in the config files. Users might also want to preserve property order and indentation. To avoid possible frustration, rewriting would have to be handled delicately (not merely by mutating and stringifying the JSON, nor brazenly by regexp; parsing may be required).

Though, having to change a rule at all (even by coercing the user to manually pass `--upgrade-config`) could be annoying for the user, which leads me to question the premise of that feature. It doesn't provide any benefit to the user, it just benefits the maintainers of this project. For maximum user happiness, probably better to just leave the names as aliases forever, rather than forcing an upgrade.

Still, I did as you as asked in the PR. If you change your mind we can alias rather than deprecate.

**Comment by markelog** [comment]
New format and renaming is planned for the user convenience - to make it more consistent and easier to understand

**Comment by hzoo** [comment]
Moving to #1834 - let me know/change it if it's moved over incorrectly.
