### ISSUE TITLE
Consider using conventional-changelog to generate changelog

### ISSUE THREAD

**Issue by stevemao** [jscs-dev/node-jscs#1563]
we have [conventional-changelog](https://github.com/ajoslin/conventional-changelog) or [conventional-github-releaser](https://github.com/stevemao/conventional-github-releaser) (there are also grunt/gulp tasks) to automate the process of writing the changelog. As you are using formatted commit messages so the logs can be generated well according to the parts of the message. We use handlebars for templating the logs. It can also ignore reverted commits. There are many other features. We have a jquery preset for people using jquery commit format.
The modules are actively maintained.

**Comment by stevemao** [comment]
Sample logs generated based on your commits

### AlignedObjectValues

* support computed property names ([2b9bf5c](https://github.com/jscs-dev/node-jscs/commit/2b9bf5c)), closes [#1404](https://github.com/jscs-dev/node-jscs/issues/1404) [#1407](https://github.com/jscs-dev/node-jscs/issues/1407)

### AnonymousFunctionExpression

* account for shorthand methods ([1441305](https://github.com/jscs-dev/node-jscs/commit/1441305)), closes [#1470](https://github.com/jscs-dev/node-jscs/issues/1470) [#1505](https://github.com/jscs-dev/node-jscs/issues/1505)

### API

* allow external entities to be defined without "jscs" prefix ([8b0ac2c](https://github.com/jscs-dev/node-jscs/commit/8b0ac2c))

### Autofix

* remove merge artefact ([c617a58](https://github.com/jscs-dev/node-jscs/commit/c617a58))
* support disallowTrailingComma rule ([7b4212a](https://github.com/jscs-dev/node-jscs/commit/7b4212a))
* support trailing whitespaces and missing commas ([5f2370e](https://github.com/jscs-dev/node-jscs/commit/5f2370e)), closes [#1479](https://github.com/jscs-dev/node-jscs/issues/1479)

### Checker

* more API changes for 2.0 ([83baef5](https://github.com/jscs-dev/node-jscs/commit/83baef5))
* remove deprecated constructor options ([2d5745f](https://github.com/jscs-dev/node-jscs/commit/2d5745f))

### CLI

* Differentiate exit codes ([6f8920d](https://github.com/jscs-dev/node-jscs/commit/6f8920d)), closes [#1095](https://github.com/jscs-dev/node-jscs/issues/1095) [#1506](https://github.com/jscs-dev/node-jscs/issues/1506)

### Configuration

* add "getConfiguredRule" method ([6bdf65d](https://github.com/jscs-dev/node-jscs/commit/6bdf65d))
* add ability to load external presets ([7246452](https://github.com/jscs-dev/node-jscs/commit/7246452)), closes [#109](https://github.com/jscs-dev/node-jscs/issues/109) [#1083](https://github.com/jscs-dev/node-jscs/issues/1083)
* allow "getReporter" method to require node modules ([ce1a877](https://github.com/jscs-dev/node-jscs/commit/ce1a877)), closes [#1030](https://github.com/jscs-dev/node-jscs/issues/1030)
* exclude `node_modules/` by default ([1ba4b45](https://github.com/jscs-dev/node-jscs/commit/1ba4b45)), closes [#1461](https://github.com/jscs-dev/node-jscs/issues/1461) [#1467](https://github.com/jscs-dev/node-jscs/issues/1467)
* improve JSDoc notes ([41e0c58](https://github.com/jscs-dev/node-jscs/commit/41e0c58))
* initial pass on the polymorphic require ([6fc7b41](https://github.com/jscs-dev/node-jscs/commit/6fc7b41))
* simplify and modulize configuration module ([6bdacb1](https://github.com/jscs-dev/node-jscs/commit/6bdacb1)), closes [#1150](https://github.com/jscs-dev/node-jscs/issues/1150)
* small corrections to JSDoc of "node-configuration" module ([87956be](https://github.com/jscs-dev/node-jscs/commit/87956be))
* small refactoring of the configuration module ([c2c5a9b](https://github.com/jscs-dev/node-jscs/commit/c2c5a9b))

**Comment by mrjoelkemp** [comment]
This is pretty great! Thanks for the recommendation @stevemao. 

I assume we'd have to tweak the handlebars templates to get this sample closer to what we produce for our changelogs. We like giving authors credit and grouping all Rule-related changes under a rules section – instead of a section per rule. 

This is definitely a +1 from me to try integrating it into the build flow. 

@stevemao Do you have the command that you used to generate our changelogs handy?

**Comment by stevemao** [comment]
I can definitely tweak the templates for you. I will create a `jscs` preset as the `jquery` preset may not be suitable. 
It would be great if you could create requirements with a sample changelog. 

The sample log I generated was using `conventional-changelog -p jquery` but once `jscs` preset is done you can do `conventional-changelog -p jscs`. To regenerate all previous logs, use `conventional-changelog -p jscs -r 0`

**Comment by hzoo** [comment]
What do we need to do now to use this? I'm ok with manually tweaking the changelog after running `npm run changelog` now like in the past few [releases](https://github.com/jscs-dev/node-jscs/releases/tag/v2.3.0) so it's not too big for me

**Comment by stevemao** [comment]
I have pushed several new releases and a ton of bugs have fixed. Would you still consider using it?

**Comment by stevemao** [comment]
@hzoo Hmmm... Not interested?

**Comment by hzoo** [comment]
Not at the moment, just closing things that we can come back to
