### ISSUE TITLE
Not correct warning: «Inconsistent param found», as i see

### ISSUE THREAD

**Issue by a-x-** [jscs-dev/node-jscs#1564]
Hi, guys!
I have a problem with jscs:
```
Inconsistent param found at ... :
   291 |     * @param {Number} size.width  - ширина картинки
   292 |     * @param {Number} size.height - высота картинки
-------------------------------^
```

As i understang, this is not correct. Right?

See [here our jscs config](https://gist.github.com/a-x-/011958661c1c8fd41bf7).

Thank you!

----

Но по-английски это я так, для прикола :) But English i accept too...

**Comment by hzoo** [comment]
Would this be an issue for https://github.com/jscs-dev/jscs-jsdoc?

**Comment by a-x-** [comment]
ok, you're right

**Comment by a-x-** [comment]
https://github.com/jscs-dev/jscs-jsdoc/issues/127
