### ISSUE TITLE
requireAnonymousFunctions support functionDeclaration exception

### ISSUE THREAD

**Issue by tkissing** [jscs-dev/node-jscs#1569]
As I understand https://github.com/jscs-dev/node-jscs/pull/510 this rule should only apply to function expressions, not declarations, but it does apply to both (effectively disallowing function declarations)

    jscs minimal.js 
    Functions must not be named at minimal.js :
         1 |function foo() {
    --------^
         2 |    return 'foo';
         3 |}

**Comment by mrjoelkemp** [comment]
Hi @tkissing. Thanks for inquiring.

The rule forces you to use anonymous function expressions instead:

```js
var foo = function() {
  return 'foo';
};
```

**Comment by tkissing** [comment]
So the comment 

> please add tests proving it doesn't yell for function declarations.

has been "reversed"?
That is rather unfortunate. I can see the value in saying "all function expressions should be named (for better stacktraces)" or "no function expressions should be named (because we still cater to IE7 and they are just buggy there)", but I don't see why either opinion should have any impact on function declarations.

**Comment by mrjoelkemp** [comment]
I think the best option here is to support `allExcept: ['functionDeclarations']` to avoid changing the default behavior.

Would you like to give that a go? I'll reopen and update the title accordingly if so.

**Comment by tkissing** [comment]
I kinda feel this should be more than one rule conceptually, but given the preference for require/disallow rule pairs I can't come up with anything that's obviously better than `allExcept: ['functionDeclarations']`, so yeah, let's try that. Thank you!
