### ISSUE TITLE
automatic style fixing

### ISSUE THREAD

**Issue by bartosz-k** [jscs-dev/node-jscs#157]
Nice project with JS style hints, but who/what fixes code to follow the defined style? Human or another algorithm? I have not found function that fixes code in the file :)

**Comment by aik099** [comment]
I've contributed to https://github.com/squizlabs/PHP_CodeSniffer project, which uses tokenizer to locate style errors more efficiently. Over time the fixer module was used, that used same parser to replaced bad tokens with correct ones. Style list is composed of sniff classes, that each is responsible for finding an error and fixing it.

**Comment by ryanki1** [comment]
It appears given the following jscs configuration in gruntfile.js:
    ..
    jscs: {
      options: {
        fix: true
      },
      src: 'client/app/**/*.js'
    },
    ..

that commit takes place first and then fix applied. This means that sloppy indentation for example initially gets committed to repository, and only on subsequent commit, following auto-fix, is correct code style applied.
