### ISSUE TITLE
JSCS looks through node_modules

### ISSUE THREAD

**Issue by TheSavior** [jscs-dev/node-jscs#1570]
Running 2.0 on the root directory of my app spends a lot of time looking through node_modules. If I include every file in my app, it lints extremely quickly.

We should make sure that JSCS doesn't even look into the `node_modules` folder.

For example, this glob:
```
**/*.js
!node_modules/**/*
```

Will first iterate through every file in every folder (including in node_modules), and then will iterate through that array to remove everything that matches node_modules. We need to avoid loading the hundreds of thousands of files that the first line might be looking at.

**Comment by mrjoelkemp** [comment]
Nice catch :)

What's the alternative?

**Comment by TheSavior** [comment]
This seems to be what ESLint wrote: https://github.com/eslint/eslint/blob/11f7c712fcec57e8a8cb6feea597e55c6c83348e/lib/util/traverse.js

It seems like they manually walk the directory tree instead of using glob and check if a file matches the exclusion and if it does it stops going down that tree. That seems like it is going to limit the possibilities of glob / minimatch though.

I'm really not sure what the best course of action is. As things stand now though, the option of searching at root is pretty useless. For us it takes over a minute while looking for files if at the root, I had to cancel it and be more specific.

**Comment by mrjoelkemp** [comment]
Thanks @TheSavior. Not a fan of the custom file walker, but it gets the job done.

Working with globbing for me has involved hitting my head against a wall several times – particularly when it comes to multiple excludes. node-glob does have an exclude option that I haven't been able to get working properly (outside of jscs). The approach of constructing one glob pattern that incorporates directory and file exclusions should work.

Will explore other globbing libs and node-glob's exclude to see if there's a better way.

**Comment by TheSavior** [comment]
Something interesting I came across the other day:

[Per node-glob's documentation](https://github.com/isaacs/node-glob#comments-and-negation):

```
Comments and Negation

Note: In version 5 of this module, negation and comments are disabled by default. You can explicitly set nonegate:false or nocomment:false to re-enable them. They are going away entirely in version 6.
```

**Comment by zxqfox** [comment]
We should go for manual tree-walk with https://www.npmjs.com/package/ignore — the most compatible library for gitignore format. IMHO.

**Comment by markelog** [comment]
That's been done
