### ISSUE TITLE
Readme.md looks incorrect in NPM

### ISSUE THREAD

**Issue by oredi** [jscs-dev/node-jscs#1571]
It appears that the badges on NPM looks incorrect for the latest release. Could there be a problem with the comments before the "Dependency Status" tag in the Readme.md. I have attached a screenshot of the problem on my PC

![image](https://cloud.githubusercontent.com/assets/637249/8922894/662363be-3524-11e5-9566-8e82aafcd408.png)

**Comment by stevemao** [comment]
This is more likely an issue with npm website? They have problems with block comments https://github.com/npm/newww/issues/631

**Comment by mrjoelkemp** [comment]
Thanks @stevemao for finding that npm issue. Closing this since we can't do anything about it and it's within npm's wheelhouse.

**Comment by stevemao** [comment]
You could remove your block comment. @mrjoelkemp

**Comment by mrjoelkemp** [comment]
True :) I didn't see why we would change our readme for an npm bug, which is why I didn't consider it an option.
