### ISSUE TITLE
Unknown node type Export Declaration

### ISSUE THREAD

**Issue by kobezzza** [jscs-dev/node-jscs#1573]
"esnext": true 

JSCS@2.0.0

```js
export const foo = {

};
```

**Comment by mrjoelkemp** [comment]
Thanks for reporting @kobezzza. Would you mind sharing your entire jscsrc? 

The error implies that the babel visitor types aren't being applied to estraverse in our tree iterator. @hzoo, can you confirm that all is well on that front? Hopefully babel didn't remove those keys. We should also likely peg our babel version in jscs proper. 

@kobezzza Can you try removing jscs from node_modules and installing it again? Any change?

**Comment by kobezzza** [comment]
> Thanks for reporting @kobezzza. Would you mind sharing your entire jscsrc? 

https://github.com/Collection-JS/Collection/blob/v6/.jscsrc

> @kobezzza Can you try removing jscs from node_modules and installing it again? Any change? 

No :disappointed: 

----

I'm using JSCS with WebStorm for JSX files and he needs eprima-fb parser, maybe the problem in it?

**Comment by kobezzza** [comment]
Issue for JetBrains
https://youtrack.jetbrains.com/issue/WEB-17471

**Comment by mrjoelkemp** [comment]
@kobezzza Thanks! I'm not familar with how Jetbrains uses JSCS, but does it require you to globally install jscs? Or does it ship with a particular version of jscs?

**Comment by kobezzza** [comment]
@mrjoelkemp path to JSCS must be required in Project Preferences and it can be global or local.

**My config**: 

JSCS package: *C:\Users\kobezzza\Documents\dev\myProject\node_modules\jscs*

But in JSX mode WebStorm also need to install **eprima-fb** package, and i installed it locally with my project.

**Comment by mrjoelkemp** [comment]
Can you globally install jscs 2.0? Make sure your jscsrc has `esnext: true` to use babel-jscs. The `esprima-fb` parser is deprecated and babel-jscs replaces it.

Seems like there's a workaround, so I assume your issue is resolved. Feel free to report back if the upgrade to 2.0 and esnext flag fixed your issue.

Thanks again for reporting!

**Comment by kobezzza** [comment]
@mrjoelkemp unfortunately it didn't help :disappointed: It seems like that WS by default in JSX uses esprima-fb. I hope that they fix it soon. Thanks for help!

**Comment by smashercosmo** [comment]
@mrjoelkemp 
> Seems like there's a workaround

so, what's the workaround?)

**Comment by mercuriete** [comment]
I had exactly the same problem.

i fixed it deleting from the .jscsrc
the line that i had


"esprima": "esprima-fb"


then it appeared a lot of new warnings about linting with the rule validateQuoteMarks

but in the end i got working the project without esprima-fb.

**Comment by hzoo** [comment]
Basically the `esnext` option uses `"esprima": "babel-jscs"` so you need to remove the other `esprima` options. I guess your other issue is probably https://github.com/jscs-dev/babel-jscs/issues/12

**Comment by mercuriete** [comment]
yes, but i am basically changing all quotes of my code from doublequotes to singlequotes and its fine.

thanks you so much for your quick answer.
