### ISSUE TITLE
Indentation is off when autoformatting code

### ISSUE THREAD

**Issue by ryanjadhav** [jscs-dev/node-jscs#1576]
Used autoformat with `"validateIndentation": 4`, resulted in incorrect indentation. Using jscs version 1.8.0. 

Example:
![screen shot 2015-07-27 at 6 24 46 pm](https://cloud.githubusercontent.com/assets/238376/8937417/15fb6fce-350d-11e5-9e74-24a6c8b16ed6.png)

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
