### ISSUE TITLE
JSDoc and spread

### ISSUE THREAD

**Issue by kobezzza** [jscs-dev/node-jscs#1577]
All examples are valid for Closure Compiler.

*Expects valid type instead of ...?*

```js
/**
 * @param {...?} args
 */
function decorate(args) {

}
```

*Expects valid type instead of function(...?)*

```js
/**
 * @return {function(...?)}
 */
function decorate() {
	return function () {
		[].slice.call(arguments).forEach(function () {

		});
	};
}
```

**Comment by zxqfox** [comment]
Are you sure about `...?`? Looks like you need to use `...*`.

**Comment by kobezzza** [comment]
> Are you sure about ...?? Looks like you need to use ...*

Yep.

**The ALL type**  `*` Indicates that the variable can take on any type.
**The UNKNOWN type** `?` Indicates that the variable can take on any type, and the compiler should not type-check any uses of it.

https://developers.google.com/closure/compiler/docs/js-for-compiler

**Comment by kobezzza** [comment]
JSCS@2.1.0 still has this bug :cry:

**Comment by zxqfox** [comment]
I've left an issue in jsdoctypeparser, hope to find some time in a week or two.

**Comment by zxqfox** [comment]
Okay, my turn now ;-)

**Comment by trikadin** [comment]
+1

**Comment by kobezzza** [comment]
pleeeese, very need this fix :sob:

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
