### ISSUE TITLE
Autofixing quote is commenting out code

### ISSUE THREAD

**Issue by TheSavior** [jscs-dev/node-jscs#1578]
We have a few cases in our code base of multi line template strings like this:

```
{
  html: '\
      <iframe class="classes"\
              src="foo<%= foo %>">\
      </iframe>\
    '
}
```

When running the autofix for `validateQuoteMark`, it returns this:

```
{
  html: '\
/*  <iframe class="classes"\
              src="foo<%= foo %>*/">\
/*  </iframe>*/\
    '
}
```

How did those comment tags get in there?

**Comment by mrjoelkemp** [comment]
Thanks for reporting @TheSavior. Any help investigating this is appreciated.
