### ISSUE TITLE
`requireHyphenBeforeDescription` should not apply to descriptions on next line

### ISSUE THREAD

**Issue by BigstickCarpet** [jscs-dev/node-jscs#1579]
The new `requireHyphenBeforeDescription` option is great, but it should only apply to _inline_ descriptions.  If a description is on the next line (usually because it's a long one), then no hyphen should be required.

**Example:**
```javascript
/**
 * This function does foo to bar.
 *
 * @param {string} bar
 * This is a really long description of the "bar" parameter.  In fact, the description
 * is so long that it spans multiple lines.
 */
function foo(bar) {
```

Currently, in order to make this check pass, I have to add a hyphen, like this (which looks weird):

```javascript
/**
 * This function does foo to bar.
 *
 * @param {string} bar
 * - This is a really long description of the "bar" parameter.  In fact, the description
 * is so long that it spans multiple lines.
 */
function foo(bar) {
```

**Comment by zxqfox** [comment]
Thanks for report, it's not really for jscs, but for jscs-jsdoc. Going to fix that. ;-)

**Comment by markelog** [comment]
@zxqfox don't forget to update `jscs-doc` dep

**Comment by zxqfox** [comment]
@markelog Yeah, sure. Will try to work on #1531
