### ISSUE TITLE
Add "pessimistic" arrow function rules

### ISSUE THREAD

**Issue by jacksonrayhamilton** [jscs-dev/node-jscs#1580]
There should be a `disallowArrowFunctions` rule, and a `disallowShorthandArrowFunctions` rule.

It turns out that you don't need `this` to write JavaScript. Object-orientation is perfectly viable with functions that return objects. In fact, it might be better, because if you create objects with functions, you can hide information with closures; whereas everything on `this` has to be publicly accessible.

Since `this` isn't needed, arrow functions' lexical `this` isn't useful. Arrow functions are also less versatile than `function`, because you can't give them names. Arrow functions' tricky syntax is also harmful to maintenance. Adding additional lines to an arrow function which implicitly returns a value will result in that function returning `undefined`, unless you remember to add an explicit `return`. The shorthand syntax is also ambiguous in terms of returning objects, as `(name) => {id: name}` is interpreted as a longhand arrow function with the label `id:`.

Some people might decide to just eliminate them altogether, since `function` seems a lot better if you aren't using `this`. But for people who don't mind `this`, they might want to reap the perceived benefits of arrow functions while avoiding their syntactic problems, by requiring they be written in the most-generalized form, the longhand form. Therefore, it is important these rules be added.

**Comment by mrjoelkemp** [comment]
Thanks @jacksonrayhamilton. Great ideas. Would love two separate issues on the rule proposals. Alternatively, if you're up for submitting a PR that lands both, then that would be awesome.

**Comment by jacksonrayhamilton** [comment]
I will gladly implement these rules.

**Comment by markelog** [comment]
Sometimes it is scary to observe how Crockford ideas influence people so strongly

**Comment by jacksonrayhamilton** [comment]
It's the idea that matters, not the person.

JSLint actually [forbids](http://jslint.com/help.html#function) the block (though for a similar reason, ambiguity):

> Finally, ES6 provides an even shorter form of function expression that leaves out the words function and return:
>
> ```
> (parameters) => expression
> ```
>
> **JSLint** requires the parens around the parameters, and forbids a { left brace after the => fart to avoid syntactic ambiguity.

**Comment by markelog** [comment]
You can also add https://gist.github.com/qubyte/43e0093274e793cc82ba#gistcomment-1292183 to your list, would be cool if you unite those lists together, so we would have explanation for this rule and why it is useful.

Could in docs or it could be a link to the such page

**Comment by jacksonrayhamilton** [comment]
Should I add the explanation to the documentation for the rules? A quick skim reveals other rules don't contain justifications. Or is there another document I could add it to?

**Comment by markelog** [comment]
You could create a gist for it add link to the docs or put them directly.

> A quick skim reveals other rules don't contain justifications

Would be nice isn't it? Since arrow syntax is "improvement" on ECMAScript previous version, it might be convenient to explain to the user of why we add such a rule.
