### ISSUE TITLE
Error running rule `requirePaddingNewLinesAfterBlocks`

### ISSUE THREAD

**Issue by angelomichel** [jscs-dev/node-jscs#1583]
Hi. 

While using Atom editor v 1.0.3 (just updatet from 1.0.2) I got the follow issue.
```
Error running rule requirePaddingNewLinesAfterBlocks: This is an issue with JSCS and not your codebase. 
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
TypeError: Cannot read property 'type' of null
  at isException (/Users/atom/.atom/packages/linter-jscs/node_modules/jscs/lib/rules/require-padding-newlines-after-blocks.js:132:27)
  at Object.

 (/Users/atom/.atom/packages/linter-jscs/node_modules/jscs/lib/rules/require-padding-newlines-after-blocks.js:190:17)
  at Array.forEach (native)
  at Object.JsFile.iterateNodesByType (/Users/atom/.atom/packages/linter-jscs/node_modules/jscs/lib/js-file.js:478:42)
  at Object.module.exports.check (/Users/atom/.atom/packages/linter-jscs/node_modules/jscs/lib/rules/require-padding-newlines-after-blocks.js:185:14)
  at [object Object].
```

The error requested me to post it here :) so there you go!

**Comment by mrjoelkemp** [comment]
@angelomichel Thanks for reporting. For use with atom, do you need to globally install jscs, or does it ship with an Atom plugin? 

If you have to globally install jscs, you're likely on an old version. Upgrading your version of jscs will fix the issue. Mind reporting back if that worked?

Thanks!

**Comment by angelomichel** [comment]
I have just updatet via npm -g to jscs@2.0.0, restarted atom. Problem still occours.

**Comment by mrjoelkemp** [comment]
Thanks for reporting back. Is it possible to provide a snippet of code that reproduces the error?

**Comment by angelomichel** [comment]
@mrjoelkemp I now see the actual problem. The preset of airbnb has been changed so that trailingComma's now is mandatory. 

So problem fixed again (for those, non Babel users, who wonder how to fix; overwrite it in your own jscs settings!)

**Comment by mrjoelkemp** [comment]
Glad to hear about the fix, but the error message is concerning. It should have produced a style error, not a runtime error. 

We'd still appreciate a snippet to prevent this from happening to others. 

Thanks again.

**Comment by angelomichel** [comment]
I have added in my git project on root this `.jscs.json` file:
```json
{
  "preset": "airbnb",
  "disallowTrailingComma": true,
  "requireTrailingComma": null
}
```

**Comment by hzoo** [comment]
This would related to changing airbnb to have es5 and es6 presets

**Comment by zxqfox** [comment]
> but the error message is concerning. It should have produced a style error, not a runtime error.

@mrjoelkemp @hzoo Let's reopen this then?

**Comment by mrjoelkemp** [comment]
Happy to reopen if we have a snippet of code for reproducing the error message. 

@angelomichel, any chance you could help us?
