### ISSUE TITLE
are you able to mix preset and properties

### ISSUE THREAD

**Issue by skinnybrit51** [jscs-dev/node-jscs#1585]
Are you able to define a `.jscsrc` with a preset and then override some of the properties?
EG

```
{
  "preset": "airbnb",
  "requireSpaceAfterObjectKeys": true,
  "safeContextKeyword" : "that",
  "validateIndentation" : 4
}

```

**Comment by mrjoelkemp** [comment]
You sure can! Thanks for asking. Feel free to ask in the [gitter room](https://gitter.im/jscs-dev/node-jscs) if you need any further assistance.
