### ISSUE TITLE
Project has ~1200 lines worth of dependencies

### ISSUE THREAD

**Issue by kevinburkeshyp** [jscs-dev/node-jscs#1586]
I downloaded this project and was surprised at how many other packages it depends on; it blew up the `npm-shrinkwrap` file we use by 1100 lines. Surely some of these are extraneous, or would make more sense as code written inline in the project? 

How do you manage all of these? Does someone in the project at least understand the code for every new dependency you add?

**Comment by zxqfox** [comment]
I bet it's because of `babel-*` packages have a lot of dependencies.

**Comment by mrjoelkemp** [comment]
Why shrinkwrap jscs? It's usually a devDependency.

We could remove the babel dependency and inline its visitor keys for
estraverse.

**Comment by ruimarinho** [comment]
In addition to @mrjoelkemp's comment, just tested the improvement from dependency flattening from npm@2 to npm@3 and that number gets reduced by ~330 lines. Not a huge improvement, but still nice.

**Comment by mrjoelkemp** [comment]
Btw, we're totally open to a Pr that inlines the visitor keys into
tree-iterator.js if anyone is interested.

**Comment by hzoo** [comment]
@kevinburkeshyp yeah the babel dependency was just added last release (2.0) - if we want to support using esnext with babel-jscs it needs to be a dependency (it uses babel-core) or we remove that. Or something weird would be to install the dependency later if they use esnext somehow.

Internet at the place I'm at doesn't really work and I'll probably be too busy the next few days to work on anything :(

**Comment by mrjoelkemp** [comment]
@hzoo Good point about babel-core being used within babel-jscs. I forgot that `parse` was being used. Looking into parse though, it seems like it's just mostly a passthrough to [babylon](https://github.com/babel/babel/tree/master/packages/babylon). 

Do you think that babel-jscs could just inline parts of babel-core's parse and parse directly with babylon? This would avoid the [truckton of dependencies](https://github.com/babel/babel/blob/master/packages/babel/package.json#L30-L76) from babel-core (unless I'm underestimating how much of those dependencies are necessary for an ast parse).

**Comment by hzoo** [comment]
Yeah I think it's possible - it's only recently that the parser was split from acorn and in its own package - I'll look into it.

**Comment by hzoo** [comment]
`index.js` uses `var parse          = require("babel-core").parse;` which we could inline. But it's not the parse problem that is the problem

```js
var traverse = require("babel-core").traverse;
var tt       = require("babel-core").acorn.tokTypes;
var t        = require("babel-core").types;
```

in `acorn-to-esprima` (the file that's needed to convert from the acorn/babel format to esprima) uses some more methods/data also in babel-core. Yeah I don't think we can reduce the babel packages needed in `babel-jscs`

**Comment by mrjoelkemp** [comment]
Good point, @hzoo. Thanks for looking into it.

I'm going to close this as a wont-fix since my original question of why a devDependency should be shrinkwrapped wasn't addressed. I'm not convinced this is an actual problem that's breaking anything.

Happy to reopen with more details.

**Comment by hzoo** [comment]
It might be possible to split it since it since looks like @sebmck is splitting babel-core - I'm guessing we would use `babel-types` and `babel-traverse` at least

**Comment by hzoo** [comment]
Just a heads up that we will be able to just use babylon when we integrate with cst (which uses that) in 3.0
