### ISSUE TITLE
ExportDeclaration is unknown node type

### ISSUE THREAD

**Issue by kadmil** [jscs-dev/node-jscs#1591]
After update to 2.0 jscs-check fails with es6 export declaration.

**Comment by markelog** [comment]
Could your jscs config and problematic code?

**Comment by kadmil** [comment]
Code

    const ururu = 500
    export default ururu

Config

    {
        "preset": "airbnb",
        "requireCurlyBraces": null,
        "disallowSemicolons": true,
        "disallowTrailingComma": null,
        "requireTrailingComma": {"ignoreSingleValue": true,"ignoreSingleLine": true},
        "excludeFiles": ["node_modules/**"],
        "fileExtensions": [".js", ".jsx"],
        "esnext": true,
        "verbose": true,
        "esprima": "esprima-fb"
    }

**Comment by markelog** [comment]
Remove this
`"esprima": "esprima-fb"`

**Comment by kadmil** [comment]
Would it work with jsx?

**Comment by markelog** [comment]
Yep, it you could even remove `esnex:true`, since `airbnb` preset already does it

**Comment by kadmil** [comment]
Thanks a lot!
