### ISSUE TITLE
Dot location rule

### ISSUE THREAD

**Issue by TheSavior** [jscs-dev/node-jscs#1593]
ESLint has a rule to enforce dot location: http://eslint.org/docs/rules/dot-location

For example:

```
var foo = object
  .property;
```

vs

```
var foo = object.
  property;
```

It seems like a code style rule that should be part of JSCS.

**Comment by mrjoelkemp** [comment]
JSCS did it first: http://jscs.info/rule/disallowOperatorBeforeLineBreak.html :)

That should suffice. There's a require counterpart as well.
