### ISSUE TITLE
disallowPaddingNewlinesInBlocks & requirePaddingNewlinesInBlocks to be set independently for functions and other blocks

### ISSUE THREAD

**Issue by 9point6** [jscs-dev/node-jscs#1596]
It would be nice to be able to specify newline padding settings independently for functions and other blocks.

disallowPaddingNewlinesInBlocks & requirePaddingNewlinesInBlocks currently both apply to every kind of block.

**Comment by mrjoelkemp** [comment]
Thanks for contributing @9point6. The typical rule values for these exceptions would be `allExcept: ['function', 'if', 'else']`.

Would you like to submit a pull request to tackle this issue? We could use the help.
