### ISSUE TITLE
Allow immediate require() statements following use strict when requirePadding...=true

### ISSUE THREAD

**Issue by Qix-** [jscs-dev/node-jscs#1599]
Our code style requires `require()` statements to immediately follow `'use strict';`. However, JSCS doesn't like that :)

```javascript
// requirePaddingNewlinesAfterUseStrict
'use strict';
var something = require('something'); // ERROR

/* rest of code, after exactly 1 empty line */
```

It'd be nice to have

```json
{
  "requirePaddingNewlinesAfterUseStrict": "require"
}
```

I'd attempt a PR but the learning curve for this node/AST system is a bit steep for the time I have right at this moment.

// @sindresorhus

**Comment by mrjoelkemp** [comment]
Good idea. Thanks for contributing. The value should be allExcept:
['require'].

**Comment by Qix-** [comment]
Thank you :dancer:

// @sindresorhus
