### ISSUE TITLE
requireSpacesInAnonymousFunctionExpression breaks ES6 classes

### ISSUE THREAD

**Issue by ronkorving** [jscs-dev/node-jscs#1607]
I use the following configuration:

```json
"requireSpacesInAnonymousFunctionExpression": {
	"beforeOpeningRoundBrace": true,
	"beforeOpeningCurlyBrace": true
}
```

And it breaks in a simple ES6 class on each declared method. Saying for example (in verbose mode):

```
requireSpacesInAnonymousFunctionExpression: Missing space before opening round brace at lib/MyWriter.js :
     7 |class MyWriter extends Transform {
     8 |
     9 | constructor() {
---------------------^
    10 |  super({ writableObjectMode: true });
    11 |
```

The ES6 code:

```js
class MyWriter extends Transform {
  constructor() {
    super({ writableObjectMode: true });
  }
}
```

These are ES6 class methods, I have `"esnext": true` set, so I don't expect my methods to be considered anonymous functions.

PS: If this is all because of Babel turning these methods into anonymously assigned prototype functions, sure it makes sense why this happens. But it's not obvious and while perhaps by spec these *are* anonymous functions assigned to the prototype, I think they deserve their own rule or perhaps some exception value.

PS2: Wow, even adding a space before the opening brace (ie: `constructor () {`) gives the **same** error. Mind blown.

**Comment by markelog** [comment]
> I think they deserve their own rule or perhaps some exception value.

Yeah, it might be a good thing, would you like to create one? Should be pretty similar to `requireSpacesInAnonymousFunctionExpression `

> PS2: Wow, even adding a space before the opening brace (ie: constructor () {) gives the same error. Mind blown.

Oh, god, No! There is so much blood! 

... 

Anyway, that is bug and [that](https://github.com/jscs-dev/node-jscs/pull/1608) is a fix for it.

**Comment by markelog** [comment]
> I think they deserve their own rule or perhaps some exception value.

https://github.com/jscs-dev/node-jscs/issues/1513 btw :-)

**Comment by ronkorving** [comment]
You work fast, awesome job :)

**Comment by hzoo** [comment]
So we need to make the changes (and previous ones) for `inNamedFunctionExpression` and `inFunction` right

**Comment by ronkorving** [comment]
I just tried out 2.1.0, and the problem persists...

```
requireSpacesInAnonymousFunctionExpression: Missing space before opening round brace at lib/Foo.js :
     7 | }
     8 |
     9 | add(chunk) {
------------^
```

**Comment by markelog** [comment]
This fix was intended for the 

> PS2: Wow, even adding a space before the opening brace (ie: constructor () {) gives the same error. Mind blown.

issue, everything else is https://github.com/jscs-dev/node-jscs/issues/1513

**Comment by markelog** [comment]
btw, would you like to implement such value?

**Comment by ronkorving** [comment]
I'm currently not too familiar with the internals, Esprima, and I don't have much time. I'll live if I can't have this now and we put it on the backburner. But I don't think this issue should be closed, should it?

**Comment by hzoo** [comment]
@markelog is saying the issue is in #1513 so follow that for the new option
