### ISSUE TITLE
Add option to disallowEmptyBlocks to allow blocks with comments

### ISSUE THREAD

**Issue by ptarjan** [jscs-dev/node-jscs#1611]
https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/disallow-empty-blocks.js

I'd like this to be allowed:

```
if (foo) {
  ...
} else if (bar) {
  // We shouldn't do anything here because of ...
} else {
  ...
}
```

**Comment by mrjoelkemp** [comment]
Thanks for contributing! Great idea. 

A new rule value to support this would be allExcept: ['comments']. 

Would you like to give the implementation a shot? We could use the help.

**Comment by faceleg** [comment]
I've had a go at this - a stumbling block I've run into is that the parse doesn't seem to give an if-block's node a body if that body consists only of a comment.

**Comment by hzoo** [comment]
@faceleg Yeah I think it would be empty - although comments aren't aren't in the tree in that way - maybe look at some other rules dealing with comments (like https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/require-padding-newlines-before-line-comments.js which iterates over comments or https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/maximum-line-length.js#L117 which checks if an option is there to iterate over comments)

**Comment by faceleg** [comment]
@hzoo thanks this is very helpful.

**Comment by ptarjan** [comment]
yay, thanks
