### ISSUE TITLE
[disallowPaddingNewlinesInObjects] Getting false positives

### ISSUE THREAD

**Issue by ShimShamSam** [jscs-dev/node-jscs#1612]
The following code has two false errors:

```javascript
var events = {
	playeradded   : [],
	playerremoved : [],
};
```

The errors I'm getting are:

    Illegal newline after opening curly brace
    Illegal newline before closing curly brace

Removing the following rules fixes the issue:

    "disallowPaddingNewLinesInObjects": true,

**Comment by christophehurpeau** [comment]
Unless I'm mistaken, please read the documentation on this rule : http://jscs.info/rule/disallowPaddingNewLinesInObjects.html

Your valid code with this rule should probably be:
```js
var events = { playeradded   : [],
    playerremoved : [], };
```

**Comment by mrjoelkemp** [comment]
Yes. @christophehurpeau is correct. Thanks!
