### ISSUE TITLE
validateIndentation -- is this indention format validation achievable

### ISSUE THREAD

**Issue by KrekkieD** [jscs-dev/node-jscs#1613]
Ran across this formatting issue in my unit tests:

```javacript
// fails:
it ('should do something that has a rather long description ' +
    'and is therefore split in two lines', function () {

    /* mark */
    doSomethingHere();

});
```

The rule `validateIndention: 4` appears to expect all lines starting from `/* mark */` to be indented 4 spaces more than they are now.

I would like it to use the line containing `it` as base indention and count `+4` from there, but it appears to be using the next line which increases required indention by 4:

```javacript
// passes:
it ('should do something that has a rather long description ' +
    'and is therefore split in two lines', function () {

        /* mark */
        doSomethingHere();

    });
```

The passed version creates a weird layout when continuing the script:

```javacript
// passes:
it ('should do something that has a rather long description ' +
    'and is therefore split in two lines', function () {

        doSomethingHere();

        /* if there's a lot of code here, the base indention is no longer visible */

    });

it ('my next "it" is required to start on column 0 again, which creates ' +
    'an unexpected indention jump from 4 to 0', function () { });

```

Is it currently possible to configure the rules to allow the failing snippet to pass?
If not, could it be added as a feature?

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
