### ISSUE TITLE
requireParenthesesAroundArrowParam incorrectly flags rest parameters

### ISSUE THREAD

**Issue by mduvall** [jscs-dev/node-jscs#1616]
`.jscsrc`:

```json
{
  "esnext": true,
  "requireParenthesesAroundArrowParam": true
}
```

Code that breaks `requireParenthesesAroundArrowParam`:

```js
const foo = (...args) => {};
```

This however, is okay:

```js
const foo = (args) => {};
```

**Comment by mrjoelkemp** [comment]
Thanks for reporting the issue @mduvall. 

cc @hzoo

**Comment by hzoo** [comment]
The `isWrapped` function doesn't account for rest param since it just does `getPrevToken` once - probably can do a helper or something but I guess this PR works in the meantime.

**Comment by mduvall** [comment]
@hzoo: Fantastic, amazing turnaround time, thank you.
