### ISSUE TITLE
requireCapitalizedComments conflicts with JSHint configuration comments

### ISSUE THREAD

**Issue by westonruter** [jscs-dev/node-jscs#1627]
Consider some standard JSHint configuration comments:

```js
/* globals jQuery, _httpsResourceProxyExports */
/* exported httpsResourceProxy */
var httpsResourceProxy = ( function( $ ) {
```

JSCS is reporting these comments as being violations of `requireCapitalizedComments`:

```
requireCapitalizedComments: Comments must start with an uppercase letter, unless it is part of a textblock at js/https-resource-proxy.js :
     1 |/* globals jQuery, _httpsResourceProxyExports */
--------^
     2 |/* exported httpsResourceProxy */
     3 |var httpsResourceProxy = ( function( $ ) {

requireCapitalizedComments: Comments must start with an uppercase letter, unless it is part of a textblock at js/https-resource-proxy.js :
     1 |/* globals jQuery, _httpsResourceProxyExports */
     2 |/* exported httpsResourceProxy */
--------^
     3 |var httpsResourceProxy = ( function( $ ) {
     4 |
```

If you then try to upper-case these JSHint comments, then JSHint doesn't recognize them and later complains, e.g.:

```
js/https-resource-proxy.js: line 10, col 25, '_httpsResourceProxyExports' is not defined.
js/https-resource-proxy.js: line 3, col 5, 'httpsResourceProxy' is defined but never used.
```

Should such JSHint comments be whitelisted from `requireCapitalizedComments` in JSCS?

**Comment by KrekkieD** [comment]
You can exclude them manually right? http://jscs.info/rule/requireCapitalizedComments.html

**Comment by westonruter** [comment]
@KrekkieD sure, but then it seems like `requireCapitalizedComments` would need to be usually excluded, considering most JS files have JSHint/JSLint configuration comments like `global`.

Otherwise, `requireCapitalizedComments` will need to be excluded by default for the `wordpress` preset.

**Comment by mrjoelkemp** [comment]
Thanks for contributing @westonruter! 

> most JS files have JSHint/JSLint configuration comments like global.

Seems like a codebase-specific choice. You could just define the globals in a jshintrc. The only built-in exception to the rule is the `jscs` pragma.

It seems to me like the best course of action is to set `allExcept: ['globals']` in your configuration. I don't see why the wordpress preset would need to be extended for this.

**Comment by markelog** [comment]
Since wordpress (see the #1632) explicitly prescribes use of such comments, should we reconsider? 

@mrjoelkemp ?

**Comment by mrjoelkemp** [comment]
Yup!
