### ISSUE TITLE
Spaces in ES2015 object literals

### ISSUE THREAD

**Issue by verkholantsev** [jscs-dev/node-jscs#1628]
In `jscs:2.0.0` this code with new ES2015 literal syntax causes an error `Missing space before opening round brace`.
```
let obj = {
  method() {
  }
};
```

 And this code causes an error  `Illegal space after key`. 
```
let obj = {
  method () {
  }
};
```

Are there any rules for this case?

**Comment by hzoo** [comment]
Thanks for reporting @verkholantsev. You can specify `jscs . --verbose` to see the rule that causes the error. I think we have an issue for this already but not sure.

**Comment by kobezzza** [comment]
https://github.com/jscs-dev/node-jscs/issues/1513

**Comment by hzoo** [comment]
Ok closing in favor of #1513.
