### ISSUE TITLE
jscs tries to validate excluded files =(

### ISSUE THREAD

**Issue by iamstarkov** [jscs-dev/node-jscs#1631]
> Specific rules that that have issues (jscs --verbose helps with this)

it doesnt relate to rules

> A failing test would be amazing

```
➜  jscs-exlude-files-bug git:(master) ✗ cat .jscsrc
{
  "plugins": ["jscs-config-nordnet"],
  "preset": "nordnet",
  "excludeFiles": [
    "app/templates/_index.test.js"
  ]
}
➜  jscs-exlude-files-bug git:(master) ✗ npm run jscs
> jscs-exlude-files-bug@1.0.0 jscs /Users/vlasta/projects/jscs-exlude-files-bug
> jscs app

parseError: undefined at app/templates/_index.test.js :
     1 |import sinon from 'sinon';
     2 |import { expect } from 'chai';
     3 |import <%= camelModuleName %> from './../src/index';
---------------^
     4 |
     5 |describe('<%= camelModuleName %>', () => {


1 code style error found.
```

you can reproduce this error here https://github.com/iamstarkov/jscs-exlude-files-bug

**Comment by iamstarkov** [comment]
it seems to work fine, if you will delete `plugins` field

**Comment by iamstarkov** [comment]
I check [docs](https://github.com/jscs-dev/node-jscs/wiki/Plugin-API) and [jscs-config-nordnet implementation](https://github.com/nordnet/jscs-config-nordnet/blob/master/lib/index.js) and cannot see any problem with jscs-config-nordnet

**Comment by iamstarkov** [comment]
change preset from "nordnet" to "airbnb" also solve the issue

**Comment by iamstarkov** [comment]
but anyway it should be some bug in jscs

**Comment by markelog** [comment]
What happens if you change 
```js
 "excludeFiles": [
    "app/templates/_index.test.js"
  ]
```
to
```js
 "excludeFiles": [
    "./app/templates/_index.test.js"
  ]
```
?

**Comment by iamstarkov** [comment]
it doesn’t help https://travis-ci.org/iamstarkov/jscs-exlude-files-bug#L43-L65

**Comment by markelog** [comment]
Thank you for the repo, this looks severe, so this should fixed soon and release should happen on monday.

**Comment by iamstarkov** [comment]
@markelog any news here? also is there anything I can help with?

**Comment by markelog** [comment]
There you go - #1652
