### ISSUE TITLE
Eventually support property AST types for ES7 features undoing _babelType

### ISSUE THREAD

**Issue by mrjoelkemp** [jscs-dev/node-jscs#1633]
Ref https://github.com/jscs-dev/node-jscs/pull/1625/files#r36373503

`_babelType` is a temporary AST addition that adds non-standard es7+ AST types like 'SpreadOperator'.

**Comment by hzoo** [comment]
Ok after https://github.com/jscs-dev/babel-jscs/pull/22 we can use `node.type === "SpreadProperty"` instead.

**Comment by hzoo** [comment]
We can do ^ now.
