### ISSUE TITLE
Should we support ES7+ rules?

### ISSUE THREAD

**Issue by mrjoelkemp** [jscs-dev/node-jscs#1634]
Ref https://github.com/jscs-dev/node-jscs/pull/1625#issuecomment-128199638
Ref https://github.com/jscs-dev/babel-jscs/issues/13#issuecomment-120954046

Arguments for:

* Users of these experimental features have linting options
* JSCS keeps up with the advancements in the language

Arguments against: 

* non-standard node types have to be added to the AST (see #1633) and then later changed during standardization in ESTree and parser adoption.
* these rules will likely need to change behavior as the es7+ proposed rule is revised through the stages
 * How do these rules affect our semver policy?
 * Should they be versioned separately (see http://bit.ly/1NdBUss for an argument pro separate versioning)?

**Comment by hzoo** [comment]
If we have esnext using babel-jscs then users are going to report many es7+ issues - with async, await, generators, object rest, spread - looks like a few already.

**Comment by markelog** [comment]
I'd say we should wait and see how many people needed it, presumably all rules should work correctly with es7

**Comment by hzoo** [comment]
So we would fix issues like #1637 and https://github.com/jscs-dev/babel-jscs/issues/13? I'm ok with doing it

**Comment by mrjoelkemp** [comment]
All rules working with es7 is the other half of supporting es7. We run into
issues with new syntax that doesn't have the appropriate types without
workarounds like _babelType.

Agreed about waiting for es7 rule requests.

**Comment by markelog** [comment]
>  We run into
issues with new syntax that doesn't have the appropriate types without
workarounds like _babelType.

Yeah, that is unfortunate, but looking at amount of es7 issues recently, it seems people want it

**Comment by hzoo** [comment]
I guess we already started on doing this then?

**Comment by zxqfox** [comment]
I've started using babel and this is my :+1: for this. We should keep going ;-)

**Comment by mrjoelkemp** [comment]
Haven't done any es7-only rules, but we are making fixes to support es6.

**Comment by hzoo** [comment]
Well the object spread stuff is es7
