### ISSUE TITLE
Problems with disallowSpacesInFunctionExpression and beforeOpeningRoundBrace, if I use async functions

### ISSUE THREAD

**Issue by donaldpipowitch** [jscs-dev/node-jscs#1637]
It looks like this code

```
await* files.map(async function(file) {
  // ...
})
```

throws an error, if I use `disallowSpacesInFunctionExpression` with `beforeOpeningRoundBrace: true` and will be auto-fixed to `asyncfunction`.

It looks like using an arrow function here works.

**Comment by hzoo** [comment]
Another es7 fix

**Comment by MikeMcElroy** [comment]
Supplied PR #1745 to fix this -- sorry for the multiple references.
