### ISSUE TITLE
requireShorthandArrowFunctions returning object literal

### ISSUE THREAD

**Issue by SimenB** [jscs-dev/node-jscs#1639]
```js
requestSent = _.map(requests, req => {
  return {
    requestBody: $.parseJSON(req.requestBody),
    requestHeaders: req.requestHeaders,
    method: req.requestMethod,
    url: req.requestURL
  };
});
```

JSCS tells me to use shorthand, but I'm returning an object literal, so shorthand breaks.

Using `2.0.0`

**Comment by mrjoelkemp** [comment]
You can do:

```js
requestSent = _.map(requests, req => ({
    requestBody: $.parseJSON(req.requestBody),
    requestHeaders: req.requestHeaders,
    method: req.requestMethod,
    url: req.requestURL
  })
);
```

https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=requestSent%20%3D%20_.map(requests%2C%20req%20%3D%3E%20(%7B%0A%20%20%20%20requestBody%3A%20%24.parseJSON(req.requestBody)%2C%0A%20%20%20%20requestHeaders%3A%20req.requestHeaders%2C%0A%20%20%20%20method%3A%20req.requestMethod%2C%0A%20%20%20%20url%3A%20req.requestURL%0A%20%20%7D)%0A)%3B

**Comment by SimenB** [comment]
Ah! Thanks :smile:
