### ISSUE TITLE
disallowSpaceBeforeSemicolon is incompatible with requiring spaces inside for()

### ISSUE THREAD

**Issue by Reinmar** [jscs-dev/node-jscs#1640]
```
  1730 |    nodeData = nodesData[ nodeIndex ];
  1731 |
Illegal space before semicolon at core/editable.js :
  1927 |   var insideOfList = path.contains( DTD.$list );
  1928 |
  1929 |   for ( ; nodeIndex < nodesCount; ++nodeIndex ) {
----------------^
```

I use:

```
"disallowSpaceBeforeSemicolon": true
"requireSpacesInsideParentheses": "all",
```

Full config – https://github.com/ckeditor/ckeditor-dev/blob/master/dev/tasks/jscs-config.json (without `disallowSpaceBeforeSemicolon`).

**Comment by ShashankaNataraj** [comment]
The original PR is here: https://github.com/jscs-dev/node-jscs/pull/1457

**Comment by markelog** [comment]
This is also needed for the jquery preset, i guess, technically, this is not a bug, since rule does exactly what it supposed to do.

We need to add `allExcept` option for it.

**Comment by markelog** [comment]
@Reinmar would you like to try to implement such option?
