### ISSUE TITLE
Add "Issue Closer Bot"

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1641]
https://github.com/twbs/no-carrier

Bootstrap's bot: https://github.com/twbs-closer

> NO CARRIER is a tool to auto-close old GitHub issues that were abandoned by their reporter, which is to say that we were waiting for a response from the reporter but never got a response in a reasonable amount of time.

Example:

![screen shot 2015-08-07 at 12 04 12 pm](https://cloud.githubusercontent.com/assets/588473/9140079/76090ed4-3cfc-11e5-83ab-554171c9cb79.png)

**Comment by hzoo** [comment]
What's the simplest way to set this up (I'm not familiar with any of this stuff)? Something like heroku? @cvrebert

**Comment by cvrebert** [comment]
You just need something that supports Java 8 and lets you run a daily cronjob (or equivalent). (No Carrier isn't a daemon.) I'm not familiar enough with Heroku to say whether it'd be suitable.
We happen to run Bootstrap's No Carrier instance on the cheapest DigitalOcean VM (and we have other stuff also running on that same VM).

**Comment by zxqfox** [comment]
Would be nice to start it on Heroku, it support java 8, but it's not so easy to make daily cron runs there, even with https://addons.heroku.com/temporize

Feels like it needs some help to make it work. I'm not familiar with Scala ;-( Guess it's much easier to run on some VM.

**Comment by hzoo** [comment]
Looks like there's this on heroku https://devcenter.heroku.com/articles/scheduler - if there is a way to run the jar on heroku through a that/cron..

**Comment by zxqfox** [comment]
I've did a try and got this error:
```
2015-08-08 17:29:10,653 [ERROR] com.jcabi.aspects.aj.MethodValidator - JSR-303 validator failed to initialize: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath. (see http://aspects.jcabi.com/jsr-303.html)
```

What I did:
- made a heroku app with stub java app (it let's me to use java 8)
- added github user credentials to env
- downloaded and pushed no-carrier.jar to the heroku git repo
- made a simple script to run `java -jar no-carrier.jar jscs-dev/node-jscs "awaiting reply" 14` under the `./cron.daily.sh`
- ran `heroku run ./cron.daily.sh`

**Comment by cvrebert** [comment]
@zxqfox That error is non-fatal and can be safely ignored.

**Comment by zxqfox** [comment]
Great! It means that it works with free Heroku app ;-) Should I write a recipe?

**Comment by cvrebert** [comment]
If you add it to [the wiki](https://github.com/twbs/no-carrier/wiki), I'd be happy to add a link in the README :-)

**Comment by zxqfox** [comment]
@cvrebert https://github.com/twbs/no-carrier/wiki Hope I didn't failed there ;-)

**Comment by cvrebert** [comment]
Looks good :-) I tweaked the phrasing a little and [added the README link.](https://github.com/twbs/no-carrier/commit/91e41293ac57ebdb69c0e7e31fdb5ed205827c12)

I'd also love to add JSCS to the [list of users](https://github.com/twbs/no-carrier#used-by), if y'all would be okay with that.

Hope y'all enjoy your new tooling :smile:

**Comment by hzoo** [comment]
Don't know how far we got to doing this but I guess we aren't getting that many issues (nothing compared to bootstrap) so we can revisit this later
