### ISSUE TITLE
requireArrowFunctions top most callback

### ISSUE THREAD

**Issue by SimenB** [jscs-dev/node-jscs#1646]
Hi again!

I'm currently going through our Jasmine specs converting the callbacks to arrow functions. But the first `describe`'s callback has to be in the old style because jasmine binds the context.

I'm thinking it's a general problem though, babel always makes `this` undefined if outer callback uses arrows
https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=false&code=describe('context'%2C%20()%20%3D%3E%20%7B%0A%20%20it('should%20be%20defined'%2C%20()%20%3D%3E%20%7B%0A%20%20%20%20console.log(this)%0A%20%20%7D)%3B%0A%7D)%3B%0A%0Adescribe('context'%2C%20function%20()%20%7B%0A%20%20it('should%20be%20defined'%2C%20()%20%3D%3E%20%7B%0A%20%20%20%20console.log(this)%0A%20%20%7D)%3B%0A%7D)%3B%0A

For now it's `// jscs:ignore` on the top one.

**Comment by SimenB** [comment]
@hzoo I also get a false positive if the only arg is a rest param. Shall I report another bug?

https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=false&code=export%20default%20(...stuff)%20%3D%3E%20%7B%0A%20%20if%20(stuff.length%20%3C%202)%20return%20null%3B%0A%0A%20%20verdier.splice(-1%2C%201)%3B%0A%0A%20%20return%20verdier.reduce((streng%2C%20memo)%20%3D%3E%20%60%24%7Bmemo%7D%20%24%7BescapeExpression(streng)%7D%60%2C%20'')%3B%0A%7D%3B

**Comment by zxqfox** [comment]
allExcept: topmost?

**Comment by hzoo** [comment]
or should this error by default?

**Comment by zxqfox** [comment]
Yeah, depends on "top most" case.

Personally I don't use Jasmine and don't need `() => {` for root "describe".

**Comment by SimenB** [comment]
Eslint also has a `prefer-arrow-callback`-rule, which sees that `this`is used within, so it does not warn. Maybe take a look at their implementation?.

We should just migrate to using a `let` at the scope over, avoiding magical `this`...

**Comment by fluky** [comment]
I agree with @SimenB on this one.  I have a case where the callback is called with call or apply by the 3rd party library and this is referenced in the function.  Having to use ignore for now but the suggestion above would handle that case much and an all except "topmost" would not.

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
