### ISSUE TITLE
Unexpected reserved word - unusable with ES6 Module syntax

### ISSUE THREAD

**Issue by knownasilya** [jscs-dev/node-jscs#165]
Have the following code

``` javascript
export default DS.FixtureAdapter.extend();
```

and get the the following error, `Unexpected reserved word`, and I don't have `disallowKeywords` specified in my config. Maybe we could add a `allowKeywords` option?

**Comment by andywillis** [comment]
@mikesherov, can you confirm that disabling the rules for `import`, `export` etc doesn't have any effect?

I've tried:
```javascript
// jscs:disable
import merge from '../modules/utilities/merge';
// jscs:enable
```
but that doesn't seem to prevent the error from occurring.

**Comment by mikesherov** [comment]
@andywillis are you testing against master and using es6 mode?

**Comment by tnguyen14** [comment]
The Esprima issue is fixed. Is this issue also resolved? I am running into this error today while using the `import` syntax in ES6.

**Comment by hzoo** [comment]
You should be able to use the `exnext` option or use a different `esprima` parser (either with `--esnext` or `--esprima='esprima-fb' in cli or in your `.jscsrc`

```js
{
  "esnext": true // uses jscs-dev/esprima-harmony
  "esprima": "./node_modules/esprima" // need to npm install esprima or esprima-fb, etc
}

**Comment by tnguyen14** [comment]
I wasn't aware of the `esnext` option/ flag. Sorry, just saw that now. Thanks!
