### ISSUE TITLE
Write a mini guide in the contributing section for addition of new rules

### ISSUE THREAD

**Issue by ShashankaNataraj** [jscs-dev/node-jscs#1651]
Hi, having contributed my first PR to this probject 14 days back, I want to write a mini guide on creating new rules with JSCS. This would help newbies like me and would serve as a first entry point for new contributors. What do you guys think?

@markelog @hzoo

**Comment by markelog** [comment]
We have [this](http://jscs.info/contributing.html#implementing-features) comprehensive "Contribution Guide", but "new rule" guide would be very interesting to see.

You could start by creating wiki page - https://github.com/jscs-dev/node-jscs/wiki/_new and we will figure out the rest.

**Comment by hzoo** [comment]
It's in `MAINTAIN.md` which I don't think is linked anywhere or read https://github.com/jscs-dev/node-jscs/blob/master/MAINTAIN.md#maintaining-validation-rules - But would be nice to rewrite that or do it step by step if it makes it easier/clearer.

**Comment by ShashankaNataraj** [comment]
@markelog I already went through the contribution guide you quoted. It isnt very explicit. I had to figure a couple of things and go through some files myself and had to do some guess work as the maintain.md file @hzoo quoted isnt linked from any other guide on JSCS guide. Its a little difficult to get to. It wasnt difficult to come up with my first rule for JSCS, but certainly involved a lot of guesswork.

Im looking at making a wiki page on https://github.com/jscs-dev/node-jscs/wiki/_new and then taking it from there.

**Comment by hzoo** [comment]
@ShashankaNataraj if you still want to make the wiki page that would be cool - or we could link the maintain/contributing docs better in places.

**Comment by ShashankaNataraj** [comment]
linking better works too. will see if I can put in some time when I get back from travel.

**Comment by hzoo** [comment]
Ok I finished up a few things in https://github.com/jscs-dev/node-jscs/wiki/Creating-a-New-Rule - so we can close for now and continue adding to it.
