### ISSUE TITLE
Checkstyle reporter gives invalid XML when there are too many errors

### ISSUE THREAD

**Issue by thenovices** [jscs-dev/node-jscs#1654]
If you use `--reporter=checkstyle` and you exceed the maximum number of errors, then you get an extra string printed at the end, saying "Too many errors..." (see: https://github.com/jscs-dev/node-jscs/blob/852204310a7a8e3f0a7021c4cee30909c5411376/lib/cli.js#L163)

Checkstyle is supposed to output XML, but this extra string throws off the XML parser.

e.g.:
```
$ jscs --reporter=checkstyle code.js
<?xml version="1.0" encoding="utf-8"?>
<checkstyle version="4.3">
    <file name="code.js">
        <error line="1" column="13" severity="error" message="Invalid quote mark found" source="jscs" />
        ... more errors
    </file>
</checkstyle>
Too many errors... Increase `maxErrors` configuration option value to see more.
```

**Comment by hzoo** [comment]
> If you use the json reporter and you get more errors then the limit then this code https://github.com/jscs-dev/node-jscs/blob/master/lib/cli.js#L164 will make your JSON unparsable.

The outputting of this error message should be either moved to the reporter code so that each reporter could display it in its own format or we should have a setting/cli argument to disable it.

@danechitoaie

**Comment by hzoo** [comment]
Looks like this needs to be change all any of the errors in cli.js actually

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
