### ISSUE TITLE
Ignore templating delimiters

### ISSUE THREAD

**Issue by thenovices** [jscs-dev/node-jscs#1655]
I would like to run JSCS on .js.erb files, but they are getting hung up on the ERB delimiters (`<%` and `%>`). jshint now has an option to include delimiters that can be ignored. Is there any way to do this in JSCS right now? Googling didn't turn up anything.

**Comment by mrjoelkemp** [comment]
Hey @thenovices! Thanks for contributing.

We don't currently have a way to allow users to configure delimiters to skip. In https://github.com/jscs-dev/node-jscs/issues/1434, we spoke about giving the user the power to transform source code pre-linting (where you'd be able to remove all of your erb delimiters).

How does JSHint strip the delimiters?

**Comment by thenovices** [comment]
Here is the PR where they added the feature: https://github.com/jshint/jshint/pull/1841/files

**Comment by mrjoelkemp** [comment]
Very interesting. Thanks for linking the PR. #1434 gives the user (perhaps too much) power to make their own source transformations (which could include stripping erb tags or anything else). However, the JSHint solution is effective and avoids the redundancy of users regex replacing source files in the case of wanting to strip delimiters.

I'm definitely in favor of supporting a similar feature. @markelog thoughts?

**Comment by markelog** [comment]
Yeah, we can do this at "pre-parsing" phase, essentially same issues as in https://github.com/jscs-dev/node-jscs/issues/1156

**Comment by hzoo** [comment]
I can we can close either this or #1156 since it's the same. @markelog
