### ISSUE TITLE
Cannot disable `disallow-spaces-in-function-expression`

### ISSUE THREAD

**Issue by DanielHeath** [jscs-dev/node-jscs#1656]
In `lib/rules/disallow-spaces-in-function-expression.js`, it's not possible to override the default setting (to work around async/await) by setting null.

**Comment by hzoo** [comment]
Hmm weird, you should always be able to disable any rule (if it's already in a preset) - otherwise just remove the rule from your config. Can you post what you're doing with the config?

http://jscs.info/overview.html#preset

**Comment by DanielHeath** [comment]
Airbnb style enables the rule, I'm trying to disable it (so I can't just leave it out).

When I assign it `null`, I get `disallowSpacesInFunctionExpression option must be the object`.
If I assign it `{}`, I get `disallowSpacesInFunctionExpression must have beforeOpeningCurlyBrace or beforeOpeningRoundBrace property`.

**Comment by markelog** [comment]
Could you post your config?

**Comment by hzoo** [comment]
Yeah posting what you tried would help - `"disallowSpacesInFunctionExpression": null` should work.

**Comment by hzoo** [comment]
Going to close, can't reproduce with

```js
// .jscsrc
{
  "preset": "airbnb",
  "disallowSpacesInFunctionExpression": null
}
```

Let us know if you still have an issue!
