### ISSUE TITLE
Explicitly including certain files, excluding all others

### ISSUE THREAD

**Issue by melbourne2991** [jscs-dev/node-jscs#1657]
We have a lot of code that has not yet been subject to any style guide. Because of this virtually our entire codebase contains errors (over 5k). We want to apply the style guide only to new files, I noticed the config does have an "excludeFiles" array, but no mechanism for excluding all and just including a specified list of files/folders

I tried globbing

excludeFiles:
!**/folder/**/myfoldertoinclude

This didn't seem to work. Is there any work around for this?

Thanks

**Comment by mrjoelkemp** [comment]
Thanks for reporting. You can use the errorFilter feature to decide which
files should report errors.

Let me know if you need any help getting started with that feature.
