### ISSUE TITLE
Rework: Update documentation of disallowKeywordsOnNewLine, requirePaddingNewlinesBeforeKeywords, requirePaddingNewlinesInBlocks, requireVarDeclFirst 

### ISSUE THREAD

**Issue by oredi** [jscs-dev/node-jscs#1658]
The documentation for the rules stated is following the old format for the configuration section. I am wondering if we should update them to follow https://github.com/jscs-dev/node-jscs/commit/c536b21ca16b74e44081f4c7d89a38e08439e23c#diff-98bfebb24c1ec81d05c332bf6483e9beR6 . I will take the tasks if it is agreeable.

**Comment by markelog** [comment]
That would be cool, docs require some love
