### ISSUE TITLE
ES6: Replace bind(this) with arrow function

### ISSUE THREAD

**Issue by SimenB** [jscs-dev/node-jscs#1659]
Cross-post eslint. Tried searching for it here as well.
I'd like to get a linting warning on all usages of `function () {}.bind(this);`, as it could be replaces by `() => {}`. This is stylistic.

Warning: 
```js
$.ajax(/**/, {
  error: function (model, res) {
    this.someFuntion();
  }.bind(this)
})
```

OK: 
```js
$.ajax(/**/, {
  error: (model, res) => {
    this.someFuntion();
  }
})
```

Also OK:
```js
$.ajax(/**/, {
  error: this.someFuntion.bind(this)
})
```

**Comment by mrjoelkemp** [comment]
requireArrowFunctions should work

**Comment by mrjoelkemp** [comment]
Let me know if it doesn't and I'll reopen

**Comment by SimenB** [comment]
Doesn't work. It doesn't trigger on properties in objects

**Comment by SimenB** [comment]
```js
    _.each(lenker, function (lenke) {
      this.meep(lenke)
    }.bind(this));
```

Doesn't trigger error. If I remove `bind` it triggers.

**Comment by mrjoelkemp** [comment]
Cc @hzoo

**Comment by hzoo** [comment]
Yeah it checks `node.parentNode.type === 'CallExpression'` only and that is a `MemberExpression`
