### ISSUE TITLE
Add "allExcept" option to `disallowSpaceBeforeSemicolon` rule

### ISSUE THREAD

**Issue by markelog** [jscs-dev/node-jscs#1665]
Like `allExcept: ["("]`, so this:
```js
for ( ; i < length; i++ )
```

Would be acceptable, needed for jquery preset.

**Comment by hzoo** [comment]
This is the same as https://github.com/jscs-dev/node-jscs/issues/1640 right

**Comment by markelog** [comment]
Wow

**Comment by hzoo** [comment]
But you can update the labels/title!
