### ISSUE TITLE
Please add @todo jsDoc to checkTypes

### ISSUE THREAD

**Issue by piotr-cz** [jscs-dev/node-jscs#1666]
`warning: jsDoc unavailable tag todo`

See usejsdoc: [@todo](http://usejsdoc.org/tags-todo.html).

**Comment by alawatthe** [comment]
Thanks for the report @piotr-cz!
Can you please post the exact code which is creating the error and your configuration?

In my quick tests everything worked and according to https://github.com/jscs-dev/jscs-jsdoc/blob/master/lib/tags/jsdoc3.json#L70 the ```@todo``` token should exist.

**Comment by piotr-cz** [comment]
Sorry for false alarm.
I'm using the _google_ preset and looks like this is the desired behavior for `checkannotations: closurecomiler` option.

**Comment by zxqfox** [comment]
I think this is a problem that should be solved. I thought about using multiple tag sets.

@markelog What you think about it? Should we add jsdoc3 tag set to google preset?

Ref: jscs-dev/jscs-jsdoc#69

**Comment by piotr-cz** [comment]
I'd love such solution - but I'm not sure if this is not overcomplicating things.
