### ISSUE TITLE
requirePaddingNewlinesInBlocks: Rename internal variable minStatements and _minStatements

### ISSUE THREAD

**Issue by oredi** [jscs-dev/node-jscs#1668]
With reference to the conversation in #1620 where we renamed the internal variable minStatements and _minStatements to minLines and _minLines for requireBlocksOnNewline to better reflect the purpose of the variables. I am thinking of doing the same to requirePaddingNewlinesInBlocks. This will make the variable fit the explanation of the updated document in #1667 as well

**Comment by markelog** [comment]
For sure
