### ISSUE TITLE
ES7 scope resolution

### ISSUE THREAD

**Issue by brenolf** [jscs-dev/node-jscs#1670]
I'm trying to use ES7 scope resolution feature and JSCS warns me with "unexpected token". I have tried to disable through comment but it doesn't work either.

```
Message:
    Unexpected token : at game.js :
    10 |    // jscs:disable
    11 |    /* jshint ignore:start */
    12 |    this.game::Score.preload();
----------------------^
    13 |    this.game::Player.preload();
    14 |    this.game::UI.preload();
```

I tried setting esprima's path in `.jscsrc` but it didn't work too.

**Comment by hzoo** [comment]
Are you using `esnext`?

**Comment by brenolf** [comment]
Yes, I'm using it in both `gulp-jscs` call and it is also set in my `.jscsrc`

**Comment by hzoo** [comment]
what version are you using, 2.0?

**Comment by brenolf** [comment]
Yes, `gulp-jscs` is 2.0.0 and `esprima` is 2.5.0.

**Comment by hzoo** [comment]
If you are using the `esnext` option then you need to remove the `esprima` option since esprima doesn't support `::` - `esnext` uses `babel` which does.

**Comment by brenolf** [comment]
The gulp task is:

```js
gulp.task ('code-check', function () {
  return gulp
  .src('./src/js/**/*')
  .pipe(jshint())
  .pipe(jshint.reporter('jshint-stylish'))
  .pipe(jscs({esnext: true}));
});
```

Where `jscs` is a `require('gulp-jscs')`. And I have put an entry in `.jscsrc`: `"esnext": true,`

**Comment by hzoo** [comment]
As an aside: I think the jscs disable comment only disables rules - if the parser dosn't support it it won't run.

Are you sure the error isn't from jshint then (although I guess that's what the comment is for?)

I can't reproduce with jscs itself and `esnext` in config

**Comment by brenolf** [comment]
I didn't know about that, thanks!

And yes, these errors are being generated by gulp-jscs. Are you trying using jscs CLI or the plugin?

**Comment by hzoo** [comment]
I'm using jscs cli - can you try it with that? Although I don't see why it would be an issue only with the plugin. 

What about

```js
gulp.task ('code-check', function () {
  return gulp
  .src('./src/js/**/*')
  //.pipe(jshint())
  //.pipe(jshint.reporter('jshint-stylish'))
  .pipe(jscs({esnext: true}));
});
```

what happens when it's jscs by itself or jshint by itself?

**Comment by brenolf** [comment]
Both are still throwing the error:
```
> jscs game/src/js/**/*.js; exit 1;

Unexpected token : at game/src/js/ui/button.js :
    53 |
    54 |    /* jshint ignore:start */
    55 |    this.sprite.events.onInputDown.add(context::this.callback);
-------------------------------------------------------^
    56 |    /* jshint ignore:end */
    57 |  }
```

**Comment by hzoo** [comment]
and `jscs -V` is `2.0.0`? maybe your global jscs is different? It definitely shouldn't be erroring with 2.0.0 and `--esnext`

**Comment by brenolf** [comment]
I'm using gulp-jscs 2.0.0, doesn't it already get the latest version of jscs as dependency?

**Comment by brenolf** [comment]
I've reinstalled

```
gulp-jscs@2.0.0 node_modules/gulp-jscs
├── object-assign@3.0.0
├── tildify@1.1.0 (os-homedir@1.0.1)
├── through2@2.0.0 (xtend@4.0.0, readable-stream@2.0.2)
├── gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reevaluate@3.0.0, beeper@1.1.0, lodash._reinterpolate@3.0.0, lodash._reescape@3.0.0, replace-ext@0.0.1, minimist@1.1.3, chalk@1.1.0, lodash.template@3.6.2, vinyl@0.5.1, dateformat@1.0.11, multipipe@0.1.2)
└── jscs@2.1.0 (strip-json-comments@1.0.4, reserved-words@0.1.1, natural-compare@1.2.2, babel-jscs@2.0.3, pathval@0.1.1, estraverse@4.1.0, vow@0.4.10, exit@0.1.2, esprima@2.5.0, minimatch@2.0.10, commander@2.8.1, cli-table@0.3.1, chalk@1.1.0, glob@5.0.14, vow-fs@0.3.4, lodash.assign@3.2.0, prompt@0.2.14, to-double-quotes@1.0.1, to-single-quotes@1.0.3, xmlbuilder@2.6.4, jscs-jsdoc@1.1.0, babel-core@5.8.22)
```

And it seems to be fetching jscs 2.1.0...

**Comment by hzoo** [comment]
Yeah since that's the latest version which is fine. Ok I downloaded `gulp-jscs` to reproduce. I can reproduce it actually with `.pipe(jscs({esnext: true}));` because I had a `.jscsrc` file already - so I would just do `.pipe(jscs());` if you already have a config (or use the option to set the config path)

**Comment by brenolf** [comment]
i wasn't actually loading my own jscsrc file at all. Thanks for that!

**Comment by brenolf** [comment]
I wasn't actually loading my own jscsrc file at all. Thanks for that!
