### ISSUE TITLE
disallowAnonymousFunctions should support ES2015(ES6) Method Definitions

### ISSUE THREAD

**Issue by syoichi** [jscs-dev/node-jscs#1671]
![screenshot](https://cloud.githubusercontent.com/assets/69238/9243025/c70a2052-41c5-11e5-91de-ba1ca0d5576a.png)

It seems that `disallowAnonymousFunctions` handles "Method Definitions" as "anonymous functions", In JSCS 2.1.0.

**Comment by markelog** [comment]
See https://github.com/jscs-dev/node-jscs/issues/1513

Would you like to implement such value?

**Comment by markelog** [comment]
> t seems that disallowAnonymousFunctions handles "Method Definitions" as "anonymous functions"

That is because they technically are "anonymous functions", since this request for same value but for different rule then #1513, i will leave this open

**Comment by syoichi** [comment]
I think that `disallowAnonymousFunctions` shouldn't target "Method Definitions", in the same way as "Arrow Functions".

![screenshot1](https://cloud.githubusercontent.com/assets/69238/9266734/261edf1e-4280-11e5-8305-806d70ec8fdd.png)

Because "Method Definitions" isn't complete "named functions", but "Method Definitions" isn't "anonymous functions".

![screenshot1](https://cloud.githubusercontent.com/assets/69238/9266529/49aa3f6c-427d-11e5-97f7-98105322d297.png)
![screenshot2](https://cloud.githubusercontent.com/assets/69238/9266642/eaf33ef4-427e-11e5-9a2d-6c06a209e934.png)

Therefore, I think that it doesn't need to add new value for `disallowAnonymousFunctions`'s "Method Definitions" support.

**Comment by markelog** [comment]
This is method definition, as property of the class, it as a property that has a name and that name points to function, which is a function expression, without a name.

You can see that on mdn page - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions#Description, as a "shorten" version of 

```js
var obj = {
  foo: function() {},
  bar: function() {}
};
```

not of 
```js
var obj = {
  foo: function foo() {},
  bar: function bar() {}
};
```

You can also see this in the spec - http://www.ecma-international.org/ecma-262/6.0/#sec-method-definitions, which divides property name and function or more precisely in here - http://www.ecma-international.org/ecma-262/6.0/#sec-runtime-semantics-definemethod, this is why it doesn't do lexical identifier binding:
```js
var o = {
   foo() { console.log(foo) } // undefined
}; o.foo()
```

Nevertheless, what ever you want to call it, we still would need to fix it, if you want to help us out that is great, we already show you the way, otherwise this discussion has no meaning.

**Comment by syoichi** [comment]
Please see [my comment](https://github.com/jscs-dev/node-jscs/issues/1671#issuecomment-130946659)'s images.

And [ES6 spec](http://www.ecma-international.org/ecma-262/6.0/#sec-method-definitions-runtime-semantics-propertydefinitionevaluation) says...

``` md
MethodDefinition : PropertyName ( StrictFormalParameters ) { FunctionBody }

1. Let methodDef be DefineMethod of MethodDefinition with argument object.
2. ReturnIfAbrupt(methodDef).
3. Perform SetFunctionName(methodDef.[[closure]], methodDef.[[key]]).
4. Let desc be the Property Descriptor{[[Value]]: methodDef.[[closure]], [[Writable]]: true, [[Enumerable]]: enumerable, [[Configurable]]: true}.
5. Return DefinePropertyOrThrow(object, methodDef.[[key]], desc).
```

`SetFunctionName` is used in `MethodDefinition`.

You can confirm this in Chrome 46 and Firefox 43.

``` js
(function executeTest() {
  'use strict';

  let obj = {
    foo() {
      return typeof foo;
    },
    bar: function () {
      return typeof bar;
    }
  };

  console.log(obj.foo.name); // 'foo'
  console.log(obj.bar.name); // ''
}());
```

From the above, I think that "anonymous functions" doesn't contain "Method Definitions".

**Comment by markelog** [comment]
> Please see my comment's images.

Awesome images, very enjoyed them! Dutch is tilt though.

`SetFunctionName` gives `name` property to a function, but it is still, for all intents and purposes, anonymous. If it wasn't, you could do recursion, you could do event binding, etc, but you can't.

Now see the
> 4. Let scope be the running execution context’s LexicalEnvironment.

Some say that this makes spec inconsistent, that it is has `name` but it don't have lexical binding. Some say that it is a bug, but as AST shows that it is anonymous, we show you that is anonymous.

And once again, if you don't think i'm right, that is fine, we still need to fix it.

**Comment by syoichi** [comment]
>AST shows that it is anonymous

Oh... In that case, it can't be helped.
I'm sorry to take up your time.

**Comment by hzoo** [comment]
Going to close this for now then? let me know if it should be reopened
