### ISSUE TITLE
[feature request] expose `cli-config.load` for programmatic usage

### ISSUE THREAD

**Issue by AnimiVulpis** [jscs-dev/node-jscs#1673]
If a project uses `node-jscs` they have to find and read potential configuration files on their own, which can lead to differences between CLI execution of `jscs` and the tool.

It would be nice to expose the functionality for easier tool development.

Currently it is possible to use it by directly importing it like this:
```javascript
import configFile from './node_modules/jscs/lib/cli-config';
```
This seems a little unclean to me (maybe only me)

Is this feature something that would be considered worthy, or would you consider it to expose to much?

**Comment by markelog** [comment]
`cli-config` already used in couple projects, how would you suggest to make it "clean"?

btw, this
```js
import configFile from './node_modules/jscs/lib/cli-config'
```

Could be simplified to this
```js
import configFile from 'jscs/lib/cli-config'
```

**Comment by markelog** [comment]
Friendly ping

**Comment by zxqfox** [comment]
Perhaps I know what's the problem.

What if:
```js
import * as configFile from './node_modules/jscs/lib/cli-config';
```
?

**Comment by AnimiVulpis** [comment]
I think it would be nice if it was possible to do something like this if using `jscs` programmatic:
```javascript
checker.configure(checker.load('somepath'));
```

This could make sure, that usage from the command line and from code always load the **same** config in the **same** order and manner.

Furthermore programmatic changes to the existing config would be based on the config which would be loaded by `jscs`.
```javascript
var config = checker.load('somepath');
config.dontWantThisOption = false;
checker.configure(config);
```

But maybe I overestimate the usefulness of this feature.

**Comment by hzoo** [comment]
Do we still want this?

**Comment by AnimiVulpis** [comment]
I am good with the already proposed solutions :ok_hand:
and as I am the only one who seemed to want this I will close this issue.
Thanks for asking though :+1:

**Comment by markelog** [comment]
You are not the only one :-). Not sure who we can do it better though
