### ISSUE TITLE
Disallow certain native JS methods?

### ISSUE THREAD

**Issue by serendipitic** [jscs-dev/node-jscs#1674]
Is there a way to prevent usage of certain native JS methods (e.g. eval() or encodeURIComponent())?

I tried disallowKeywords, however as the name already suggests, that only works with actual keywords of the JS language. Is there a config option I overlooked?

**Comment by hzoo** [comment]
We have a few of these types of rules - `disallowKeywords`, `disallowNodeTypes`,`disallowIdentifiers` - http://jscs.info/rule/disallowIdentifierNames.html. That rule could use some more options though

**Comment by markelog** [comment]
Yeah, so `disallowIdentifiers` should work for your case, ping us up if you want more
