### ISSUE TITLE
Docs: Update documentation of safeContextKeyword, validateNewlineAfterArrayElements, validateLineBreaks, validateAlignedFunctionParameters

### ISSUE THREAD

**Issue by oredi** [jscs-dev/node-jscs#1677]
The rules are using the old format for the Type and value sections with little details on how to use the options to configure the rule. I am proposing to update the documentation to follow the new format used in #1667

**Comment by oredi** [comment]
Replaced validateQuoteMarks with safeContextKeyword as validateQuoteMarks  is already using the new format.

**Comment by markelog** [comment]
Kudos
