### ISSUE TITLE
How can you disable maxErrors?

### ISSUE THREAD

**Issue by danechitoaie** [jscs-dev/node-jscs#1678]
Looking through the code if the value is null then this check should be disabled.

Is this correct?

How do you pass the null value from command line?

**Comment by hzoo** [comment]
You can pass it in the `.jscsrc` config file - also not sure you can pass null but you can pass `Infinity` (searching in the codebase)

```js
{
  "maxErrors": Infinity
}

**Comment by zxqfox** [comment]
Is Infinity supported by JSON?

**Comment by markelog** [comment]
> Is Infinity supported by JSON?

totally

@danechitoaie, not sure of what you asking, if the question is `How can you disable maxErrors?` you can also provide a cli argument too

**Comment by gibson042** [comment]
Um, what? `Infinity` is most certainly _not_ [valid JSON](https://tools.ietf.org/html/rfc7159#section-6): 
> Numeric values that cannot be represented in the grammar below (such as Infinity and NaN) are not permitted.

**Comment by markelog** [comment]
> Um, what? Infinity is most certainly not valid JSON:

okay, okay, you don't need to act so suprised, like this is a common knowledge :-).   
```js
{
  "maxErrors": null
}
```

should be used instead

**Comment by danechitoaie** [comment]
@markelog So I had two questions:

1. How do you disable maxErrors in general? (I got an answer to this above. Looks like you need to set null in .jscsrc)
2. How do you disable maxErrors when using the cli? (it's still not clear here to me how to do this. What do I pass as argument in the cli? `null` doesn't work there as it's interpreted as string.

**Comment by markelog** [comment]
> How do you disable maxErrors when using the cli? (it's still not clear here to me how to do this. What do I pass as argument in the cli? null doesn't work there as it's interpreted as string.

jscs --max-errors Infinity <path>.

Okay, reopening, since we have two types of issues here:
1. Need to document disabling maxErrors option through config and cli
2. Need to improve error output, since now we have this -
```bash
$ jscs --max-errors null lib/cli.js
`maxErrors` option requires positive number or null value`
```

**Comment by markelog** [comment]
btw, @danechitoaie would you like to help us out, and try to tackle one of these issues?

**Comment by danechitoaie** [comment]
Yes, sure. How can I help?

**Comment by markelog** [comment]
There is two issues, first one is easy - docs update, you [these](https://github.com/jscs-dev/node-jscs/blob/c9a239d54221d61b16d86bdeef91c37e5bf4e848/OVERVIEW.md) docs, basing on this discussion, or/and you can sink to the jscs repo and try to change logic of the cli `max-errors` flag, like `jscs --max-errors null <path>` either to allow null value or change error output.

**Comment by danechitoaie** [comment]
Done. Can you take a look at this https://github.com/jscs-dev/node-jscs/pull/1682 ?

**Comment by hzoo** [comment]
This was fixed right? https://github.com/jscs-dev/node-jscs/commit/57bc29ecf57fe2d4005b0a9aaf354cec5874d435
