### ISSUE TITLE
The "Too many errors... Increase `maxErrors` configuration option value to see more." makes json reporter unparsable.

### ISSUE THREAD

**Issue by danechitoaie** [jscs-dev/node-jscs#1679]
If you use the json reporter and you get more errors then the limit then this code https://github.com/jscs-dev/node-jscs/blob/master/lib/cli.js#L164 will make your JSON unparsable.

The outputting of this error message should be either moved to the reporter code so that each reporter could display it in its own format or we should have a setting/cli argument to disable it.

**Comment by hzoo** [comment]
This is probably the same as #1654 except for json reporter but would probably be fixed in the same way?

**Comment by danechitoaie** [comment]
Yes. Looks that way. This definitely affects all reporters that output in a specific format.

**Comment by hzoo** [comment]
Going to close in favor of that then
