### ISSUE TITLE
validateIndentation - array of exceptions is confusing

### ISSUE THREAD

**Issue by monk-time** [jscs-dev/node-jscs#1684]
Changes to **validateIndentation** introduced in 1a4a46256f3f319869fe781090b48a7ad59e1780, specifically deprecation of `includeEmptyLines` in favor of `allExcept: ['emptyLines']` make it quite hard to understand the module's default behavior and `allExcept`'s purpose. It doesn't help that descriptions for tests for the new option are wrong, and the second test shouldn't include `includeEmptyLines: false` in its configuration.

Furthermore, the new option doesn't mirror the behavior of `allExcept: ['comments']`, but the way they both are defined in the same array called `allExcept` makes one think that they would behave similarly - by default the module would check all lines excluding those specified in that array. But that's not the case.

 | allExcept: ['comments'] | allExcept: ['emptyLines']
--- | --- | ---
if omitted | validate comments | ignore empty lines
if specified | ignore comments | validate empty lines

So, the proposed solution imo would be to either change the default behavior of **validateIndentation** to produce new errors on empty lines, rename `allExcept` ('invert'? 'special'?) or restore `includeEmptyLines`, and the last one would make an array of exceptions redundant.

**Comment by markelog** [comment]
Yeah, pretty confusing.

> rename allExcept ('invert'? 'special'?) or restore includeEmptyLines

How about we would add option `include` that would accept array, just like `allExcept`?

**Comment by monk-time** [comment]
It would make the case with empty lines more intuitive, but not for comments: `"include": ["comments"]`- they are already included by default, what would this option do? 

Basically, I see no reasonable way to keep these two exceptions in a single array, since they contradict each other. That is, short of changing the default behavior for validating either comments or empty lines.

**Comment by markelog** [comment]
> ["comments"]- they are already included by default

Yep, we included by default and document it, if options are contradicts with each other, we would need to throw.

**Comment by markelog** [comment]
Sounds good?

**Comment by monk-time** [comment]
How would you then disable validation for comments?

What I mean is that current behavior is counterintuitive: no matter how you call that array of exceptions, `['comments']` disabled validation, `['emptyLines']` enables it, and `['comments', 'emptyLines']` does different things for different types of lines. I don't think these two exceptions should be in a single array (unless you call it `exceptions`).

What about adding two options, `includeEmptyLines` and `excludeComments`?

**Comment by markelog** [comment]
> What about adding two options

Like this - 
```js
validateIndentation: {
  allExcept: ['comments'],
  include: ['emptyLines']
}
```
and if
```js
validateIndentation: {
  allExcept: ['comments'],
  include: ['comments']
}
```
then throw

**Comment by monk-time** [comment]
Oh I get it now. Sounds good! :thumbsup:

**Comment by markelog** [comment]
Would you like to implement it?

**Comment by monk-time** [comment]
I'd rather not, sorry. Maybe some time later, if it's not fixed by then.

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
