### ISSUE TITLE
add common exceptions to requireCapitalizedComments by default

### ISSUE THREAD

**Issue by markelog** [jscs-dev/node-jscs#1685]
Like for jshint, jscs, etc

**Comment by alawatthe** [comment]
Hmm, why do we want to do this? Writing
```js
"requireCapitalizedComments": { "allExcept": ["jshint"] }
```
does not seem to be to complicated...

How would one then disable these default values?

Furthermore, eshint sometimes uses the keyword ```global``` to start comments (see [Specifying Globals](http://eslint.org/docs/user-guide/configuring#specifying-globals)). So should ```global``` then also be a default exception to requireCapitalizedComments? I can easily see comments starting with ```global``` which are not eslint comments and therefore should be capitalized.

**Comment by markelog** [comment]
> Hmm, why do we want to do this?

To make rule more friendly, since such comments, are not exactly comments but controlling instructions, similar to the `"use strict"` literal

> How would one then disable these default values?

"requireCapitalizedComments": { "allExcept": [] }

> I can easily see comments starting with global which are not eslint comments and therefore should be capitalized.

Yeah, so there is two ways of dealing with this, argue that amount of false positive would be greatly lower then legitimated cases or even further, you could implement heuristic for each case, which would make false negatives to nil.

Or don't include it in the default list.

**Comment by alawatthe** [comment]
For the record, I am not against these default values, I am just playing the devil's advocate here :-)

>> How would one then disable these default values?

>"requireCapitalizedComments": { "allExcept": [] }

This means, that setting the ```"allExcept"``` option overrides the default values, right? So the default values are only there for the
```js
"requireCapitalizedComments": true
```
case. This feels a little inconsistent :-/

**Comment by markelog** [comment]
> This means, that setting the "allExcept" option overrides the default values, right?

Well, yeah, that is why they are "default".

> This feels a little inconsistent :-/

With what?

**Comment by alawatthe** [comment]
> With what?

With setting the ```"allExcept"```option. Let me explain a little further:
Let's say I am using the ```"requireCapitalizedComments": true``` way and also use these default values. Next I want to add one further value, like so ```"requireCapitalizedComments": { "allExcept": ['foobar'] }``` and now the default values are gone. This means, I now get errors for using the default values, as I (implicitely) overwrote them.

I think our different opinions came from the fact that you saw the set of default values as one which can be overwritten and I saw it as a set, which can be extended by the user.

But ok, ok, you convinced me :-D
Shall I implement these changes?

**Comment by markelog** [comment]
> "requireCapitalizedComments": { "allExcept": ['foobar'] } and now the default values are gone

Yeah, this is a downside, but i guess there is no better way.

> Shall I implement these changes?

That would be cool :-)

**Comment by alawatthe** [comment]
I had a look at this. Right now the exceptions I identified are:

http://eslint.org/docs/user-guide/configuring
```js
/* eslint eqeqeq:0, curly: 2*/
/* eslint-env node, mocha */
/* global var1, var2*/
/* eslint-disable */
/* eslint-enable */
// eslint-disable-line
```

http://jshint.com/docs/#inline-configuration
```js
/* jshint strict: true */
/* exported EXPORTED_LIB */
/* falls through */
```

https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md
```js
/* istanbul ignore next */
```

Did I miss any keywords/libraries? (jscs support is already there.)

**Comment by markelog** [comment]
`globals` i guess, other then that, it looks good

**Comment by mrjoelkemp** [comment]
From a maintenance perspective, I'm against these additions. We can't
provide a total set that makes everyone happy and we'll get requests for
every pragma from every popular tool.

Furthermore, only extension makes sense with the defaults. As stated in
this thread, you either get the defaults only or the user supplied set,
never both. And wanting all but one (to avoid a false positive) involves
copying all other exceptions unless we also have a way to negate a single
default.

On top of this, we have shareable presets. Folks can write exceptions once
and use everywhere.

I don't see the benefits that warrant this special treatment and
maintenance.

**Comment by markelog** [comment]
> we'll get requests for every pragma from every popular tool

Don't see anything bad with it, if people would send as a request, it would mean they needed it.

> involves copying all other exceptions unless we also have a way to negate a single default

Yeah, that is surely a downside, although we could mention that set in the docs, so user would need to copy-paste it.

-- 

Right now, if user use some preset and istanbul for example, their would need to add that an exception, whereas a goal here, at least how i see it, is for users to know much less about configuration of specific config, and just set `"preset": "something"`, and do not require to know anything else, don't go to read docs or figure out how to add an exception.

And it is pretty much what already do with other rules, like http://jscs.info/rule/requireSpaceBeforeKeywords.html

Whereas, downside is although probable but speculative.

**Comment by mrjoelkemp** [comment]
Speculation based on the pattern of community requests, not misguided
speculation. Just wanted to throw my thoughts in.

:+1:

**Comment by markelog** [comment]
Still interested?

**Comment by alawatthe** [comment]
Yep, I hope, I can leave work earlier today to create a pr. Sorry for the delay :-/

**Comment by alawatthe** [comment]
I implemented this. Here are a few comments/problems:

1. I didn't include the ```/* falls through */```-comments from jshint, as I think "falls" is more common in normal comments than in  ```/* falls through */```-comments.
2. In the current implementation "jscs" is always allowed (independent of setting the rule to ```true```or setting the ```allExcept```-option). In the new implementation "jscs" is not allowed, when using the ```allExcept```-option.
3. Dumb question, but what does this have to do with #1729?

**Comment by markelog** [comment]
> In the current implementation "jscs"...

Since it is not a breaking change, we all good there

> Dumb question, but what does this have to do with #1729?

Could you spot the difference between https://github.com/jscs-dev/node-jscs/pull/1729/files#diff-50e3aa130a4f97a42ee2cf111c7b1d9dR208 and https://github.com/jscs-dev/node-jscs/pull/1731/files#diff-32c54cbe9c291803095ecdfe5f955728R99 ? :-)

Since two rules already can use that list, we should put it in `utils`

**Comment by alawatthe** [comment]
Hmm, yeah there is some similarity :smile:
I'll update the pr

**Comment by alawatthe** [comment]
For the record: I updated the pull request on my machine to work with the changes made in https://github.com/jscs-dev/node-jscs/pull/1729. Once #1729 is merged, I'll upload my code.

**Comment by markelog** [comment]
Okay, lets wait until your [suggestion](https://github.com/jscs-dev/node-jscs/pull/1729#issuecomment-136968886) is resolved
