### ISSUE TITLE
requireDollarBeforeJqueryAssignment: Only validates the first key

### ISSUE THREAD

**Issue by mrjoelkemp** [jscs-dev/node-jscs#1688]
Failing test:

```js
            it('should look at keys besides the first', function() {
                assert.equal(checker.checkString('var x = { bar: 1, foo: $(".foo") }').getErrorCount(), 1);
            });
```

Passing assertion:

```js
assert.equal(checker.checkString('var x = { foo: $(".foo") }').getErrorCount(), 1);
```

Problem line is here: https://github.com/jscs-dev/node-jscs/blob/7c2d0dd9d848cf0de4eeabb52a2514b480179956/lib/rules/require-dollar-before-jquery-assignment.js#L96

**Comment by hzoo** [comment]
same as https://github.com/jscs-dev/node-jscs/issues/1373 right?

**Comment by mrjoelkemp** [comment]
No, that's the assuming properties about the left-hand side that don't hold with destructuring. This ticket is an existing bug in the rule where it only checks the first property in an object on the right hand side.
