### ISSUE TITLE
disallowEmptyBlocks: Don't warn `Empty block found` for empty functions

### ISSUE THREAD

**Issue by lahmatiy** [jscs-dev/node-jscs#169]
Empty functions may be used in various cases, that's not a mistake.
Valid examples:

``` js
var noop = function(){};

function doSomeStuff(){
  // TODO: implement code in future
}
```

**Comment by ptarjan** [comment]
What ever happened to this? I'd like to to allow comments in if blocks

```
if (foo) {
  // Clearly foo is ok
} else {
  ...
}
```

**Comment by hzoo** [comment]
How about you make another issue since it's for blocks with only comments rather than functions

**Comment by ptarjan** [comment]
@hzoo https://github.com/jscs-dev/node-jscs/issues/1767
