### ISSUE TITLE
auto-configure only analyzes presets against 50 error

### ISSUE THREAD

**Issue by con-ssc** [jscs-dev/node-jscs#1695]
Hello,
I tried to run auto-configure against a single file to have it analyzed against the preset profiles. In the results it says only 50 errors but there are at least over 5k. Adding -m 100000 didn't do anything at all. Also adding maxerrors in a config file didn't help. It seems to be hard coded somewhere.

**Comment by con-ssc** [comment]
It seems that auto-configure uses the default value from the /lib/config/configuration.js and doesn't deviate from it. I can change the value there to get rid of the limit.

**Comment by mrjoelkemp** [comment]
Hey @con-ssc. Thanks for reporting. Which version of jscs are you using?

**Comment by con-ssc** [comment]
% jscs --version
2.1.0

**Comment by markelog** [comment]
Yeah, that is definitely an issue, we "fix" this for `-x` flag but not for `--auto-configure`

**Comment by hzoo** [comment]
So do we just have to change [this line](https://github.com/jscs-dev/node-jscs/blob/4a9bfa2b1ce84df5b141cbf4295e862798a7ff1e/lib/cli.js#L86)

```js
    if (program.fix || program.autoConfigure) {
        program.maxErrors = Infinity;
    }
```

**Comment by mrjoelkemp** [comment]
That could work

**Comment by seriema** [comment]
I'm using `2.6.0` and it doesn't pick up the max errors from CLI, so I had to set it in the `configure.json` as the OP did.

@hzoo maybe I'm reading the unit test wrong from your PR #1734 so I wrote some comments there. It seems to test maxError against `1` instead of `-1`?

**Comment by markelog** [comment]
Could you post the full command?

**Comment by markelog** [comment]
And config would be also helpful

**Comment by seriema** [comment]
Regular linting (I have a `.jscsrc`):
```
> jscs -m -1 ./
.........
4840 code style errors found.
```

Auto generate config:
```
> jscs -m -1 --auto-configure ./
Checking C:\....... against the presets
   Preset           #Errors #Rules
1  airbnb           50      8
2  crockford        50      9
3  google           50      7
4  grunt            50      8
5  idiomatic        50      9
6  jquery           50      5
7  mdcs             50      5
8  node-style-guide 50      8
9  wikimedia        50      7
10 wordpress        50      5
11 yandex           50      9
Please choose a preset number:
```

**Comment by markelog** [comment]
Thank you for noticing!
