### ISSUE TITLE
requireSpaceAfterBinaryOperators: ignores commas if set to true

### ISSUE THREAD

**Issue by monk-time** [jscs-dev/node-jscs#1698]
After 9fc861494156a44b20616b710a5e9ffc5b328749 it's become very unwieldy to detect missing spaces after binary operators AND after commas in arrays. [All style guides use `requireSpaceAfterBinaryOperators: true`](https://github.com/jscs-dev/node-jscs/search?utf8=✓&q=requireSpaceAfterBinaryOperators+path%3Apresets&type=Code) and disapprove of a cramped style with no space after comma, but that option surprisingly won't detect it.

Examples below:

Code: `var a = [1,2, 3 +4];`
***
Rule: `{ "requireSpaceAfterBinaryOperators": [","] }`
```
Operator , should not stick to following expression at test.js :
     1 |var a = [1,2, 3 +4];
-------------------^

1 code style error found.
```
***
Rule: `{ "requireSpaceAfterBinaryOperators": true }`
```
Operator + should not stick to following expression at test.js :
     1 |var a = [1,2, 3 +4];
-------------------------^

1 code style error found.
```
***
Rule: `{ "requireSpaceAfterBinaryOperators": [ 
     "=", "+=", "-=", "*=", "/=", "%=", "<<=", ">>=", ">>>=",
     "&=", "|=", "^=",
     "+", "-", "*", "/", "%", "<<", ">>", ">>>", "&",
     "|", "^", "&&", "||", "===", "==", ">=",
     "<=", "<", ">", "!=", "!==",
     ","
] }`
```
Operator , should not stick to following expression at test.js :
     1 |var a = [1,2, 3 +4];
-------------------^

Operator + should not stick to following expression at test.js :
     1 |var a = [1,2, 3 +4];
-------------------------^


2 code style errors found.
```
2 errors is the expected result for `true`, but jscs produces only 1 error instead. I'd say it counts as a bug.

**Comment by monk-time** [comment]
Is there anything wrong with this bug report? I've tried to explain as best I could, but maybe I have failed to formulate this issue clear enough. Anyone?

**Comment by hzoo** [comment]
I guess we decided at that time to remove `,` from that list of operators since it was confusing to people? If the presets aren't doing what you need you can do the workaround mentioned for now.

We could add `,` back in for this rule but we'll have to get everyone's opinion.

can add it in this line https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/require-space-after-binary-operators.js#L55

**Comment by monk-time** [comment]
Airbnb doesn't mention putting a space after `,` explicitly, but uses this convention throughout its guide consistently:
> 5.2 Use array destructuring.

> `const arr = [1, 2, 3, 4];`

> // good
> `const [first, second] = arr;`

Same with Google:

> Array and Object literals
> <...> To avoid these kinds of weird cases, always use the more readable array literal.
> `var a = [x1, x2, x3];`
> `var a2 = [x1, x2];`

> Array and Object Initializers
> Single-line array and object initializers are allowed when they fit on a line:
> `var arr = [1, 2, 3];`  // No space after [ or before ].
> `var obj = {a: 1, b: 2, c: 3};`  // No space after { or before }.

and with jQuery:
> Object and Array Expressions
> Object and array expressions can be on one line if they are short (remember the line length limits). <...>

> // Good
> `map = { ready: 9, when: 4, "you are": 15 };`
> `array = [ 9, 4, 15 ];`

and with Node:
> Object / Array creation
> Use trailing commas and put short declarations on a single line. Only quote keys when your interpreter complains:

> Right:
> `var a = ['hello', 'world'];`

Wikimedia recommends having a space after comma **semi-explicitly**:
> These and other aspects of our style guide are enforced with JSCS.
> Whitespace examples

> No
> `foo = [bar,baz];`
> Yes
> `foo = [ bar, baz ];`

Yandex - **explicit rule**:
> Arrays
> When enumerating elements in an array literal, spaces should be typed after the comma only:
> `var fellowship = ['foo', 'bar', 'baz'];`

And Crockford too:
> Whitespace should follow every , (comma).

And MDCS:
> Objects / Arrays
> The comma should have no space before and 1 space behind itself.

> good
> `var obj = { A: 1, b: 2, C: 3 };`
> `var arr = [ 1, 2, 3 ];`
> poor
> `var obj = {A:1,b:2,C:3};`
> `var arr = [1,2,3];`

This uniformity is why I believe all these presets assume that `requireSpaceAfterBinaryOperators: true` would cover this [very common] case. Changing its behavior results in jscs not catching errors where preset authors assumed it would, and that may be called a bug.

OTOH, is it even correct to call a comma in array/object literals a binary operator? On second thoughts, it seems to me the decision to remove comma from `binaryOperators` was a reasonable one, and this case should be treated by a new `requireSpaceAfterComma` rule to mirror the existing `requireSpaceBeforeComma`. This new rule should also be added to all current presets.

**Comment by hzoo** [comment]
Yeah we can either change `requireSpaceAfterBinaryOperators` to add commas back (specifically for this rule) or make a new rule for commas in arrays/objects on a single line.
