### ISSUE TITLE
jscs looking in .git folder

### ISSUE THREAD

**Issue by bstream** [jscs-dev/node-jscs#1707]
Found a weird issue when running jscs on my code. It appears that `jscs .` will look in dot-directories by default (for example `.git`). The error was triggered because my branch name ends in .js and jscs therefore tried to parse `/.git/logs/refs/heads/branch.js`.

```
> jscs .

parseError: undefined at ./.git/logs/refs/heads/branch.js :
     1 |0000000000000000000000000000000000000000 897bfdbcabdfa7ce535205c6b2c751bb0d84e69e Andreas Broström <andreas.brostrom@nordnet.se> 1440067510 +0200 branch: Created from HEAD
----------------------------------------------------^
     2 |

parseError: undefined at ./.git/refs/heads/branch.js :
     1 |897bfdbcabdfa7ce535205c6b2c751bb0d84e69e
-----------^
     2 |


2 code style errors found.
```

The example can be found at: https://github.com/bstream/jscs-js-branchname/tree/branch.js

This error can be fixed by supplying ".git" to the "excludeFiles"-list in `.jscsrc`, or by supplying the specific folders and files to be tested as arguments to jscs. However, maybe jscs should ignore hidden files by default? (Which is the case with for example ESLint, see https://github.com/eslint/eslint/issues/1077)

**Comment by mrjoelkemp** [comment]
`.git` sounds like a good default exception to add to excludeFiles. 

If @markelog agrees, then would you be open to submitting a PR? We could use the help.

**Comment by markelog** [comment]
+1 :)

**Comment by hzoo** [comment]
Ignore all dot directories or `.git` specifically?

**Comment by iamstarkov** [comment]
im going to create pr with ignoring all dot folders, is it ok?

**Comment by markelog** [comment]
Nuh, https://github.com/jscs-dev/node-jscs/issues/241

**Comment by iamstarkov** [comment]
@markelog these changes will not break #241

**Comment by markelog** [comment]
It seems we need to always ignore `.git` folder, otherwise user could redefine that value and will have same issue

**Comment by iamstarkov** [comment]
imo, the same for node_modules

**Comment by iamstarkov** [comment]
but its another issue

**Comment by markelog** [comment]
It is different way of solving it

**Comment by markelog** [comment]
> @markelog these changes will not break #241

Why not?
