### ISSUE TITLE
requireTrailingComma: false, if there preset

### ISSUE THREAD

**Issue by Gurylev** [jscs-dev/node-jscs#1711]
I want set parameter "requireTrailingComma": false, when "preset", this parameter true, but reports an error. This applies to all objects.

```requireTrailingComma option ignoreSingleLine requires true value or should be removed```

**Comment by Gurylev** [comment]
The docs stated "Boolean"

**Comment by zxqfox** [comment]
Just set it to null instead of false.

http://jscs.info/overview.html
> You can specifically disable any preset rule by creating a .jscsrc config file and assigning it to null, like so:

Would be great if you know how to improve docs ;-)

**Comment by hzoo** [comment]
If they use a preset then the option maybe should say to allow null to disable (or we allow `false` eventually which I think we talked about a bit)

**Comment by magicdawn** [comment]
@hzoo Both are good~

of which `allow false` maybe better & straighter

**Comment by hzoo** [comment]
We can add a new issue to discuss adding `false` as an option.

**Comment by Gurylev** [comment]
But my question was about the "false"...

**Comment by hzoo** [comment]
Sorry I had meant supporting false in all rules in general

**Comment by markelog** [comment]
Duplicate of https://github.com/jscs-dev/node-jscs/issues/1342
