### ISSUE TITLE
JsFile#getNodeByRange doesn't use the prebuilt index

### ISSUE THREAD

**Issue by gibson042** [jscs-dev/node-jscs#1712]
`iterate` relies on the `estraverse.traverse` visitor, which can be slow for large and/or complex files. Using the node index instead can speed things up [dramatically](https://github.com/jscs-dev/node-jscs/pull/1254#issuecomment-133462374).

**Comment by hzoo** [comment]
What can we do to measure performance for JsFile and rules? I guess there's #1043

**Comment by markelog** [comment]
we could use `time` command, but without service like coveralls, it is pretty much useless i guess

**Comment by markelog** [comment]
Okay, so this improvement only for the rules that use that method? Still pretty cool
