### ISSUE TITLE
Missing hyphen before description and newline

### ISSUE THREAD

**Issue by kobezzza** [jscs-dev/node-jscs#1715]
```js
/**
 * @param {!Array} value -
 *   [0] - some value;
 *   [1] - some value
 */
function foo(value) {
}
```

**Comment by zxqfox** [comment]
Can you elaborate? ;-) You don't want to have this hyphen if it ends with a newline?

**Comment by kobezzza** [comment]
> Can you elaborate? ;-) You don't want to have this hyphen if it ends with a newline?

**All fine**

```js
/**
 * @param {!Array} value - parameters:
 *   [0] - some value;
 *   [1] - some value
 */
function foo(value) {
}
```

**Error, but it must work**

```js
/**
 * @param {!Array} value -
 *   [0] - some value;
 *   [1] - some value
 */
function foo(value) {
}
```

**Comment by markelog** [comment]
@zxqfox is this still an issue?

**Comment by zxqfox** [comment]
Yep, unfortunately. I've missed this issue. Will fix it in a week or so.

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
