### ISSUE TITLE
Constructor functions should be capitalized.

### ISSUE THREAD

**Issue by nicksyndicate** [jscs-dev/node-jscs#1721]
Hi. Thanks for this instrument!

I have rule that "constructor should be capitalized".
But on practise there are several browser build-in constructors that are lowercased.
For exampe ``` new webkitSpeechRecognition ```
What can i do with this?

Thanks.

**Comment by hzoo** [comment]
Hey there! If you go to the docs or rule itself, it looks like we have an option to allow exceptions 

http://jscs.info/rule/requireCapitalizedConstructors.html

```
js
"requireCapitalizedConstructors": {
    "allExcept": ["somethingNative", "webkitSpeechRecognition"]
}
```
