### ISSUE TITLE
maxErrors IS respected when fix is true

### ISSUE THREAD

**Issue by arschmitz** [jscs-dev/node-jscs#1722]
When fix is true the documentation says `maxErrors` is ignored however using 2.1.0 this does not seem to be the case i can run with fix true repeatedly and it will fix 50 errors at a time fixing 50 more with each run. I am using this with the jQuery preset and grunt-jscs.

**Comment by hzoo** [comment]
Are you sure this is the case?

Maybe it's showing errors it can't fix? I just did `function a () {}` 51 times and tried autofixing and it fixed all of them to `function a() {}`

**Comment by arschmitz** [comment]
Yes reproduced repeatedly with this config on the jQuery ui repository

```js
jscs: {
		all: {
			options: {
				requireCapitalizedComments: null,
				fix: true,
				config: ".jscsrc"
			},
			files: {
				src: [ "demos/**/*.js", "build/**/*.js", "tests/**/*.js", "ui/**/*.js" ]
			}
		}
	}
```

the result is a passing status with no errors on each run
but running `git status` after each run shows an ever increasing number of changed files as it fixes 50 errors at a time.

adding `maxErrors: 500000` causes the whole lib to be fixed and 175 unfixable errors to be out put

**Comment by hzoo** [comment]
Hmm ok the code is in https://github.com/jscs-dev/node-jscs/blob/b5da623613bc81d8e92eaa3037cb8375d2909eca/lib/cli.js#L96-L98 @markelog

**Comment by markelog** [comment]
Yeah, `maxErrors` is respected if you run through CLI, but not programmatically

**Comment by markelog** [comment]
Okay, it is `grunt-jscs`, since `fix` property is its flag not of jscs - https://github.com/jscs-dev/grunt-jscs/issues/95
