### ISSUE TITLE
jQuery Preset unenforacable with requireDotNotation

### ISSUE THREAD

**Issue by arschmitz** [jscs-dev/node-jscs#1723]
The jQuery preset is currently unenforcable when using an object with a property named `float` because it has `requireDotNotation: true` when it should be `requireDotNotation: { "allExcept": [ "keywords" ] } ` The result is that if you do `thing[ "float" ]` you get the warning `Use dot notation instead of brackets for member expressions` but when you change that to be thing.float you get `Reserved words as properties can be used under the 'es5' option.` and `Expected an identifier and instead saw 'float' (a reserved word).`

This is currently preventing jQuery UI from fully passing with the jQuery preset

Ref https://github.com/jquery/jquery-ui/blob/master/tests/unit/effects/core.js#L256

**Comment by mikesherov** [comment]
@arschmitz you should add `es3: true` to the config on top of the preset.

**Comment by mikesherov** [comment]
`Expected an identifier and instead saw 'float' (a reserved word).` is from JSHint I believe.

**Comment by arschmitz** [comment]
@mikesherov ha ha your right it didnt get to jscs guess i should have had coffe before issue reporting this morning :-)

**Comment by markelog** [comment]
> coffee before issue reporting this morning :-)

I will drink to that! :-)
