### ISSUE TITLE
Remove requireCapitalizedComments from jQuery preset

### ISSUE THREAD

**Issue by arschmitz** [jscs-dev/node-jscs#1724]
This rule should probably be removed from the jQuery preset until #1686 is fixed because it makes it impossible to enforce the current preset on jQuery UI or Mobile or likely any project with a lot of comments as i would say when you take all the listed examples as a whole these are pretty common.

**Comment by hzoo** [comment]
Closing since #1686 is fixed?

**Comment by arschmitz** [comment]
:+1:
