### ISSUE TITLE
requireAlignedObjectValues: "ignoreFunction" is ignored by --fix option

### ISSUE THREAD

**Issue by acusti** [jscs-dev/node-jscs#1726]
Given the following `.jscsrc`:

```json
{
  "preset": "airbnb",
  "disallowSpaceAfterObjectKeys": { "allExcept": ["aligned"] },
  "requireSpaceBeforeObjectValues": true,
  "requireAlignedObjectValues": "ignoreFunction"
}
```

And a file with these contents:

```js
var foo = {
  foo: 'bar',
  foobar: 'baz',
  a: 1
};

var bar = {
  baz: function() {
    return true;
  },

  quuuux: false
};
```

The `--fix` option will produce:

```js
var foo = {
  foo   : 'bar',
  foobar: 'baz',
  a     : 1,
};

var bar = {
  baz   : function() {
    return true;
  },

  quuuux: false,
};
```

It seems to me that the `requireAlignedObjectValues: "ignoreFunction"` rule (“ if one of the property values is a function expression”) should prevent `--fix` from aligning the `bar` object.

-----------

Off-topic: can I make PRs for the JSCS docs? I wanted to make a tiny fix for the [disallowSpaceAfterObjectKeys](http://jscs.info/rule/disallowSpaceAfterObjectKeys.html) rule page. For all the `allExcept` examples, the headers say “Valid for ` allExcept: ['singleline'} }`” (instead of “Valid for ` allExcept: ['singleline'] }`”

**Comment by hzoo** [comment]
Yeah feel free to make PR's for any docs/typos - although that particular one is probably https://github.com/jscs-dev/node-jscs/commit/7c2d0dd9d848cf0de4eeabb52a2514b480179956 which was fixed (I think the website isn't updated yet)

**Comment by hzoo** [comment]
You can use `--verbose` to see which rules are erroring. When I run the code I get

```js
disallowSpaceAfterObjectKeys: Illegal space after key at a.js :
     6 |
     7 |var bar = {
     8 |  baz: function() {
-------------^
     9 |    return true;
    10 |  },
```

so the thing that's getting autofixed is from that rule and aligning to the `quuux`

**Comment by acusti** [comment]
Yes, that seems to work. Is that expected?

The intersections of all the possible rules is mind-melting. You all do a really impressive job with this tool!
