### ISSUE TITLE
jscs --auto-configure src fails due to no config file

### ISSUE THREAD

**Issue by fsbdev** [jscs-dev/node-jscs#1727]
`jscs --auto-configure src` 
returns 
`Config source is corrupted - TypeError: Cannot redefine property: configPath`. 

Of course I don't have a config file yet, I'm trying to generate one.

v2.1.0

**Comment by fsbdev** [comment]
I got around it for now by just having an empty object in a config file before I ran auto configure.

**Comment by hzoo** [comment]
Can't reproduce on jscs 2.1.0 - are you using a global/local jscs?

I made a new directory with a js file and ran `jscs --auto-configure a.js` with my global jscs and a `node_modules` one. Can you try reinstalling?

**Comment by fsbdev** [comment]
Was using a global jscs

**Comment by hzoo** [comment]
@fsbdev Were you able to reproduce?

**Comment by fsbdev** [comment]
Yes but I'll close this until I can give more information. Thanks
