### ISSUE TITLE
Yaml support for .jscsrc

### ISSUE THREAD

**Issue by ronkorving** [jscs-dev/node-jscs#1732]
I know this is a recurring theme about once a year. I would like to raise it once more, as my reasons are different from the ones before (where it was about the ability to comment out a rule).

To me it's very simple...
YAML is just so much nicer to the human eye than JSON. I love it, and I love how ESLint for example supports it out of the box. I think writing the configuration would look so much more readable in YAML format than JSON. Of course I'm not saying "drop JSON", but allow for both. It would be a real blessing for readability.

**Comment by ronkorving** [comment]
Imagine turning:

```json
{
	"requireSpaceBeforeKeywords": ["if", "else", "for", "while", "do", "switch", "return", "try", "catch", "finally"]
}
```

Into:

```yaml
requireSpaceBeforeKeywords: [if, else, for, while, do, switch, return, try, catch, finally]
```

**Comment by mikesherov** [comment]
:+1: from me

**Comment by markelog** [comment]
Sure, lets do it, would you like to implement it?

**Comment by hzoo** [comment]
ESLint uses https://github.com/nodeca/js-yaml

**Comment by ronkorving** [comment]
js-yaml is indeed *the* library of choice for yaml parsing. I can have a crack at it.

**Comment by markelog** [comment]
Nooice!

**Comment by ronkorving** [comment]
\o/
