### ISSUE TITLE
Proposal: requireChainMethods [$115]

### ISSUE THREAD

**Issue by gnarf** [jscs-dev/node-jscs#1736]
This is very similar to #1448 - the actual motivation behind it is more similar to [this stackoverflow question](http://stackoverflow.com/q/29784473/91914).

I would like to be able to specify a list of methods that **REQUIRE** using chain indentation.

Specifically, I am trying to enforce the following style of promise chains in my style guide, as I feel it greatly improves readability, and reduces diff noise.

```js
somePromise
  .then( /*...*/ )
  .then(function exampleMultiLineFunction() {
    return someWork;
  })
  .catch( /*...*/ );
```

I would propose a rule `requireChainMethods: [ 'then', 'catch' ]` that forces all `.then()` or `.catch()` calls to start on new lines chain indented.  The same rule could use `requireChainMethods: true` to force all `method().method()` calls to require a newline/chain indent and fix #1448 also.

I have no idea how one would implement such a rule, but I really wish there were one.

cc @mzgoddard @markelog @mikesherov @dgeb

**Comment by gnarf** [comment]
Chatted briefly with @mikesherov about how something like this might be implemented, he had some good wisdom:

> Yeah, it's basically any call expression whose callee is a member expression whose object is a call expression.  
> Those should be indented the same...
> Continue traversing up until the member expressions object is not a call expression... That object should be indented -1 times.
> Can be traversed downward or upward. Both strategies should work.

This seems to solve the `requireChainMethods: true` part of the proposal, and with a minor tweak I thikn we could solve my "list of methods that must be on a newline" case.

* For any call expression who's callee is a member expression:
  * If (`requireChainMethods: true` OR `requireChainMethods.contains(true)`) AND the object is a call expression
  * If `requireChainMethods.contains( memberExpressionIdentifier )` (the object of the call expression does not matter)

This handles my "forced chain" case on my example promise in the OP, as well as arbitrary chains as requested by #1448

**Comment by jzaefferer** [comment]
I've implemented something similar as a esformatter plugin for formatting jQuery method chains, might come in handy as a reference for the AST traversal: https://github.com/jzaefferer/esformatter-jquery-chain. I think the relevant code would be here: https://github.com/jzaefferer/esformatter-jquery-chain/blob/master/plugin.js#L13-L57

**Comment by gnarf** [comment]
Awesome, thanks Jörn.  Any chance one of you with the knowledge in this
code could take a stab at this?

**Comment by arschmitz** [comment]
+1 for this I actually just ran into some code today I wished I could have enforced this one

**Comment by markelog** [comment]
It seems we can add to the jquery preset?

**Comment by timmywil** [comment]
I like it.

**Comment by homerjam** [comment]
+1

**Comment by homerjam** [comment]
Possibly useful https://github.com/dsheiko/jscodesniffer/blob/b59cf8a7cad4259a5298421f28e192a6f6ab8643/lib/Sniff/SyntaxTree/ChainedMethodCallsPerLineConventions.js

**Comment by denim2x** [comment]
Towards an adequate resolution of this issue please take a look at the following:

* Valid for true:
```javascript
object .field1
  .method1()
  .field2 .field3 [method2]()
  [method3]();

object. field1.
  method1().
  field2. field3 [method2]().
  [method3]();
```

* Invalid for true:
```javascript
object
  .field1 .method1();

var result = object
  .method1() .field1;

object.
  method1()
  .method2();

object
  .method1()
.method2();
```

These may be similarly applied to a specific set of identifiers (such as 'then', 'catch' etc.)

**Comment by denim2x** [comment]
I'm waiting for feedback on my previous comment; this feature can only be implemented after properly establishing all details.

**Comment by gnarf** [comment]
Yeah, sorry I didn't reply to the previous message. I'm actually more interested in the specific identifiers mode myself.

I don't think any of your 'invalid' examples are actually invalid... Chain should be limited to methods only, just forced for methods, I would think the only invalid examples would have two chained method calls on the same line, the dot placement seems unimportant also, the call () and the identifier before it should not share a line with the object it is being called on.

**Comment by gnarf** [comment]
Also, I'm not sure about the 'method().foo.bar.method() ' case.

I think as long as the method() aren't on the same line its passing case for the rule

**Comment by gnarf** [comment]
Same line as the trailing parents on the previous call in the chain

**Comment by gnarf** [comment]
*not on* the same line... I should stop GitHub commenting from my phone now... Sorry

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
