### ISSUE TITLE
Contributing.md refences folders which no longer exist

### ISSUE THREAD

**Issue by arschmitz** [jscs-dev/node-jscs#1739]
In the section on submitting pr's it says to include a test with folders which they should be in but the folders no longer exist
neither 
`test/rules`
nor
`test/options/preset`
exist any longer they should be updated to i *believe*
`/test/specs/rules`
and
`/test/data/options/preset`

**Comment by hzoo** [comment]
Do you want to submit a PR?

**Comment by hzoo** [comment]
Made https://github.com/jscs-dev/node-jscs/pull/1765
