### ISSUE TITLE
disallowCommaBeforeLineBreak incorrectly errors on a function declaration

### ISSUE THREAD

**Issue by bengourley** [jscs-dev/node-jscs#1746]
This bug applies to current latest master as of time of writing. I believe it was introduced by this commit: https://github.com/jscs-dev/node-jscs/commit/cd8ce2e36b4c7fece12ad33cc7e7709ff71fd561 (PR #1410).

Last seen working in version `1.9.0`.

With the `disallowCommaBeforeLineBreak` rule set to `true`, jscs tells me that there is a style error with a a function declaration, see the following screenshot:

![screen shot 2015-09-02 at 15 44 57](https://cloud.githubusercontent.com/assets/609579/9635733/b82afac8-518f-11e5-9da6-9993045d2db2.png)

Or more simply:

```
function a(b,c) {
}
```

I have written a failing test case here:

https://github.com/bengourley/node-jscs/commit/e12bfb3b0f87e1a38be302f758f31c2cbc1f8a94

**Comment by hzoo** [comment]
cc @dreef3

**Comment by hzoo** [comment]
@bengourley Can you check if https://github.com/jscs-dev/node-jscs/commit/6571ebbbf29e5b96be45ade585e4676de3c2817d fixes it? We'll try to release 2.3.0 tomorrow.

**Comment by bengourley** [comment]
@hzoo Thanks for the update. I tried this and it doesn't appear to have changed the behaviour in my case.

**Comment by hzoo** [comment]
Always weird to have a rule using tokens. Also odd to have added that and no tests fail

**Comment by hzoo** [comment]
I can make a simple fix for function params but I think we need this rule is really brittle after adding `errors.assert.differentLine({` and counting on `canSkip` @dreef3
