### ISSUE TITLE
Indentation checks fail when closing curly bracket is preceded with spaces

### ISSUE THREAD

**Issue by lukeman** [jscs-dev/node-jscs#1753]
Using jscs 2.1.1 and testing against either the Airbnb or Google preset (and also with a custom config with four spaces), indentation checks seem to fail if the closing curly bracket is preceded by a space. Consider the following against Airbnb or any two space config:

```javascript
// two space indentation, PASS
var foo = {
  foo: 'bar',
};

// three space indentation, FAIL
var foo = {
   foo: 'bar',
};

// three space indentation, with an extra space before the closing brace, PASS
var bar = {
   foo: 'bar',
 };
```

It seems the indentation is checked relative to the closing brace, as this also passes:
```javascript
// five space indent, with three spaces before closing brace
var bar = {
     foo: 'bar',
   };
```

**Comment by markelog** [comment]
Would you like to try to fix it?

**Comment by KrekkieD** [comment]
Also hitting this issue. In my case I have a `validateIndentation` value of 4. I had a more complicated situation but it also seems to be related to the closing bracket position.

This bug allows my colleague to create hideous code ;)

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
