### ISSUE TITLE
disallowParenthesesAroundArrowParam false positive object destructuring

### ISSUE THREAD

**Issue by SimenB** [jscs-dev/node-jscs#1760]
Simplified sample:
```js
const stuff = obj => _.chain(obj)
    .map(({ thing, thing2 }) => ({ thing, thing2 }))
    .value();
```

JSCS wants me to remove the parentheses around the object destructuring. Doing so breaks the code

**Comment by hzoo** [comment]
Is this still an issue for you on master branch?

**Comment by SimenB** [comment]
Ah, good question.

**Comment by SimenB** [comment]
@hzoo It works correctly with code from master. Thanks!

Any timeline on 2.1.2?
