### ISSUE TITLE
validateIndentation fails to report errors in certain cases when encountering tabs

### ISSUE THREAD

**Issue by ottumm** [jscs-dev/node-jscs#1762]
.jscsrc:
```json
{
  "validateIndentation": 2
}
```

test.js (note tab character before ```.catch``` and before ```})```):
```javascript
var foo = function() {
  return bar()
	.catch(function(e) {
  throw new Error( e );
	})
};
```

`jscs test.js` fails to find any errors. It should be reporting an indentation error on the ```throw new Error( e )``` line, because it should be indented four spaces instead of two.

**Comment by ottumm** [comment]
I'm working on a fix for this.

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
