### ISSUE TITLE
Auto formatting should report changes

### ISSUE THREAD

**Issue by rdebeasi** [jscs-dev/node-jscs#1763]
When the `--fix` option is used, jscs should report any changes that it makes.

Currently, jscs is run with the `--fix` option, it does not report any violations that it has been able to fix. From the developer's perspective, it looks as if the violations hadn't existed in the first place.

**Comment by hzoo** [comment]
I guess you can see the changes after running `git diff`but to your point it would be cool/nice to see how how fixes were made for each rule in summary?

**Comment by markelog** [comment]
Maybe we can output amount of fixed errors

**Comment by rdebeasi** [comment]
I'd love to help, but I am totally new to jscs development. Here's roughly what I'm thinking:

- In the `fixString` function in `string-checker.js`, remove the line that wipes out fixed errors: `errors = new Errors(file, this._verbose);`
- In reporters, look at the `.fixed` property of each error to decide whether to output it. Some reporters could output each fixed error, while other reporters could report the number of fixed errors.

Alternately, we could filter out the fixed errors before they get to the reporter, and just provide the reporter with the number of fixed errors.

Does this approach sound reasonable? Feel free to let me know if I'm totally off base here. :smiley:

**Comment by markelog** [comment]
> Alternately, we could filter out the fixed errors before they get to the reporter, and just provide the reporter with the number of fixed errors.

This approach sounds better to me :-), otherwise we can confuse the users, showing them errors that we already fix. 

For that task we could introduce new flag, like '--dry-run' but since everyone these days use some kind of VCS it might be redundant.

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
