### ISSUE TITLE
requireVarDeclFirst vs const/let

### ISSUE THREAD

**Issue by markelog** [jscs-dev/node-jscs#1783]
Those are block scoped, so it doesn't makes sense to require them to be the first statements in function.

So we need to either apply more comprehensive algorithm or remove them.

/cc @oredi

**Comment by oredi** [comment]
@markelog when requireVarDeclFirst  was implemented I did not consider ES6 at that time. I think I could look into allowing let to have block scope. This might take sometime though, is it a time critical requirement or can we let #1069 get released without the requireVarDeclFirst  rule and add that to the preset once I can swing around to fix it. I am looking into a 3-4 weeks time frame as the past 2 weeks will be tight for me to look into this. :)

**Comment by markelog** [comment]
For sure! No hurry ;)

**Comment by oredi** [comment]
I will look into that when my schedule frees up.
Something out of topic but I love the new reporting for npm test 

![image](https://cloud.githubusercontent.com/assets/637249/9841011/4420d8ba-5ad5-11e5-8438-dac529fd6b83.png)

**Comment by hzoo** [comment]
This should be added to the idiomatic preset.

**Comment by dsebastien** [comment]
+1 for a change of behavior of this property. I disabled it for now, way too annoying w/ ES2015 :)

**Comment by lukebennett** [comment]
Yep, agree with the need to change this rule.

**Comment by oredi** [comment]
I might have sometime next week, I will try looking into this. :)

**Comment by bturk** [comment]
Another +1.

When you implement don't forget you can't just look for braces:

for (let item in obj) and  for (let i = 0; i < len; i++) are implicitly block scoped.

**Comment by oredi** [comment]
Sure. Sorry I had to delay on this as I just let my company and had a little cleaning up to do on the day job.

**Comment by bturk** [comment]
No big rush, I've been doing JavaScript for a long time so it's not very natural to me to put variables anywhere else, let will take some getting used to.

Actually, now that I've thought about it, I'm surprised this rule gets triggered at all.  Seems it would specifically be looking for var.  Just  a suggestion, it's your product and it's a good one but I'd split the rule.

requireVarDeclFirst - only look at var
requireLetDeclFirst - only look at let/const and at block level

**Comment by hzoo** [comment]
If people want it, I can create a change now that ignores let/const and release another patch version

**Comment by bturk** [comment]
That would work for me.  I could remove the override comments and add the new rule later if you do it that way.
