### ISSUE TITLE
Exponentiation Operator

### ISSUE THREAD

**Issue by alawatthe** [jscs-dev/node-jscs#1787]
I'd like to include the [exponentiation operator](https://github.com/rwaldron/exponentiation-operator) (```**``` and ```**=```) into the [binary operator list](https://github.com/jscs-dev/node-jscs/blob/master/lib/utils.js#L175). And wanted to use the opportunity to ask, at which stage new JavaScript features have to be, that we include rules for them. i.e. is it too soon to include the stage 3 proposal exponentiation operator?

**Comment by markelog** [comment]
> I'd like to include the exponentiation operator (** and **=) into the binary operator list. 

Yeah sure, lets do it

> use the opportunity to ask

Stage 2 i suppose, rules with earlier stages could be made as a plugin.

**Comment by hzoo** [comment]
Should be easy to include this with tests

**Comment by alawatthe** [comment]
Yes, will do this later today.
And I agree with the stage 2 plan.
