### ISSUE TITLE
ES6: Object shorthand and disallowSpaceAfterObjectKeys

### ISSUE THREAD

**Issue by SimenB** [jscs-dev/node-jscs#1788]
Would it be possible to disable `disallowSpaceAfterObjectKeys` for object shorthand functions, but keep it for other keys? (add it to `allExcept`).

To allow 
```js
{
  initialize (opt) { // Space before parenthesis
    console.log(opt);
  }
}
```

**Comment by hzoo** [comment]
That sounds ok

**Comment by markelog** [comment]
@SimenB  Would you like to take a stab at it?

**Comment by indexzero** [comment]
+1 this just bit me hard.

**Comment by hzoo** [comment]
Oh this should of been closed (fixed in master)

**Comment by indexzero** [comment]
Hmm ... then I'll open a bug for what I was seeing. It didn't seem related to this rule the more I think about it.

**Comment by indexzero** [comment]
Yup. Unrelaed: https://github.com/jscs-dev/node-jscs/issues/1805
