### ISSUE TITLE
Exit codes listed in the wiki don't match those in implementation

### ISSUE THREAD

**Issue by jawshooah** [jscs-dev/node-jscs#1800]
The exit codes specified in the [wiki](https://github.com/jscs-dev/node-jscs/wiki/Exit-codes) don't match those in the [implementation](https://github.com/jscs-dev/node-jscs/commit/6f8920da5fccba534ce69e51cad7b79731bbfe85). Specifically:

> 3 - No input files specified

This actually [returns 5](https://github.com/jscs-dev/node-jscs/blob/6f8920da5fccba534ce69e51cad7b79731bbfe85/lib/cli.js#L63).

> 5 - Config is corrupted

This actually [returns 4](https://github.com/jscs-dev/node-jscs/blob/6f8920da5fccba534ce69e51cad7b79731bbfe85/lib/cli.js#L40).

**Comment by hzoo** [comment]
@markelog Probably just have to update the wiki then right?

**Comment by markelog** [comment]
Looks we need to change both, will check this out more thoroughly

**Comment by hzoo** [comment]
Ok we can add it to 2.2.0 if you get to it today/tomorrow
