### ISSUE TITLE
ES6 Object literal function short-hand and requireSpacesInAnonymousFunctionExpression { beforeOpeningRoundBrace: true } 

### ISSUE THREAD

**Issue by indexzero** [jscs-dev/node-jscs#1805]
This code:

``` js
var anObject = {
  ok() {
    console.log('ok');
  }
};
```

With this setting:

```
{
  "requireSpacesInAnonymousFunctionExpression": {
    "beforeOpeningRoundBrace": true
  }
}
```

Causes this output:

```
Missing space before opening round brace at wtf.js :
     1 |
     2 |var anObject = {
     3 |  ok() {
------------^
     4 |    console.log('ok');
     5 |  }

1 code style error found.
```

From an AST point of view I can see why this would be the case, but from a style point of view you can see how this is very close to a named function expression. Would an exception for this case be excepted?

**Comment by indexzero** [comment]
It is also worth mentioning that since there is no `function` keyword here. This can cause an unlintable code situation when used in conjunction with other rules.

**Comment by hzoo** [comment]
Yeah this should be fixed - although I just found https://github.com/jscs-dev/node-jscs/issues/1513 - we actually have a option for shorthand methods now - http://jscs.info/rule/requireSpacesInAnonymousFunctionExpression

We should an example to the docs though

**Comment by hzoo** [comment]
Although maybe this should be by default
