### ISSUE TITLE
Preset: Organization owned presets

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1811]
- [x] Wikimedia: https://github.com/jscs-dev/node-jscs/pull/1770#issuecomment-139113833
- [ ] Airbnb: https://github.com/airbnb/javascript/pull/455#issuecomment-128103763 - ping @hshoff
- [ ] Wordpress: @paulschreiber @westonruter 

Instructions to create a preset in the [wiki](https://github.com/jscs-dev/node-jscs/wiki/Creating-a-Custom-Preset-or-Config)

If an org wants to update/maintain their preset themselves, they can/should have the option to do? Otherwise we can maintain it.
Then they can update their preset independently of jscs itself and no one has to wait on us to release (although hopefully we can be more responsive in the future).

Example: Wikimedia preset (https://github.com/wikimedia/jscs-preset-wikimedia)

Added preset docs in [2.1.1 notes](https://github.com/jscs-dev/node-jscs/releases/tag/v2.1.1)

> Move presets to their own repo/module and release it in the different manner then jscs

**Comment by hzoo** [comment]
Another idea I had is that we make presets their own npm packages either in different repos, or in this repo (thinking of babel) so we can independently version them.

**Comment by paulschreiber** [comment]
I'm happy to help out with the WordPress preset if you'd like.

**Comment by hzoo** [comment]
@paulschreiber Ok cool - can make one with https://github.com/jscs-dev/node-jscs/wiki/Creating-a-Custom-Preset-or-Config and then we can use that in own package.json
