### ISSUE TITLE
Discussing Tags for commits

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1812]
Although this isn't as important with a more manual changelog

Suggestions (and examples):

- `Fix` | `Bugfix`
- `Docs`
  - ```Docs: `disallowParenthesesAroundArrowParam` fixes```
- `New` | `New Rule`
  - ```New: `disallowArrowFunctions` ```
- `Update` | `Rule Update` - new rule values, support that isn't a bug fix
  - ``` Update: `disallowMultiLineTernary` - add `nested` option ```
- `Internal`: - something for jsfile, string-checker
  - ``` Internal: `CLI` - implement `extract` option ```
- `Config` | `Configuration` - change related to .jscsrc
  - ```Config: strip BOM from config files```
- `Dependency` | `Package` | `Upgrade` - updating a dependency
  - ```Upgrade: esprima@2.6.0```
- `Chore` | `Build` - related to dev-ops, CI, or dependencies
- `Misc`
- `Preset`
- `Test`
- `Feat`
- `Perf`
- `Cleanup` | `Refactor`
- `Security`
- ` Breaking`

Don't need that many but just some thoughts

**Comment by zxqfox** [comment]
I'm just looking at changelog. Not sure that we need so detailed list of tags. `Breaking` can be a flag, like: `Fix: BREAKING etc.`

Docs: Documentation only changes
Feat: A new feature
Fix: A bug fix
Chore: Changes to the build process or auxiliary tools and libraries such as documentation generation
Preset
New Rule
Update Rule
Perf
Cleanup | Refactor

Misc ← Test, Config, Internal, Security
Chore ← Dependency | Package | Upgrade, ?

**Comment by hzoo** [comment]
Less categories is good - just shouting out possibilities.

General: Docs, Fix, Chore, Misc
JSCS: New Rule, Update Rule, Preset

**Comment by markelog** [comment]
We would need to use those tags with changelog generator, since primarily we want to do it for changelog itself.

Like what it would generate if we would use `Fix:Breaking: ...`?

Also we need to make sure we can add such checks in githook.

**Comment by hzoo** [comment]
Similar to https://github.com/jscs-dev/node-jscs/issues/407 so goina close that one again.

https://github.com/jzaefferer/commitplease, http://gitcop.com/, etc

**Comment by hzoo** [comment]
I've been using Fix, Misc, Docs so far - New Rule, Update Rule, Preset sound good. If we want a flag then we can do it like angular `fix(rule-here): description`, `chore(package-here): description`

**Comment by markelog** [comment]
Did you implemented commitplease? Since you moved that ticket here but not implemented it

**Comment by markelog** [comment]
We also need to document this
