### ISSUE TITLE
"Illegal space before opening round brace" for async anonymous functions

### ISSUE THREAD

**Issue by donaldpipowitch** [jscs-dev/node-jscs#1813]
Using `2.1.1` and `"esnext": true,` this example doesn't work, but is compiled by Babel:

````
// Illegal space before opening round brace
beforeEach(async function() {
  await doFoo();
});
````

However these alternatives work:
````
beforeEach(function() {
  doFooSync();
});
````
````
beforeEach(async function beforeEach() {
  await doFoo();
});
````
````
beforeEach(async () => {
  await doFoo();
});
````

When `beforeEach(function() {` works, I'd expect `beforeEach(async function() {` to work, too.

**Comment by donaldpipowitch** [comment]
Could be related to https://github.com/jscs-dev/node-jscs/issues/1637, because auto-fixing results in `beforeEach(asyncfunction() {`. I'll try it.

**Comment by hzoo** [comment]
Releasing 2.2.0 today so just wait a bit :smile:

**Comment by donaldpipowitch** [comment]
Thank you!
