### ISSUE TITLE
disallowSpaceAfterObjectKeys - aligned: "Illegal space after key" without spaces

### ISSUE THREAD

**Issue by avdv** [jscs-dev/node-jscs#1818]
Input:
```javascript
var f = {
    "name": 1,
    "x": 2
};
```

Config:
```json
{
    "disallowSpaceAfterObjectKeys": {
        "allExcept": ["aligned"]
    }
}
```

output:
```
Illegal space after key at test.js :
     1 |var f = {
     2 |    "name": 1,
     3 |    "x": 2
---------------^
     4 |};
     5 |

1 code style error found.
```

There is no space after the key, so I would expect that to be valid, ie. "aligned" should only matter when there're spaces so that the colons are aligned.

**Comment by hzoo** [comment]
So if you look at the rule options examples  - http://jscs.info/rule/disallowSpaceAfterObjectKeys,

It looks like what is valid is

```js
var y = {
    abc: 1,
    d  : 2
}
```

so that it's always checking that colons are 'aligned'
@dreef3

**Comment by davidrapin** [comment]
@hzoo This behavior is confusing and does not look like a real-world use-case.
My understanding of the rule: `disallowSpaceAfterObjectKeys: { allExcept: ['aligned'] }` is:
"disallow all spaces after object keys **except when keys are aligned**".

So no space before the key should **always** be valid when using `disallowSpaceAfterObjectKeys`. Would that not be a saner implementation?

**Comment by hzoo** [comment]
No, yeah I totally agree just wondering about the original implemented of `aligned` https://github.com/jscs-dev/node-jscs/issues/1420 for reference

**Comment by davidrapin** [comment]
I believe the error in the implementation of `aligned` is to **exclusively** allow aligned `:` after keys, where the intent of the configuration (`disallowSpaceAfterObjectKeys`) is to disallow spaces between the key and `:`.

`aligned` should allow:
- no spaces between object keys and `:` for the whole object
- all `:` space-aligned after object keys for the whole object

**Comment by davidrapin** [comment]
Thank you for this fix!
