### ISSUE TITLE
New Rule: disallowNestedTernaries

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1824]
disallowNestedTernaries/disallowNestedConditionalExpressions

Don't know if we want to make a parameter for a certain maxLevel of nesting since that might be too much right now?

Ref https://github.com/jscs-dev/node-jscs/pull/1806#issuecomment-142786850
@bjdixon

**Comment by markelog** [comment]
Would love that rule

**Comment by bjdixon** [comment]
I would like to implement this please.

**Comment by hzoo** [comment]
Go ahead!
