### ISSUE TITLE
validateLineBreaks and git with "core.autocrlf true" on Windows

### ISSUE THREAD

**Issue by indexzero** [jscs-dev/node-jscs#1825]
A rather narrow bug came up in a channel at GoDaddy today, but the usecase is real for Windows developers if I understand it correctly _(see: https://help.github.com/articles/dealing-with-line-endings/ for initial background)_

The TL;DR here is that the accepted best practice for Windows developers with `git` is to use `core.autocrlf true`. That means in Windows, it will convert line endings to `crlf`, but when committing it converts back to Unix line endings.

This means that the lint errors thrown by `jscs` with this config:

``` js
{ "validateLineBreaks": "LF" }
```

on Windows are erroneous because the line endings are, in fact going to be changed back by `git` before being committed. Any thoughts on potentially checking `git config` as part of our setup stage?

**Comment by markelog** [comment]
Why would anyone use `validateLineBreaks` if their have correct `.gitattributes` file?

**Comment by hzoo** [comment]
We should probably at least leave a note about it in the rule docs or even in the rule error message since I remember this or similar issues coming up a few times?

**Comment by markelog** [comment]
Yeah!

**Comment by hzoo** [comment]
What should we put? Maybe suggesting not using the rule if it's only windows users? Or should we be checking `.gitconfig` like suggested

**Comment by zxqfox** [comment]
Guess we could disable this rule on windows if it requires LF and git has crlf=auto. Or check it as CRLF. Just it.

**Comment by jcrugzz** [comment]
@zxqfox i feel that its safe to disable on windows if it can be checked that `auto.crlf = true`. This would solve the use case I have where multiple contributors to projects running different machines will all link properly based on the universal style guide that leverages this

**Comment by indexzero** [comment]
@hzoo @zxqfox I started on a basic implementation of this tonight: https://github.com/indexzero/git-lint Will currently work for `autocrlf` checking only.

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
