### ISSUE TITLE
disallowTabs fails with TypeError, Extracting HTML by default 

### ISSUE THREAD

**Issue by yekver** [jscs-dev/node-jscs#1828]
```
TypeError: Cannot call method 'replace' of undefined
    at renderLine (/home/vagrant/www/node_modules/jscs/lib/errors.js:250:17)
    at Object.Errors.explainError (/home/vagrant/www/node_modules/jscs/lib/errors.js:181:13)
    at /home/vagrant/www/node_modules/jscs/lib/reporters/console.js:16:36
    at Array.forEach (native)
    at /home/vagrant/www/node_modules/jscs/lib/reporters/console.js:14:35
    at Array.forEach (native)
    at Object.module.exports [as writer] (/home/vagrant/www/node_modules/jscs/lib/reporters/console.js:9:22)
    at /home/vagrant/www/node_modules/jscs/lib/cli.js:151:18
    at Array.0 (/home/vagrant/www/node_modules/vow/lib/vow.js:711:56)
    at Object.callFns [as _onImmediate] (/home/vagrant/www/node_modules/vow/lib/vow.js:23:35)
```

**Comment by hzoo** [comment]
If you could post a code snippet, config, jscs version that would be helpful (run with `--verbose` to be sure it's disallowTabs). Hmm I don't see a `.replace` in [the file](https://github.com/jscs-dev/node-jscs/blob/6ca665fe7068d3a1e7a6e4787a77c757802388b8/lib/rules/disallow-tabs.js) but we can keep looking?

**Comment by zxqfox** [comment]
It's here: https://github.com/jscs-dev/node-jscs/blob/master/lib/errors.js#L250

Would be nice to see something that helps to repeat this.

**Comment by hzoo** [comment]
@yekver Could we get a code snippet that reproduces the issue? We definitely want to fix this.

**Comment by hzoo** [comment]
@yekver friendly ping

**Comment by yekver** [comment]
Sorry, but I can't reproduce this issue with an example piece of code.

**Comment by hzoo** [comment]
Do you mean you aren't getting the error anymore or you can't paste the code that is erroring?

**Comment by yekver** [comment]
Can I debug it somehow?

**Comment by yekver** [comment]
I can't create an example that will throw an error.

**Comment by zxqfox** [comment]
hashbang? eol at eof? You can try to add `console.log(i, line)` before `errors.add` in `node-jscs/lib/rules/disallow-tabs.js`. If `line` is not empty — dump lines in explainError here: https://github.com/jscs-dev/node-jscs/blob/master/lib/errors.js#L177

**Comment by markelog** [comment]
I think, file example would be enough, if you don't want to go in the internals

**Comment by yekver** [comment]
Here is an `error` from [here](https://github.com/jscs-dev/node-jscs/blob/master/lib/errors.js#L177):

```javascript
{ 
  filename: './500.html',
  rule: 'requireSpacesInAnonymousFunctionExpression',
  message: 'Missing space before opening round brace',
  line: 2,
  column: 9
}
```


`500.html` is a symlink to a file that contains one-string obfuscated html-code.

**Comment by hzoo** [comment]
`./500.html`? That shouldn't be linting unless you are using the extract option http://jscs.info/overview#extract?

**Comment by yekver** [comment]
If I understood rigth:
> Default value is ["**/*.+(htm|html|xhtml)"]. So JavaScript is extracted from files with .htm, .html or .xhtml extension.

`.html` files will be checked by default. Right?

**Comment by hzoo** [comment]
Yeah but that's with the extract option - are you using it?

**Comment by yekver** [comment]
Nope. here is my config:
```javascript
{
    "preset": "yandex",
    "excludeFiles": [
        ".git",
        ".npm",
        ".bower",

        "libs/**/*",
        "node_modules/**/*",
    ],
    "requireDotNotation": null,
    "requireCamelCaseOrUpperCaseIdentifiers": "ignoreProperties",
    "disallowTrailingComma": true,
    "disallowNewlineBeforeBlockStatements": true,
    "disallowMultipleSpaces": true,
    "disallowSpacesInCallExpression": true,
    "requireBlocksOnNewline": 1,
    "requireSpaceBeforeBlockStatements": true
}
```

**Comment by yekver** [comment]
I think there is something wrong with this `./500.html` file. Because if I make any changes to it - everything is working fine.

Finally I made an example: https://yadi.sk/d/hcjAjGL_jkMwr
I run jscs with this command: 
```
$ node_modules/jscs/bin/jscs -c ./.jscs.json .
```

**Comment by yekver** [comment]
By the way, there is no error till `2.1.0` (included)

**Comment by yekver** [comment]
Does my example helps you to reproduce the issue?

**Comment by hzoo** [comment]
Yeah. So it's not related to disallowTabs at all and for some reason you it's linting html files by default which we need to fix.

Unrelated, but is there a particular reason why you are doing `-c ./.jscsrc`? It will do it automatically

**Comment by yekver** [comment]
Yes, topic title is wrong, I think you can change it. I dunno why don't you get the error `TypeError: Cannot call method 'replace' of undefined`.

I get undefined because the file contains only single string, and as I wrote in https://github.com/jscs-dev/node-jscs/issues/1828#issuecomment-148107092 jscs matches to the second (non-existing) line.

P.S. There is no particular reason it's just a habit :)

**Comment by lahmatiy** [comment]
> That shouldn't be linting unless you are using the extract option

Actually we did one bad thing. Extract option is used by default. If you use `--extract` option for cli, it's just override default setting. I thought about several times, but have no time to fill an issue.
I think extract should be opt-in by default.

Anyway, in this case looks like something wrong with line position in html.

> a file that contains one-string obfuscated html-code.

Probably there is an edge case:

```html
<script> /* some wrong style js here*/ </script>
```

And we have no test for it :-/

**Comment by hzoo** [comment]
Ok lines is an array that is something like [ 'html-here' ] and lineNumber is 1 so `lines[1]` becomes `undefined`

**Comment by lahmatiy** [comment]
> Ok lines is an array that is something like [ 'html-here' ] and lineNumber is 1 so lines[1] becomes undefined

`extract` convert line number in js to line number in html. Looks like in this edge case (`a file that contains one-string ... html-code`) it fails.
I think we should fix it.
