### ISSUE TITLE
[[FEAT]] requireNewlineBeforeSingleStatements

### ISSUE THREAD

**Issue by minj** [jscs-dev/node-jscs#1829]
Consider these options:
```json
{
    "requireNewlineBeforeBlockStatements": false,
    "requireCurlyBraces": false
}
```
I'd like to enforce this style:
```js
// bad
if (x) doX();
else doY();

// good
if (x)
    doX();
else
    doY();
```

or is this a case of me being too peculiar?

**Comment by minj** [comment]
Pros:
- no redundant braces
- easier to spot
- similar to python
- easier to convert to a block statement and add more statements*

\* at least my IDE adds the second brace automatically

**Comment by hzoo** [comment]
I don't think any of us have resources to implement the rule ourselves - if you want to submit a PR or just just a plugin rule to submit yourself, free feel though!

**Comment by markelog** [comment]
That would be a cool rule, @minj would you like to give it a shot?

**Comment by minj** [comment]
@markelog not at this point, no. I have no knowledge of the internals of jscs. I'll start overviewing any contributing information one of these days.

**Comment by schempy** [comment]
Silly question. When implementing this rule would you check if requireNewlineBeforeBlockStatements and requireCurlyBraces are set to specific values before checking the file? I'm guessing no but figured I'd ask.

Thanks!

**Comment by hzoo** [comment]
We would like to stay from rules depending on one another if possible

**Comment by schempy** [comment]
Great. Thanks for answering. I'll try implementing this rule.

**Comment by markelog** [comment]
@schempy still interested?

**Comment by schempy** [comment]
@markelog  Yes! I'm Working on a PR.
