### ISSUE TITLE
Disallow spaces around dot notation

### ISSUE THREAD

**Issue by minj** [jscs-dev/node-jscs#1830]
How do I enforce the following:
```js
// valid
foo.bar();

// invalid
foo. bar();
foo .bar();
foo . bar();
```

Sometimes those spaces sneak in when joining lines.

I tried these options:
```json
{
	"disallowSpaceBeforeBinaryOperators": ["."],
	"disallowSpaceAfterBinaryOperators": ["."]
}
```
but it did not work

**Comment by hzoo** [comment]
`.` isn't a binary operator I don't think doing what you did will work - It's a `MemberExpression` in that case. I'm not sure if we have a rule for spaces around `.` - I thought we did for new lines or something. http://jscs.info/rule/disallowOperatorBeforeLineBreak

Yeah maybe we need a new rule for that

**Comment by samarpanda** [comment]
@hzoo Can i work on this feature?

**Comment by samarpanda** [comment]
```
{
  "disallowSpaceBeforeMemberExpression": false,
  "disallowSpaceAfterMemberExpression": false
}
```

**Comment by samarpanda** [comment]
```
var foo = function(){console.log('foo');};
foo.prototype.boo = function(){console.log('boo');};
var obj = new foo();
obj . boo();
obj['boo']();
```
Wondering if we have to consider both MemberExpression here i.e `obj . boo` and `obj ['boo']`?

**Comment by hzoo** [comment]
If you are going to name it that then maybe? Or you could create an option to turn it on for `a.b` and/or `a['b']`.Maybe true does it for both?
```
"disallowSpaceBeforeMemberExpression": {
  "allExcept": "" // not sure how we want to name either type
}

**Comment by hzoo** [comment]
But yeah definitely encourage you to try sending in a PR. Most of the team will be busy working on 3.0 issues instead of adding new rules/options so help would be greatly appreciated!

**Comment by MichaelHazani** [comment]
@samarpanda : are you working on this? I have some time off and was considering giving this one a go.

**Comment by MichaelHazani** [comment]
@hzoo , I went ahead and took the initiative on this (one catchall rule for the aforementioned cases). I'm close to sending a PR, but my tests are failing with:

```
      at Context.<anonymous> (test/specs/rules/disallow-spaces-around-property-accessors.js:15:10)
All errors:
 - : Unsupported rule: disallowSpacesAroundPropertyAccessors
```
Is "unsupported rule" a normal error until it's implemented? Or am I missing something? I created the rule (per the instructions) in /lib/rules and the respective test in /test/specs/rules...

Thanks, and please bear with me as this is literally my first "IRL" PR;)

**Comment by markelog** [comment]
Ping us up if you are still interested
