### ISSUE TITLE
False positive: disallowParenthesesAroundArrowParam rest-params

### ISSUE THREAD

**Issue by SimenB** [jscs-dev/node-jscs#1831]
If the only arg is a rest-param (to get `arguments` as a real array)

Using 2.2.1

https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=false&code=export%20default%20(...stuff)%20%3D%3E%20%7B%0A%20%20if%20(stuff.length%20%3C%202)%20return%20null%3B%0A%0A%20%20verdier.splice(-1%2C%201)%3B%0A%0A%20%20return%20verdier.reduce((streng%2C%20memo)%20%3D%3E%20%60%24%7Bmemo%7D%20%24%7BescapeExpression(streng)%7D%60%2C%20'')%3B%0A%7D%3B

**Comment by hzoo** [comment]
Thought I checked for that :cry: - looks like I only added it for the require rule lol - https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/require-parentheses-around-arrow-param.js#L51
