### ISSUE TITLE
Glob not working on Windows

### ISSUE THREAD

**Issue by mborman** [jscs-dev/node-jscs#1835]
I am on Windows. In my npm scripts `jscs src/**/js` fails to find files. I tried other variants to no avail. `jscs src/**/js/*.js`, `jscs **/js`, `jscs *.js`. None work. I tried going back a few versions to see if globbing has ever worked. It has not. See error at end of post.

I have seen a few issues with globbing on Windows for other projects. They either add or switch to "glob" to bring glob compatibility to Windows. I see glob is already a dependency for jscs. Any chance JSCS will support globbing on windows anytime soon? As a work around I am using explicit paths (no globs). Ok for smaller projects but will be a pain once the project grows.

I verified globbing works using [copyfiles](https://github.com/calvinmetcalf/copyfiles) in my npm scripts like this:

    "copyfiles -u 1 src/**/css/*.css build/dist"

It works perfect. 

Let me know if you are interested in me creating a PR. I'd be more than happy to contribute... Just need to find the time.

*Glob Error*

    jscs src/**/js
    
    Error: Path src/**/js was not found.
        at null.<anonymous> (C:\workspace\ReferenceArchitecture\FrontEnd\Core\node_modules\jscs\lib\checker.js:177:19)
        at Array.<anonymous> (C:\workspace\ReferenceArchitecture\FrontEnd\Core\node_modules\jscs\node_modules\vow\lib\vow.js:711:39)
        at Immediate.callFns [as _onImmediate] (C:\workspace\ReferenceArchitecture\FrontEnd\Core\node_modules\jscs\node_modules\vow\lib\vow.js:23:35)
        at processImmediate [as _immediateCallback] (timers.js:358:17)

**Comment by hzoo** [comment]
Thanks for the report! If needed a PR would be great. Also, can you try if you haven't already if `jscs src/**/*.js` works?

**Comment by markelog** [comment]
hm, that is weird, it should work, since we have windows and CI and users with windows, would you mind creating a test repo?

**Comment by mborman** [comment]
I tried `jscs src/**/*.js`. Same issue. I'll try to find some time to dig into it in the next week or two.

**Comment by mborman** [comment]
Just noticed the comment from @markelog .  I will try that first.  Maybe there is something wonky in my project.

**Comment by markelog** [comment]
Friendly ping

**Comment by TheSavior** [comment]
I seem to be hitting this on mac too. If I use `**/*.js`, everything is dandy. If I use `src/**/*.js`, I get `Error: Path src/**/js was not found.`

**Comment by TheSavior** [comment]
If anyone comes across this in the future, the answer is to just use `src` and not specify the glob on the end.
