### ISSUE TITLE
Consider using "table" package instead of "cli-table"

### ISSUE THREAD

**Issue by gajus** [jscs-dev/node-jscs#1836]
https://github.com/gajus/table package is a very modular, well documented and well tested module/function for generating text tables. It allows granular customisation of how table contents is aligned, text wrapping, text truncation, border style and text padding.

If accepted, I will happily create a PR.

**Comment by mrjoelkemp** [comment]
Thanks for suggesting it. What problem does it fix with the current
implementation? We've received no complaints so far.

**Comment by gajus** [comment]
The problems that table package fixes (https://github.com/Automattic/cli-table/issues/35, https://github.com/Automattic/cli-table/issues/8, https://github.com/Automattic/cli-table/issues/10, https://github.com/Automattic/cli-table/issues/64) do not affect, as far as I can tell, JSCS use case. However, `table` does not have these problems to begin with.

**Comment by mrjoelkemp** [comment]
Thanks for the insight.

> do not effect, as far as I can tell, JSCS use case

That's precisely the point though. Until we have the pain caused by those issues you mentioned, we have no real need to move off of it.

If that time comes, we'll give `table` a shot. Thanks for contributing.

**Comment by markelog** [comment]
> If that time comes, we'll give table a shot. Thanks for contributing.

Yeah, we always try to choose best package out there to work with, so @gajus, if you submit pr we will consider it :-)
