### ISSUE TITLE
Setting jsDoc.requireDescriptionCompleteSentence to false/null is not allowed

### ISSUE THREAD

**Issue by ronkorving** [jscs-dev/node-jscs#1838]
output:

```
Only accepted value for jsDoc.requireDescriptionCompleteSentence is true
```

Since [2.1.1 this should work](https://github.com/jscs-dev/node-jscs/blob/master/CHANGELOG.md#disable-a-rule-with-false-or-null) I believe, but it doesn't for JSDoc. Is that a bug in the plugin, or in jscs itself?

**Comment by hzoo** [comment]
I'm assuming it is only for the plugin?

**Comment by ronkorving** [comment]
Yes, and a different property I *could* set to false in jsDoc. I don't know the codebase well enough... Is the plugin to blame for this?

**Comment by zxqfox** [comment]
@ronkorving Yeah, jsDoc scope is all about plugin. I'll try to take a look asap.

Atm I can propose you only monkey patching or disabling plugin at all to decrease noise ;-(

**Comment by ronkorving** [comment]
No worries, I've commented out the rule, so it's no biggy.

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
