### ISSUE TITLE
JSCS hangs when running against a folder on Windows

### ISSUE THREAD

**Issue by irengrig** [jscs-dev/node-jscs#1839]
2.2.1

**Comment by markelog** [comment]
@zxqfox i remember you were using windows (?), could you check this out?

**Comment by zxqfox** [comment]
@irengrig I need some additional info. Can't repeat with `jscs --preset .\path` (it works as expected). What hangs you see?

**Comment by markelog** [comment]
Friendly ping

**Comment by irengrig** [comment]
I'm really sorry, but now it just works ok. Checked with several projects.
Seems to have been some local problem.

**Comment by hzoo** [comment]
Ok great - thanks for the report anyway!
