### ISSUE TITLE
disallowParenthesesAroundArrowParam doesn't work for ...args

### ISSUE THREAD

**Issue by ptarjan** [jscs-dev/node-jscs#1842]
When using `...args` the `()`s are required and it shouldn't be considered a single argument

Allowed:

```
let foo = (...args) => {
};
```

Parse error:

```
let foo = ...args => {
};
```

But when I feed that through jscs I get:

```
Illegal wrap of arrow function expressions in parentheses [javascript/jscs]
```

**Comment by hzoo** [comment]
Thanks for the report @ptarjan - this is the same as https://github.com/jscs-dev/node-jscs/issues/1831 - and I have a fix in master already https://github.com/jscs-dev/node-jscs/commit/bcfaa5192b09391bdec31adecab14d3861817c8a. Just need to make a release later

**Comment by ptarjan** [comment]
:ship:

**Comment by hzoo** [comment]
Tomorrow sounds good!

**Comment by hzoo** [comment]
sorry, releasing 2.3.0 now
