### ISSUE TITLE
Small doc typo in rule disallowMultipleVarDecl

### ISSUE THREAD

**Issue by ValYouW** [jscs-dev/node-jscs#1845]
Hi,

The doc for rule `disallowMultipleVarDecl` states that the `allExcept` array can get a `required` value, while actually is should be `require`.
The doc:
https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/disallow-multiple-var-decl.js#L13

The code:
https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/disallow-multiple-var-decl.js#L99

**Comment by alawatthe** [comment]
Thanks for the report @ValYouW, do you want to send a pull request for this?
