### ISSUE TITLE
Allow any var that sourced from a require in disallowMultipleVarDecl

### ISSUE THREAD

**Issue by ValYouW** [jscs-dev/node-jscs#1848]
Hi,

In disallowMultipleVarDecl, when using allExcept require, what do you think about allowing all vars that sourced from a require call?
For example, this is currently failing on the `Emitter` var
```js
var fs = require('fs'),
    Emitter = require('events').EventEmitter;
```
How about allowing such cases?
I played a little bit with the rule and came up with this:
https://github.com/ValYouW/node-jscs/commit/999c71457ec30571223ebc1dae28014686fccb5b

Not sure it's 100% ok as I am not so familiar with esprima...

**Comment by markelog** [comment]
I think that would be a good idea, i think current behaviour could be considered as bug

**Comment by hzoo** [comment]
@ValYouW maybe paste some code and play around with http://astexplorer.net/ if you want to make a PR for it later

**Comment by ValYouW** [comment]
Ahh, sorry for all the commits mess...
Created a PR #1849 (with tests) lets discuss it there...
