### ISSUE TITLE
WordPress preset: set requireCamelCaseOrUpperCaseIdentifiers to ignoreProperties

### ISSUE THREAD

**Issue by paulschreiber** [jscs-dev/node-jscs#1851]
In the WordPress preset, I think it makes sense to set requireCamelCaseOrUpperCaseIdentifiers to ignoreProperties, as many WP-internal properties used in AJAX calls are `snake_case`.

**Comment by hzoo** [comment]
Ok that sounds fine and we were about to release a new version anyway.

Also did you see https://github.com/jscs-dev/node-jscs/issues/1811?
