### ISSUE TITLE
disallowAnonymousFunctions support for function expressions

### ISSUE THREAD

**Issue by ValYouW** [jscs-dev/node-jscs#1852]
Hi,

Currently function expression considered as anonymous, is there a way to except this case?
The reason I want to except this is because in the callstack the function would not be anonymous.
```js
var foo = function() {throw new Error('ERR');}
```
Output:
```
Error: ERR
    at foo (repl:1:29)
    at repl:1:2
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:203:10)
    at Interface._line (readline.js:532:8)
    at Interface._ttyWrite (readline.js:761:14)
    at ReadStream.onkeypress (readline.js:100:10)
    at ReadStream.emit (events.js:98:17)
```

**Comment by ValYouW** [comment]
Something like that: https://github.com/ValYouW/node-jscs/commit/989c319560094d7fa96a644bc7dc4c142c59776f

Add support for a `strict` option, if it is false then named function expression are allowed, for example the following is all valid if `strict = false`:
```js
var a = function() {}
module.exports.coo = function() {}
var Obj = {
 doo: function() {} 
}
Obj.eoo = function() {}
```

**Comment by hzoo** [comment]
I think we have http://jscs.info/rule/requireNamedUnassignedFunctions - does that cover it?

**Comment by ValYouW** [comment]
Great thx!
I searched for all the rules with `Anonymous`...

**Comment by hzoo** [comment]
yeah we need to work on naming. Also it would be nice if http://jscs.info/rules had fuzzy search

**Comment by ValYouW** [comment]
Well, I practiced my rule writing skills :)

**Comment by hzoo** [comment]
Is this good to close then?

**Comment by ValYouW** [comment]
Yes, thx!
