### ISSUE TITLE
Update "ignoreIfInTheMiddle" documentation for "requireCapitalizedComments" rule

### ISSUE THREAD

**Issue by AuthorProxy** [jscs-dev/node-jscs#1853]

**Comment by hzoo** [comment]
Thanks for the report! Do you want to make a PR for it? Otherwise @markelog should be able to - I guess he forgot https://github.com/jscs-dev/node-jscs/commit/cd3473bee7ee864e099f5f94262f78d76c3ac953

**Comment by markelog** [comment]
Didn't document, since i'm still hoping someone will come up with a better name

**Comment by hzoo** [comment]
Looks like your use case is `function test( /* \n option */ ) {}` for in a parameter list of a function?

**Comment by markelog** [comment]
Could be a `1 + /* yep! */ 2`

**Comment by hzoo** [comment]
so maybe an inlined comment - basically it's between some code?

**Comment by markelog** [comment]
yep

**Comment by markelog** [comment]
So, any ideas?

**Comment by hzoo** [comment]
not really - `"allExcept": "inlined"`
