### ISSUE TITLE
undefined is not a function with --auto-configure

### ISSUE THREAD

**Issue by gmoulin** [jscs-dev/node-jscs#1862]
Hello,

I get an error trying with the auto-configure jscs on a fresh install.

Versions installed:
windows 7 with cygwin
node v0.12.7
jscs 2.3.0

Using a preset is working fine.

<pre>g.moulin@EULAP048 /cygdrive/c/sources-demandware
$ jscs app_vilebrequin_assets/cartridge/static/default/_assets/js/global.js --auto-configure
C:\Program Files (x86)\nodejs\node_modules\jscs\lib\utils.js:115
    var start = path.substring(0, 2);
                     ^
TypeError: undefined is not a function
    at Object.exports.isRelativePath (C:\Program Files (x86)\nodejs\node_modules\jscs\lib\utils.js:115:22)
    at Object.exports.normalizePath (C:\Program Files (x86)\nodejs\node_modules\jscs\lib\utils.js:128:14)
    at Generator.generate (C:\Program Files (x86)\nodejs\node_modules\jscs\lib\config\generator.js:54:23)
    at cli (C:\Program Files (x86)\nodejs\node_modules\jscs\lib\cli.js:111:10)
    at Object.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\jscs\bin\jscs:41:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)</pre>

The install log:
<pre>
C:\Program Files (x86)\nodejs
└─┬ jscs@2.3.0
  ├─┬ babel-core@5.8.25
  │ ├── babel-plugin-constant-folding@1.0.1
  │ ├── babel-plugin-dead-code-elimination@1.0.2
  │ ├── babel-plugin-eval@1.0.1
  │ ├── babel-plugin-inline-environment-variables@1.0.1
  │ ├── babel-plugin-jscript@1.0.4
  │ ├── babel-plugin-member-expression-literals@1.0.1
  │ ├── babel-plugin-property-literals@1.0.1
  │ ├── babel-plugin-proto-to-assign@1.0.4
  │ ├── babel-plugin-react-constant-elements@1.0.3
  │ ├── babel-plugin-react-display-name@1.0.3
  │ ├── babel-plugin-remove-console@1.0.1
  │ ├── babel-plugin-remove-debugger@1.0.1
  │ ├── babel-plugin-runtime@1.0.7
  │ ├─┬ babel-plugin-undeclared-variables-check@1.0.2
  │ │ └── leven@1.0.2
  │ ├── babel-plugin-undefined-to-void@1.1.6
  │ ├── babylon@5.8.23
  │ ├── bluebird@2.10.2
  │ ├── convert-source-map@1.1.1
  │ ├── core-js@1.2.1
  │ ├─┬ debug@2.2.0
  │ │ └── ms@0.7.1
  │ ├─┬ detect-indent@3.0.1
  │ │ ├── get-stdin@4.0.1
  │ │ └── minimist@1.2.0
  │ ├── esutils@2.0.2
  │ ├── fs-readdir-recursive@0.1.2
  │ ├── globals@6.4.1
  │ ├─┬ home-or-tmp@1.0.0
  │ │ ├── os-tmpdir@1.0.1
  │ │ └── user-home@1.1.1
  │ ├─┬ is-integer@1.0.6
  │ │ └─┬ is-finite@1.0.1
  │ │   └── number-is-nan@1.0.0
  │ ├── js-tokens@1.0.1
  │ ├── json5@0.4.0
  │ ├─┬ line-numbers@0.2.0
  │ │ └── left-pad@0.0.3
  │ ├─┬ output-file-sync@1.1.1
  │ │ ├─┬ mkdirp@0.5.1
  │ │ │ └── minimist@0.0.8
  │ │ └── xtend@4.0.0
  │ ├── path-exists@1.0.0
  │ ├── path-is-absolute@1.0.0
  │ ├── private@0.1.6
  │ ├─┬ regenerator@0.8.35
  │ │ ├─┬ commoner@0.10.3
  │ │ │ ├── commander@2.5.1
  │ │ │ ├─┬ glob@4.2.2
  │ │ │ │ └─┬ minimatch@1.0.0
  │ │ │ │   ├── lru-cache@2.7.0
  │ │ │ │   └── sigmund@1.0.1
  │ │ │ ├── graceful-fs@3.0.8
  │ │ │ ├── iconv-lite@0.4.13
  │ │ │ ├── install@0.1.8
  │ │ │ └── q@1.1.2
  │ │ ├─┬ defs@1.1.1
  │ │ │ ├─┬ alter@0.2.0
  │ │ │ │ └── stable@0.1.5
  │ │ │ ├── ast-traverse@0.1.1
  │ │ │ ├── breakable@1.0.0
  │ │ │ ├── esprima-fb@15001.1001.0-dev-harmony-fb
  │ │ │ ├── simple-fmt@0.1.0
  │ │ │ ├── simple-is@0.2.0
  │ │ │ ├── stringmap@0.2.2
  │ │ │ ├── stringset@0.2.1
  │ │ │ ├── tryor@0.1.2
  │ │ │ └─┬ yargs@3.27.0
  │ │ │   ├── camelcase@1.2.1
  │ │ │   ├─┬ cliui@2.1.0
  │ │ │   │ ├─┬ center-align@0.1.1
  │ │ │   │ │ └─┬ align-text@0.1.3
  │ │ │   │ │   ├─┬ kind-of@2.0.1
  │ │ │   │ │   │ └── is-buffer@1.1.0
  │ │ │   │ │   ├── longest@1.0.1
  │ │ │   │ │   └── repeat-string@1.5.2
  │ │ │   │ ├── right-align@0.1.3
  │ │ │   │ └── wordwrap@0.0.2
  │ │ │   ├── decamelize@1.0.0
  │ │ │   ├─┬ os-locale@1.4.0
  │ │ │   │ └─┬ lcid@1.0.0
  │ │ │   │   └── invert-kv@1.0.0
  │ │ │   ├── window-size@0.1.2
  │ │ │   └── y18n@3.2.0
  │ │ ├── esprima-fb@15001.1.0-dev-harmony-fb
  │ │ ├─┬ recast@0.10.24
  │ │ │ ├── ast-types@0.8.5
  │ │ │ └── esprima-fb@15001.1.0-dev-harmony-fb
  │ │ └── through@2.3.8
  │ ├─┬ regexpu@1.3.0
  │ │ ├── esprima@2.6.0
  │ │ ├── regenerate@1.2.1
  │ │ ├── regjsgen@0.2.0
  │ │ └─┬ regjsparser@0.1.5
  │ │   └── jsesc@0.5.0
  │ ├── repeating@1.1.3
  │ ├── shebang-regex@1.0.0
  │ ├── slash@1.0.0
  │ ├─┬ source-map@0.4.4
  │ │ └── amdefine@1.0.0
  │ ├─┬ source-map-support@0.2.10
  │ │ └── source-map@0.1.32
  │ ├── to-fast-properties@1.0.1
  │ ├── trim-right@1.0.1
  │ └── try-resolve@1.0.1
  ├─┬ babel-jscs@2.0.4
  │ └─┬ lodash.assign@3.2.0
  │   ├─┬ lodash._baseassign@3.2.0
  │   │ └── lodash._basecopy@3.0.1
  │   ├─┬ lodash._createassigner@3.1.1
  │   │ ├── lodash._bindcallback@3.0.1
  │   │ ├── lodash._isiterateecall@3.0.9
  │   │ └── lodash.restparam@3.6.1
  │   └─┬ lodash.keys@3.1.2
  │     ├── lodash._getnative@3.9.1
  │     ├── lodash.isarguments@3.0.4
  │     └── lodash.isarray@3.0.4
  ├─┬ chalk@1.1.1
  │ ├── ansi-styles@2.1.0
  │ ├── escape-string-regexp@1.0.3
  │ ├─┬ has-ansi@2.0.0
  │ │ └── ansi-regex@2.0.0
  │ ├── strip-ansi@3.0.0
  │ └── supports-color@2.0.0
  ├─┬ cli-table@0.3.1
  │ └── colors@1.0.3
  ├─┬ commander@2.8.1
  │ └── graceful-readlink@1.0.1
  ├─┬ escope@3.2.0
  │ ├─┬ es6-map@0.1.1
  │ │ ├── d@0.1.1
  │ │ ├─┬ es5-ext@0.10.8
  │ │ │ ├── es6-iterator@2.0.0
  │ │ │ └── es6-symbol@3.0.0
  │ │ ├─┬ es6-iterator@0.1.3
  │ │ │ └── es6-symbol@2.0.1
  │ │ ├─┬ es6-set@0.1.2
  │ │ │ ├── es6-iterator@2.0.0
  │ │ │ └── es6-symbol@3.0.0
  │ │ ├── es6-symbol@0.1.1
  │ │ └── event-emitter@0.3.4
  │ ├─┬ es6-weak-map@0.1.4
  │ │ └── es6-symbol@2.0.1
  │ ├─┬ esrecurse@3.1.1
  │ │ └── estraverse@3.1.0
  │ └── estraverse@3.1.0
  ├── esprima@2.5.0
  ├── estraverse@4.1.0
  ├── exit@0.1.2
  ├─┬ glob@5.0.15
  │ ├─┬ inflight@1.0.4
  │ │ └── wrappy@1.0.1
  │ ├── inherits@2.0.1
  │ └── once@1.3.2
  ├─┬ htmlparser2@3.8.3
  │ ├── domelementtype@1.3.0
  │ ├── domhandler@2.3.0
  │ ├─┬ domutils@1.5.1
  │ │ └─┬ dom-serializer@0.1.0
  │ │   ├── domelementtype@1.1.3
  │ │   └── entities@1.1.1
  │ ├── entities@1.0.0
  │ └─┬ readable-stream@1.1.13
  │   ├── core-util-is@1.0.1
  │   ├── isarray@0.0.1
  │   └── string_decoder@0.10.31
  ├─┬ js-yaml@3.4.3
  │ ├─┬ argparse@1.0.2
  │ │ └── sprintf-js@1.0.3
  │ └── esprima@2.6.0
  ├─┬ jscs-jsdoc@1.2.0
  │ ├── comment-parser@0.3.0
  │ └── jsdoctypeparser@1.2.0
  ├─┬ jsonlint@1.6.2
  │ ├── JSV@4.0.2
  │ └─┬ nomnom@1.8.1
  │   ├─┬ chalk@0.4.0
  │   │ ├── ansi-styles@1.0.0
  │   │ ├── has-color@0.1.7
  │   │ └── strip-ansi@0.1.1
  │   └── underscore@1.6.0
  ├── lodash@3.10.1
  ├─┬ minimatch@2.0.10
  │ └─┬ brace-expansion@1.1.1
  │   ├── balanced-match@0.2.0
  │   └── concat-map@0.0.1
  ├── natural-compare@1.2.2
  ├── pathval@0.1.1
  ├─┬ prompt@0.2.14
  │ ├── pkginfo@0.3.0
  │ ├─┬ read@1.0.7
  │ │ └── mute-stream@0.0.5
  │ ├── revalidator@0.1.8
  │ ├─┬ utile@0.2.1
  │ │ ├── async@0.2.10
  │ │ ├── deep-equal@1.0.1
  │ │ ├── i@0.3.3
  │ │ ├── ncp@0.4.2
  │ │ └── rimraf@2.4.3
  │ └─┬ winston@0.8.3
  │   ├── colors@0.6.2
  │   ├── cycle@1.0.3
  │   ├── eyes@0.1.8
  │   ├── isstream@0.1.2
  │   └── stack-trace@0.0.9
  ├── reserved-words@0.1.1
  ├── resolve@1.1.6
  ├─┬ strip-bom@2.0.0
  │ └── is-utf8@0.2.0
  ├── strip-json-comments@1.0.4
  ├─┬ to-double-quotes@1.0.2
  │ └── get-stdin@3.0.2
  ├─┬ to-single-quotes@1.0.4
  │ └── get-stdin@3.0.2
  ├── vow@0.4.11
  ├─┬ vow-fs@0.3.4
  │ ├── glob@4.5.3
  │ ├── node-uuid@1.4.3
  │ └── vow-queue@0.4.2
  └── xmlbuilder@2.6.5
</pre>

**Comment by hzoo** [comment]
Hmm can reproduce. Looking at the docs (http://jscs.info/overview#cli), the cli format is `jscs --auto-configure path` so `jscs  --auto-configure app_vilebrequin_assets/cartridge/static/default/_assets/js/global.js` should work for you. That can be a workaround but maybe we should change it so it allows `jscs path --auto-configure` since that is similar to other options.

**Comment by mrjoelkemp** [comment]
That sounds like an issue in Commander @hzoo; I'd expect either form to work. The stacktrace hints at `path.substring` not existing – which doesn't make sense.

**Comment by gmoulin** [comment]
The command is working with ```jscs --auto-configure path``` format.
