### ISSUE TITLE
requireSpacesInsideParentheses not respecting allExcept containing single quote

### ISSUE THREAD

**Issue by gmoulin** [jscs-dev/node-jscs#1867]
Hello, 

thanks a lot for this superb tool.

I am having problem with spaces rules and quotes.
The example is for requireSpacesInsideParentheses rule but I got the same with any "space inside" rule.
Both the escaped double quote and the single quote are not taken into account.

The definition:
```json
	"requireSpacesInsideParentheses": {
		"all": true,
		"except": [ "{", "}", "'", "\"" ]
	}
```

The code:
```javascript
vbq.$body = $('body');
```

The result: (for single quote)
```bash
requireSpacesInsideParentheses: Missing space after opening round bracket at C:/sources-demandware/app_vilebrequin_assets/cartridge/static/default/_assets/js/collection-SS16.js :
    22 |    vbq.$body = $('body');
------------------------------^
requireSpacesInsideParentheses: Missing space before closing round bracket at C:/sources-demandware/app_vilebrequin_assets/cartridge/static/default/_assets/js/collection-SS16.js :
    22 |    vbq.$body = $('body');
------------------------------------^
```

**Comment by hzoo** [comment]
Thanks for reporting! What version of jscs are you using? @markelog

**Comment by gmoulin** [comment]
node v0.12.7
jscs 2.3.0

**Comment by markelog** [comment]
Hm, can't repro, what **jscs** version? Do you use gulp or grunt?

**Comment by gmoulin** [comment]
I tested with the command line (jscs directly), grunt and gulp.

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
