### ISSUE TITLE
Update 'fix' command to fix 'requireLineBreakAfterVariableAssignment'

### ISSUE THREAD

**Issue by chaucerbao** [jscs-dev/node-jscs#1868]
Running `jscs -x` on a script containing

```javascript
var a=1;var b=2;
```

is expected to produce

```javascript
var a = 1;
var b = 2;
```

The linter accounts for the rule correctly, the fixer just doesn't fix it.

**Comment by hzoo** [comment]
https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/require-line-break-after-variable-assignment.js#L72 is using `errors.assert` so it should be fixing it. What version are you using/what's your config?

**Comment by chaucerbao** [comment]
I'm using JSCS 2.3.0.

My config is [here](https://github.com/chaucerbao/project-skeleton/blob/master/.jscsrc), but you can simply use:

```json
{
  "requireLineBreakAfterVariableAssignment": true
}
```

```javascript
// test.js
var a=1;var b=2;
```

```sh
$ jscs --version
2.3.0
$ jscs -x test.js
Variable assignments should be followed by new line at test.js :
     1 |var a=1;var b=2;
---------------^
     2 |


1 code style error found.
$ cat test.js
var a=1;var b=2;
$
```

**Comment by hzoo** [comment]
Weird - definitely a bug - will check it out

**Comment by markelog** [comment]
It is a bug, but we can't fix it without supporting https://github.com/jscs-dev/node-jscs/issues/454

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
