### ISSUE TITLE
Issue with Spread operator when deconstructing

### ISSUE THREAD

**Issue by tjbenton** [jscs-dev/node-jscs#1869]
![screen shot 2015-10-15 at 12 37 27 pm](https://cloud.githubusercontent.com/assets/4776422/10522193/8be7b89a-7339-11e5-9ab5-9d1a52f7e0eb.jpg)

```js
export const base_config = {
  ...default_options,
  comments,
  annotations
}
```

This is a valid way of deconstructing one objects keys and adding them to another onto another

I've also opened an issue with JSHint for the same error https://github.com/jshint/jshint/issues/2718

**Comment by hzoo** [comment]
Using spread in an object is not es6 and isn't destructuring if that's what you mean. I think you mean a spread property right? https://github.com/sebmarkbage/ecmascript-rest-spread#spread-properties

That is experimental and in Stage 2 so you will need to use `esnext: true` if you aren't already in jscs (which uses babel in the background) which supports this.
