### ISSUE TITLE
jscs --fix breaks async function declarations

### ISSUE THREAD

**Issue by jaredly** [jscs-dev/node-jscs#1873]
```
const a = async function() {}
```
becomes
```
const a = asyncfunction() {}
```
which is a syntax error

**Comment by hzoo** [comment]
This is on latest right? Also what rules do you have on?

**Comment by hzoo** [comment]
Ok but in https://github.com/jscs-dev/node-jscs/pull/1745#issuecomment-137537924 - that PR didn't apply the fixes to the other rules - only FunctionExpression so that's probably what happened.

**Comment by hzoo** [comment]
Yeah there's so much duplication in those rules @mrjoelkemp. SpacesInNamedFunctionExpression, SpacesInAnonymousFunctionExpression, and SpacesInFunction, SpacesInFunctionExpression

**Comment by hzoo** [comment]
Might as well fix it now - should be fixed in 2.3.3
