### ISSUE TITLE
Enhancing maximumNumberOfLines

### ISSUE THREAD

**Issue by sivakumar-kailasam** [jscs-dev/node-jscs#1880]
`maximumNumberOfLines` accepts `Integer` in the current implementation.

would an additional `Object` value with,
- `value`: `Integer`,
- `exceptComments`: true (**default**: false)

 make sense?

**Comment by hzoo** [comment]
Yeah sounds good. Would probably be `allExcept: "comments"` to be consistent with the others. Would you want to make a PR? The core team is going to be mainly working on 3.0 issues

**Comment by sivakumar-kailasam** [comment]
:+1:  Sure!

**Comment by hzoo** [comment]
Feel free to make PR or comment here if you need help (or ask on [gitter](https://gitter.im/jscs-dev/node-jscs))
