### ISSUE TITLE
Default reporter results not visible in iTerm2

### ISSUE THREAD

**Issue by JGulbronson** [jscs-dev/node-jscs#1881]
On iTerm2, the reporter results aren't immediately visible, as shown below.

<img width="452" alt="screen shot 2015-10-17 at 11 26 20 am" src="https://cloud.githubusercontent.com/assets/2644780/10560520/0f8ecfe2-74c2-11e5-9468-bebc55be6ac0.png">

However, if I highlight the results, this appears.

<img width="447" alt="screen shot 2015-10-17 at 11 26 54 am" src="https://cloud.githubusercontent.com/assets/2644780/10560519/0f8e49e6-74c2-11e5-8c15-e96e5fea6bf0.png">

Not sure if this is an issue with the default reporter, or iTerm, but figured I'd report it.

**Comment by hzoo** [comment]
Sounds like an issue with the color scheme you are using (probably solarized). You can change the contrast in iTerm as a workaround for now.
