### ISSUE TITLE
Feature request: paddingNewLineAfterVariableDeclaration exclude exports

### ISSUE THREAD

**Issue by SimenB** [jscs-dev/node-jscs#1882]
I'd like to export constants, but this rule bitches about missing newlines between the exports (because they're declared as `const`s). Would it be possible to allow the rule to take an array of allowed words, or something like that?

```js
export const HENT_DATA = 'HENT_DATA';
export const HENT_METADATA = 'HENT_METADATA';
export const HENT_MELDINGER = 'HENT_MELDINGER';
export const LUKK_MELDINGER_AV_TYPE = 'LUKK_MELDINGER_AV_TYPE';
```

**Comment by hzoo** [comment]
Don't have to curse :stuck_out_tongue:. Maybe we can just make exported variables an exception? Either by default or an option `"allExcept": "exports"` or something.

**Comment by SimenB** [comment]
:grinning: 

Yeah, an option like that was what I was expecting to find when I looked up the docs, would be perfect :smile:

**Comment by hzoo** [comment]
Looking at the original issue - it seems to be a padding between variable declarations and other statements, not variable declarations themselves. Sounds like it could be ok by default then?

**Comment by SimenB** [comment]
Is `export` considered a declaration? In my mind it's just shorthand for exposing a declaration, so I'm with you on making it default to not reporting. As long as an option to enforce spaces are added, it should be fine as default, right?

**Comment by hzoo** [comment]
`export const a = 1`

<img width="332" alt="screen shot 2015-10-18 at 4 17 18 pm" src="https://github-cloud.s3.amazonaws.com/assets/588473/10566381/ba0725d6-75b3-11e5-9b5c-446169fff7ea.png">

**Comment by SimenB** [comment]
Ah, well there you go! :smile: 

OT: What tool are you using to inspect the AST? I've been trying to understand it for a couple of weeks, it's left me mostly confused :laughing:

**Comment by hzoo** [comment]
http://astexplorer.net/ - Really helps with debugging the rules and stuff.

Do you want to make the PR - doesn't seem too bad? otherwise I can

Looks like gota change something here: https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/require-padding-newline-after-variable-declaration.js#L62-L64

to either check the next token (since it's export) instead of `var, let, const`.
