### ISSUE TITLE
Feature request: requirePaddingNewLinesBeforeExport exclude scopes with only export

### ISSUE THREAD

**Issue by SimenB** [jscs-dev/node-jscs#1883]
We have a file with the following

```js
if (process.env.NODE_ENV === 'production') {
  module.exports = require('./setUpStore.prod');
} else {
  module.exports = require('./setUpStore.dev');
}
```

This warns because there is no padding newline above the export.

I'd like an option to provide the ability to not error if the export is the only thing in it's scope, or something similar.

**Comment by hzoo** [comment]
Do you think this should be a new rule value or by default?

**Comment by SimenB** [comment]
I think it should be default. I assume you enable that rule (at least we do) because we want the exports grouped by itself to make them more visible. But if they're the only thing in their scope, that's void. Right?

**Comment by hzoo** [comment]
Sounds it if it is the only statement in a block?

**Comment by SimenB** [comment]
Aye, I meant block, not scope.

**Comment by schempy** [comment]
@hzoo @SimenB If nobody is working on this I'd like to give it a shot.

**Comment by SimenB** [comment]
I'm not, go for it :smile:

**Comment by schempy** [comment]
Awesome! Thanks!

**Comment by hzoo** [comment]
FYI, we're goina switch `master` to be the 3.0 branch and move the current `master` to be 2.x after we release 2.9.0 (soon).
