### ISSUE TITLE
`return` should not be in the list of `spacedKeywords`, `function` also has an issue

### ISSUE THREAD

**Issue by Francisc** [jscs-dev/node-jscs#1885]
Hello,

I'm running JSCS with this rule enabled:
`disallowSpaceAfterKeywords: true`.

As such, JSCS is telling me that this:
`return obj`
should be:
`returnobj`.

Which is obviously invalid.
I expect setting `disallowSpaceAfterKeywords` to `true` to not affect `return` statements.

**Comment by Francisc** [comment]
I noticed that the same setting also indicated that `function test` is wrong and there should be no space between `function` and `test`.
```
Unexpected whitespace between function and test at ...
```

**Comment by hzoo** [comment]
Yep thanks for the report! I guess it's because we are using that list for a bunch of rules and usually people use the opposite rule of disallowSpaceAfterKeywords. This should definitely be fixed - the list is from https://github.com/jscs-dev/node-jscs/blob/master/lib/utils.js#L14

**Comment by Francisc** [comment]
Thanks for the super-quick reply, Henry.

**Comment by Francisc** [comment]
By the way, the opposite rule's (`requireSpaceAfterKeywords`) "Valid" example is kind of stupid:
```
return true;
```

I mean, `return true;` as opposed to what? `returntrue;` haha.

**Comment by hzoo** [comment]
Yeah we should change that too

**Comment by Francisc** [comment]
Thanks again.

**Comment by hzoo** [comment]
not sure why the example isn't just the opposite of the invalid one lol
