### ISSUE TITLE
jsDoc.requireDescriptionCompleteSentence and HTML description

### ISSUE THREAD

**Issue by ficristo** [jscs-dev/node-jscs#1886]
I would like to enable the rule jsDoc.requireDescriptionCompleteSentence but usually I write HTML description like this:
```
/**
 * Foo bar baz.<br />
 * Foo bar.
 * ...
*/
```
Can be allowed HTML tag with this rule?

**Comment by zxqfox** [comment]
Am I right that you suggest to strip html before checking?

**Comment by ficristo** [comment]
@zxqfox I was thinking to a whitelist of tags, but actually maybe to strip the html is easier/cleaner.

**Comment by ficristo** [comment]
This should have been fixed by https://github.com/jscs-dev/jscs-jsdoc/pull/186.
I didn't check; I'll open new issues if I'll find problems.

**Comment by zxqfox** [comment]
@ficristo Thank you! 😸
