### ISSUE TITLE
jsDoc: Unavailable tag example

### ISSUE THREAD

**Issue by ficristo** [jscs-dev/node-jscs#1887]
I write documentation using JSDoc3 which has an `example` tag, and JSCS doesn't recognize it.
I have jsDoc configured with `"checkAnnotations": "jsdoc3"`, if I remove this line JSCS works as expected. But `example` is a valid JSDoc3 tag.

**Comment by zxqfox** [comment]
Can you provide a code sample? https://github.com/jscs-dev/jscs-jsdoc/blob/master/lib/tags/jsdoc3.json#L26

You can try to use `"checkAnnotations": { "preset": "jsdoc3", "extra": { "example": true } }`

**Comment by ficristo** [comment]
ehm... actually the tag was `@example:`, note the colon at the end.
If I remove the colon it works as expected.
