### ISSUE TITLE
Missing `disallowSpaceAfterComma`

### ISSUE THREAD

**Issue by Francisc** [jscs-dev/node-jscs#1889]
Hello,

There's `disallowSpaceBeforeComma`, `requireSpaceBeforeComma` and `requireSpaceAfterComma`.
However, there isn't a `disallowSpaceAfterComma` property.

As an example, I would like to be able to make this invalid:
```
[1, 2, 3]
```
And his valid:
```
[1,2,3]
```

Is there a way to validate this given current options?

**Comment by hzoo** [comment]
We can just add the rule if it's not there.

**Comment by hzoo** [comment]
Do you want to do that PR? Otherwise I will

**Comment by Francisc** [comment]
I'll take a look now. Thanks.
