### ISSUE TITLE
`disallowAnonymousFunctions` and `esnext` aren't playing nice

### ISSUE THREAD

**Issue by Francisc** [jscs-dev/node-jscs#1890]
Hello,

I have `esnext` and `disallowAnonymousFunctions` set to `true`.
For this bit of code below:
```
class Test
{
	constructor(first,last)
	{
		this.first=first;
		this.last=last;
	}
	getName()
	{
		return `${this.first} ${this.last} is a name.`;
	}
}
```

I get two errors saying that `Anonymous functions need to be named`.
They are pointing between `constructor` and the opening parenthesis and between `getName` and opening parenthesis.

**Comment by Francisc** [comment]
Also, is there anyway to prevent IIFEs having to be named?
So for example `(function(){})()` isn't reported as invalid?

**Comment by hzoo** [comment]
We would need to add a method shorthand exception similar to https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/require-spaces-in-anonymous-function-expression.js#L139, and a iife exception

**Comment by Francisc** [comment]
Sounds like a good idea to me.
Thanks.

**Comment by Francisc** [comment]
Hm, the `shorthand` thing isn't very accurate though.
That's the way class methods are defined in ES2015, there's no longer way to do it.
And besides, `getName()` is named, it's not anonymous.

**Comment by hzoo** [comment]
That's what I was mentioning - in the AST itself it is a MethodDefinition that contains a value that is a FunctionExpression with no id (anonymous) - so it's confusing in that sense. We could just check if the parent is a MethodDefinition and `return;`

**Comment by Francisc** [comment]
Ah, OK. Sorry, misunderstood.

**Comment by gczene** [comment]
Hi,

Is there any update on this one? I've just bumped 1.4.0 and I have the same problem 

```
Missing space before opening round brace at modules/ember-commons/adapters/application.js :
    50 |   * @return {String}      dasherized path
    51 |   */
    52 |  pathForType(type) {
---------------------^
    53 |    return Ember.String.pluralize(Ember.String.dasherize(type));
    54 |  },
```

However in earlier version it worked as expected. 

Thanks

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
