### ISSUE TITLE
Feature Request: requireAlignedMultilineParams

### ISSUE THREAD

**Issue by JGulbronson** [jscs-dev/node-jscs#1894]
Currently it doesn't seem like there's a way to enforce indentation of parameters when a function takes up multiple lines. This rule would attempt to address the issue. I have a working implementation, and am posting this mainly so that I can see if it's something there's interest in, and for any feedback.

Option can be one of:
  - true
  - a number
  - "firstParam"

I've broken down the three cases, to show what's valid/invalid for each:

### when option === true

Parameters that continue past the first line of a function definition must be aligned with the body of the function. For example:

```javascript
function addThreeNumbers(one,
  two,
  three) {
  return one + two + three;
}
```

would be considered valid, as would

```javascript
function addThreeNumbers(one,
    two, three) {
    return one + two + three;
}
```

Note that there are no restrictions on the number of parameters per line, just that the first parameter on each line from the second on, is aligned with the body. This also applies for anonymous functions passed as an argument:

```javascript
beforeEach(inject(function(one, two, three,
    four, five, six,
    seven) {
    one = 1;
    // Do some more stuff
}));
```

Below is an example of code that would NOT pass the check

```javascript
function addThreeNumbers(one,
    two,
    three) {
  return one + two + three;
}
```

It will not pass, because the parameters are indented two spaces past the body of the function.

### when typeof option === 'number'

You can also pass a number to the rule, which will be the number of columns you want the params to be shifted right, relative to the body of the function. For example, if option is 2, the following is valid:

```javascript
function addThreeNumbers(one,
    two,
    three) {
  return one + two + three;
}
```

Note that passing 0, is also the same as passing true, which I'm not a huge fan of.

### when option === 'firstParam'

Here, each parameter of a newline must be in the same column as the first parameter. For example:

```javascript
function addThreeNumbers(one,
                                             two, three) {
  return one + two + three;
}
```

would be valid, while

```javascript
function addThreeNumbers(one,
  two,
  three) {
  return one + two + three;
}
```

would not.

Thanks for taking the time to read this. I hope we can work on getting a rule like this merged, and would appreciate any feedback you have on if you think it'll be useful, any functionality improvements, as well as your thoughts on the options.

Cheers

**Comment by hzoo** [comment]
The closest we have is: http://jscs.info/rule/validateAlignedFunctionParameters - although you are talking about indentation we have an issue for most of those - https://github.com/jscs-dev/node-jscs/issues/1866

**Comment by JGulbronson** [comment]
This is more a validateFunctionDefinitionIndentation rule... I don't think it's really covered by existing rules, and I know at work we found it quite useful to have. Plus the fact it's indentation means it can get automatically fixed, which is great (amazing job on that).

How would you recommend I proceed? It seems like that issue you referenced has a lot of stuff rolled up in to one, but this would be a more targeted PR.

**Comment by hzoo** [comment]
Well if you already have a PR then that's cool. I'm not sure about the different options

I think could think of a style like this as well

```js
function addThreeNumbers(
  a,
  b,
  c
) {
  return a + b + c;
}
```

**Comment by JGulbronson** [comment]
That'd actually be a combination of two rules

`validateAlignedFunctionParameters: true` would make sure the parameters and parens are each on their own line.

The proposed new rule, `requireAlignedMultilineParams: true` would check that the parameters are aligned with the body of the function. In your example, they are, and it'd pass!

I think it'l compliment the existing rules well, and hope to have a PR up during this week.
