### ISSUE TITLE
requireNewLinesInBlocks for multiline\big stringline

### ISSUE THREAD

**Issue by cybermerlin** [jscs-dev/node-jscs#1899]
if simple line:
```
if (true){ doSomething(); }
```
then leave as is.

**But** if more than one line:
```
if (true) { doSomething();
    doSomethingElse(); }
```
then needs formatting to:
```:javascript
if (true) {
    doSomething();
    doSomethingElse();
}
```

The same goes for the big line

**Comment by hzoo** [comment]
Most of the team will be busy working on 3.0 issues instead of adding new rules/options. Sounds like you want a new option to ignore if the block is a single line. maybe `allExcept: "singleLine"` or something. Would you like to make a PR?

**Comment by cybermerlin** [comment]
good

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
