### ISSUE TITLE
If pairing brackets are not in same line, then make sure the opening bracket end is last character, and closing bracket is the first character.

### ISSUE THREAD

**Issue by shobhitg** [jscs-dev/node-jscs#190]
Its hard to explain in words, but here I try...

Here is the example:

This should be invalid:
```javascript
if (x < 0) { x++;
    func1 ( foo );   // this should be okay
    func2 ( foo,
            bar
    );
} else { x--;
}
```
This should be valid:
```javascript
if (x < 0) {
    x++;
    func1 ( foo );
    func2 (
        foo,
        bar
    );
} else {
    x--;
}
```
If the pair of brackets are in same line, then everything is fine.

If the pair of brackets are not in same line: then the opening brackets should be the last character in its line; and the closing bracket should be the first character in its line.

Same concept applies for all types of brackets.... i.e.  () {} []

**Comment by markelog** [comment]
This issue has been open more than a month without supported PR for it. 

Unfortunately, we don't have the resources to implement rules that could not be included in any of the supported [presets](https://github.com/jscs-dev/node-jscs/tree/master/presets) (if it could be, please point that out).

However, if you or anybody else submit PR for it, we will gladly consider it.
