### ISSUE TITLE
Allow `opt_varName` like variables

### ISSUE THREAD

**Issue by tonyganch** [jscs-dev/node-jscs#1900]
I would like to make a pr that allows naming optional parameters in Google style: `opt_varName`.
What is an appropriate way of reflecting this in config?
As an example: `"requireCamelCaseOrUpperCaseIdentifiers": "optionalSnakeCase"` or `"requireCamelCaseOrUpperCaseIdentifiers": "allowOpt"`.

**Comment by hzoo** [comment]
If you need to add it to your own preset you can override the rule yourself http://jscs.info/overview#preset - with a value of `null` or `false` to disable the rule completely, or choose a different value.

As a separate issue, it seems like you are proposing another option - how would we determine what should or should not be allowed? Might as well add a list of exceptions.

**Comment by tonyganch** [comment]
I'm proposing an extension to existing `requireCamelCaseOrUpperCaseIdentifiers`.
[Google Code Style](http://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml?showone=Naming#Naming) says:

> Optional function arguments start with opt_.
> Functions that take a variable number of arguments should have the last argument named var_args.

So what I'm proposing is adding a new acceptable value for `requireCamelCaseOrUpperCaseIdentifiers` option which will check that variables are named using camelCase, but also allow `opt_` prefix and `var_args` variable name.
I'm also proposing to include that new value in google preset.

**Comment by tonyganch** [comment]
So, for example, these will be valid:
```
variableName
EnumName
CONST_NAME
opt_variableName
var_args
```
And these will be invalid:
```
variable_name
var_arguments
```

**Comment by markelog** [comment]
How about: 
```js
requireCamelCaseOrUpperCaseIdentifiers: {
  value: '...'
  allExcept: [...]
}
```
?

Would be a good opportunity to try out [is-my-json-valid](https://github.com/mafintosh/is-my-json-valid) so you wouldn't go crazy writing all those checks in `configure`.

**Comment by tonyganch** [comment]
@markelog, how should I write `allExcept` in this case for `opt_thereCanBeAnything`?

**Comment by markelog** [comment]
How about glob patterns? So we wouldn't be tied to specific cases, but could be more generic, i imagine such conditions also could be used in other styles.

Also, it would be cool to justify such option in docs

**Comment by tonyganch** [comment]
@markelog, do I get it right?
```
requireCamelCaseOrUpperCaseIdentifiers: {
  value: true,
  allExcept: ['opt_*', 'var_args']
}
```

**Comment by markelog** [comment]
Looks good to me

**Comment by tonyganch** [comment]
@markelog, okay, thank you!
