### ISSUE TITLE
Bug: Sparse arrays in any rules with spacing and commas

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1909]
Example: `["foo", , “bar”]`

I know there's an issue for
- [x] `disallowSpaceBeforeComma`
- [x] `disallowSpaceBeforeBinaryOperators`
- [x] `disallowSpaceAfterComma`
- [x] `disallowSpaceAfterBinaryOperators`

// not an issue
- [x] `requireSpaceBeforeComma`
- [x] `requireSpaceAfterComma`

maybe
- [ ] `disallowCommaBeforeLineBreak`
- [ ] `requireCommaBeforeLineBreak`

**Comment by markelog** [comment]
What about `(require | disallow)CommaBeforeLineBreak` rules?

**Comment by hzoo** [comment]
Looks like a fix was only needed for disallow space. Also I don't think it's an issue for `disallowCommaBeforeLineBreak` or `requireCommaBeforeLineBreak` so we can close this still

**Comment by markelog** [comment]
```js
Commas should be placed on the same line as value at test.js :
     1 |var a = [
     2 |    1
     3 |    ,
-------------^
     4 |]
```

Why not?

**Comment by hzoo** [comment]
I didn't test it I just assumed.
