### ISSUE TITLE
validateIndentation passes for code that is too deeply indented

### ISSUE THREAD

**Issue by ngeor** [jscs-dev/node-jscs#1919]
Normally, we would indent a function's code with one level of indentation (lets say we use 4 spaces):

```
function answer() {
    var result = 42;
    return result;
}
```

This however also passes validation: lines are indented with 6 spaces and the last closing brace with 2 spaces:

```
function answer() {
      var result = 42;
      return result;
  }
```

You can basically indent as much as you like, as long as you drop the indentation on the last closing brace consistently:

```
function answer() {
            var result = 42;
            return result;
        }
```

**Comment by cybermerlin** [comment]
+ #1912

**Comment by jontayesp** [comment]
I've realized that validateIndentation doesn't actually care if your code is indented at the proper level, just that indentation aligns with with the correct number of spaces/tabs. So indenting too little or too much is validated ok, so long as its divisible by validateIndentation.

And --fix gives unexpected results when trying to cleanup. This makes indentation validation really useless if you care about block alignment.

Doing a search on validateIndentation on the issues gives lots of results. I would say this is a critical issue hurting lots of users right now.

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
