### ISSUE TITLE
Contributing manual

### ISSUE THREAD

**Issue by cybermerlin** [jscs-dev/node-jscs#1925]
Can you tell me please, how to check whether the work my changes?
I do not know how to build this project to run it under node.js.
And please write how to compile the project for run from the console.
Vielen Dank!

**Comment by hzoo** [comment]
Could you write your issue/request in english?

**Comment by cybermerlin** [comment]
Can you tell me please, how to check whether the work my changes?
I do not know how to build this project to run it under node.js.
And please write how to compile the project for run from the console.

**Comment by mdevils** [comment]
Checkout the project, then

```
cd node-jscs
npm install
npm test
```

**Comment by hzoo** [comment]
https://github.com/jscs-dev/node-jscs/blob/master/CONTRIBUTING.md#setting-up-your-environment

**Comment by hzoo** [comment]
If there is something missing from CONTRIBUTING.md then let us know but check that out first. Thanks!

**Comment by markelog** [comment]
If that information is not enough, please ping us up!
