### ISSUE TITLE
Using path.extname to detect whether config path is file or folder fails for .jshintrc

### ISSUE THREAD

**Issue by tobobo** [jscs-dev/node-jscs#1932]
As of recently, before loading an additional rule, `extname` is used to check to see if the config path has an extension, and if it does not, it assumes it to be a folder (https://github.com/jscs-dev/node-jscs/commit/7d11461b773cbf107f903fcb817530106103adf4).

Unfortunately, dotfiles are reported by node to have no extension (https://nodejs.org/api/path.html#path_path_extname_p), and therefore jscs assumes the path to .jscsrc to be a folder.

This prevents the loading of additional rules by adding a .jshintrc folder in the middle of the path name after the project root.

**Comment by markelog** [comment]
Could you check it with current master?

**Comment by tobobo** [comment]
@markelog it's fixed, thank you!

**Comment by markelog** [comment]
Releasing tomorrow
