### ISSUE TITLE
HTML reporter

### ISSUE THREAD

**Issue by boldfacedesign** [jscs-dev/node-jscs#1933]
I've written a simple html reporter that creates a pretty html file for easy viewing in browser. I'm using this for my CI build. Would this be something you're interested in if I create a merge request?

**Comment by markelog** [comment]
Hm, other linters do not include it by default and we have 8 already. I'd say it would be interesting to see it as a plugin first.

**Comment by boldfacedesign** [comment]
Plugin sounds like a good idea. I'll post back later with details.
