### ISSUE TITLE
Allow multiple .sjcsrc files

### ISSUE THREAD

**Issue by danwellman** [jscs-dev/node-jscs#1934]
I have a .jscsrc file at the root of my project, which is cool, but it would be nice to be able to drop additional .jscsrc files into sub-directories to allow different rules to be enabled/disabled on a per-directory basis

**Comment by markelog** [comment]
Yeah, we have a long standting ticket about that - https://github.com/jscs-dev/node-jscs/issues/1106, if you would help us with it, it would be great!

**Comment by danwellman** [comment]
Sorry for the dupe! I'll take a look at the other ticket :)
