### ISSUE TITLE
validateLineBreaks prevent mixed LineBreaks

### ISSUE THREAD

**Issue by ketamin** [jscs-dev/node-jscs#1936]
Hello,
I work in an environment, where both systems commit their files: Linux and Windows.
Unfortunately eol-style:system for committing files is used since approx 100 years.
That is why we could use validateLineBreaks to accept everything, but to check for mixed Line-Breaks.
Can you please extend that feature, thanks.

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
