### ISSUE TITLE
disallowSpace(After|Before)Comma

### ISSUE THREAD

**Issue by Francisc** [jscs-dev/node-jscs#1944]
Hello,

The rules were changed to allow spaces in arrays with empty slots and I was wondering why.
I believe this is wrong since I expect there to be no spaces allowed.
At least, that should be the default behavior with an `"allExcept"` option to allow such things.

What do you think?

**Comment by Francisc** [comment]
To give an example:
This should not be allowed for `true`:
```
[, , ,]
```

**Comment by hzoo** [comment]
I made an issue for it https://github.com/jscs-dev/node-jscs/issues/1909. What should be allowed then instead of `[1, ,2]`, like `[1,,2]`?

**Comment by Francisc** [comment]
Yeah, there should be *no* spaces after or before commas if this rule is enabled.
