### ISSUE TITLE
There should be an opposite rule to requireSpacesInGenerator

### ISSUE THREAD

**Issue by Francisc** [jscs-dev/node-jscs#1945]
So yeah, there should be `disallowSpacesInGenerator`.

**Comment by markelog** [comment]
Yeah, wanna do it?

**Comment by Francisc** [comment]
Oups, GitHub is awful with notifications.
Sure. I'll give it a shot soon.

**Comment by Francisc** [comment]
Would you say this rule also needs both before and after rules?
I was thinking that it could just take a boolean and enforce no spaces before.

For example, this would be valid:
```JavaScript
function* aGenerator(){}
```

And this would be invalid:
```JavaScript
function * aGenerator(){}
```

If you think we should allow this rule to validate / invalidate this as well, let me know:
```JavaScript
function*aGenerator(){}
```

**Comment by markelog** [comment]
> Would you say this rule also needs both before and after rules?

This could be done with options, but if you would want it this way, we would need such options for the opposite rule too.

**Comment by Francisc** [comment]
I don't understand.
`requireSpacesInGenerator` takes an object which conditions spaces before and after the asterisk.
My proposal was to have the opposite rule, `disallowSpacesInGenerator`, only take a boolean value which checks spaces before the asterisk, since it doesn't really make sense to not have a space after it.

**Comment by markelog** [comment]
Well, if we do that, rules would be different in their behaviour, ideally, they should be full opposite of each other, if one rule require something the other should disallow it in the same occurrence

**Comment by Francisc** [comment]
I agree with that.
Arguably, the `requireSpacesInGenerator` should only require them *before*.
Seems silly to require them after.
It's like saying `function name(){}` is valid for a require-spaces rule and `functionname(){}` is valid for a disallow-spaces rule.

**Comment by markelog** [comment]
```js
```

**Comment by Francisc** [comment]
OK, I'll make `disallowSpacesInGenerator` take an object, just like `requireSpacesInGenerator`.

**Comment by Francisc** [comment]
Done.
