### ISSUE TITLE
separate validateQuoteMarks rule for jsx

### ISSUE THREAD

**Issue by DanLipsitt** [jscs-dev/node-jscs#1953]
There should be a way to use single quotes in js and double quotes in jsx.
See jscs-dev/babel-jscs#12.

**Comment by markelog** [comment]
New value for it, would be fine, would you like try to implement it?

**Comment by DanLipsitt** [comment]
I'm probably not the right person to implement this one. Does jscs already know which context it's in (js vs jsx)?

**Comment by josh18** [comment]
I assume this fix just ignores quotes in jsx rather than letting you choose a type of quote to validate?

**Comment by markelog** [comment]
Yep
