### ISSUE TITLE
disallowNewlineBeforeBlockStatements and multiline statements

### ISSUE THREAD

**Issue by ficristo** [jscs-dev/node-jscs#1956]
Usually I write code like this:
`if (conditions) {`
so I enabled the rule `disallowNewlineBeforeBlockStatements`.

But sometimes, if the conditions are too long, I would like to enforce the brace to new line:
```javascript
if (cond1 && cond2 &&
    cond3...)
{
```

The same thing should work for `for`
```javascript
for (inits;
     conds;
     steps)
{
```

and in this case would be nice to enforce that `inits`, `conds` and `steps` are on different lines.

**Comment by markelog** [comment]
```js 
if (cond1 && cond2 &&
    cond3...)
```
Check it out - http://jscs.info/rule/requireOperatorBeforeLineBreak

> The same thing should work for for

Not sure by what condition we could decide if body is too long.

**Comment by ficristo** [comment]
Sorry I should have be clearer. I'm am not interested in the operators but in the curly bracket.
Usually I want it on the same line of the round bracket but when the conditions are on different lines (that was what I meant with too long...) they should be on a new line.

So if I write the if like this:
```javascript
if (a==b &&
    b==c)
```
the curly bracket should be on new line:
```javascript
if (a==b &&
    b==c)
{
```

Please reopen.

**Comment by markelog** [comment]
Would you like to try to implement it?

**Comment by ficristo** [comment]
@markelog I have some trouble to run `npm test` on my windows machine so If I resolve them maybe I can take a look in the future.

**Comment by ficristo** [comment]
Initially I thought to implement this as an exception for both `disallowNewlineBeforeBlockStatements` and `requireNewlineBeforeBlockStatements`, but maybe it is confusing?
If I'll implement this with a new rule how should it interact with the previous `disallowNewlineBeforeBlockStatements` and `requireNewlineBeforeBlockStatements`?
@markelog

**Comment by ficristo** [comment]
@markelog @hzoo gentle ping for previous comment.

**Comment by ficristo** [comment]
Any ideas for the prevoius comments?

**Comment by hzoo** [comment]
We want rules to be independent of each other - I think its fine to make it as an exception. Basically in the test part of the `IfStatement` or anything like that is multiline, then the brace should be on a new line

**Comment by ficristo** [comment]
Is there an api to get the position of the round braces?
I tried something like this but seems very fragile...
```javascript
file.iterateNodesByType(['BlockStatement', 'ClassBody'], function(node) {
    var prevToken_ = file.getFirstNodeToken(node);        // {
    var prevToken2_ = file.getPrevToken(prevToken_);      // )

    var parentNode = node.parentNode;
    var nextToken_ = file.getFirstNodeToken(parentNode);  // function
    var nextToken2_ = file.getNextToken(nextToken_);      // foo
    var nextToken3_ = file.getNextToken(nextToken2_);     // (
});
```
The code tested was this:
```javascript
function foo()
{
    var str = "";
};
```

**Comment by markelog** [comment]
There is `find(Next | Prev)Token(token, type, value)`
