### ISSUE TITLE
Preset: remove yandex preset

### ISSUE THREAD

**Issue by ikokostya** [jscs-dev/node-jscs#1958]
We want to remove `yandex` preset from `jscs`.  Can we make this changes in version `2.6.0`?

/cc @markelog  @tarmolov

**Comment by ikokostya** [comment]
Explanation: now [yandex codestyle](https://github.com/yandex/codestyle) isn't official, i.e. some teams in yandex doesn't use this preset or use it with overrides. Therefore my suggestion on creating repository for `jscs-preset-yandex` npm package in `yandex` organization on github was rejected. 

In this situation we decided rename codestyle and move npm package for preset to another repo [jscs-preset-awesome](https://github.com/ymaps/jscs-preset-awesome). Version `1.x` of `jscs-preset-awesome` is backward compatible with `yandex` preset. 

Migration guide for moving from `yandex` preset:
1. `npm install --save-dev jscs-preset-awesome`
2. Replace 

```json
{
    "preset": "yandex"
}
```
to

```json
{
    "preset": "awesome"
}
```
in `.jscsrc` file.

**Comment by markelog** [comment]
Said news, but now surprise :/

> Can we make this changes in version 2.6.0?

It would break backcompat, so only in 3.0

**Comment by markelog** [comment]
Fixed via https://github.com/jscs-dev/node-jscs/commit/25b92408ae7f5410bf930e2497814538f034270f

**Comment by ikokostya** [comment]
Actual link to package with preset https://github.com/ymaps/codestyle/tree/master/packages/jscs-preset-loris
