### ISSUE TITLE
No else after return

### ISSUE THREAD

**Issue by ficristo** [jscs-dev/node-jscs#1960]
Is there a way to enforce this rule?
For example:
```javascript
// Valid
if (cond) {
  return true;
}

return false;
```
```javascript
// Invalid
if (cond) {
  return true;
} else {
  return false;
}
```

**Comment by hzoo** [comment]
I don't think so other than https://github.com/jscs-dev/node-jscs/issues/1223

**Comment by markelog** [comment]
If you want to take a shot at it, it would be great!
