### ISSUE TITLE
The rule "requireSpacesInsideObjectBrackets" doesn't cover the case of `{}`

### ISSUE THREAD

**Issue by justinmchase** [jscs-dev/node-jscs#1964]
I have this set in my jscsrc file:
```
{
  "requireSpacesInsideObjectBrackets": "all"
}
```

Yet this code doesn't produce any errors:
```
var abc = {};
```

If there are any keys in the object then it validates as expected but I would expect this to be invalid, and for the following to be valid:
```
var abc = { };
```

Is this a bug or intentional?

**Comment by hzoo** [comment]
Looks to be intentional: `// Don't check empty object`

https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/require-spaces-inside-object-brackets.js#L105-L108

**Comment by justinmchase** [comment]
Good eye, thanks. I kind of think that "all" should include this case and there should be an option to not have it.

**Comment by markelog** [comment]
Logical! But would be kinda weird to check such case, but it is easy to implement such rule yourself and use it as a plugin
