### ISSUE TITLE
Autofix fixes disabled rules

### ISSUE THREAD

**Issue by difosfor** [jscs-dev/node-jscs#1967]
**Steps to reproduce:**
- Have a `.jscsrc` file
- Have a file with two errors
  - Error "A" (e.g: for `disallowMultipleSpaces`)
  - Error "B" (e.g: for `disallowMultipleVarDecl`)
- Run jscs to verify you see errors A and B
- Disable the rule that was producing error A (e.g: `/*jscs:disable disallowMultipleSpaces*/`)
- Run jscs to verify you only see error B
- Run jscs again but with `--fix` option

**Expected output:**
File unchanged.

**Actual output:**
File changed with occurrences of A autofixed in spite of the corresponding rule being disabled there.

**Comment by difosfor** [comment]
PS: Note that when you also disable the rule for error B (making the file error free) that `jscs --fix file.js` will then leave the file alone as you would expect.

**Comment by markelog** [comment]
For the file -
```js
var x = "hello",
    b = 3;

/*jscs:disable disallowMultipleSpaces*/
function  y() {}
```
I see no applied fix

**Comment by difosfor** [comment]
Did you also have disallowMultipleVarDecl in your .jscrc file? When you disable all errors this is not an issue. You need to disable one while still leaving the other.

**Comment by markelog** [comment]
Sorry for late response, yeah, i did. Config looks like this - 
```js
{
    "disallowMultipleSpaces": true,
    "disallowMultipleVarDecl": true
}

```

**Comment by markelog** [comment]
Can't repro
