### ISSUE TITLE
Bad "Mixed tabs and spaces" warning when a line starts with block comment

### ISSUE THREAD

**Issue by MatmaRex** [jscs-dev/node-jscs#1968]
Consider the following snippet:

```js
foo(
	'parameter',
	/* bar */ false
);
```

(`foo` is a poorly written function that takes boolean parameters, and the `/* bar */` comment is meant to explain what this `false` means. A faux named parameter, if you will.)

JSCS points to the line with the comment, claiming  "Mixed tabs and spaces", as if the comment was not there at all.

A simple workaround is to remove the space:
```js
foo(
	'parameter',
	/* bar */false
);
```
…or move the comment elsewhere.

(I am using the "wikimedia" preset.)

**Comment by markelog** [comment]
Hm, can't repro it, what version of do you use? Can you run jscs with `--verbose` flag?

**Comment by MatmaRex** [comment]
JSCS 2.5.1. Note that you have to set `{ "disallowMixedSpacesAndTabs": true }` in .jscsrc (or use a preset that has it). Note also that my snippet is indented with tabs and not spaces (GitHub mangles it… I didn't notice before).

`jscs --verbose` output:
```
disallowMixedSpacesAndTabs: Mixed spaces and tabs found at test.js :
     1 |foo(
     2 | 'parameter',
     3 | /* bar */ false
--------^
     4 |);


1 code style error found.
```
