### ISSUE TITLE
Can't disallow space in shorthand function declaration

### ISSUE THREAD

**Issue by jlowcs** [jscs-dev/node-jscs#1970]
With the following config:

```javascript
{
	"disallowSpacesInFunctionDeclaration": {
		"beforeOpeningRoundBrace": true
	},
	"requireSpacesInAnonymousFunctionExpression": {
		"beforeOpeningRoundBrace": true
	},
	"esnext": true
}
```

The following code outputs a warning:
```javascript
{
	foo() {
	}
}
```

The warning: "Missing space before opening round brace".

It seems jscs considers the function as anonymous. Maybe a new option is needed for shorthand function declaration?

Might be linked to https://github.com/jscs-dev/node-jscs/issues/1890

**Comment by markelog** [comment]
I guess this is one of the most confusing addition to ES6, those methods, are in fact anonymous functions, see discussion in - https://github.com/jscs-dev/node-jscs/issues/1671#event-438122364

If you would like to send us pull to include exceptions to this rule, we would welcome it.
