### ISSUE TITLE
Current babel-core version deprecated (Known issue)

### ISSUE THREAD

**Issue by JSMike** [jscs-dev/node-jscs#1972]
I'm receiving the following message when installing jscs

```
npm WARN deprecated babel-core@5.8.33: Babel 5 is no longer being maintained. Upgrade to Babel 6.
```
Babel 6.0.0 was released on October 29th, 2015. http://babeljs.io/blog/2015/10/29/6.0.0/

Updated based on comment from @hzoo

**Comment by hzoo** [comment]
There are breaking changes so it won't just work. JSCS only uses babel for the parser so its fine just using babel 5 for now. Also we are switching to using cst which will just use babylon.

**Comment by markelog** [comment]
@hzoo 

> Also we are switching to using cst which will just use babylon.

Yeah, this week i will start working on it, if you not beat me to it :-)

**Comment by hzoo** [comment]
Similar to https://github.com/jscs-dev/babel-jscs/issues/24. We should be able to remove babel-core and replace it for now.

**Comment by hzoo** [comment]
We should just inline the types again instead of `var types = require('babel-core').types;`
