### ISSUE TITLE
Unable to suppress 'Unexpected Illegal Token' error

### ISSUE THREAD

**Issue by justinmchase** [jscs-dev/node-jscs#1973]
I have a JS file which is pre-processed (for better or worse). It has code like this in it:

```
function init() {
  // jscs: disable
  @@CODE
  // jscs: enable
}
```

When I run jscs on it I get this error:
> Unexpected token ILLEGAL at ...

My understanding is that it is that it is parsing the entire file and the disable/enable flags are only applied to rule processing much later. Correct?

Other than redesigning our template system, is there an easy way to fake out the jscs parser to read this successfully? Hacks welcome.

**Comment by hzoo** [comment]
Yes if it could understand the token then it wouldn't need to error in teh first place

Similar to https://github.com/jscs-dev/node-jscs/issues/1655, https://github.com/jscs-dev/node-jscs/issues/1156

**Comment by justinmchase** [comment]
Is there a solution or just proposed features / fixes for now? I will close this for now since it seems to be a duplicate.

**Comment by hzoo** [comment]
Not sure if there is a solution right now

**Comment by justinmchase** [comment]
Thanks, I was actually able to adjust my pre-processor to replace
```
// @@CODE
```

Instead, which happens to work in just my scenario. I can see a need for this feature in general in jscs but I'm unblocked for now. Thanks.

**Comment by zxqfox** [comment]
If you still want to check this file, I'd rename it (or just ignore), but copy to file.tmpl.js with e.g. empty blocks (as you do it in real life) before checking, and rm after.

But better to change syntax to replace multiline comment blocks like `/* @@code */`.

**Comment by justinmchase** [comment]
@zxqfox :metal:
