### ISSUE TITLE
Organize Rule Listing

### ISSUE THREAD

**Issue by danny-andrews** [jscs-dev/node-jscs#1975]
The flat list of rules listed on the jscs [website](http://jscs.info/rules) is overwhelming and unnecessarily long. Would it make sense to condense converse rules (e.g. requireAnonymousFunctions/disallowAnonymousFunctions) into one rule which can be set to true, false, or default (null)? At the very least, we should provide some visual organization in the listing. Examples would include listing by language construct (conditional, function, etc.) or by rule type (naming, comments, spacing, etc.).

**Comment by hzoo** [comment]
> Would it make sense to condense converse rules (e.g. requireAnonymousFunctions/disallowAnonymousFunctions) into one rule which can be set to true, false, or default (null)?

This would require a breaking change to the config and would be in 3.0 - covered in "new structure" in https://github.com/jscs-dev/node-jscs/issues/1854.

And yes it would be a good idea to organize the website rules - we have a repo for that https://github.com/jscs-dev/jscs-dev.github.io/issues. Right now we have https://github.com/jscs-dev/node-jscs/blob/master/grouping.json but we haven't done anything with it on the website yet.

**Comment by markelog** [comment]
So @danny-andrews, would you help us out?

**Comment by danny-andrews** [comment]
Sure, I've already got a start on some categories. I'll make a gist soon!

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
