### ISSUE TITLE
jscs startup takes ~1.5s

### ISSUE THREAD

**Issue by toupeira** [jscs-dev/node-jscs#1996]
This is on a recent i7 quad-core with SSD and plenty of RAM, running Debian sid:

```sh
$ time nodejs --version
v4.2.2

real    0m0.006s
user    0m0.004s
sys     0m0.000s
$ time npm --version
v1.4.21

real    0m0.469s
user    0m0.480s
sys     0m0.008s
$ mkdir /tmp/jscs
$ cd /tmp/jscs
$ time node --prof /usr/local/bin/jscs --version
2.6.0

real    0m1.749s
user    0m1.768s
sys     0m0.160s
```

I did the test in an empty directory because I first noticed the issue when running `jscs` in a large(ish) project and wanted to see if it makes a difference.

See the [attached log output](https://github.com/jscs-dev/node-jscs/files/47667/v8.log.txt) from `node --prof`, you can analyze it by installing [`node-tick`](https://github.com/sidorares/node-tick) and running `node-tick-processor v8.log.txt`.

`strace` also shows a *lot* of syscalls for the files below `node_modules`, so I guess that has something to do with it.  Not sure how much of this can be realisitically optimized, the slow startup time of `npm` itself suggests a more general issue here :)

**Comment by hzoo** [comment]
I think npm3 should help if the issue is checking node_modules (nested dependencies?)

**Comment by toupeira** [comment]
@hzoo thanks for the hint, on first look it doesn't seem to make a difference:

```sh
$ time npm --version
3.5.0

real    0m0.462s
user    0m0.472s
sys     0m0.012s
$ time node_modules/jscs/bin/jscs --version
2.6.0

real    0m1.597s
user    0m1.612s
sys     0m0.056s
```

This time I ran the test inside the project folder, since I could just quickly blow away `node_modules` there and reinstall. Some dependencies are still nested though because of version differences:

```sh
$ ls node_modules/jscs/node_modules/
ansi-regex  chalk      esprima     glob      js-yaml    resolve     supports-color
argparse    commander  estraverse  has-ansi  minimatch  strip-ansi
```

Can somebody else confirm faster startup time with npm3? In that case I wouldn't mind closing this issue.

**Comment by TheSavior** [comment]
Processes typically do a lot of work in node_modules because they require a bunch of stuff and the system has to read and access those files to start. If there are files being accessed that aren't part of the JSCS dep tree, that would be a sign of a problem.

Also, are you running jscs-babel? Babel has a lot of requires itself and might be doing a lot of work to start up.

If you can run 
```
strace -e trace=open,close,read,write,connect,accept YOUR_COMMAND > output.txt
```

And post a gist with that text file (make sure to scrub it first!) we can probably get a better idea of what file access is happening during startup.

**Comment by toupeira** [comment]
@TheSavior I don't use Babel directly but `babel-jscs` is a fixed dependency of `jscs` so it does get loaded.

You can find the gist at https://gist.github.com/toupeira/cbf30a75bb9c0f84a465, generated with `strace -e trace=open jscs --version 2> jscs-strace.txt` (the other syscalls don't seem to be relevant here). There's no access outside of the `jscs` dependencies.

I think I'll just close this issue, sorry for the noise ;-)
