### ISSUE TITLE
--fix 100% cpu usage

### ISSUE THREAD

**Issue by ilwebdifabio** [jscs-dev/node-jscs#1998]
Hi there,
sorry to bother you but with version
2.6.0 If I run like this

>jscs --fix ./gulpfile.js  ./src/scripts

my cpu usage go to 100%
With the same comand I'd no problem 
with 2.5.1 version.

Best regards

**Comment by mrjoelkemp** [comment]
Hi @ilwebdifabio! Thanks for reporting the issue.

I'm not seeing a possible cause right away, but some additional information might help lead to possible causes:

* Did your jscsrc change at all between version bumps?
* Do you mind pasting your jscsrc so we can see which rules you're using?
* Did the number of files change significantly between version bumps?
* How many files are in `src/scripts` roughly?
* Or are you saying that you only bumped the version, changed nothing else, and noticed this problem?
* Do you notice the problem if you only fix your gulpfile?

Other maintainers may have other hunches. Thanks in advance for the information.

**Comment by ilwebdifabio** [comment]
You are welcome.
I'm awfully sorry just now I've realized 
that in the fix path there were also the bower_components as well.
You can close the issue.
Thanks and sorry again

**Comment by mrjoelkemp** [comment]
You should be able to ignore those by using excludeFiles. Thanks!
