### ISSUE TITLE
requireCamelCaseOrUpperCaseIdentifiers and destructure assignment doesn't play nice

### ISSUE THREAD

**Issue by maherbeg** [jscs-dev/node-jscs#2003]
Hi!

When using the `requireCamelCaseOrUpperCaseIdentifiers` rule with the `ignoreProperties` flag turned on, JSCS still flags destructured assignments in functions

Sample JSCS config
```json
{
  "esnext": true,
  "esprima": "babel-jscs",
  "requireCamelCaseOrUpperCaseIdentifiers":{
    "ignoreProperties": true
  }
}
```

Sample failed Javascript
```javascript
  const x = ({testProperty: test_property}) => testProperty.length;
```

Results in
```
All identifiers must be camelCase or UPPER_CASE at src/test.js :
     3 |
     4 |  var x = ({testProperty: test_property}) => testProperty.length;
----------------------------------^
```

The same issue applies to default destructuring, but that is understandable.
```javascript
  const x = ({test_property, ...rest}) => test_property.length;
```

**Comment by markelog** [comment]
Wanna try to tackle this bug?

**Comment by maherbeg** [comment]
@markelog Sure! Any pointers for doing so?

I've got something along the lines of retrieving the node, and then determining the parent node of the AST to see if it is an `ObjectProperty` type. Will post a PR soon!
