### ISSUE TITLE
disallowNewlineBeforeBlockStatements dose not apply for class blocks

### ISSUE THREAD

**Issue by Bnaya** [jscs-dev/node-jscs#2004]
disallowNewlineBeforeBlockStatements is ignoring class declarations 
```js
class 
{
func() {
}
}
```
will pass lint with disallowNewlineBeforeBlockStatements: true

**Comment by markelog** [comment]
Would be cool to have, would you like to try to implement it?

**Comment by Bnaya** [comment]
I can try to, where i should start?

**Comment by markelog** [comment]
We have more or less extensive guide - https://github.com/jscs-dev/node-jscs/blob/master/CONTRIBUTING.md, but whole architecture of jscs is pretty simple.

Nevertheless, if you have any questions don't hesitate to ask

**Comment by Bnaya** [comment]
I'm looking for a straightforward way  to debug node cli tools, i'm having trouble to do so with node-inspector

Also i don't see console.logs i put in the sourcecode of node-jscs

**Comment by markelog** [comment]
If your console statements are in some parts of the tests, they might be omitted though, due to stubbing - https://github.com/jscs-dev/node-jscs/blob/365569a60bb6b908f27b151f55a9b0d9418fdfd8/test/specs/cli.js#L27-L28

But it is probably not your case. Hard to come up with the other hypothesis without seeing any code, as you might imagine. For most cases console output should be there.

`node-inspector` or [iron-node](https://github.com/s-a/iron-node) might be useful, but usually not as much.

**Comment by Bnaya** [comment]
Eventually node-debug $(which jscs) file.js done the trick, its just takes long time to start

**Comment by Bnaya** [comment]
@markelog  it was pretty simple to implement, tell me if its looks ok
https://github.com/jscs-dev/node-jscs/compare/master...Bnaya:disallowNewlineBeforeBlockStatements-class?expand=1

We will need update the docs about the new block type
My tests have parse error and i'm not sure why
```
 parseError: Unexpected token {
```

**Comment by markelog** [comment]
Send us a pull request and we will go from there

**Comment by Bnaya** [comment]
the pr #2006

**Comment by Bnaya** [comment]
@markelog 
I'm not on the contributors list any idea why? (just wondering :))
https://github.com/jscs-dev/node-jscs/graphs/contributors

**Comment by markelog** [comment]
github has a limit for this page, which is hundred, we have more then a hundred contributors, so anyone else that has less then couple commits might not gonna appear there.

 In other words, just send us another PR :-).
