### ISSUE TITLE
requireParenthesesAroundArrowParam incorrect flags arrow function's params with flow

### ISSUE THREAD

**Issue by trikadin** [jscs-dev/node-jscs#2005]
Sample:
```js
const func = (x: number) => {};
```

> Wrap arrow function expressions in parentheses at [file]

**Comment by hzoo** [comment]
Makes sense - the logic for this rule is using tokens which makes this annoying - https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/require-parentheses-around-arrow-param.js.

**Comment by markelog** [comment]
Would you like to try to fix it?

**Comment by kepta** [comment]
@hzoo I was interested in fixing this bug.
Should we try to use a different mechanism to detect parenthesis or use a short cut to check for ':', which takes care of this particular flow case in here,
```
var closingParensToken = file.getNextToken(file.getLastNodeToken(node));

```
closingParensToken  takes the value ':', can't we have a function like getNextTokenExcept(':') ?

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
