### ISSUE TITLE
requirePaddingNewLinesAfterBlocks in JSX

### ISSUE THREAD

**Issue by TheSavior** [jscs-dev/node-jscs#2008]
Currently this rule says that this is a problem:

```
var foo = (
  <div
    ref={function() {
    }}
  >
    foo
  </div>
);
```

but this is accepted:

```
var foo = (
  <div
    ref={function() {
    }}

  >
    foo
  </div>
);
```

There should probably be an exception for JSX.

**Comment by markelog** [comment]
Would you like to try to fix it?

**Comment by TheSavior** [comment]
I don't currently have the bandwidth to do so. :-/

**Comment by bomatson** [comment]
@markelog  @TheSavior I had the bandwidth! See PR ^^

**Comment by c089** [comment]
There is another case that is not covered by this fix: Self-closing tags. I often use this to split components with many props over several lines like this:

```
const foo = (
  <Foo
      a="foo"
      b="bar" />
);
```

**Comment by markelog** [comment]
Feel free to create a ticket about this with or without accompanied pr.
