### ISSUE TITLE
requireCamelCaseOrUpperCaseIdentifiers rule marks the Image() built-in function 

### ISSUE THREAD

**Issue by NoNameProvided** [jscs-dev/node-jscs#2011]
```javascript
var image = new Image();
```

This line trigger a requireCamelCaseOrUpperCaseIdentifiers error and I have to change the ```Image()``` to ```image()``` to make the error disappear. 

Jscs should not mark this as an error since its not an user defined variable.

**Comment by markelog** [comment]
Can't repro this, would you mind posting `jscs --verbose` output and your config?

**Comment by NoNameProvided** [comment]
My `.jscsrc`:

```javascript
{
    "preset": "airbnb",
    "validateIndentation": 4,
    "validateLineBreaks": null,
    "requireTrailingComma": null,
    "requireCamelCaseOrUpperCaseIdentifiers": {"ignoreProperties": true, "strict": true},
    "excludeFiles": ["lib/**", "dist/**", "resources/**"]
}
```

```
$ jscs social.js --verbose
requireCamelCaseOrUpperCaseIdentifiers: All identifiers must be camelCase or UPPER_CASE at social.js :
   191 |    downloadProfilePicture: function(successHandler, errorHandler) {
   192 |        this.api('/me/picture', 'get', {type: 'large'}, function(response) {
   193 |            var image = new Image();
------------------------------------^
   194 |            image.crossOrigin = 'anonymous';
   195 |            image.src = response.data.url;

requireCamelCaseOrUpperCaseIdentifiers: All identifiers must be camelCase or UPPER_CASE at social.js :
   335 |
   336 |    downloadProfilePicture: function(successHandler, errorHandler) {
   337 |        var image = new Image();
--------------------------------^
   338 |        image.crossOrigin = 'anonymous';
   339 |        image.src = this.auth.currentUser.get().getBasicProfile().getImageUrl() + '?sz=512';

requireCamelCaseOrUpperCaseIdentifiers: All identifiers must be camelCase or UPPER_CASE at social.js :
   429 |            }
   430 |
   431 |            var image = new Image();
------------------------------------^
   432 |            image.crossOrigin = 'anonymous';
   433 |            image.src = src;


3 code style errors found.
```

**Comment by markelog** [comment]
Oh yeah, that because of the `strict` mode.

Wonder what we should do here.

@janpieterz thoughts?

**Comment by janpieterz** [comment]
It's certainly not handling this currently.

Am I correct in stating that the strict shouldn't actually care about a new xxx statement, even if it is a user defined object? Seems to me that this should be valid:
``` js
var user = new User();
var template = new Template();
``` 
But that might simply be because my background is mostly C#. 

To be honest my knowledge of the inner workings of jscs is a bit too narrow to specify how to solve this, but I'm more than willing to pick it up and including a unit test for it, with a little nudge in how to recognize in code which item is of what type etc (examples in the source will do fine).

**Comment by NoNameProvided** [comment]
I don't know how much my word counts here, but we use the CamelCase naming convention for our objects. So I vote to allow constructor methods being capitalized.

**Comment by markelog** [comment]
It is common practise to name "classes"  in JS with uppercase, but that would be "PascalCase" which `strict` mode disallows.

Yeah, we can allow using first uppercase letter with `new` operator, but `new` is often optional operator. "classes" could defined in way that allows to be invoked without it.

We can also try to omit all expression statements.

**Comment by janpieterz** [comment]
@NoNameProvided do you use camelCase for other stuff and CamelCase (PascalCase) for your types, or do you use CamelCase everywhere else? As in, are types the only place you divert from the current 'strict' setting?

If we do that it feels like we're making opinionated choices while they should probably become settings. I feel it could become a  'bigger' feature, looking at for example this:
https://msdn.microsoft.com/en-us/library/x2dbyw72(v=vs.71).aspx
or this:
http://docs.scala-lang.org/style/naming-conventions.html
Microsoft themselves changes their conventions between versions of the .NET framework, see above link, and:
https://msdn.microsoft.com/en-us/library/ms229043(v=vs.100).aspx
and:
https://msdn.microsoft.com/en-us/library/ms229043(v=vs.110).aspx

It almost feels like the capitalization style should become some kind of configurable preset, slightly comparable to the jquery/airbnb etc presets, where there are a certain amount of individual settings per type (types, variables, properties etc) which are easily configurable per item but also easily defined with a preset (dotnet46, dotnet35, scala). 

This would obviously cost quite a bit of time to develop and I'm not sure if that would currently be worth it.

**Comment by NoNameProvided** [comment]
@janpieterz Yes we use CamelCase only for our types (user defined objects). Other stuff like variables are camelCase, I think this is the kinda standard naming convention in javascript,

**Comment by markelog** [comment]
How about right now, we just would check the `new` keyword and omit such warnings? And see how it would go from there.

How is that sound?

**Comment by dharkness** [comment]
Wouldn't it be easier to ignore function/constructor calls *entirely* and flag them only at the declaration? Since the calls must match the declarations, it's better to flag the source of the problem (declaration). And if you ignore it for a single function, you don't have to ignore it at each call.

This is hitting me with some jQuery "constructors" such as `$.Deferred()` which do not use `new` and so won't be detected as a constructor.

**Comment by markelog** [comment]
> Wouldn't it be easier to ignore function/constructor calls entirely and flag them only at the declaration? Since the calls must match the declarations, it's better to flag the source of the problem (declaration). And if you ignore it for a single function, you don't have to ignore it at each call.

Or flag both cases, but only if we find a declaration? Since you would still would wanna know where do you use such naming after renaming

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
