### ISSUE TITLE
requireEnhancedObjectLiterals

### ISSUE THREAD

**Issue by kobezzza** [jscs-dev/node-jscs#2013]
```js
export const COMMENTS = {
	[SINGLE_COMMENT]: SINGLE_COMMENT // Error
};
```

**Comment by hzoo** [comment]
What's the error say?

**Comment by kobezzza** [comment]
> What's the error say?

Property assignment should use enchanced object literal function. `{propName: propName}` is not allowed.

**Comment by hzoo** [comment]
Ok `requireEnhancedObjectLiterals` just needs to account for computed properties

**Comment by markelog** [comment]
@kobezzza Would like to try to tackle this bug?

**Comment by kobezzza** [comment]
> @kobezzza Would like to try to tackle this bug?

Ok

**Comment by markelog** [comment]
Friendly ping
