### ISSUE TITLE
disallowKeywords has no affect on 'null'

### ISSUE THREAD

**Issue by danny-andrews** [jscs-dev/node-jscs#2016]
The setting `"disallowKeywords": ["null"]` has no affect.

**Comment by markelog** [comment]
That's because `null` is not a keyword it is a literal, you would need a special rule for that.

If you would like to implement it, let us know

**Comment by danny-andrews** [comment]
I would like to implement it. Douglas Crackford makes a good case for using `undefined` in place of `null`. https://youtu.be/rhV6hlL_wMc?t=22m6s. I'll see if I can get a PR running sometime this week.
