### ISSUE TITLE
Add ignoreQuotedProperties to requireCamelCaseOrUpperCaseIdentifiers

### ISSUE THREAD

**Issue by xaka** [jscs-dev/node-jscs#2018]
Hi there,

The problem with existing `ignoreProperties` and why it's not enough is that I really want to enforce camelCased properties, not ignore, but there are situations when you need to consume 3rd party API and it uses snake_case. What does it mean? JSCS is going to complain about:

```js
var myObjectFor3rdPartyApi = {
 snake_property: ...
}
```

Until I set `ignoreProperties` to `true`, which at the same time entirely disables property enforcement, which isn't good.

The proposal is to add another flag, `ignoreQuotedProperties`, which when `true` would skip, well, quoted properties as in:

```js
var myObjectFor3rdPartyApi = {
 'snake_property': ...
}
```

So it'll be up to developer to either fix the coding formatting OR **explicitly** and **intentionally** enclose property in quotes and put JSCS in silent mode.

In case you agree with such proposal, I'm happy to provide a pull request.

Thanks!

**Comment by markelog** [comment]
Sounds good to me, pr welcome

**Comment by markelog** [comment]
Friendly ping

**Comment by xaka** [comment]
Houston, we've had a problem here. As it turned out, proposal conflicts with http://jscs.info/rule/disallowQuotedKeysInObjects and my understanding is that rules should know nothing about other rules and properties to keep things less simple. What's interesting is that `requireCamelCaseOrUpperCaseIdentifiers` doesn't validate quoted keys/properties as of now, which one might consider as bug. In this case we have another option - change `disallowQuotedKeysInObjects` instead of changing `requireCamelCaseOrUpperCaseIdentifiers`. We'd add `allButSnakeCased` boolean property to control behavior more precisely.

**Comment by markelog** [comment]
> As it turned out, proposal conflicts with http://jscs.info/rule/disallowQuotedKeysInObjects and my understanding is that rules should know nothing about other rules and properties to keep things simple.

If you would disable it, it wouldn't ;).

> What's interesting is that requireCamelCaseOrUpperCaseIdentifiers doesn't validate quoted keys/properties as of now, which one might consider as bug

Sounds like it

**Comment by markelog** [comment]
> Sounds like it

Although it more like a behaviour specialty, not necessary a bug. 

Okay so feel free to send open an issue and pr for `disallowQuotedKeysInObjects`, note though, that you would need to add `snake_case` to `allExcept` value
