### ISSUE TITLE
Rule for use scrict

### ISSUE THREAD

**Issue by diegoaguilar** [jscs-dev/node-jscs#2019]
I got following `.jscsrc` file:

```json
{
  "requireSemicolons": true,
  "validateQuoteMarks": "'",
  "requirePaddingNewLinesAfterUseStrict": true,
  "dissallowTrailingComma": true,
  "disallowSpacesinFunction": true,
  "maximumLineLength": 120,
  "requireCamelCaseOrUpperCaseIdentifiers": true,
  "disallowMixedSpacesAndTabs": "smart",
  "disallowEmptyBlocks": true,
  "requireSpaceAfterLineComment": {
    "allExcept": [
      "#",
      "="
    ]
  },
  "validateIndentation": {
    "value": 2,
    "allExcept": ["comments"]
  },
  "requireAlignedMultilineParams": true,
  "validateParameterSeparator": ", ",
  "requireSpaceBetweenArguments": true,
  "requireSpaceAfterKeywords": [
      "do",
      "for",
      "if",
      "else",
      //"switch",
      "case",
      "try",
      "catch",
      "void",
      "while",
      "with",
      "return",
      "typeof"
  ],
  "requireSpaceBeforeBlockStatements": true,
  "requireSpacesInConditionalExpression": true
}
```

And then as soon as I start typing first JS line for `use strict`; will get some errors:

![slackbotjs](https://cloud.githubusercontent.com/assets/2483678/11761768/591688f4-a095-11e5-95b9-f688a2de487a.png)

Why is this? How can I get it working with out errs?

**Comment by hzoo** [comment]
To start `dissallowTrailingComma` is spelled wrong - `disallowTrailingComma` http://jscs.info/rule/disallowTrailingComma

Maybe we could make a better error message but we don't know if you spelled a rule wrong or not (although we could probably add that in by checking edit distance

**Comment by diegoaguilar** [comment]
Yah I got both wrong:

* `dissallowTrailingComma`  (extra 's')
* `disallowSpacesinFunction` (wrong lowerCase 'i')

My bad, sorry!
