### ISSUE TITLE
option preset does not behave the same in CLI & config

### ISSUE THREAD

**Issue by JSteunou** [jscs-dev/node-jscs#2021]
I'm trying to use a preset of my own and I struggled a little  before finding this.

This works, JSCS show me errors I add attentionally to test it

```json
{
  "preset": "@foo/jscs-preset-foo/foo.json"
}
```

But this inside package.json scripts does not load the preset. JSCS do run, returning no errors.

```
jscs src --fix --preset=@foo/jscs-preset-foo/foo.json
```

**Comment by markelog** [comment]
Sorry for the late responce.

How about
```
jscs src --fix --preset="@foo/jscs-preset-foo/foo.json"
```
?

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
