### ISSUE TITLE
requireTrailingComma should be made optional when closing bracket/brace is on same line

### ISSUE THREAD

**Issue by fenduru** [jscs-dev/node-jscs#2024]
Using angular's DI syntax, it is common to end up with code that looks like: 

```js
module.directive('foo', ['someDependency', function(someDependency) {
  // logic here
},]);
```

While requireTrailingComma is useful in most other scenarios, I don't think it makes sense when the comma is immediately followed by the corresponding bracket/brace. I feel that the benefit of requireTrailingComma is avoiding 2-line diffs when adding one item to an object/array, however in this case that benefit is not realized because you would already have to move the closing bracket/brace to the next line.

I think this case is very similar to the case handled by the `ignoreSingleLine` option.

Thanks :)

**Comment by markelog** [comment]
Feel free to implement `allExcept` option, like, for example, in http://jscs.info/rule/disallowSpacesInsideParenthesizedExpression

Also, check out - https://github.com/olov/ng-annotate

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
