### ISSUE TITLE
requireCamelCaseOrUpperCaseIdentifiers: allow specific prefixes and suffixes to be ignored

### ISSUE THREAD

**Issue by pabigot** [jscs-dev/node-jscs#2029]
Proposal for rule enhancement:

I've got projects where I want to use `requireCamelCaseOrUpperCaseIdentifiers `but have a higher priority requirement that variables and properties that hold measurements specify the [units of measure](http://unitsofmeasure.org/ucum.html) in a suffix with an underscore separator. For example: `ambientTemperature_cCel` or `centerFrequency_kHz`.

Issue #1900 expresses a similar desire for specific prefixes to be ignored, but the proposed solution may involve wildcards that would not validate the remainder of the identifier.

The proposed solution is to augment the configuration value for `requireCamelCaseOrUpperCaseIdentifiers` to take options `allowedPrefixes` and `allowedSuffixes`.  Each of those is an array of strings or regular expressions identifying text sequences that are permitted as a prefix followed by an underscore (for `allowedPrefixes` or a suffix after an underscore (for `allowedSuffixes`).  If an identifier has one of these prefixes (suffixes) and would pass the rule if the prefix (suffix) was removed, then it is allowed with the prefix (suffix) as well.

Pull request #2028 will have an implementation of this just as soon as I know what issue number this is so I can reference it in the commit message.

**Comment by ChrisPearce** [comment]
This would also be very useful when referencing NPM script config values from within Node JS (e.g. var myProp = process.env.npm_package_config_MY_ENVIRONMENT_VARIABLE).

**Comment by pabigot** [comment]
@markelog @ChrisPearce @tonyganch Pull request #2028 which had my initial attempt at this has gotten complex and involves questions of how to specify the configuration, so I want to move attention back here where we can work out the semantics and interface in a more visible area.  If there are others who should be invited to participate please do so.

As I noted in the original description, the behavior I want is to specify arbitrary prefix and suffix values with separating underscores that are stripped off identifiers before submitting the remainder to the validation of `requireCamelCaseOrUpperCaseIdentifiers`.

In #1900 and a comment in #2028 it was proposed to use `allExcept` for something like this, but I believe that name implies completely excluding a matching identifier from the rule.  As such I don't believe the prefix and suffix exceptions should be incorporated into the `allExcept` option, though I do need that capability as well.

Thus I propose three additional configuration options, all arrays, and all containing string, RegExp, or [minimatch](https://github.com/isaacs/minimatch) string values.  For example

    "allExcept": [ "var_args", /^ignore/, ],
    "allowedPrefixes": [ "opt" ],
    "allowedSuffixes": [ "dCel", /[kMG]Hz/, "?(k|M|G)Hz" ],

(Pardon any errors in the minimatch syntax, I haven't investigated that yet.  I intend to still support RegExp values as they're nice for programmatic use.)

I propose the following rule behavior:

0. Let V represent the initial input identifier.
1. If V matches anything in `allExcept`, it will be accepted without further checks.
2. Leading and trailing underscores, which traditionally represent a notion of visbilility, are stripped from V before proceeding.  (This is not a behavior change, but is where I believe the effect should occur in the validation sequence.)
3. If V decomposes to a sequence P followed by an underscore followed by a non-empty sequence R, and the sequence P matches anything in `allowedPrefixes`, the value R replaces V in all subsequent validation.  Prefix checking stops after the first match.  P is specifically permitted to contain underscores.
4. If V decomposes to a non-empty sequence R followed by an underscore followed by a sequence S, and the sequence S matches anything in `allowedSuffixes`, the value R replaces V in all subsequent validation.  Suffix checking stops after the first match.  S is specifically permitted to contain underscores.
5. V is checked against the existing rule.

Comments?

**Comment by gibson042** [comment]
I like this approach; it is a significant step towards a fully general treatment. Two comments:
* It feels strange to hard-code underscore as the stem–adfix separator in the midst of so much configurability... why not just incorporate separators directly _into_ prefixes and suffixes?
* "_I intend to still support RegExp values as they're nice for programmatic use_" should be interpreted as meaning that they are impossible to specify by static configuration, right?

**Comment by pabigot** [comment]
@gibson042 Thanks.
* It was separate mostly because I'd conceived of it as a separating character rather than part of the affix.  I agree that putting it into the pattern is not a hardship and is more general, and will proceed that way subject to opposing input.
* Yeah, putting things like `/[kMG]?Hz/` into JSON doesn't work so well.

**Comment by pabigot** [comment]
[minimatch](https://github.com/isaacs/minimatch) isn't going to cut it as it matches whole sequences: there's no public API way to extract the non-affix part of the identifier, and the feature to create equivalent regular expressions has multiple unaddressed issues against it.  To support JSON configuration I'll treat any string pattern that itself matches `'/^\/(.*)\/([gimuy]*)$/` as a regular expression that will be compiled when the configuration is installed.

I think minimatch could work in `allExcept`, but without a clear statement of interest backed by maintainer approval I'll stick to strings and regular expressions.

**Comment by gibson042** [comment]
minimatch can work if you manually insert `*`s at the correct positions (e.g., prefix "opt_" becomes pattern "opt_*").

Also, regular expressions could be specified as ESTree [RegExpLiteral](https://github.com/estree/estree/blob/master/spec.md#regexpliteral) objects instead of specially-formatted strings:
```js
{
  regex: {
    pattern: "_[kMG]?Hz",
    flags: ""
  }
}
```

**Comment by pabigot** [comment]
Given "opt_*" with minimatch, how would you get it to say what matched the "*" part so that could be validated against the rule?

I'll go with ESTree, assuming flags is optional.  Thanks for the pointer.

**Comment by gibson042** [comment]
> Given "opt_\*" with minimatch, how would you get it to say what matched the "\*" part so that could be validated against the rule?

Good point. It _could_ be done with [`set`](https://github.com/isaacs/minimatch#properties) or [`makeRe()`](https://github.com/isaacs/minimatch#methods), but not very robustly.
