### ISSUE TITLE
Need a method to turn off/override rules for presets

### ISSUE THREAD

**Issue by nschonni** [jscs-dev/node-jscs#203]
From @mikesherov  in https://github.com/mdevils/node-jscs/pull/181#issuecomment-32684534

> ... we need ability to turn off a rule. Imagine user wants to use jQuery preset except one rule. Null value for a rule should disable it.  Thoughts?

**Comment by Hanzig** [comment]
Hi all! I'm currently using AirBnB preset, and would like to override the 2 spaces indentation. Have any of you encountered such an issue and how did you achieve that?
