### ISSUE TITLE
checkString ignores excludeFiles

### ISSUE THREAD

**Issue by Arcanemagus** [jscs-dev/node-jscs#2031]
It seems that the `checkString` function doesn't handle the `excludeFiles` section of the configuration as reported by several people using the Atom package linter-jscs here: https://github.com/AtomLinter/linter-jscs/issues/83

Their configuration is being loaded and processed properly, but when `checkString` is called with the file contents and the path of a file that _should_ be ignored errors are being reported back.

Is this an issue here in `jscs`, or are we somehow utilizing it improperly [here](https://github.com/AtomLinter/linter-jscs/blob/v3.2.0/index.js#L121)?

**Comment by markelog** [comment]
Well yeah, it is called "check**String**" for a reason :-), it doesn't deal with paths, second argument is need just to tell the reporter where is the violation. In other words use "check**Path**"

**Comment by Arcanemagus** [comment]
Thanks for the information, I guess we will have to work around this limitation in the package.

_Note: Other linters handle their file ignore patterns if passed a string as long as they are also passed an original file path, so I assumed this was similar and just not working._

**Comment by markelog** [comment]
Hm, will you able to send us a pr? I suppose we can do that, if that is really needed. Would want you to create some hacks in your app, instead of just using it

**Comment by Arcanemagus** [comment]
I can try putting something together, it's going to be a while before I can get to it though. If somebody who is actually familiar with the code wants to take a stab at it that would be appreciated.
