### ISSUE TITLE
maximumLineLength allExcept functionSignatures - broken in IIFE

### ISSUE THREAD

**Issue by himdel** [jscs-dev/node-jscs#2032]
With jscs-2.7.0, maximumLineLenght.allExcept = ['functionSignatures'] does not work if such a function is wrapped in an IIFE block.

I assume that's a bug, right?

Simple case:

`.jscsrc`
```json
{
  "maximumLineLength": {
    "value": 64,
    "allExcept": [
      "functionSignature"
    ]
  }
}
```

`bug.js`
```js
function tooLongButOK_spam_spam_spam_spam_spam_spam_spam_spam_spam() {
}

(function() {
  function tooLongAndNotOK_spam_spam_spam_spam_spam_spam_spam_spam() {
  }
})();

(function() {
  "use strict";
  function tooLongAndStillNotOK_spam_spam_spam_spam_spam_spam_spam() {
  }
})();
```

I'd expect jscs to run on this without errors, but I get 2 errors.

**Comment by markelog** [comment]
It totally is! By looking at the code, it is not ideally implemented, one might say - badly implemented.

Do you wanna try to fix it

**Comment by himdel** [comment]
Sure, looks like a fun xmas project :) though after a (really) quick look the day before I couldn't really make heads or tails of it..

But if I'm fixing it, do we still really want this to *not* apply to `var foo = function(...) {`?

**Comment by markelog** [comment]
Judging by name of the option, i'd say it would be okay to make that changes.

Happy Christmas btw!

**Comment by himdel** [comment]
@markelog Thanks!, Merry Christmas to you as well :)

And what do you think of #2040?, should hopefully be a bit cleaner than the current approach..
