### ISSUE TITLE
child_process.spawn Jscs file match pattern issue

### ISSUE THREAD

**Issue by 1001b** [jscs-dev/node-jscs#2033]
I tried to spawn a process to run jscs and ran into a problem with using "\*", ie, "src/\*".  Please see below link to reproduce the error:
https://github.com/1001b/jscs_spawn_issue/blob/master/index.js

The same command text runs fine directly in sh:
*./node_modules/jscs/bin/jscs -c .jscsrc src/*.js*

**Comment by markelog** [comment]
That is actually a cool thing that happens, when you executing jscs from the console, it goes through shell, say bash for example, which parses the stdin, so *bash parsers the input*, not jscs, not node, but shell, which unfolds that wildcard.

But with `spawn`, you bypass the shell part, so there is nobody who doing this job anymore.

Anyhow, primary, you have two options, either use [`exec`](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) or unfold that pattern yourself.

**Comment by 1001b** [comment]
Just curiosity.  The spawn approach works for ESLint.   What is the implementation difference between ESLint and JSCS?
