### ISSUE TITLE
(ES6) requireObjectShorthandFirst

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#2038]
- `requireObjectShorthandFirst`

> Group your shorthand properties at the beginning of your object declaration.
> Why? It's easier to tell which properties are using the shorthand.

```js
// good
{
  a,
  handler,
  abc: xyz,
  test: test2
}
```

**Comment by hzoo** [comment]
@markelog I made this is for sorting object shorthand alphabetically - `requireObjectShorthandFirst`?

**Comment by markelog** [comment]
Oh, cool, will revert
