### ISSUE TITLE
What is the color theme on the main site?

### ISSUE THREAD

**Issue by yaroslavya** [jscs-dev/node-jscs#2039]
Not an issue at all, but wanted to ask what is the color theme on 
the main page of your website ( http://jscs.info/ ).
Interested in themes for Sublime, Webstorm and VisualStudio.

**Comment by markelog** [comment]
@hzoo should know about it, since he did the decoration

**Comment by yaroslavya** [comment]
Looks like [solarized dark](http://ethanschoonover.com/solarized), actually.

**Comment by hzoo** [comment]
Oh in the pictures? Yeah its a solarized dark theme for the terminal.
