### ISSUE TITLE
requireSpaceBeforeKeywords should ignore functions as arguments

### ISSUE THREAD

**Issue by radek-holy** [jscs-dev/node-jscs#2041]
The `requireSpaceBeforeKeywords` reports an error:
> Missing space before function keyword

in the following code:
```javascript
[].forEach(function (arg) {
    console.log(arg);
});
```

I believe that such occurrence of a keyword should be an exception from this rule.

**Comment by markelog** [comment]
Sounds like we should add an option for this, would you like to implement `allExcept` for this rule?

**Comment by markelog** [comment]
See example - http://jscs.info/rule/disallowSpacesInsideParenthesizedExpression.html

**Comment by radek-holy** [comment]
Hm, have you ever seen a code convention to write a space in this case? I am new to JavaScript so I have no idea.
My opinion is that this rule should not apply in this case at all. If you have aver seen such code, maybe I would add an opposite exception: "ignore this case by default unless an `includeParenthesized` option is enabled".
But it's just my opinion. Feel free to choose your solution. It will help too.

**Comment by markelog** [comment]
Yep - https://contribute.jquery.org/style-guide/js/#spacing, but i agree, that is seems pretty esoteric and could be accomplished by other rules.

So i'm fine implementing this behaviour by default.

**Comment by gpiress** [comment]
I'm interested in helping with this issue, as I had the same problem.

But just to make sure if what I thought is enough. I'm thinking in following @markelog  suggestion and implementing a third way of using this rule, i.e using an Object with the 'allExcept' property, and one could define it such as:

`requireSpaceBeforeKeywords: { allExcept: 'function' }`

And this would be sufficient for the issue to be solved, am I right?

**Comment by radek-holy** [comment]
I still prefer if it was a default behaviour but yes, better this than nothing...

**Comment by markelog** [comment]
I think we can make this as a default behaviour, if jquery followers would want such style, they could use different rules for that
