### ISSUE TITLE
--fix option breaks code by removing \\ in strings

### ISSUE THREAD

**Issue by justin808** [jscs-dev/node-jscs#2043]
See https://github.com/shakacode/react_on_rails/commit/eac2a29dc1c6352b34a1a0fa0957c78b3e428a3c#diff-f1982fe6b827afdc18aa0d36700f4cc2R80

When I run --fix on the below code, the `\\` are removed! and that breaks the test.

```
(npm bin)/jscs --version    
title:8: parse error
2.7.0
```

code that breaks

```js
test('buildConsoleReplay wraps console replay in a script tag', (assert) => {
  assert.plan(1);
  console.history = [
    { arguments: ['some message', { a: 1, b: 2 }], level: 'log' },
    { arguments: ['other message', { c: 3, d: 4 }], level: 'warn' },
  ];
  const actual = buildConsoleReplay();
  const expected = `
<script>
console.log.apply(console, ["some message","{\\"a\\":1,\\"b\\":2}"]);
console.warn.apply(console, ["other message","{\\"c\\":3,\\"d\\":4}"]);
</script>`;
  assert.equals(actual, expected, 'Unexpected value for console replay history');
});
```

**Comment by markelog** [comment]
Hm, doesn't happen for me -

```bash
markelog in ~/Workspace/react_on_rails on (HEAD detached at eac2a29)*
$ git status
HEAD detached at eac2a29
nothing to commit, working directory clean
markelog in ~/Workspace/react_on_rails on (HEAD detached at eac2a29)*
$ jscs -x node_package/tests/buildConsoleReplay.test.js
markelog in ~/Workspace/react_on_rails on (HEAD detached at eac2a29)*
$ git status
HEAD detached at eac2a29
nothing to commit, working directory clean
markelog in ~/Workspace/react_on_rails on (HEAD detached at eac2a29)*
$ node -v
v5.1.0
```

**Comment by justin808** [comment]
@markelog What do you recommend? Is my version of jscs wrong? or my .jsrc? or version of node?

**Comment by markelog** [comment]
It seems config is okay. Can you try to reinstall your modules? And post version of the node.

**Comment by justin808** [comment]
Should I first update to node latest? Did you pull my project and run `jscs -x`?

**Comment by markelog** [comment]
> Should I first update to node latest?

No, it should work from node .10

>  Did you pull my project and run jscs -x?

Yeah, you can see my actions at the comment - https://github.com/jscs-dev/node-jscs/issues/2043#issuecomment-168161191

Happy new year btw!

**Comment by justin808** [comment]
When I tried again, with no linting issues, so let's close this. I'll keep an eye out for this one. Thanks for the great work on this tool!

**Comment by markelog** [comment]
Okay, keep us posted if you see anything :)
