### ISSUE TITLE
New Rule: Alphabetize Imports

### ISSUE THREAD

**Issue by danny-andrews** [jscs-dev/node-jscs#2049]
It might be nice to have a rule that requires imports to be alphabetized. Even more useful would be a rule that forces you to separate local imports from external imports with a newline.

**Comment by hzoo** [comment]
For sure! Your other suggestion can be a separate rule. Also would you like to give it a shot?

**Comment by rheh** [comment]
To be clear, we are referring to ES6 imports here?  If so, esnext provides the following ways of importing:

  // Default exports and named exports
    import theDefault, { named1, named2 } from 'src/mylib';
    import theDefault from 'src/mylib';
    import { named1, named2 } from 'src/mylib';
    
    // Renaming: import named1 as myNamed1
    import { named1 as myNamed1, named2 } from 'src/mylib';
    
    // Importing the module as an object
    // (with one property per named export)
    import * as mylib from 'src/mylib';
    
    // Only load the module, don’t import anything
    import 'src/mylib';

**Comment by hzoo** [comment]
This could be for es6 imports or commonjs requires?

**Comment by kepta** [comment]
Can someone be kind enough to explain what  alphabetise imports are? 
Google failed to give me an answer :/

**Comment by danny-andrews** [comment]
It means sorting your imports in alphabetical order. e.g. This rule would complain about this:
```javascript
import a from 'a';
import z from 'z';
import c from 'c';
```
It should be:
```javascript
import a from 'a';
import c from 'c';
import z from 'z';
```

**Comment by rheh** [comment]
I will take a look a implementing this.
