### ISSUE TITLE
jsDoc: Not all periods end a sentence

### ISSUE THREAD

**Issue by dharkness** [jscs-dev/node-jscs#2054]
Several of our descriptions are being improperly-flagged because the rule assumes every period ends a sentence.

Examples of valid descriptions:

`The values are encoded in the cookie (lnk vs. kwd).`
`Call this method as foo.bar().`

Neither of the periods in `vs.` and `foo.bar` end a sentence. I was going to recommend requiring a space after the period (fixes second case), but that still flags abbreviations. Honestly, I'd be happy to just enforce a capital letter for the start of each description and not try to detect multiple sentences.

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
