### ISSUE TITLE
running --fix with a validateNewlineAfterArrayElements rule doesnt apply the fix

### ISSUE THREAD

**Issue by joerideg** [jscs-dev/node-jscs#2065]
Hi guys,

first of all my jscsrc: 
```json
{
  "preset": "airbnb",
  "validateNewlineAfterArrayElements": {
    "maximum": 1
  }
}
```

I'm currently bumping into this situation:
I have the following array:
```js
const someArr = [{
    test: 'test',
  }];
```
Linting this will warn me that there should be a new line after the [ and before the ].
Unfortunately trying to --fix this array will turn it into:
```js
  const someArr = [{
    test: 'test',
  },];
```
It will append the trailing comma to the only object since that is one of the rules of Airbnb. But it doesnt put the newlines in. 

I think this is a bug or am I missing something?

**Comment by hzoo** [comment]
Looking at the source for the rule - https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/validate-newline-after-array-elements.js it doesn't look like a bug because it doesn't look like autofix is implemented for that specific rule.

Autofix applies for all the rules in your config so the requireTrailingComma rule was autofixed.

**Comment by joerideg** [comment]
Ah ok. Yes I understand why the comma gets there, thats supposed to happen according to the other rule. 

Then my question becomes: Could the autofix feature be implemented for this rule? Currently because it adds this comma but doesnt put the newlines it then again fails validation because there should be a space after the comma. And frankly it just looks ugly :P 

Just for the record my preferred outcome would be:
```js
const someArr = [
  {
    test: 'test',
  },
];
```

**Comment by hzoo** [comment]
It's certainly a valid request (we would want to have autofix for every possible rule)

**Comment by kepta** [comment]
@hzoo , where is the source code for autofix of requireTrailingComma?

**Comment by markelog** [comment]
> Could the autofix feature be implemented for this rule? 

For realsies! Wanna do it?

Check out similar rule, like https://github.com/jscs-dev/node-jscs/blob/6ca665fe7068d3a1e7a6e4787a77c757802388b8/lib/rules/disallow-padding-newlines-after-blocks.js

This is the kicker - 
```js

errors.assert.linesBetween({
    token: endToken,
    nextToken: nextToken,
    atMost: 1,
    message: 'Extra newline after closing curly brace'
});
```

`linesBetween` will automatically will do all the fixing, you just need to pass right arguments to it.

**Comment by joerideg** [comment]
Sure I'll have a look tonight!

**Comment by joerideg** [comment]
Alright then I pretty much got it working. Only thing that I'm not sure how to fix is the indentation after putting in the newline. 
running .jscsrc with:
```json
{
  "validateNewlineAfterArrayElements": 1,
  "validateIndentation": 2
}
```
It currently transforms from:
```js
var arr = [1, 2, 3, 4, 5,];

var arr2 = ['string', 'string2', 'string4'];

var arr3 = [{test: 'test'}, {test2: 'test2'}, {test3: 'test3'}];

var arr4 = [1, 'string2', {test3: 'test3'}];
```
to
```js
var arr = [
1,
 2,
 3,
 4,
 5,
];

var arr2 = [
'string',
 'string2',
 'string4'
];

var arr3 = [
{test: 'test'},
 {test2: 'test2'},
 {test3: 'test3'}
];

var arr4 = [
1,
 'string2',
 {test3: 'test3'}
];
```

**Comment by markelog** [comment]
`validateIndentation` rule doesn't work for this kind of indentation - http://jscs.info/rule/validateIndentation

> Validates indentation for switch statements and block statements

I guess you can detect and fix indentation in  `validateNewlineAfterArrayElements` rule, which might not be trivial

**Comment by joerideg** [comment]
I could also try fixing the array indentation in validateIndentation. 
I really like the codebase btw, nice and clear. I will dive into this a bit more.

**Comment by hzoo** [comment]
I would think we want separate indentation rules then? https://github.com/jscs-dev/node-jscs/issues/1866 and not put indentation in `validateNewlineAfterArrayElements`. This particular can be standalone right?

**Comment by joerideg** [comment]
I would think so yes. The code I have now would in fact fix the errors logged by validateNewlineAfterArrayElements. So I think I can PR and then we can to fix the indentation in #1866 
I will prepare the PR tonight.

**Comment by markelog** [comment]
If you would be champion of it, it would be great! We would really like to improve our indentation situation.

**Comment by joerideg** [comment]
Just for the record: I ment PR just the fix for validateNewlineAfterArrayElements. 
I'll be happy to look the indentation aswell somewhere over the weekend see if I can make heads and tails of it.

**Comment by markelog** [comment]
Yeah, sure, ping us up in gitter or at the github if you would have any questions
