### ISSUE TITLE
requireSpaceAfterKeywords:true rule conflict causes fix toggling

### ISSUE THREAD

**Issue by lancecaraccioli** [jscs-dev/node-jscs#2067]
Intent: to force function definitions to have a space after the keyword "function"

.jscsrc
```json
    "preset": "google",
    "requireSpaceAfterKeywords": true
```

example.js
```javascript
(function() {
  console.log('foo');
}());
```

run auto fix
```bash
jscs --fix ./example.js
```

cat ./example.js results
```javascript
(function () {
  console.log('foo');
}());
```

running auto fix again results in the fix being reverted
```bash
jscs --fix ./example.js
```

cat ./example.js results
```javascript
(function() {
  console.log('foo');
}());
```

.jscsrc workaround gives the expected behaviour
```json
{
    "preset": "google",
    "disallowSpacesInAnonymousFunctionExpression": null,
    "disallowSpacesInFunctionExpression": null,
    "disallowSpacesInFunctionDeclaration": null,
    "requireSpacesInFunctionExpression": null,
    "requireSpaceAfterKeywords": true
}
```

**Comment by markelog** [comment]
Well, yeah, `requireSpaceAfterKeywords` conflicts with pre-defined rules in `google` preset, so you need to disable them.

And since their conflict with each other, `--fix` will always give different output
