### ISSUE TITLE
requireObjectDestructuingReturn

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#2073]
For the airbnb style guide https://github.com/airbnb/javascript#5.3.

  - [5.3](#5.3) <a name='5.3'></a> Use object destructuring for multiple return values, not array destructuring.

    > Why? You can add new properties over time or change the order of things without breaking call sites.

    ```javascript
    // bad
    function processInput(input) {
      // then a miracle occurs
      return [left, right, top, bottom];
    }

    // the caller needs to think about the order of return data
    const [left, __, top] = processInput(input);

    // good
    function processInput(input) {
      // then a miracle occurs
      return { left, right, top, bottom };
    }

    // the caller selects only the data they need
    const { left, right } = processInput(input);
    ```

**Comment by hzoo** [comment]
Maybe a better name is disallowArrayDestructuringReturn or preferObjectDestructuringReturn

**Comment by fxmaxvl** [comment]
I'll implement this rule.
I think, disallowArrayDestructuringReturn is more suitable to this case.

**Comment by markelog** [comment]
Be sure to send doc update to the airbnb folks
