### ISSUE TITLE
Unused var, const or let

### ISSUE THREAD

**Issue by felipekm** [jscs-dev/node-jscs#2076]
There's some configuration that handle it?

**Comment by hzoo** [comment]
No, we don't have a rule for that yet - there is http://jscs.info/rule/disallowUnusedParams.

**Comment by markelog** [comment]
It should be in 3.0 though!

**Comment by markelog** [comment]
With autofixing too

**Comment by felipekm** [comment]
Great, thanks!

**Comment by schempy** [comment]
If nobody is working on this I'd like to implement.

Thanks!
