### ISSUE TITLE
disallowNewlineBeforeBlockStatements and multiline statements error

### ISSUE THREAD

**Issue by ficristo** [jscs-dev/node-jscs#2077]
With this rule:
```javascript
"disallowNewlineBeforeBlockStatements": {
    "value": true,
    "allExcept": ["multiLine"]
}
```
This snippet fail, and souldn't:
```javascript
function test() {
    if (false) {
        f();
    } else {
    }
}
```
I gave a try to fix it but I'm lost.

**Comment by ficristo** [comment]
I was trying to special case the else condition, but I found even the following snippet is failing.
I cannot find a clean solution.
```javascript
f();
try {
} catch (e) {
    f();
} finally {
}
```

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
