### ISSUE TITLE
Illegal space before opening round brace error when using `[ propName ]: value` notation for objects

### ISSUE THREAD

**Issue by Reinmar** [jscs-dev/node-jscs#2078]
I get:

```
Illegal space before opening round brace at tests/utils.js :
   239 |
   240 |   const Mixin = {
   241 |    [ symbolA ]() {
---------------------^
   242 |     return 'a';
   243 |    }
```

With this configuration: https://github.com/ckeditor/ckeditor5-core/blob/master/.jscsrc

The error does not appear when more than just variable name is used inside `[]`. E.g. this passes:

```
	[ Symbol.iterator ]() {
		return new PositionIterator( this );
	}
```

**Comment by hzoo** [comment]
Can you give the rule name for this? `jscs . --verbose` should print out the exact rule for this issue

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
