### ISSUE TITLE
Rules missing from http://jscs.info/rules

### ISSUE THREAD

**Issue by cookch10** [jscs-dev/node-jscs#2079]
It seems that `additionalRules`, `excludeFiles`, and `preset` are valid rules, however they are not documented here:
http://jscs.info/rules?q=additionalRules
http://jscs.info/rules?q=excludeFiles
http://jscs.info/rules?q=preset

**Comment by hzoo** [comment]
They are valid options not rules. Check out overview: http://jscs.info/overview#options.

**Comment by cookch10** [comment]
@hzoo I see that now.  Thank you for the clarification.
