### ISSUE TITLE
requireCommaBeforeLineBreak autofix eliminates the line break

### ISSUE THREAD

**Issue by dryoma** [jscs-dev/node-jscs#2081]
Not sure if this is an issue.

If `requireCommaBeforeLineBreak` is set to `true`, running `jscs --fix file.js` changes this code:
```
var c = {
    a: 10
    , b: 12
    , c: 11
};
```
into this:
```
var c = {
    a: 10, b: 12, c: 11
};
```
(spaces are not important) Meanwhile, `requireOperatorBeforeLineBreak` - somewhat similar, but for operators, - moves the operator to the previous line:
```
var c = a
    + b;
```
becomes 
```
var c = a +
    b;
```

So is `requireCommaBeforeLineBreak` autofixing expected to work the same way: moving commas to previous lines while preserving line breaks?

I'm using node-jscs v2.7.0 on node v4.2.2, Windows 7 x86.

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
