### ISSUE TITLE
Airbnb preset: current state?

### ISSUE THREAD

**Issue by pm5** [jscs-dev/node-jscs#2085]
I realized there are some rules in [Airbnb style guide](https://github.com/airbnb/javascript) that are not implemented in current [airbnb preset](https://github.com/jscs-dev/node-jscs/blob/master/presets/airbnb.json).  A quick scan shows the following missing rules:

```
disallowVar
disallowIdentifierNames
requireEnhancedObjectLiterals
requireObjectDestructuring
requireArrayDestructuring
requireTemplateStrings
requireFunctionDeclarations
requireArrowFunctions
disallowParenthesesAroundArrowParam
requireShorthandArrowFunctions
disallowParenthesesAroundArrowParam
disallowNewlineBeforeBlockStatements
disallowPaddingNewlinesInBlocks
maximumLineLength
requireDollarBeforejQueryAssignment
```

My question is where should I send a PR to fix this?  From #1811 it seems that the Airbnb preset is moving to another place, but I'm not sure if I should wait until airbnb/javascript/pull/455 gets resolved.

**Comment by hzoo** [comment]
Yeah I wrote that comment if the airbnb/javascript repo wanted to host the preset instead of us but I'm not sure that it's happening anytime soon. I just added those in https://github.com/airbnb/javascript/pull/682 but yeah we can update the preset here.

**Comment by markelog** [comment]
In other words, we would welcome the pr from you :-)

**Comment by pm5** [comment]
Okay.  I think #2089 fixed most of the missing rules I see.

**Comment by markelog** [comment]
https://github.com/jscs-dev/node-jscs/pull/2089#issuecomment-179094387
