### ISSUE TITLE
Unexpected error with validateLineBreaks

### ISSUE THREAD

**Issue by gustafl** [jscs-dev/node-jscs#2086]
I'm having a problem with the `validateLineBreaks` rule. The docs seem to contradict how the `character` option work. The docs says:

> String specifies the line break character that is allowed. (Values allowed: "CR", "LF" or "CRLF")

I set it to `"CRLF"`, because in my files lines end with CRLF. But I still get an error. If I set it to `"LF"`, I get no error. See images below:

![newline_error.png](http://gustaf.us/temp/newline_error.png)

![jscsrc.png](http://gustaf.us/temp/jscsrc.png)

![hexview.png](http://gustaf.us/temp/hexview.png)

**Comment by markelog** [comment]
There might be a lot of things that could affect it. Do you have `.editorconfig`/`.gitattributes` file? What mode enabled in sublime? You can see it with view -> line edings

**Comment by gustafl** [comment]
Thank you for the quick feedback. I have neither `.editorconfig` nor `.gitattributes` in my current project. The View > Line Endings setting is set to Windows. It makes no difference how I set it.

**Comment by gustafl** [comment]
Perhaps the error I get is due to a clash of rules in the `.jscsrc` file? I put the whole file [here](http://gustaf.us/temp/.jscsrc), in case it helps.

**Comment by markelog** [comment]
Sorry, can't reproduce, feel free to check out the code, we would welcome the pr, if error is indeed there
