### ISSUE TITLE
Ability to treat multiple var and const/let more distinctly

### ISSUE THREAD

**Issue by sholladay** [jscs-dev/node-jscs#2090]
I am a big fan of the `requireMultipleVarDecl` option. Prior to ES6, the `onevar` mode worked exactly the way I wanted it to. It makes tons of sense because it helps to prevent genuine (but often silent) bugs in code written by developers who don't understand hoisting while also being tidy in terms of style.

However, with the advent of block-scoped let/const, the reasonable thing is just about the opposite. You should declare them as close as possible to their point of first use. They have a [temporal dead zone](http://jsrocks.org/2015/01/temporal-dead-zone-tdz-demystified/) that makes this particularly great.

What I want from JSCS is effectively:
`"requireMultipleVarDecl" : "onevar"` for `var`
`"requireMultipleVarDecl" : true` for `let` and `const`

**I would like these to pass:**
````javascript
var x = 1;
let y = 2;
const z = 3;
````
````javascript
var x = 1;
const y = 2;
x++;
const z = 3;
````
````javascript
var x = 1;
const
    y = 2,
    z = 3;
````

**I would like these to error:**
````javascript
var x = 1;
x++;
var y = 2;
````
````javascript
var x = 1;
const y = 2;
// Comments don't change the fact that
// this is consecutive. Yuck.
const z = 3;
````

**Comment by markelog** [comment]
Sounds like a different rule to be honest, since this - 

> You should declare them as close as possible to their point of first use.

Is still looks debatable, especially given that in many languages you also can't use variables before they were initialized, but they still follow convention of defining all used variables at the beginning of the subprogram, in other words, some people might find current behaviour appealing.

Having said that do you want to add such rule(s)?

**Comment by sholladay** [comment]
Fair enough. But if anything, I would expect `onevar` to only apply to `var`.

At any rate, I would be fine with a separate option. Whatever works. :)

I have limited bandwidth to do this myself, I would appreciate it if someone else took it on. It *seems* to me like many people are going to want it as ES6 get more adoption.

If no one picks it up, I might get a PR together at some point.

**Comment by markelog** [comment]
Ping us up, if you still interested
