### ISSUE TITLE
disallowNestedTernaries - invalid option types described on website

### ISSUE THREAD

**Issue by cookch10** [jscs-dev/node-jscs#2092]
The `disallowNestedTernaries` rule described [here](http://jscs.info/rule/disallowNestedTernaries) indicates that values for the rule take a `boolean` or an `integer`.  However, the example and inspection of the source indicates it takes a `boolean` or an `object`, where the `object` has a `maxLevel` integer attribute.

**Comment by markelog** [comment]
It works as expected - https://github.com/jscs-dev/node-jscs/blob/72f9cb5ce85fb6a2fa737a791e8227de79b743cf/test/specs/rules/disallow-nested-ternaries.js#L12

JS is confusing sometimes :)

**Comment by cookch10** [comment]
@markelog None of the test describe a test where an integer is passed in as an option.

**Comment by hzoo** [comment]
Then it sounds like we need to change the docs to say an object with a maxLevel property that takes an integer (like in other rules), would you like to do a PR?

**Comment by cookch10** [comment]
Sure, I'll create a PR for it.

**Comment by markelog** [comment]
Oh, i see what you mean, yeah, pr welcome

**Comment by cookch10** [comment]
I also noticed incosistency in the rule / example for [disallowSpaceAfterObjectKeys](http://jscs.info/rule/disallowSpaceAfterObjectKeys) which I will fix as part of the PR.

**Comment by markelog** [comment]
Friendly ping

**Comment by cookch10** [comment]
Been on my list (which is a long one).  Will take a look now.

**Comment by cookch10** [comment]
Just about there.  Not that it matters in this case since it's a matter of changing comments, but running `npm test` on my Windows 7 x64 machine hangs / fails:

```bash
c:\dev\proj\node-jscs>npm test

> jscs@2.9.0 pretest c:\dev\proj\node-jscs
> npm run lint

> jscs@2.9.0 lint c:\dev\proj\node-jscs
> jshint . # && node bin/jscs lib test bin publish

ERROR: Can't open #
```
