### ISSUE TITLE
v2.9.0 contained a breaking change, should be semver-major

### ISSUE THREAD

**Issue by ljharb** [jscs-dev/node-jscs#2095]
The `requireCapitalizedConstructorsNew` rule defaults to on - thus v2.9.0 is a breaking change in that tests fail that passed on v2.8.0 with identical config.

Please release a v2.9.1 with this defaulting to `false`.

**Comment by hzoo** [comment]
We've been doing these changes for a while though https://github.com/jscs-dev/node-jscs/blob/master/OVERVIEW.md#versioning--semver

This is probably the best reason for why presets should be moved out of the repo / just versioned independently since every rule change is breaking/major right?

**Comment by ljharb** [comment]
preset changes are likely to be major but don't have to be.

It's not new rules that are breaking - it's defaulting them to "on". Adding a new rule is always a minor, and fixing a bug is always a patch. I realize it's tricky specifically with linter rules.

**Comment by hzoo** [comment]
Yeah it's weird and I certainly see how it's breaking - @markelog. Also would https://github.com/airbnb/javascript be willing to host/maintain the airbnb preset? https://github.com/jscs-dev/node-jscs/issues/1811

**Comment by ljharb** [comment]
Absolutely - let's have an off-github discussion about what's involved first :-)

**Comment by markelog** [comment]
See http://jscs.info/overview#versioning-semver
