### ISSUE TITLE
Special case for "if" in requireKeywordsOnNewLine

### ISSUE THREAD

**Issue by sholladay** [jscs-dev/node-jscs#2096]
When supplying `if` in the array for `requireKeywordsOnNewLine`, I came across an issue that seems obvious in hindsight, but I didn't think of at the time,

This code fails:
````javascript
if (x) {}
else if (y) {}
else {}
````

It fails because the `if` in `else if` is not on a new line. But that's not really what I was trying to convey to `JSCS` about what I wanted. I want it to know that `if` and `else if` are different things.

**Comment by markelog** [comment]
So what do you propose?

**Comment by sholladay** [comment]
Well is it crazy to assume no one is writing code like this:
````javascript
if (x) {
    // ...
}
else
if () {
    // ...
}
````

Until someone comes along and says they desire to split up `else if` onto two lines, which I've never seen, I think it would be reasonable for `jscs` to just assume this is an exception when `if` is supplied.

**Comment by markelog** [comment]
Feel free to send us a pr for it
