### ISSUE TITLE
Special case for "typeof" in requireSpaceBeforeKeywords

### ISSUE THREAD

**Issue by sholladay** [jscs-dev/node-jscs#2097]
There are some common exceptions for people who otherwise really want spaces before their keywords.
````javascript
if (typeof x === 'foo') {

}
````

Currently, that code fails when using `requireSpaceBeforeKeywords : true`. At the moment, the only alternative is to specify every other keyword as an array. Maybe the `allExcept` pattern is appropriate here?

**Comment by markelog** [comment]
Sounds good!

**Comment by gpiress** [comment]
I think this issue is solved by the pull request https://github.com/jscs-dev/node-jscs/pull/2063. It creates the allExcept value for this very rule =).

**Comment by markelog** [comment]
Yay!
