### ISSUE TITLE
ES6 shorthand methods confuse requireSpacesInAnonymousFunctionExpression

### ISSUE THREAD

**Issue by sholladay** [jscs-dev/node-jscs#2098]
The rule `requireSpacesInAnonymousFunctionExpression` is triggering errors for [ES6 shorthand methods](http://www.benmvp.com/2015/09/learning-es6-enhanced-object-literals.html), which are not anonymous.

**Error:**
````javascript
Missing space before opening round brace
````

**Sample code:**
````javascript
const foo = {
    doStuff() {
        console.log();
    }
};
````

**Configuration:**
````javascript
"requireSpacesInAnonymousFunctionExpression" : {
    "beforeOpeningRoundBrace" : true,
}
````

**Comment by hzoo** [comment]
There's an option for shorthand http://jscs.info/rule/requireSpacesInAnonymousFunctionExpression

Yeah it's true its not 'anonymous` but it is that way in the AST/ESTree http://astexplorer.net/#/f7rzQ9dHCc (FunctionExpression with id null)

**Comment by sholladay** [comment]
I did actually see that, but I assumed that would then not enforce a space before the curly brace. Is that not the case? I didn't bother testing that. I still want the curly space enforced for shorthand methods.

**Comment by markelog** [comment]
Okay, it seems question is answered, ping us up, if i'm wrong

**Comment by sholladay** [comment]
This does not behave as I desire.

I want this to error due to lack of space before the curly brace, but it does not with the `allExcept` hack.

````javascript
const foo = {
    doStuff(){
        console.log();
    }
};
````
