### ISSUE TITLE
ES6 shorthand methods confuse requireSpaceAfterObjectKeys

### ISSUE THREAD

**Issue by sholladay** [jscs-dev/node-jscs#2099]
The rule `requireSpaceAfterObjectKeys` is triggering errors for [ES6 shorthand methods](http://www.benmvp.com/2015/09/learning-es6-enhanced-object-literals.html). The purpose of this rule is to ensure separation between the key and the colon `:` in property definitions, but when defining an ES6 shorthand method, the colon is not used at all, and thus there is no need to separate it from anything.

In my opinion, the spacing between the "key" and the round braces should be left to one of the existing `...SpacesInFunction...` rules, in this case.

**Error:**
````javascript
Missing space after key
````

**Sample code:**
````javascript
const foo = {
    doStuff() {
        console.log();
    }
};
````

**Configuration:**
````javascript
{
    "requireSpaceAfterObjectKeys" : true
}
````

**Comment by alawatthe** [comment]
> The purpose of this rule is to ensure separation between the key and the colon : in property definitions

Uhm, well no, I think the purpose of ```requireSpaceAfterObjectKeys``` is to require a space after the keys in an object . Completely independent whether the key is followed by a colon or not.

So if you put a space after the ```doStuff``` like this:
```js
const foo = {
    doStuff () {
        console.log();
    }
};
```
JSCS does not complain at all.

That said, I think the rule could have an option like:
```js
{
    "requireSpaceAfterObjectKeys" : {
        allExcept: ["shorthandMethods"]
    }
}
```

**Comment by sholladay** [comment]
Sure, fine, but traditionally there has been *no other possible way to use it*. Let's not pretend like its name means it will handle all new ways of keying an object without some fresh thinking.

The shorthand is for:
````javascript
const foo = {
    doStuff : function doStuff() {

    }
};
````

If you want to see `doStuff()` as a key with some braces immediately after it, fair enough. That's not wrong. But the entirety of the shorthand comes from the method signature. It is not really the same category of thing that I want to reason about here.

I would most prefer to handle the spacing for these in a `...SpacesInFunction...` rule. But if it has to be an exception for keys, so be it. Not worth much debate.

**Comment by alawatthe** [comment]
I am in no way against the style and think it should be added to JSCS. Do you want to implement it? :-D

**Comment by markelog** [comment]
It is hard to understand what is the "key" in this situation, if are strict about it it seems @alawatthe is right, but neither rule has been expected to handle such cases nor it logical perceivable.

Anyway, looks as a bug to me, i think there is no need for option, it could be handled by different rule.

To echoing @alawatthe question - @sholladay would you like to fix it?

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.

**Comment by sholladay** [comment]
So there's no interest in this? I can't contribute a PR anytime soon.
