### ISSUE TITLE
Space before and after the equal sign

### ISSUE THREAD

**Issue by billen** [jscs-dev/node-jscs#2100]
Have a rule that spaces out after each variable assignment.

```javascript
//bad
$scope.hello=function(){ 

//good
$scope.hello = function(){ 
```

**Comment by markelog** [comment]
http://jscs.info/rule/requireSpaceAfterBinaryOperators and http://jscs.info/rule/requireSpaceBeforeBinaryOperators

**Comment by billen** [comment]
My apologies! Thank you for the links!
