### ISSUE TITLE
requireCamelCaseOrUpperCaseIdentifiers - strict is misleading

### ISSUE THREAD

**Issue by trystanj** [jscs-dev/node-jscs#2109]
Either the docs are misleading or strict is not working as expected.

Under **Valid for mode `strict`**, the following is okay:
```javascript
var UPPER_CASE = 4
```
[source](http://jscs.info/rule/requireCamelCaseOrUpperCaseIdentifiers)

This simply does not work, nor does `var UPPER = 4`

So. Is strict truly strict even in the case of UPPER_CASE (in which case the documentation should be fixed) or should UPPER_CASE (and UPPER) be allowed in strict mode (in which case the linter should be fixed)?

**Comment by markelog** [comment]
Seems as 

> Is strict truly strict even in the case of UPPER_CASE

Should be true, i see in docs note about it though - 

> strict: boolean that forces the first character to not be capitalized

What kind of clarification do you think is needed?

**Comment by trystanj** [comment]
If that's the case, then `var UPPER_CASE = 4;` should be invalid for mode strict, not valid (as it is currently listed)

**Comment by Prairie-Falcon** [comment]
Another vote: I was surprised to receive a report "requireCamelCaseOrUpperCaseIdentifiers: All identifiers must be camelCase or UPPER_CASE" for line "const COUNTRY_US = 'US'". The identifier there appears to pass the test of "UPPER_CASE"; it'd be better for this not to generate a report.

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
