### ISSUE TITLE
Semicolons become mandatory after a class property 

### ISSUE THREAD

**Issue by ChrisCinelli** [jscs-dev/node-jscs#2112]
Babel 6.4 started reporting errors when a class property do not end in a semicolon. 
jscs seems not even be bother that the semicolons are missing there.

In particular it would be great if `--fix-` could fix this problem since we now have hundreds of classes and almost all files are missing multiple semicolons.

See also http://stackoverflow.com/questions/35103415/autofix-babel-6-4-a-semicolon-is-required-after-a-class-property

**Comment by hzoo** [comment]
Yeah you can use the requireSemicolons rule for this.

**Comment by markelog** [comment]
@hzoo so we can close this, right?

**Comment by ChrisCinelli** [comment]
I am using atom-jscs. This is my `.jscrc`:

```
{
  "preset": "airbnb",
  "disallowSpacesInAnonymousFunctionExpression": null,
  "validateLineBreaks": "LF",
  "validateIndentation": 2,
  "excludeFiles": ["build/**", "node_modules/**"],
  "requireSemicolons" : true,
  "esnext": true,
  "validateQuoteMarks": null
}
```

Class properties without a semicolon are not highlighted with a linting error and not fixed.

**Comment by hzoo** [comment]
Did you update to jscs 2.9.0? It was added in that version

**Comment by ChrisCinelli** [comment]
No, I am using Atom-linter-jscs that apparently has not update yet.
See also : https://github.com/AtomLinter/linter-jscs/issues/171 and https://github.com/AtomLinter/linter-jscs/commits/master/package.json

**Comment by hzoo** [comment]
You should be able to reinstall that package and it would have the latest dependency right? It's using `^` https://github.com/AtomLinter/linter-jscs/blob/master/package.json#L18
