### ISSUE TITLE
Feature request: Disable exponentiation operator

### ISSUE THREAD

**Issue by jamesdwilson** [jscs-dev/node-jscs#2113]
I would like a rule to disable the exponentiation operator, I feel it is too fragile of a feature and too easy to typo to introduce bugs. 

Example:

Exponentiation operator – **
The exponentiation operator – or a ** b – is the syntactic equivalent to doing Math.pow(a, b). It’ll work similarly to the exponentiation operator in Python. (care of https://ponyfoo.com/articles/es2016-features-and-ecmascript-as-a-living-standard#exponentiation-operator )

1 ** 2 === Math.pow(1, 2)
// <- true
Just like with any other operators, it’s possible to mix exponentiation with assignment, as show below.

var a = 2;
a **= 3; // equivalent to a = Math.pow(a, 3)
console.log(a);
// <- 8

**Comment by hzoo** [comment]
This should be simple to do but I don't think we want to make a rule just to disable the operator (should be a bit more general). Could be a `disallowOperators` or modify http://jscs.info/rule/disallowNodeTypes to pass in certain parameters.

**Comment by jamesdwilson** [comment]
:+1:

On Sun, Jan 31, 2016 at 6:55 PM, Henry Zhu <notifications@github.com> wrote:

> This should be simple to do but I don't think we want to make a rule just
> to disable the operator (should be a bit more general). Could be a
> disallowOperators or modify http://jscs.info/rule/disallowNodeTypes to
> pass in certain parameters.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jscs-dev/node-jscs/issues/2113#issuecomment-177678232>
> .
>



-- 
Thank you!

**Comment by hzoo** [comment]
Also we are open to PRs if you're willing to give it a shot! https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/disallow-node-types.js is actually very simple with no options. I suppose `disallowOperators` would be ok.

**Comment by markelog** [comment]
Ping us up, if you would try to fix this
