### ISSUE TITLE
Docs: Any way to get fixes related to individual issues?

### ISSUE THREAD

**Issue by sils1297** [jscs-dev/node-jscs#2117]
I understand jscs can point out issues and can automatically fix files. Is there any way to e.g. get all issues with a unified diff appended as JSON or something?

Background: I'm lead developer of coala (coala-analyzer.org) in the quest to make it for you people in the future easier to create code analysis (simply write your logic, coala handles paralellization, user interaction, editor plugins, dependency handling and so on - completely language independent; also you can reuse language independent routines e.g. for spacing correction, no need to rewrite those, right?) and for users easier to use it (one user interface and config that manages all languages and tools). So we want jscs because you do an awesome job and apparently have fixes, ideally we want them to be correlated to the issues they solve one by one.

**Comment by markelog** [comment]
> I understand jscs can point out issues and can automatically fix files. Is there any way to e.g. get all issues with a unified diff appended as JSON or something?

You mean output the ast structures?

**Comment by sils1297** [comment]
Not really. So JSCS has certain rules, we'd love to get for each violation the following information:

1. The rule it violates
2. The information on how to fix it.

I understand you have the `--fix` option but I'd love to get this data correlated with the issues/violations.

Still confusing? :/

**Comment by markelog** [comment]
Sorry, forgot about this one.

> The rule it violates

That is basically running a jscs without `--fix` flag

> The information on how to fix it.

Only link to the docs of specific rule is suited here i guess.
