### ISSUE TITLE
Bug with safeContextKeyword and destructuring with multiple-variable declarations

### ISSUE THREAD

**Issue by jimf** [jscs-dev/node-jscs#2119]
The following should not warn, but currently does:

```js
const a = 1, { smth } = this;
```

#1699 did not take multi-var declarations into account.

I'm looking into fixing this myself, but still wrapping my head around how the tokenizing works and figured I'd open the issue if its a quick fix for someone else.

**Comment by markelog** [comment]
Did you made any progress?

**Comment by jimf** [comment]
Unfortunately no. I haven't spent the time to look into it :sweat:. I'll try and take another look.

**Comment by jimf** [comment]
Okay, I've got this squared away. About to head on the road shortly, but I'll have a PR up by EOD.
