### ISSUE TITLE
\n inside backticks replaced with actual newline on fix

### ISSUE THREAD

**Issue by dwelle** [jscs-dev/node-jscs#2120]
```
var s = `\n`
```

is replaced (via fix on save) with:

```
var s = `
`
```

possibly related to https://github.com/jscs-dev/node-jscs/issues/2015

running `v2.9.0` via [AtomLinter/linter-jscs](https://github.com/AtomLinter/linter-jscs)

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
