### ISSUE TITLE
False positive for "jQuery identifiers must start with a $"

### ISSUE THREAD

**Issue by pascalberger** [jscs-dev/node-jscs#2126]
Having the following code I get an `jQuery identifiers must start with a $` error from JSCS:

    var title = $('div').first().text();

Since `.text()` returns a string (contrary to `.text(text)`) the message should not be thrown in this case.

**Comment by markelog** [comment]
Would you like try to fix this?

**Comment by pascalberger** [comment]
@markelog I don't have the inside into the code for being able to quickly fix this, and unfortunately don't think have the time to digg into it. Sorry.

**Comment by gpiress** [comment]
Has this issue been fixed already?

I can't seem to reproduce it. Using the current master version, I've created an unit test for the rule to check it, and it correctly passes (marks as no $ sign needed).

I also tried to add it to a js file and linting it using the rule, and I also didn't get any errors.

With the current master version, is it still showing a false-positive for `var title = $('div').first().text();`? If so, can you provide an example so I can look into it?

**Comment by markelog** [comment]
Nope, this still should be reproducible, right now, this rule basically checks that if some function called `$` then result of it should also starts with `$`

**Comment by gpiress** [comment]
There is this test, lines 104 to 106 of the `require-dollar-before-jquery-assignment` spec file:

```
it('should not report chained jquery operator with variable', function() {
    expect(checker.checkString('var x = $(evt.target).val();')).to.have.no.errors();
});
```

And this test is passing, which I guess covers the case of the issue? I'm failing to reproduce this issue here =/

**Comment by markelog** [comment]
Hm, yeah you right, apparently rule stop checking when it detects chaining, which is not ideal, but i guess enough to close this ticket
