### ISSUE TITLE
changelog missing v2.10.0

### ISSUE THREAD

**Issue by ljharb** [jscs-dev/node-jscs#2134]
I'd assume updating this is part of the release process :-/

**Comment by hzoo** [comment]
Oh yeah, its because i'm publishing to the `2.x` branch. https://github.com/jscs-dev/node-jscs/tree/2.x

**Comment by ljharb** [comment]
Thanks, ideally changelogs and readmes should be cherry-picked to master (or, "master" should be the same as "latest", and unreleased majors should be what's in a separate branch)

**Comment by hzoo** [comment]
Ah yeah. I figured we would spend more time on 3.x and not do any more 2.x changes so we switched it
