### ISSUE TITLE
disallowSpacesInsideTemplateStringPlaceholders incorrect

### ISSUE THREAD

**Issue by justin808** [jscs-dev/node-jscs#2137]
This just started on 2.9:

```
disallowSpacesInsideTemplateStringPlaceholders: Illegal space before "}" at ./node_package/tests/buildConsoleReplay.test.js :
    52 |  ];
    53 |  const actual = consoleReplay();
    54 |  const expected = `console.log.apply(console, ["some message","{\\"a\\":1,\\"b\\":2}"]);
--------------------------^
    55 |console.warn.apply(console, ["other message","{\\"c\\":3,\\"d\\":4}"]);`;
    56 |  assert.equals(actual, expected, 'Unexpected value for console replay history');
```

jscs is not catching the fact that the syntax within the backticks is for interpolation.

https://github.com/shakacode/react_on_rails/blob/master/node_package%2Ftests%2FbuildConsoleReplay.test.js#L52

@ikokostya, here's the issue: https://github.com/jscs-dev/node-jscs/blob/0c4602569fb435bf98127617fe9745db173f88d5/lib/rules/disallow-spaces-inside-template-string-placeholders.js#L59

you're not checking that we're inside of an interpolation.

TBH, I think some better parsing needs to be done for the beginning and the end.

Maybe you can crib how babel is doing this?

CC: @alexfedoseev

**Comment by ikokostya** [comment]
Look like this issue affects only `2.x` branch: https://github.com/jscs-dev/node-jscs/blob/2.x/lib/rules/disallow-spaces-inside-template-string-placeholders.js#L60
