### ISSUE TITLE
disallowSpacesInsideTemplateStringPlaceholders false positive

### ISSUE THREAD

**Issue by ronkorving** [jscs-dev/node-jscs#2144]
On

```js
var s = `some string without vars`;
```

This rule outputs `Illegal space before "}"`

This is on JSCS 2.10.1.

**Comment by ronkorving** [comment]
Thanks for the fix!

**Comment by graingert** [comment]
@markelog do you know when this will be released?

**Comment by markelog** [comment]
Monday

**Comment by graingert** [comment]
@markelog sweet

**Comment by markelog** [comment]
Waiting for pr, pushing to Tuesday
