### ISSUE TITLE
requireUseStrict to ensure strict mode is used

### ISSUE THREAD

**Issue by erikvold** [jscs-dev/node-jscs#2146]
It would be nice if there was a check called `requireUseStrict` or maybe `requireStrictMode` that each js file started with `"use strict";`.

To start the value could just be set to `true` or `false`/`undefined`, later we could perhaps add something like `{ "functions": true, "files": false }`

**Comment by markelog** [comment]
Sounds good, would you like to implement it?

**Comment by erikvold** [comment]
sure

**Comment by erikvold** [comment]
Hmm I've come to realize that we should just accept a `true` value, I don't see why someone would require that people use `"use strict";` in every functions, but not at the file level.  And if it turns out someone can come up with a reason why that is useful then we can add it later.

**Comment by erikvold** [comment]
@markelog review?
