### ISSUE TITLE
Browser version

### ISSUE THREAD

**Issue by TrySound** [jscs-dev/node-jscs#2150]
I think you shouldn't publish 4mb of browserified bundle on npm. Nobody will use so big lib.

**Comment by markelog** [comment]
Some people used it with desktop app, without firing up the node, not sure if it makes sense now though...

**Comment by markelog** [comment]
Why this was closed?

**Comment by TrySound** [comment]
@markelog I thought you removed it. Not?

**Comment by markelog** [comment]
Nuh, but let's do this

**Comment by TrySound** [comment]
Thanks
