### ISSUE TITLE
please update the changelog in master as part of the 2.x release process

### ISSUE THREAD

**Issue by ljharb** [jscs-dev/node-jscs#2154]
v2.10.1 is missing in the master branch changelog.

Please consider making sure the default branch is the same as the last released major? You could make `2.x` the default until you're ready to release v3, perhaps.

**Comment by ljharb** [comment]
also v2.11.0 now :-(

**Comment by markelog** [comment]
It seems we just need to stop releasing 2.x

**Comment by ljharb** [comment]
Certainly deciding to not be fearful since releases are cheap, and just releasing 3.x and fixing bugs as they come, is a totally valid option :-)

**Comment by markelog** [comment]
Not all tests are passing in 3.0 at the moment

**Comment by ljharb** [comment]
master branches where all tests aren't passing make me sad

**Comment by markelog** [comment]
"unstable master approach" is popular in some workflows or at the transition periods, this is the latter
