### ISSUE TITLE
disallowMultipleVarDecl with "require" does not allow requires to be called as functions

### ISSUE THREAD

**Issue by willharris** [jscs-dev/node-jscs#2155]
I have a problem similar to the one fixed in PR #1849, except this occurs when the result of a require is immediately called as function.
```
var argv = require('yargs').argv,
    gulp = require('gulp-help')(require('gulp')),
    gutil = require('gulp-util');
```
As a work-around its possible to split it up:
```
var argv = require('yargs').argv,
    gulp-help = require('gulp-help'),
    gutil = require('gulp-util');
var gulp = gulp-help(require('gulp'));
```
but that's a bit inelegant.

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
