### ISSUE TITLE
disallowTrailingComma doesn't understand array destructuring

### ISSUE THREAD

**Issue by artoale** [jscs-dev/node-jscs#2159]
This line:
```javascript
let [firstElement,] = someFunction()
```

triggers the rule `disallowTrailingComma`. It is though a perfectly legit es6 syntax using [destructuring assignment](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment).

I believe this should be checked by its own rule

**Comment by markelog** [comment]
All trailing comma code is legit js, this is a comma and it is trailing

**Comment by artoale** [comment]
@markelog yeah - what you're saying is correct, but it makes sense to have separate rules for disallowing trailing commas in array literals and in destructuring assignment since reasons for allowing one or the other can be fairly different.

**Comment by markelog** [comment]
We don't accept new features at this time :/, see https://medium.com/@markelog/jscs-end-of-the-line-bc9bf0b3fdb2 and http://eslint.org/blog/2016/04/welcoming-jscs-to-eslint for more
