### ISSUE TITLE
ES6, object keys, and spaces in function expression

### ISSUE THREAD

**Issue by indexzero** [jscs-dev/node-jscs#2161]
EDIT: updated to reflect `disallowSpacesInNamedFunctionExpression.beforeOpeningRoundBrace`
EDIT: updated BACK to reflect `requireSpacesInAnonymousFunctionExpression.beforeOpeningRoundBrace` based on #2162

The following config:

``` js
{
  "disallowSpaceAfterObjectKeys": true,
  "requireSpacesInAnonymousFunctionExpression": {
    "beforeOpeningRoundBrace": true
  },
  //
  // Also applies to less specific cousins
  // of requireSpacesInAnonymousFunctionExpression
  //
  // "requireSpacesInFunctionExpression": {
  //   "beforeOpeningRoundBrace": true
  // }
}
```

when evaluating the following ES6 code leads to an ambiguous resolution:

``` js
var fns = {
  foo() {
    console.log('hey Imma function');
  },
  /*function*/ because() {
    console.log('[space]function[space] becomes [space]');
  }
};
```

**Comment by indexzero** [comment]
Note: even **more interesting** is when `autofix` is enabled which leads to the fixer resolving this ambiguous rule ... well ambiguously as [@DullReferenceException noted here](https://github.com/jscs-dev/node-jscs/pull/2162#issuecomment-192342644)

> (...) the autofixer will add a space in one run, then remove it in the next.

**Comment by indexzero** [comment]
So the take away here is that we needed `allexcept: shorthand`. I'm going to leave this issue open to see if there might be a better way to explain these types of inherent conflicts https://github.com/jscs-dev/node-jscs/pull/2162#issuecomment-194422173

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
