### ISSUE TITLE
requireVarDeclFirst rule doesn't recognize ES6 arrow functions provide a new function scope

### ISSUE THREAD

**Issue by kfoisy** [jscs-dev/node-jscs#2163]
When declaring a variable at the top of an ES6 arrow function, a new scope isn't recognized. The following code gives a "Variable declarations must be the first statements of a function scope." error, when it shouldn't:

`() => {
var something = 'test';
}`

**Comment by fernandopasik** [comment]
This behaviour is affecting also to requireMultipleVarDecl='onevar', as it says that the declarations should be joined.

**Comment by oredi** [comment]
@markelog Sad to see JSCS go away. Anyway sorry for being away for so long, I hope to get some time to look back here now that I am done with relocation. Are we still fixing issues that are open.

**Comment by markelog** [comment]
Works for me
