### ISSUE TITLE
disallowSpacesInsideParentheses: true seems to disable all other rules

### ISSUE THREAD

**Issue by alexschrod** [jscs-dev/node-jscs#2167]
When I leave out `disallowSpacesInsideParentheses` and run jscs (through grunt, if that matters), it displays `>> 46 code style errors found!` with my codebase. Various kinds of errors show up, like `disallowImplicitTypeConversion` and `requireCamelCaseOrUpperCaseIdentifiers`.

However, after adding `"disallowSpacesInsideParentheses": true` to my .jscsrc file, I instead get `>> 22 files without code style errors.`

The version of jscs I'm using is 2.11.0. I'm using Ubuntu Linux 15.04.

**Comment by alexschrod** [comment]
Turning off auto-fixing made the errors return.

My guess as to what happened is that there was a conflict between `disallowSpacesInsideParentheses` and `requireSpacesInsideParentheses`, as I had `"preset": "jQuery"` at the top of my file, but had only gotten to the disallow* rules. I removed the preset, and so jQuery's `requireSpacesInsideParentheses: true` conflicted with my `disallowSpacesInsideParentheses: true`, and jscs just called it quits, I guess?

**Comment by markelog** [comment]
Yeah, it is generally not a good idea to have two conflicting rules

**Comment by alexschrod** [comment]
I suggest that it should probably be considered an error state in the configuration and jscs should probably spit out an error message or something instead of just pretending that everything is fine. I'm sure I'm not going to be the only one who accidentally enabled two conflicting rules.
