### ISSUE TITLE
jscs autofix failed to convert escaped slash

### ISSUE THREAD

**Issue by AuthorProxy** [jscs-dev/node-jscs#2172]
Simple test case: `console.log("\\" + 'test');`
Converted to: `console.log('\' + 'test');` (which is not valid js string)

JSCS should preserve escaping `console.log('\\' + 'test');`
Config file: https://gist.github.com/AuthorProxy/bffb5f9aa733e3ca6279#file-jscsrc

**Comment by markelog** [comment]
We use https://github.com/sindresorhus/to-single-quotes package for fixing this, you probably should open an issue there instead
