### ISSUE TITLE
Add new option to requirePaddingNewLineAfterVariableDeclaration

### ISSUE THREAD

**Issue by AuthorProxy** [jscs-dev/node-jscs#2173]
What about new option to this rule, something like `"allExcept": singleVar` or even better something like `"minRequiredVars": 1`. Like this rule but only when there more than 1 var declaration, it's very disqusting to have a lot of small methods (2-3 lines) with empty lines.

**Comment by markelog** [comment]
Would you like to implement it?

**Comment by AuthorProxy** [comment]
If nobody take it, I will

**Comment by hzoo** [comment]
We released [3.0](https://github.com/jscs-dev/node-jscs/releases/tag/v3.0.0)! We also wrote a [post](https://medium.com/@markelog/jscs-end-of-the-line-bc9bf0b3fdb2#.oot3wvgpu) about how 3.0 will be our last major release and that we are [merging with ESLint](http://eslint.org/blog/2016/04/welcoming-jscs-to-eslint).

So we won't be working on any new features moving forward including new rules/options. We will continue to fix bugs and work on CST and better autofixing for current rules in the upcoming months.

I'm putting an `orphaned` label to note this isn't being worked on unless someone wants to do a PR
