### ISSUE TITLE
Conflict between two rules because function* is not considered as a keyword

### ISSUE THREAD

**Issue by Skywalker13** [jscs-dev/node-jscs#2185]
In the case of a jscsrc config file with : 

```js
{
  "requireSpaceAfterKeywords": true,
  "disallowSpacesInGenerator": { "beforeStar": true }
}
```
```js
function* foobar() {}
```
Then `requireSpaceAfterKeywords` returns an error.

But IMHO `function*` should be considered as a keyword and not only `function`.

**Comment by markelog** [comment]
Duplicate of https://github.com/jscs-dev/node-jscs/issues/2168
