### ISSUE TITLE
npm ERR: "version not found: left-pad@0.0.3"

### ISSUE THREAD

**Issue by Krinkle** [jscs-dev/node-jscs#2186]
Most Travis builds using jscs started breaking today for me.

```
npm ERR! node v5.5.0
npm ERR! npm  v3.7.5

npm ERR! No compatible version found: left-pad@0.0.3
npm ERR! Valid install targets:
npm ERR! 0.0.9
```

```
├─┬ jscs@2.10.1
│ ├─┬ babel-jscs@2.0.5
│ │ ├─┬ babel-core@5.8.35
│ │ │ ├─┬ line-numbers@0.2.0
│ │ │ │ └── left-pad@0.0.3
```

It seems #2102 / cc5aa3538af0 would fix it (by no longer using babel-core all together), however that doesn't help stable release at the moment.

Could this be backported or otherwise fixed so that things aren't broken?

**Note:** I can still reproduce it with jscs v2.11.0.

**Comment by jishi** [comment]
https://medium.com/@azerbike/i-ve-just-liberated-my-modules-9045c06be67c#.15h0zv9yn

Nice dependency to have... for such a simple task.

**Comment by benbrown** [comment]
babel-core has been updated to fix this issue (5.8.38) 

https://github.com/azer/left-pad/issues/4#issuecomment-200068277

**Comment by paladox** [comment]
It works now.

**Comment by diffsky** [comment]
@paladox it's not working for me

```
npm install left-pad@0.0.3
npm ERR! Darwin 15.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "--registry" "https://registry.npmjs.org" "install" "left-pad@0.0.3"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.8

npm ERR! version not found: left-pad@0.0.3
```

**Comment by paladox** [comment]
@diffsky see https://twitter.com/seldo/status/712414588281552900

**Comment by diffsky** [comment]
@paladox yeah, I'm still not able to install it and I've verified with a few folks around me. Maybe something hasn't propagated.

**Comment by diffsky** [comment]
Working for me now
```
$ npm --registry https://registry.npmjs.org install left-pad@0.0.3
left-pad@0.0.3 node_modules/left-pad
```

**Comment by hzoo** [comment]
Yep seems to be fixed - I would follow https://github.com/azer/left-pad/issues/4 for more updates.

(new babel version published for babel5/6 and package was restored)
