### ISSUE TITLE
Indentation problems with arrays

### ISSUE THREAD

**Issue by brupelo** [jscs-dev/node-jscs#2192]
Hi,

I'm trying to create .jscsrc following standard conventions and i'm having some issue with jscs 2.11.0 and arrays, here's my .jscsrc file:

```
{
	"preset": "node-style-guide",
	"disallowSemicolons": true,
	"disallowSpacesInFunction": null,
	"requireSpaceAfterComma": true,
	"requireTrailingComma": null,
	"requireCamelCaseOrUpperCaseIdentifiers": null,
	"validateLineBreaks": null,
	"maximumLineLength": null,
	"validateQuoteMarks": "'",
    "requireSpacesInFunction": {
	    "beforeOpeningRoundBrace": true,
        "beforeOpeningCurlyBrace": true
    },
    "disallowMultipleSpaces": true,
	"requireCapitalizedComments": null,
	"disallowQuotedKeysInObjects": null,
	"disallowTrailingWhitespace": null,
	"validateIndentation": 2,
	"disallowMultipleLineBreaks": true
}
```

For instance, in this function i'd expect Sublime-Linter + SublimeLinter-jscs to notify me about the 4 spaces in that array, it's not saying anything though:

```
  initBuffers: function () {
    var gl = this.gl
    var triangleVertexPositionBuffer = this.triangleVertexPositionBuffer = gl.createBuffer()
    gl.bindBuffer(gl.ARRAY_BUFFER, triangleVertexPositionBuffer)
    var vertices = [
        0.0, 1.0, 0.0,
        -1.0, -1.0, 0.0,
        1.0, -1.0, 0.0
    ]
```

Is this a well known issue, any recommendation to fix it? 

PS: I'd prefer using jscs to check my code against standard convention instead standard itself, don't ask me why :-)

**Comment by markelog** [comment]
From http://jscs.info/rule/validateIndentation

> Validates indentation for switch statements and block statements

**Comment by brupelo** [comment]
@markelog : So, what does that mean? Did you see the .jscsrc i've pasted? I'm already using "validateIndentation": 2 .

When you say "Validates indentation for switch statements and block statements" you mean this is a jscs limitation won't be fixed? It'd be cool if arrays were indented properly, that way i could use jscs fix and standard wouldn't complain.

**Comment by markelog** [comment]
> When you say "Validates indentation for switch statements and block statements" you mean this is a jscs limitation won't be fixed?

We have tickets about this - https://github.com/jscs-dev/node-jscs/issues/1866, so if anyone has the time to implement this, it would be most appreciated.
