### ISSUE TITLE
excludeFiles: exclude project except several directories

### ISSUE THREAD

**Issue by DenJel7** [jscs-dev/node-jscs#2194]
I am trying to exclude all of my project in .jscsrc with the exception of several subdirectories. My .jscsrc is in the root directory. I have read many issues about this, but haven't found an answer.

I'd like to do something like this:

`excludeFiles: ["/**", "!src/ui/**", "!src/Applications/**"]`
In .eslintignore, this works. I don't understand how the glob patterns work in JSCS config.

Can you explain to me what my mistake is?

**Comment by markelog** [comment]
> "/**",

You probably need to removed the first slash
