### ISSUE TITLE
unexpected reports from requireTemplateStrings

### ISSUE THREAD

**Issue by Prairie-Falcon** [jscs-dev/node-jscs#2195]
No complaint here; just reporting.

I have
- Windows 10 Home, 64-bit, version 1511 (OS Build 10586.164)
- Node v5.7.0
- JSCS v2.11.0

My .jscsrc file includes this line:

    "requireTemplateStrings": {"allExcept": ["stringConcatenation"] },

http://jscs.info/rule/requireTemplateStrings
indicates that'll cause "ignores strings concatenated with other strings"

As I interpret that documentation, I don't expect to see this report, yet I see it.

    requireTemplateStrings: Illegal use of string concatenation. Use template strings instead. at <file> :
        18 |   let a = `a`
        19 |     , forJSCS = a + `b`
    --------------------------^

This is a great project! Thanks for your time on it.

**Comment by hzoo** [comment]
Looking at http://jscs.info/rule/requireTemplateStrings the `stringConcatenation` option is actually for a string + a string. For ``` a + `b` ```, its a variable and a string and we would probably want that to be a template string
