### ISSUE TITLE
requireShorthandArrowFunctions should not fire for functions that do not return

### ISSUE THREAD

**Issue by fluky** [jscs-dev/node-jscs#2196]
Probably just needs a new option for requireShorthandArrowFunctions.

Consider the case:

`
() => {
   return something;
}
`

This should trigger.  But 

`
() => {
   something ();
}
`

Should not trigger.

The reason is that the latter returns undefined instead of the result of something which could have a different effect in the code calling the function.

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
