### ISSUE TITLE
Possible bug in validateQuoteMarks

### ISSUE THREAD

**Issue by monoblaine** [jscs-dev/node-jscs#2198]
With a simple `.jscsrc` file like the following:

```json
{
  "validateQuoteMarks": { "mark": "'", "escape": true }
}
```

This line:

```js
var foo = "\\";
```

is converted (I'm using the "fix" option) into this:

```js
var foo = '\';
```

I'm using gulp-jscs btw, but this issue possibly belongs here.

Repo here: https://github.com/monoblaine/jscs-backslash-bug

**Comment by markelog** [comment]
We use https://github.com/sindresorhus/to-single-quotes package for fixing this, you probably should open an issue there instead
