### ISSUE TITLE
requireEnhancedObjectLiterals doesn't work with the set syntax

### ISSUE THREAD

**Issue by erikvold** [jscs-dev/node-jscs#2201]
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/set

Try on example `{set foo(v) {}}`, it fails.

**Comment by markelog** [comment]
Well, that's is incorrect syntax, while from you link, for the case - 
```js
var o = {
  set current (str) {
    this.log[this.log.length] = str;
  },
  log: []
}
```

I don't see any errors, which is what to be expected?
