### ISSUE TITLE
Unusual indentation enforcement

### ISSUE THREAD

**Issue by DarkArc** [jscs-dev/node-jscs#2210]
Given the correct code:
```
var a = function() {
  return function() {
    return true;
  };
};
```

JSCS Will correct the following invalid version of this:
```
var a = function() {
  return function() {
  return true;
  };
};
```

However, JSCS will not correct this invalid version, nor will it have any complaints:
```
var a = function() {
  return function() {
  return true;
};
};
```

**Comment by markelog** [comment]
Did you check it with master?

**Comment by DarkArc** [comment]
I did not, I'm using v2.11.0.

**Comment by markelog** [comment]
Ping us up if this behaviour is present in `master`.

**Comment by DarkArc** [comment]
@markelog I didn't get a chance to run this with master, but I just tried this with 3.0.2 (which is effectively master at the moment), it's still a problem.

**Comment by DarkArc** [comment]
Found another case:
```
var a = function() {
  return function() {
      return true;
  };
};
```
becomes
```
var a = function() {
  return function() {
      return true;
    };
};
```

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
