### ISSUE TITLE
Documentation for disallow returning array destructuring could be better. 

### ISSUE THREAD

**Issue by bcowgill** [jscs-dev/node-jscs#2211]
An explanation why one would want to disallow it would aid the user in choosing whether to select it.

 * Requires object destructuring for multiple return values,  * not array destructuring.
A quick google gave no obvious answers.

In general, I think the documentation would be more useful if it indicated whether the setting was a style issue or if there were other practical considerations. 

For example, no commas at end of line is not just style, it can make it easier to spot missing commas and easier to reorder list items without generating syntax errors.

**Comment by markelog** [comment]
We only interesting in style concerns, if you have improvement in mind please send a pr
