### ISSUE TITLE
breaking change in v3 with disallowQuotedKeysInObjects

### ISSUE THREAD

**Issue by ljharb** [jscs-dev/node-jscs#2213]
The changelog doesn't mention it, but `disallowQuotedKeysInObjects` no longer accepts "allButReserved".

**Comment by TheSavior** [comment]
I'm also getting an error on requireCamelCaseOrUpperCaseIdentifiers when upgrading from 2.11. It apparently no longer accepts `ignoreProperties`

```
requireCamelCaseOrUpperCaseIdentifiers option requires a true value or Object` 
```

**Comment by hzoo** [comment]
@ljharb right now it's `disallowQuotedKeysInObjects: { allExcept: ['reserved'] }`

@TheSavior right now it's an object with the `ignoreProperties` property. `requireCamelCaseOrUpperCaseIdentifiers: {ignoreProperties: true} `

Sorry, yeah we need to add these to the changelog

**Comment by ljharb** [comment]
@hzoo yes but `disallowQuotedKeysInObjects: "allButReserved"` worked in v2, thus it's an undocumented breaking change - the issue is just for the changelog.

**Comment by hzoo** [comment]
Just didn't get to finish it up in time for the release. And what do you know I just remembered I already did that work https://github.com/jscs-dev/node-jscs/pull/2110#issue-130002352.

**Comment by hzoo** [comment]
Ok reverting that https://github.com/jscs-dev/node-jscs/pull/2217 and will release 3.0.2 soon
