### ISSUE TITLE
requireImportsAlphabetized page doesn't load on jscs.info

### ISSUE THREAD

**Issue by ljharb** [jscs-dev/node-jscs#2214]
https://jscs.info/rule/requireImportsAlphabetized doesn't load for me.

**Comment by hzoo** [comment]
For this one, I think it's http://jscs.info/rule/requireImportAlphabetized

**Comment by markelog** [comment]
Hm it is weird it doesn't work with `https`

**Comment by ljharb** [comment]
if it's singular, then the changelog is wrong

**Comment by ljharb** [comment]
see https://github.com/jscs-dev/node-jscs/commit/096b6bf0bebc34e8a028a722d584a70af1168c2a#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR29

**Comment by artlogic** [comment]
There are a few other problems. The trailing backticks in all the links, and this particular rule is indeed singular on the site: http://jscs.info/rule/requireImportAlphabetized

**Comment by hzoo** [comment]
Yeah I fixed this on the releases page, but not the changelog
