### ISSUE TITLE
Breaking change from 2.11 to 3.0.2, unsupported rule esnext

### ISSUE THREAD

**Issue by TheSavior** [jscs-dev/node-jscs#2220]
When bumping jscs to 3.0.2, I get this error.

```
validateQuoteMarks: Unsupported rule: esnext at src/index.js :
     1 |'use strict';
```

My config looks like this:
```
{
  "plugins": ["wealthfront-javascript"],
  "preset": "wealthfront-javascript",
  "esnext": true
}
```

From the changelog it sounds like the goal was to make there be no breaking changes like this. It sounds like the configuration option was removed and I should remove it from my config.

**Comment by hzoo** [comment]
Thanks for reporting. I updated the changelog to clairfy. We removed options that we going to be on by default

**Comment by TheSavior** [comment]
It looks like the change made the error show up sooner, but it isn't a warning, it actually causes a build failure. 

```
Config values to remove in 3.0:
The `esnext` option is enabled by default.
```

https://travis-ci.org/TheSavior/clean-git-ref/jobs/123588553

**Comment by hzoo** [comment]
Ah yeah I threw an error. It wasn't warning before either but we could change it to a warning instead good point
