### ISSUE TITLE
validateQuoteMarks - error is pointing somewhere in the middle of the string

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#2223]
Probably not intentional?

```
validateQuoteMarks: Invalid quote mark found at lib/config/configuration.js :
   380 |
   381 |Configuration.prototype._errorOnRemovedOptions = function(config) {
   382 |    var errors = ["Config values to remove in 3.0:"];
-------------------------------------------^
   383 |
   384 |    if (config.hasOwnProperty('esprima')) {
```

**Comment by mdevils** [comment]
You think it's a bug?

**Comment by hzoo** [comment]
@zxqfox brought it up - it could be. I guess it depends 😄. It would be cool if the error reporter could give multiple locs - like start/end for a string

**Comment by zxqfox** [comment]
It points to the space at the moment 😺. And definitely looks like a bug.

**Comment by markelog** [comment]
Well it isn't one, it is by design, we can add exception for such rule though, since it is looks weird yeah :)
