### ISSUE TITLE
jscs 3.0.3: Multiline strings with a # incorrectly flagged as "Unterminated string constant"?

### ISSUE THREAD

**Issue by sverweij** [jscs-dev/node-jscs#2228]
running `jscs multistr-with-hash-NOK.js`
yields 

```
Unterminated string constant (1:22) at multistr-with-hash-NOK.js :
     1 |var multilinestring = "x\n\
------------------------------^
     2 |#";
     3 |console.log(multilinestring);


1 code style error found.
```

Whereas running `jscs multistr-without-hash-OK.js` validates AOK.

### Inputs
multistr-with-hash-NOK.js:
```
var multilinestring = "x\n\
#";
console.log(multilinestring);
```

multistr-without-hash-OK.js:
```
var multilinestring = "x\n\
y";
console.log(multilinestring);
```
### Version information
- jscs 3.0.3 on MacOSX 10.11.4 using node 5.10.1
- I haven't been able to isolate a single rule that triggers it (tried own config, google, airbnb and an .jscsrc with `{}` as content

**Comment by zxqfox** [comment]
@mdevils Is this issue about CST?

**Comment by mdevils** [comment]
I think it's actually for Babel

**Comment by mdevils** [comment]
Since this is a parse error from Babel

**Comment by sverweij** [comment]
With the latest babel version it seems to work OK
```
$npm i -g babel-cli
(...)

$ babel --version
6.7.7 (babel-core 6.7.7)

$ babel multistr-with-hash-NOK.js
var multilinestring = "x\n\
#";
console.log(multilinestring);

$ babel multistr-without-hash-OK.js
var multilinestring = "x\n\
y";
console.log(multilinestring);
```

The babel (core) version installed with CST is 6.6.1 - so if babel is the culprit upgrading might be a solution?

**Comment by markelog** [comment]
CST doesn't use babel it uses babylon and CST uses last available version.

**Comment by markelog** [comment]
Since there is nothing we can do here, i'm closing it, track the babylon issue - https://github.com/babel/babylon/issues/32
