### ISSUE TITLE
disallowObjectKeysOnNewLine seems not to do what it says

### ISSUE THREAD

**Issue by bcowgill** [jscs-dev/node-jscs#2229]
with disallowObjectKeysOnNewLine: true

```
disallowObjectKeysOnNewLine: Object keys must go on a new line at src/templates/jscs-test.jsx :
   514 |//Invalid
   515 |var temp1 = {
   516 |    temp2: 'b',
-----------------------^
   517 |    temp3: 'c'
   518 |};
```

Shouldn't it be disallowObjectKeysOnSameLine ?

**Comment by hzoo** [comment]
There is also http://jscs.info/rule/requireObjectKeysOnNewLine, so it looks like the message just needs to be changed [here](https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/disallow-object-keys-on-new-line.js#L57)
