### ISSUE TITLE
FR: Inline configuration, to comment out rules temporarily, like JSHint

### ISSUE THREAD

**Issue by pickhardt** [jscs-dev/node-jscs#223]
Request for inline configuration a la JSHint:
http://jshint.com/docs/

Example:

```
    /* jscs maximumLineLength: 250 */
    return /^realyreallyreallyreallyreallyreallyreallyreallylongregex$/.test(s);
    /* jscs maximumLineLength: 80 */
```

**Comment by jimthedev** [comment]
@mikesherov Did this make it in?

**Comment by mikesherov** [comment]
@jimthedev http://jscs.info/overview.html#error-suppression :-)

**Comment by jimthedev** [comment]
Thanks! Was searching for 'ignore' when I should have been searching for 'disable'. Appreciate it.
