### ISSUE TITLE
validateIndentation and indent_to_bracket in jscs3

### ISSUE THREAD

**Issue by minj** [jscs-dev/node-jscs#2232]
Since jscs3, `validateIndentation: "\t"` complains about mixed indentation in indent_to_bracket mode:
```
\tif (somewhatLongCondition && anotherLongCondition &&
\t____extremelyUberLongCondition3) {
\t\t// code
\t}
```

This is probably logical and was intended as a bugfix but a way to restore the old behavior would be nice.

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
