### ISSUE TITLE
Rule shown in message for programmatic API

### ISSUE THREAD

**Issue by Arcanemagus** [jscs-dev/node-jscs#2235]
It seems that with the changes in https://github.com/jscs-dev/node-jscs/commit/dc468431aa19b6373e6fdc67b8d8bde40d7528d1 a bug was introduced where when getting the rules via the API the ruleID is shown in the `message` attribute _as well as_ the `rule` attribute.

![image](https://cloud.githubusercontent.com/assets/427137/14764618/17f47272-0973-11e6-8dd2-24471a2069a6.png)

Since the information is already accessible it should be up to the consumer of the API what to do with it, instead of being forced to have it in the message.

**Comment by zxqfox** [comment]
Guess we can move _prepareMessage call from https://github.com/jscs-dev/node-jscs/blob/master/lib/errors.js#L86 to https://github.com/jscs-dev/node-jscs/blob/master/lib/errors.js#L211

Need to try to not break something else.

**Comment by markelog** [comment]
@zxqfox are you on it?

**Comment by markelog** [comment]
Nope that was the point - always show the error, `rule` property only for the connivance
