### ISSUE TITLE
requireSemicolons and requirePaddingNewLinesAfterBlocks combined report wrong line

### ISSUE THREAD

**Issue by Arcanemagus** [jscs-dev/node-jscs#2245]
When running `jscs` v3.0.3 against this file:

`example2.js`:

```js
{}
console.log(false)

```

With this configuration:

`.jshintrc`:

```json
{
  "requirePaddingNewLinesAfterBlocks": true,
  "requireSemicolons": true
}

```

JSCS is reporting the `requireSemicolons` error on line _3_ instead of line 2. I get the same results when running on the CLI with the default and JSON reporters, as well as when using the Node API (Inside the `linter-jscs` Atom package).

![image](https://cloud.githubusercontent.com/assets/427137/15192596/d364eaa6-176e-11e6-90c3-5cc163b03c59.png)

Note that this was initially filed as https://github.com/AtomLinter/linter-jscs/issues/241.

A folder with a minimal reproduction case is included here: [linter-jscs_GH241.zip](https://github.com/jscs-dev/node-jscs/files/259964/linter-jscs_GH241.zip)

If there is any further information you need just let me know.

**Comment by markelog** [comment]
Same as https://github.com/jscs-dev/node-jscs/issues/2244

**Comment by Arcanemagus** [comment]
Really? Interesting, it doesn't show the same error in the output and the rules are entirely different so I assumed it was a different bug.

**Comment by markelog** [comment]
Yeah, different representation of the same thing, everything would correctly with the `-x` flag aka enabled autofix
