### ISSUE TITLE
Performance issue with maximumLineLength

### ISSUE THREAD

**Issue by Arcanemagus** [jscs-dev/node-jscs#2246]
It seems that the `maximumLineLength` rule is making the CLI interface take 7.7x as long to run on a file, and the Node interface 33x times as long to run.

The configuration used was a copy of the [current `airbnb.json`](https://github.com/jscs-dev/node-jscs/blob/affa854db11c807d4d24712c17796a6d27f55b4c/presets/airbnb.json). The `maximumLineLength` rule was commented out using `/* */` (no difference was found for simply removing it).

Tested with `jscs@3.0.3` running through Node.js v5.11.0 on the CLI and through Atom v1.8.0-beta3 for the "Node API" (equivalent to Node v5.1.1).

The file used to test this can be found in here: [linter-jscs_GH241-2.zip](https://github.com/jscs-dev/node-jscs/files/260099/linter-jscs_GH241-2.zip)

The raw data can be found here: https://docs.google.com/spreadsheets/d/1HGXcBMeRCgOEvAuvgNZEgtZUdEAsPwm24BUYtS_x_cI/edit?usp=sharing

This was originally filed as part of https://github.com/AtomLinter/linter-jscs/issues/241.

If you need any additional information please let me know.

**Comment by markelog** [comment]
Replaced with https://github.com/jscs-dev/node-jscs/issues/2246

**Comment by Arcanemagus** [comment]
You referenced this issue as the one replacing it... not sure what you meant there :stuck_out_tongue:.

**Comment by Arcanemagus** [comment]
Ah, probably https://github.com/cst/cst/issues/113, as you referenced this from there.

**Comment by markelog** [comment]
Oh yeah, sorry, indeed i meant cst/cst#113

**Comment by markelog** [comment]
Oh yeah, sorry, indeed i meant cst/cst#113

**Comment by epsitec** [comment]
I don't understand how this issue with _too many long lines being reported_ has anything to do with memory consumption. Setting the `maximumLineLength` to `200` (in my case) made the problem disappear.

The lines verified by JSCS are not very long, so I am surprised that you classified this as a memory issue. Do you need additional source files which exhibit the problem?

**Comment by markelog** [comment]
Perhaps things get more clear if you would read issue description?
