### ISSUE TITLE
disallowSpaceAfterComma all except sparse arrays does not work as advertised

### ISSUE THREAD

**Issue by bcowgill** [jscs-dev/node-jscs#2248]
"disallowSpaceAfterComma" {"allExcept": ["sparseArrays"]},

// Valid for mode {"allExcept": ["sparseArrays"]}
[const1,const2, , ,const3];

// Invalid for mode {"allExcept": ["sparseArrays"]}
[const1, const2, , , const3];

Both examples from the documentation appear to be valid

**Comment by markelog** [comment]
Can't repro ```[const1, const2, , , const3];``` shows errors as expected, we also have tests which proves it - https://github.com/jscs-dev/node-jscs/blob/2cdb26d172fc8e19779dffcbab88ca8ab8f06fb9/test/specs/rules/disallow-space-after-comma.js#L58
