### ISSUE TITLE
Node process deadlocks when JSCS is run

### ISSUE THREAD

**Issue by thegranddesign** [jscs-dev/node-jscs#2256]
I can consistently get the `node` process to deadlock and peg the CPU at 100% when I run JSCS.

What information do you need from me to fix this?

![image](https://cloud.githubusercontent.com/assets/17790097/15483514/b6d8f720-20fa-11e6-8a37-3eaa34f76da7.png)

**Comment by thegranddesign** [comment]
BTW, as far as I can tell, this only happens when there is an error in the `requireAlignedObjectValues` check.

**Comment by markelog** [comment]
See https://github.com/cst/cst/issues/113
