### ISSUE TITLE
Error Code 2 A.K.A --force

### ISSUE THREAD

**Issue by ShadOoW** [jscs-dev/node-jscs#2260]
Hello,

JSCS exit with error code 2 when it finds a code style that is not allowed by the configuration file.

First: Why does it exit with error, the main purpose of this programme is to find this style issues, it found one it exit with error? WTF
Second: why not at least have a --force flag to force it to exit with 0?

This is a real issue, i've faced when writing an npm script for jscs.

PS: No disrespect intended, just pointing out something that look stupid to me, cheers.

**Comment by markelog** [comment]
That is API design, you can easily mitigate this, also see https://github.com/jscs-dev/node-jscs/wiki/Exit-codes
