### ISSUE TITLE
Errors in JSX files return incorrect column numbers

### ISSUE THREAD

**Issue by crucialfelix** [jscs-dev/node-jscs#2261]
The column numbers are incorrect when reporting errors in jsx files.

See https://github.com/AtomLinter/linter-jscs/issues/259

jscs 3.0.3

@Arcanemagus isolated a very simple reproducer: https://github.com/AtomLinter/linter-jscs/files/291711/linter-jscs_GH259.zip

Note that on the last error it's pointing well past the end of the line, and the error before that is pointing to the entirely wrong place (but isn't triggering this warning since it is still within the confines of the line).

![image](https://cloud.githubusercontent.com/assets/218738/15743392/597cbb48-28c5-11e6-98c7-9aa419342048.png)

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.

**Comment by crucialfelix** [comment]
Fair enough. Looking forward to the new eslint. Jscs has been very helpful. Thanks !
