### ISSUE TITLE
validateIndentation on switch statements fails if opening bracket is on new line

### ISSUE THREAD

**Issue by Tathanen** [jscs-dev/node-jscs#2262]
If you have `validateIndentation` set to an integer (in my case `4`), it complains about switch statements where the opening curly bracket isn't on the opening line.  See:

Freaks out:
![Error](http://i.imgur.com/LeqWaI9.png)

Fine:
![Fine](http://i.imgur.com/8i0OlyJ.png)

I write my code Allman style and everything else is fine, just switch statements seem to be actin weird.

Was able to reproduce using the JSCS CLI as well, screenshots from Atom for convenience.

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.

**Comment by Tathanen** [comment]
Is eslint what will be supported moving forward? I wasn't aware jscs was being eol'd.

**Comment by markelog** [comment]
Check it out - https://medium.com/@markelog/jscs-end-of-the-line-bc9bf0b3fdb2#.jsnhpxsjz

**Comment by Tathanen** [comment]
Got it, thanks!
