### ISSUE TITLE
validateIndentation ignores disallowMixedSpacesAndTabs setting

### ISSUE THREAD

**Issue by JonathanGawrych** [jscs-dev/node-jscs#2263]
Take for example the following config:

```
{
	"validateIndentation": "\t",
	"disallowMixedSpacesAndTabs": false
}
```
(or if disallowMixedSpacesAndTabs is "smart")

And the following test file:
```
if (true) {
\t  console.log(true &&
\t  ············false);
}
```
where `\t  `` `` ` is a tab, and `·` is a space, validateIndentation ignores disallowMixedSpacesAndTabs and throws an error "Invalid indentation character:". Turning on disallowMixedSpacesAndTabs throws 2 errors (one for each).

Correct me if I'm wrong, but isn't validateIndentation throwing false positives? Prior to https://github.com/jscs-dev/node-jscs/commit/d0c70f1c5763c923186945f4b2c10b1aab54e95e (which looks like a complete rewrite of validateIndentation) it wouldn't. Removing [validate-indentation.js#L500-L506](https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/validate-indentation.js#L500-L506) seems to fix these problems and passes a npm test (however those mixed tab-spaces lines are not validated for indentation anymore, I believe). Thanks

**Comment by markelog** [comment]
`false` is indented, but with spaces, when you want tabs. There is and there were many issues with indentation rules, but this is not one of them
