### ISSUE TITLE
Should have exception for disallowSpacesInFunction for anonymous generators

### ISSUE THREAD

**Issue by jdforsythe** [jscs-dev/node-jscs#2272]
I want to enforce no spaces after `function` or the name of the function.

```js
function() {}
function a() {}
```

I want to enforce spaces before and after the star for generators.

```js
function * () {}
function * a() {}
```

I have the rules:

```json
{
  "disallowSpacesInFunction": {
    "beforeOpeningRoundBrace": true
  },
  "requireSpacesInGenerator": {
    "beforeStar": true,
    "afterStar": true
  }
}
```

Everything works as expected except the anonymous generator `function * () {}` which errors on the `disallowSpacesInFunction`. I think I need something like:

```json
{
  "disallowSpacesInFunction": {
    "beforeOpeningRoundBrace": {
      "allExcept": [ "anonymousGenerators" ]
    }
  }
}
```

Is there a workaround for this? Or some rule I'm missing to make this work?

**Comment by markelog** [comment]
Not 100% on this, but i don't think there is such workaround and at this point, we are not committed to adding new features, sorry
