### ISSUE TITLE
Error: Symbol is not defined (first character of file)

### ISSUE THREAD

**Issue by acburdine** [jscs-dev/node-jscs#2279]
When running jscs tests on Node 0.10, every file seems to fail with this error:

`Symbol is not defined at <filename>.js` -> points at the first character of the file.
What that first character happens to be is irrelevant, as it occurs in every file.
This came up in the Ghost repository, both server and client (which means it occurs in both ES5 and ES6 code).

The error doesn't happen on node 0.12 or 4, and seemed to start happening after the upgrade to CST 0.4.2. It's also seemingly unrelated to #2278 -> that happened as well before cst 0.4.2.

**Comment by acburdine** [comment]
It's also what's breaking the jscs master travis tests [here](https://travis-ci.org/jscs-dev/node-jscs/jobs/139528006)

**Comment by markelog** [comment]
Would you mind checking it again?

**Comment by acburdine** [comment]
It works now, thank you!
