### ISSUE TITLE
Add `templateStrings` as an option for the `allExcept` property of the `maximumLineLength` rule

### ISSUE THREAD

**Issue by adambuczynski** [jscs-dev/node-jscs#2280]
As per the issue title, can we add `templateStrings` as an option for the `allExcept` property of the `maximumLineLength` [rule](http://jscs.info/rule/maximumLineLength)?

Especially with Angular templates some lines can get a bit lengthy, and I'd like to not have JSCS trip over them.

<sub><sup>PS, this must be one of the first repositories of a large project that I've seen with 0 open issues 👍 </sup></sub>

**Comment by markelog** [comment]
> PS, this must be one of the first repositories of a large project that I've seen with 0 open issues 

There is a reason for that :/, see 
https://medium.com/@markelog/jscs-end-of-the-line-bc9bf0b3fdb2 and
http://eslint.org/blog/2016/04/welcoming-jscs-to-eslint

We are not adding new features at this time

**Comment by adambuczynski** [comment]
Ah bugger :)
