### ISSUE TITLE
maximumLineLength should optionally allow string literals to break the rule

### ISSUE THREAD

**Issue by HeroicAutodidact** [jscs-dev/node-jscs#2282]
Sometimes one puts a huge data string into a JavaScript file. I'm working with a legacy code base and while I'd like to enforce concise lines of code, I would also like to passthrough massive existing string literals.

**Comment by markelog** [comment]
See https://medium.com/@markelog/jscs-end-of-the-line-bc9bf0b3fdb2 and
http://eslint.org/blog/2016/04/welcoming-jscs-to-eslint

We are not adding new features at this time

**Comment by HeroicAutodidact** [comment]
I see. On the `readme.md` it says that you have merged with ESLint, but I interpreted this to mean that ESLint had merged into you.  Perhaps a note on the readme and on the front page of http://jscs.info/ that this repo is deprecated would help others to redirect themselves appropriately.
