### ISSUE TITLE
validateIndentation should enforce endbrace at the same indentation as the line containing it's corresponding startbrace

### ISSUE THREAD

**Issue by HeroicAutodidact** [jscs-dev/node-jscs#2283]
i.e. The following should be valid with `validateIndentation=2`:
```
          scope.$apply(function() {
              scope.closeDialog();
          });
```
However, JSCS flags this the last line as `expected indentation of 12 characters` (two more spaces indented). 

If this is not desirable as the the default behavior, perhaps it should be added as an option. 

```
          scope.$apply(function() {
              scope.closeDialog();
            });
```
Is not an intuitive or common structure to enforce.

**Comment by aj-dev** [comment]
I can see the same bug with validateIndentation=4 when running jscs --fix after upgrade to JSCS v3.

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
