### ISSUE TITLE
JSCS goes into infinite loop

### ISSUE THREAD

**Issue by Igor10k** [jscs-dev/node-jscs#2286]
Here's the sample file.

```
class Test {
  test() {};
}
```

Semicolon is what causes the loop. CPU goes up to ≈100%. The process never ends.

`.jscsrc` looks like this

```
{
  "preset": "airbnb"
}
```

JSCS 3.0.6, Node 6.2.2

**Comment by markelog** [comment]
Replaced with https://github.com/cst/cst/issues/131

**Comment by markelog** [comment]
Should work now
