### ISSUE TITLE
About jsx curly braces variable

### ISSUE THREAD

**Issue by monochrome-yeh** [jscs-dev/node-jscs#2287]
refer to https://facebook.github.io/react/docs/jsx-gotchas.html
```
const test = 'test';
<div>{'First &middot; Second'}</div>
<div>{test}</div>
```

I would like find the rule to do like these:
(add space before/after curly braces)

```
const test = 'test';
<div>{ 'First &middot; Second' }</div>
<div>{ test }</div>
```

however, I haven't found that yet,
maybe I've missed keywords.

Does jscs has this relevant rules ?

**Comment by markelog** [comment]
I don't think so, if it's not on [there](http://jscs.info/rules) we don't have it, sorry
