### ISSUE TITLE
requireSpaceBetweenArguments doesn't work in constructor of es6. 

### ISSUE THREAD

**Issue by xiadengping** [jscs-dev/node-jscs#2289]
I have set requireSpaceBetweenArguments in .jscsrc file,
```
"requireSpaceBetweenArguments": true,
```
This is a test code,
```
"use strict";
class A {
    constructor(a,b) {
        console.log(a,b);
    }
}
```
jscs can only find line4 is invalid, shows "Missing space between , and b", but line3 is also invalid.

**Comment by markelog** [comment]
This rule applicable only for call expressions, see - http://jscs.info/rule/requireSpaceBetweenArguments since those are not arguments those are parameters.

You want [validateParameterSeparator](http://jscs.info/rule/validateParameterSeparator)

**Comment by markelog** [comment]
Hm, but apparently `validateParameterSeparator` doesn't notice class methods :/

**Comment by xiadengping** [comment]
Thanks ：）

**Comment by 666don** [comment]
He!p
