### ISSUE TITLE
How to write a rule which makes "case" align to "switch" in switch statement? 

### ISSUE THREAD

**Issue by xiadengping** [jscs-dev/node-jscs#2290]
For historical reasons, I want to write a rule for indentation, validateIndentation is 4, but there is a exception for switch statement, "case" is align to "switch", just like the code below,
```js
"use strict";
function test(value) {
    switch (value) {
    case 0:
        cosole.log(0);
        break;
    case 1:
        cosole.log(1);
        break;
    default:
        cosole.log(2);
    }
}
```
Which rule can I use?

**Comment by markelog** [comment]
I don't think we have the rule for this
