### ISSUE TITLE
requireCurlyBraces one-statement / one-expression exception

### ISSUE THREAD

**Issue by kangax** [jscs-dev/node-jscs#244]
"requireCurlyBraces" is a great option but needs an exception. The only time it's acceptable to ignore it is for early returns or continuations.

[Example from our Fabric.js](https://github.com/kangax/fabric.js/blob/master/src/canvas.class.js#L341):

```js
 if (!target) return;
```

[Or with `continue`](https://github.com/kangax/fabric.js/blob/master/src/canvas.class.js#L1086):

```js
if (!this._objects[i] || !this._objects[i].active) continue;
```

[Example from Underscore](https://github.com/jashkenas/underscore/blob/master/underscore.js#L82):

```js
if (iterator.call(context, obj[i], i, obj) === breaker) return;
```

[Example from Angular](https://github.com/angular/angular.js/blob/master/src/Angular.js#L836):

```js
if (key.charAt(0) === '$' || isFunction(o1[key])) continue;
```

etc.

Most of the time, I want `if` statements to have curly braces, except when there's 1 statement in its body, such as `return` or `continue`.

I couldn't find a way for JSCS to ignore these, hence the request.

I could think of 2 levels of allowance:

- Only allow "empty" statements, such as  `return;`, `continue;`, `break;`
- Only allow one statement, such as `return false;`, `return foo();`, etc.

I'm leaning towards 2nd. I noticed that both [Underscore](https://github.com/jashkenas/underscore/blob/master/underscore.js#L97) and [Angular](https://github.com/angular/angular.js/blob/master/src/Angular.js#L837) use the latter as well.

**Comment by LukeGT** [comment]
I would like to see the "require curly braces only if the statement spans multiple lines" approach taken on board. The `"requireTrailingComma"` option has a similar behaviour, where you can ask only to require a trailing comma if the expression spans more than one line (or has more than one value). 

In combination with a horizontal character limit, I feel like this is good enough to stop the absence of curly braces being abused while still allowing for it to make simple statements clearer and more concise.

**Comment by zxqfox** [comment]
```
if (x < 5) x = 5, continue; // ?
```

**Comment by markelog** [comment]
So, is there any takers for this one?

**Comment by zxqfox** [comment]
@markelog That's not so big issue but better to clarify what we really need and how to configure it.

Options, as I see:
- `"exceptSameline"`;
- `{ "exceptSingleStatement": true || [ 'ReturnStatement', 'BreakStatement', ... ] }`;
- `{ "exceptExpressions":  [ 'BooleanLiteral', 'StringLiteral', 'ReservedWord', ... ] }`.

Not sure ;-( Can we discuss this?

**Comment by markelog** [comment]
> Only allow one statement, such as return false;, return foo();, etc.

This sounds good to me

**Comment by hzoo** [comment]
Anyone want to summarize what is wanted here? Sounds like we can make an option ``` `allExcept`: ['ReturnStatement', 'BreakStatement', 'ContinueStatement']` ```

**Comment by kangax** [comment]
That would work for me.

**Comment by markelog** [comment]
Cool!

**Comment by hzoo** [comment]
Ok need to change it a bit more since the original option was an array so something like

```js
"requireCurlyBraces": {
  "keywords": ["if", "else"], 
  "allExcept" : ['ReturnStatement', 'BreakStatement', 'ContinueStatement']`
}
```

**Comment by markelog** [comment]
```js
"keywords": ["if", "else"], 
"allExcept" : ['ReturnStatement', 'BreakStatement', 'ContinueStatement']`
```

Seems inconsistent, this rule already maps those entities together, so it should be pretty easy to use same type of lists together.

Generally it is good ideas to distance from parser json

**Comment by hzoo** [comment]
What do you mean by this? combine them into a single list or either `keywords` or `allExcept`?

**Comment by markelog** [comment]
I meant if `keywords` has "token list", then it would be logical for `allExcept` to have the same, then AST entities

**Comment by hzoo** [comment]
Oh ok you mean like `"return", "break", "continue"`

**Comment by markelog** [comment]
yeah

**Comment by kangax** [comment]
Fantastic, thank you!
