### ISSUE TITLE
JSCS shuts down with error on "if (a === 5) return;"

### ISSUE THREAD

**Issue by vohtaski** [jscs-dev/node-jscs#251]
I have a file.js with one single line

``` js
if (a === 5) return;
```

JSCS stops executing with the error log:

```
$ jscs file.js
Error: Syntax error at file.js: Line 14: Illegal return statement
    at StringChecker.checkString (/usr/local/lib/node_modules/jscs/lib/string-checker.js:209:19)
    at /usr/local/lib/node_modules/jscs/lib/checker.js:58:26
    at Array.0 (/usr/local/lib/node_modules/jscs/node_modules/vow/lib/vow.js:194:56)
    at callFns (/usr/local/lib/node_modules/jscs/node_modules/vow/lib/vow.js:452:35)
    at process._tickCallback (node.js:415:13)
```

Expected behavior:
Display a warning

**Comment by feross** [comment]
In node.js, it is valid to `return` like this because the node module system wraps files in a self-executing function.

https://nodejs.org/api/modules.html#modules_exports_alias

**Comment by mikesherov** [comment]
@feross while it may be valid to do inside a node module, it's still a syntax error for Esprima, which has no concept of node currently. If you'd like this behavior, please file an esprima bug here: https://code.google.com/p/esprima/issues/list

**Comment by feross** [comment]
Esprima bug filed: https://code.google.com/p/esprima/issues/detail?id=630&thanks=630&ts=1422662287

Please star it.
