### ISSUE TITLE
New rule: validateNewlineAfterArrayElements to force each item to be on a new line

### ISSUE THREAD

**Issue by dylang** [jscs-dev/node-jscs#317]
An option something like = `requireNewLinesInArray = true;`

Invalid:
```js
var fruit = [ 'apples', 'bananas', 'pears'];
```

Valid:
```js
var fruit = [ 
  'apples', 
  'bananas', 
  'pears'
];
```

There might need to be other options, such as `firstItemOnNewLine`.

Some advantages for this style is that it makes it easier to follow diffs and it is easier to read when there are many items.

**Comment by markelog** [comment]
@zxqfox is this on your list?

**Comment by zxqfox** [comment]
@markelog I thought it's done ;-)

**Comment by markelog** [comment]
Is there a PR?

**Comment by zxqfox** [comment]
Yeah, sure. #798

**Comment by markelog** [comment]
Cool, miss this one

**Comment by hzoo** [comment]
#1115 originally was a request for the same rule except for objects. I was confused and suggested `ignoreSingleLine` option because it was for the `requirePaddingNewLinesInObjects` (which I suppose we might do anyway). So another rule for objects as well?

**Comment by zxqfox** [comment]
@hzoo Yeah, I think it will be nice to have a separate rule. ;-)
