### ISSUE TITLE
Can't override preset options

### ISSUE THREAD

**Issue by jzaefferer** [jscs-dev/node-jscs#338]
Consider this configuration:

``` json
{
    "preset": "jquery",
    "requireLineFeedAtFileEnd": false
}
```

Running `jscs` with that results in this error:

```
assert.js:92
  throw new assert.AssertionError({
        ^
AssertionError: requireLineFeedAtFileEnd option requires true value or should be removed
    at Object.module.exports.configure (/usr/local/share/npm/lib/node_modules/jscs/lib/rules/require-line-feed-at-file-end.js:12:9)
    at /usr/local/share/npm/lib/node_modules/jscs/lib/string-checker.js:142:26
    at Array.forEach (native)
    at StringChecker.configure (/usr/local/share/npm/lib/node_modules/jscs/lib/string-checker.js:135:21)
    at Checker.configure (/usr/local/share/npm/lib/node_modules/jscs/lib/checker.js:48:39)
    at module.exports (/usr/local/share/npm/lib/node_modules/jscs/lib/cli.js:74:13)
    at Object.<anonymous> (/usr/local/share/npm/lib/node_modules/jscs/bin/jscs:22:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

In other words, any option that a preset has enabled can't be disabled since I can't "remove" it, as the error suggest.

**Comment by ianjmacintosh** [comment]
Glad I found this issue, I was thrown for a loop also.

It looks like the folks maintaining this project have made a decision to make it this way. But as a casual user, I'll say `null` is not an intuitive override to `true`; when reading the options casually, I imagine appropriate responses to "Do you disallow dangling underscores?" to be `true` or `false`

I don't understand how else `false` would be interpreted, but I think the argument is that `null` makes more sense to not do anything than explicitly saying "false."

Also, when looking at the documentation for why `false` wasn't doing what I wanted, I looked at the documentation for the option I was trying to override, not the documentation for presets. When I saw the only documented value was `true`, I scratched my head, went to Google, and found this thread before I found the part of the documentation this quirk is explained.

I understand "RTFM," but +1 for folks who are saying it's a confusing approach to dealing with boolean parameters.

**Comment by mikesherov** [comment]
@ianjmacintosh we're going to be added the 'null' advice to the error output in 2.0 as per my last comment. Thanks again!

**Comment by ianjmacintosh** [comment]
@mikesherov Thanks for the quick and thoughtful response!

Sounds like this is tracked by https://github.com/jscs-dev/node-jscs/issues/971
