### ISSUE TITLE
Example .jscsrc file with list of all available options

### ISSUE THREAD

**Issue by am11** [jscs-dev/node-jscs#352]
### Note from @mikesherov: If you'd like to tackle this issue, first please look at #480

Please add an example `.jscsrc` file with list of all available options, as the options-set is growing. In Web Essentials, we are using a default [`.jscsrc`](https://github.com/madskristensen/WebEssentials2013/blob/8d5e1e5c4ae3ef702c298a68b159f64ebeae1c32/EditorExtensions/Resources/settings-defaults/.jscsrc) file which I found on @sapegin's [forked repo](https://github.com/sapegin/node-jscs/blob/master/.jscs.json).

Another consideration is we are building schemas for various configurations (so far @madskristensen has submitted [for .jshintrc](https://github.com/jshint/jshint/pull/1621)). For that matter, an updated `.jscsrc` with all options supported by (latest) v1.4.0 would really help.

(Tip: JsHint guys keep an updated config file in their [example folder](https://github.com/jshint/jshint/blob/2.x/examples/.jshintrc) and in case of TsLint, they have it on their [repo's root](https://github.com/palantir/tslint/blob/master/tslint.json))

Thanks in anticipation. :)

**Comment by mrjoelkemp** [comment]
This has been provided to a certain degree by the website: http://jscs.info/rules.html. It doesn't have the configuration out in the open, but feel free to file issues against https://github.com/jscs-dev/jscs-dev.github.io for improvements.

This issue hasn't seen a PR to provide the suggested automation so I'm closing for now. Happy to reopen if anyone wants to submit a patch.
