### ISSUE TITLE
[validateIndentation] "\t" option not working

### ISSUE THREAD

**Issue by ShimShamSam** [jscs-dev/node-jscs#370]
When setting validateIndentation to "\t", I still get errors saying "Expected indentation of X characters". The issue seems to happen specifically when the object literal is used directly as a function argument

``` JavaScript
function foo(){}

foo(123, {
        hello : [
            'world'
        ]
    }
);
```

**Comment by Hanzig** [comment]
Hi! I am also having an issue related to that. ```"validateIndentation": "\t",``` still gives me ```"Expected indentation of X characters"``` when using AirBnB preset. Any clue? Thanks in advance!

```javascript
    var config = require('./config-grunt.json');
````

**Comment by Hanzig** [comment]
Ok, I could figure out that it was a misconfiguration in Atom. ```"validateIndentation": "\t"``` works perfectly fine. If you are using linter-jscs, make sure "Only Config" is checked. Else it will still use the Preset selected in linter-jscs.
