### ISSUE TITLE
[feature request] requireYodaConditions

### ISSUE THREAD

**Issue by zz85** [jscs-dev/node-jscs#380]
one low priority feature request...

we found `disallowYodaConditions` pretty interesting and suspect that some crazy folks might want to enforce yoda style with `requireYodaConditions` :laughing:

**Comment by paulschreiber** [comment]
Glad this is fixed! When can I expect to see a new release of jscs containing this feature?

**Comment by hzoo** [comment]
We're planning on 2.0.0 very soon (I heard monday but that's past :smile: )

**Comment by markelog** [comment]
Yeah, was a bit busy, really hoping for tomorow
