### ISSUE TITLE
validateIndentation - accept shorter indents in anonymous function passed as a second parameter

### ISSUE THREAD

**Issue by mgol** [jscs-dev/node-jscs#387]
Imagine the following code:

``` js
doSth('This is a description', function () {
    doSth1();
    doSth2();
    /* lots of code */
});
```

When the description is needed to be made way longer (or additional parameters passed), you can sometimes hit the line limit, having to break the line like:

``` js
doSth('This is a terribly long description you'll ' +
    'have to read', function () {
    doSth1();
    doSth2();
    /* lots of code */
});
```

However, while jsHint accepts this code (or used to accept before it dropped most of `indent` functionality), JSCS doesn't when passed `"validateIndentation": 4`, it expects that instead:

``` js
doSth('This is a terribly long description you'll ' +
    'have to read', function () {
        doSth1();
        doSth2();
        /* lots of code */
    });
```

Making such a change would make diff huge so it's not acceptable. Therefore, IMO `validateIndentation` should accept both notations and should just check if it's consistent.

**Comment by PinkyJie** [comment]
@mikesherov Is there an option to config this? Actually I think
```
doSth('This is a terribly long description you'll ' +
    'have to read', function () {
        doSth1();
        doSth2();
        /* lots of code */
    });
```
is better. ^_^
