### ISSUE TITLE
commitplease

### ISSUE THREAD

**Issue by markelog** [jscs-dev/node-jscs#407]
Let's use <a href="https://github.com/jzaefferer/commitplease">commitplease</a> it would help us better maintain git conventions and generate more relative and simple changelog.

We could use something like <a href="http://karma-runner.github.io/0.12/dev/git-commit-msg.html">this</a> or develop our own subject types

**Comment by markelog** [comment]
Re-opening due to @hzoo request

**Comment by gustavohenke** [comment]
Maybe it's useful: http://gitcop.com

**Comment by markelog** [comment]
It is :-)

**Comment by hzoo** [comment]
Moving to #1812.
