### ISSUE TITLE
[feature request] Set keywords for disallowPaddingNewlinesInBlocks

### ISSUE THREAD

**Issue by nwhite89** [jscs-dev/node-jscs#434]
My thinking is to allow to set keywords in which ```disallowPaddingNewlinesInBlocks``` is for similar to ```requireCurlyBraces```.

As an example I have come across a sticky situation with this due to:
```js
angular.module('foo')
    .controller('FooCtrl', function ($scope, $someReallyLongServiceName,
        $anotherService, $somethingElse) {

        $scope.bar = 'baz';
        $scope.qux = 'quux';
    });
```

Therefore I'd turn off function but have everything else set as true such as ```if```

**Comment by markelog** [comment]
This issue has been open more than a month without supported PR for it. 

Unfortunately, we don't have the resources to implement rules that could not be included in any of the supported [presets](https://github.com/jscs-dev/node-jscs/tree/master/presets) (if it could be, please point that out).

However, if you or anybody else submit PR for it, we will gladly consider it.
