### ISSUE TITLE
How to run jscs with harmony support?

### ISSUE THREAD

**Issue by goloroden** [jscs-dev/node-jscs#441]
Basically, the title says it all: I would like to check a file that makes use of ES6 features, but jscs complains about an unexpected token (in my case, it's the `*` of a generator function).

How can I run jscs with harmony support?

**Comment by malandrew** [comment]
Esprima 2.0 was released 10 hours ago.

**Comment by mrjoelkemp** [comment]
@malandrew answered here: https://github.com/jscs-dev/node-jscs/issues/561#issuecomment-73288226
