### ISSUE TITLE
Improve error output

### ISSUE THREAD

**Issue by markelog** [jscs-dev/node-jscs#453]
Recent release of `1.5.0` <a href="https://github.com/mdevils/node-jscs/pull/366">showed</a>, on my opinion, that we need to improve error output, either provide warning module or adapt current error module API (rename maybe) to show notifications/warnings, without line and column number.

Also this change is required for #238 issue, just like it might beneficial for plugins and rules notification.

**Comment by hzoo** [comment]
Any updates on this?
