### ISSUE TITLE
2.x progress: rule simplification

### ISSUE THREAD

**Issue by mdevils** [jscs-dev/node-jscs#479]
I’m ready to show you an example of rule simplification and combination: https://github.com/mdevils/node-jscs/commit/40ebf3856506a85e8b120815af9af6f921eb3165

Here I:

1. Joined `(require|disallow)Space(Before|After)BinaryOperators` into a single rule: `binaryOperators`
2. Started to simplify assertions (and make errors fixable in future): instead of errors.add(..) I use assertion.spaceBetween(token1, token2, message);
3. Started to simplify token navigation: 

```javascript
                var operatorToken = file.getPrevTokenWhich(
                    file.getFirstNodeToken(expression),
                    'punctuator',
                    operator
                );
                var nextToken = file.getNextToken(operatorToken);
                var prevToken = file.getPrevToken(operatorToken);
```

You can get token for a node, you can move back and forward. And you can move back/forward to the specific token type.

Take a look at this, I need your thoughts.

**Comment by mikesherov** [comment]
Closing this one as we now have a path forward in other tickets.
