### ISSUE TITLE
Declaratively specify rule option values

### ISSUE THREAD

**Issue by mikesherov** [jscs-dev/node-jscs#480]
Instead of manually asserting in the `configure` function of a rule, we should be able to specify what values are accepted declaratively. This will also allow us to automate the creation of sample .jscsrc files. In order to do this, we need:

1. A way to set option values.
1. A way to verify provided values against use supplies values.
1. A way to automate error messages when a supplied value doesn't match.
1. A way to retrieve the possible values for a given rule.

**Comment by markelog** [comment]
First and second is https://github.com/jscs-dev/node-jscs/issues/895, consider it as sub-task to this issue

**Comment by TheSavior** [comment]
If we are considering auto generating doc blocks as well to be consistent with the specified options, how do we plan on handling good/bad examples? Seems unlikely that we'd be successful at choosing good options for those in code.
