### ISSUE TITLE
Disallow space before/after dot operator

### ISSUE THREAD

**Issue by cowwoc** [jscs-dev/node-jscs#511]
I'd like to require dots to show up at the end of lines, as opposed to the beginning of new lines.

```
// Good
a.b.
  c()

// Bad
a.b
  .c();
```

And I'm guessing other people will want the opposite. I scanned the existing rules but couldn't find anything that would allow this. Did I miss something or do we need a new rule?

**Comment by mrjoelkemp** [comment]
Looks like the original issue was fixed but now there's a lingering bug. Safe to open a new issue with the bug report and close this feature request?

**Comment by zxqfox** [comment]
:+1: for making a separate issue about the bug.

Also, looks like rule can be simplified now with new tokens API.

**Comment by mrjoelkemp** [comment]
Issue opened https://github.com/jscs-dev/node-jscs/issues/1437
