### ISSUE TITLE
requireAlignedObjectValues does not work with tabs

### ISSUE THREAD

**Issue by karamfil** [jscs-dev/node-jscs#533]
Hello,

requireAlignedObjectValues rule does not work with tabs but only with spaces. Would it be possible to work with spaces too?

Example:
```javascript
q = {
	qwe    : 1,
	asdfgh : 2
};
```
Output:
```
$ jscs test.js 
No code style errors found.
```

---

And if tabs are used (eq to 4 spaces)
```javascript
q = {
	qwe		: 1,
	asdfgh	: 2
};
```
```
$ jscs test.js 
Alignment required at test.js :
     1 |q = {
     2 | qwe  : 1,
--------------^
     3 | asdfgh : 2
     4 |};
```

Also you can notice that there is no error on line 3 because there is only a single whitespace character and jscs thinks it is aligned fine.

---

Also this seems to be fine too using lots of tabs. I guess this is because there are the same number of tabs as spaces would be.
```javascript
q = {
	qwe				: 1,
	asdfgh	: 2
};
```

Thanks!

**Comment by hzoo** [comment]
Been awhile for this particular issue, so going to close for now - if we get another PR later we can reopen/review.
