### ISSUE TITLE
Braces should be opened on newline for objects

### ISSUE THREAD

**Issue by cowwoc** [jscs-dev/node-jscs#539]
As a follow up to #65, I'm requesting equivalent functionality for objects.

@mikesherov What should this rule be called? (See related question at #538)

**Comment by markelog** [comment]
This is more or less duplicative of the jshint <a href="http://jshint.com/docs/options/#laxbreak">laxbreak</a> option

**Comment by cowwoc** [comment]
@marklog how do you figure? laxbreak suppresses warnings (what kind I can't tell, because the documentation is very vague) but either way it doesn't *add* warnings for the above cases, which is what I am asking for.

**Comment by markelog** [comment]
@cowwoc 

adding rule for the case
```js
var good2 =
{
  key: value
};
```
is a pretty much a bad move even for agnostic tool, but i didn't close it because of that, `laxbreak` warns you for the case:

```js
var bad =
{};
```
if you don't disable it, which is pretty much what you looking for.
