### ISSUE TITLE
error suppression comment bug

### ISSUE THREAD

**Issue by dbwhddn10** [jscs-dev/node-jscs#552]
i am using jscs and jshint together..

i discover the problem when using together

jshint's multiple line string error suppression code

``` js
/* jshint multistr:true */
```

is equal to jscs's multiple line string error suppression code

``` js
/* jscs:disable disallowMultipleLineStrings */
```

but there is difference between jshint and jscs when testing below code

``` js
it('', function () {
    /* jshint multistr:true */
    /* jscs:disable disallowMultipleLineStrings */
    var aaa = 'multiple line \
        comment';
});

it('', function () {
    // jshint catch error and output warning
    // jscs do not catch error and no ouput warning
    var aaa = 'multiple line \
        comment';
});
```

jshint's error suppression comment preserved in block
jscs's error suppression comment preserved in file

I think that jshint's operation is correct

**Comment by michaelhogg** [comment]
I too was very surprised to discover that JSCS's error suppression directives don't have function scope. Their behaviour reminds me of [C preprocessor](http://en.wikipedia.org/wiki/C_preprocessor) directives (ie: they operate at file-level and have no knowledge of JS scope).

I agree that this is not "wrong", but I think it's very unexpected for JS developers, who are used to the function scope of [ECMAScript 5's `"use strict"` directive](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode) and [JSHint's directives](http://jshint.com/docs/).

JSHint's docs specifically mention the scope of the directives:

> These comments are function scoped meaning that if you put them inside a function they will affect only this function's code.

I think [JSCS's docs](http://jscs.info/overview.html#inline-comments) need to make it clear that the directives *don't* have function scope.

**Comment by mrjoelkemp** [comment]
@michaelhogg Happy to review a PR with documentation clarification.
