### ISSUE TITLE
Require blank line in front of comments

### ISSUE THREAD

**Issue by jzaefferer** [jscs-dev/node-jscs#598]
Once available, this would go into the jQuery preset. See also [jQuery style guide](http://contribute.jquery.org/style-guide/js/#comments).

**Comment by jzaefferer** [comment]
Yay! Is the autofixer going to deal with this as well?

**Comment by hzoo** [comment]
Since it uses errors.assert then it should (and it does with `errors.assert.linesBetween`)!

**Comment by mikesherov** [comment]
Yup, will be autofixed.

**Comment by jzaefferer** [comment]
Nice, looking forward to start using both.
