### ISSUE TITLE
end-of-statement semicolon options

### ISSUE THREAD

**Issue by necolas** [jscs-dev/node-jscs#610]
I couldn't find any mention or previous discussion of semicolon rules. Seems like this tool is a good place to include style checks for semicolon use. What do you think?

**Comment by elsigh** [comment]
Just adding a vote to include a semicolon rule here. I get the argument, but only using jshint because of accidentally forgetting a semicolon seems like a bummer. There is otherwise a lot of overlap and overhead to run both tools on every change.

**Comment by hzoo** [comment]
We do have `requireSemicolons` and `disallowSemicolons` rules now so see if that can help?http://jscs.info/rules.html#requiresemicolons.

**Comment by elsigh** [comment]
Oh awesome, that's exactly what I want.
