### ISSUE TITLE
add rule for disallowing naive variables

### ISSUE THREAD

**Issue by mocheng** [jscs-dev/node-jscs#612]
Some variable patterns are not preferred since it hurts readability. For example,

var tmp = 123; // what the heck of tmp? It should be specific
var arr = "hello world".split(" "); // arr is meaningless. Variable words would be better

Is this kind of rule aligned with JSCS goals? If yes, I can contribute a PR.

**Comment by markelog** [comment]
This issue has been open more than a month without supported PR for it. 

Unfortunately, we don't have the resources to implement rules that could not be included in any of the supported [presets](https://github.com/jscs-dev/node-jscs/tree/master/presets) (if it could be, please point that out).

However, if you or anybody else submit PR for it, we will gladly consider it.

**Comment by mrjoelkemp** [comment]
Duplicate of #41

**Comment by pohutukawa** [comment]
I think blacklisting variable names is a possible solution, but prone to circumvention through "inventiveness" of other developers trickiness. However, together with a min length, this might actually already be quite helpful. In fact anything that helps to kerb "silly" variables and widely scoped "short" variables helps.
