### ISSUE TITLE
Properties check for undefined

### ISSUE THREAD

**Issue by rxaviers** [jscs-dev/node-jscs#618]
The [jQuery style guide](http://contribute.jquery.org/style-guide/js/#type-checks) says properties check for undefined should be of the form `object.prop === undefined`. The same happens for local variables.

Is this something that could be added to jscs checker?

Ref: https://github.com/jquery/jquery/pull/1595 and https://github.com/jquery/jquery/pull/1646#issuecomment-54070718

**Comment by hzoo** [comment]
Cleaning up some older/inactive issues: going to close and mark as `orphaned` so we can reopen again at a later time if anyone has PR
