### ISSUE TITLE
Accept array value for requireNewlineBeforeBlockStatements and disallowNewlineBeforeBlockStatements

### ISSUE THREAD

**Issue by pomeh** [jscs-dev/node-jscs#639]
When one of `requireNewlineBeforeBlockStatements ` or `disallowNewlineBeforeBlockStatements` is set to true, we have to put **all** opening curly brace on the same line or on a new line as the preceding statement, which leads to code like this:

using requireNewlineBeforeBlockStatements = true:

```javascript
function bad()
{
    var obj =
    {
        val: true
    };

    return {
        data: obj
    };
}

if (cond)
{
    foo();
}

for (var e in elements)
{
    bar(e);
}
```

using disallowNewlineBeforeBlockStatements= true:

```javascript
function good(){
    var obj = {
        val: true
    };

    return {
        data: obj
    };
}

if (cond){
    foo();
}

for (var e in elements){
    bar(e);
}
```

But, I would like to have my code looks like this instead:

```javascript
function good() {
    var obj = {
        val: true
    };

    return {
        data: obj
    };
}

if (cond)
{
    foo();
}

for (var e in elements)
{
    bar(e);
}
```

The difference is that `if` and `for` statements have their opening curly brace on a new line, whereas all other blocks opening curly brace stay on the same line, so it's basically a mix of the two rules.
To achieve this, `requireNewlineBeforeBlockStatements` and `disallowNewlineBeforeBlockStatements` should accept an array of values likes this:

```json
{
     "disallowNewlineBeforeBlockStatements": ["function", "object", "return"],
     "requireNewlineBeforeBlockStatements": ["if", "for", "while"],
}
```

With this, this code would be OK (opening curly brace of `if` should be on new line, but opening curly brace of functions should not):

```javascript
function good() {
}

if (good)
{
    good();
}
```

and both of the following should be KO:

```javascript
function bad()
{
}

if (good)
{
    good();
}
```

```javascript
function good() {
}

if (bad) {
    good();
}
```

What do you think ? I can *try* to implement it you're ok with that but don't wan't to or can't do it.

**Comment by Krinkle** [comment]
Rules `disallowKeywordsOnNewLine` and `requireKeywordsOnNewLine` may be relevant here as well.

**Comment by markelog** [comment]
@pomeh are you still interested?

**Comment by hzoo** [comment]
Cleaning up some older/inactive issues: going to close and mark as `orphaned` so we can reopen again at a later time if anyone has PR
