### ISSUE TITLE
Raise an error when a TODO-comment is found

### ISSUE THREAD

**Issue by pomeh** [jscs-dev/node-jscs#646]
Is it possible to raise an error whenever a single ligne comment like `// TODO: some stuff` is found in the code ? The rule name could be like `disallowTodoInComments`.

This rule could be extended with a more general rule which disallow a set of user-suplied keywords (or even some regex!):

```json
{
    "disallowKeywordInComments": ["TODO", "TASK", "DEBUG", "WHATEVER"]
}
```

What do you think about this ?

**Comment by joesepi** [comment]
I believe I have a new rule for this:
https://github.com/jscs-dev/node-jscs/pull/930
