### ISSUE TITLE
Rule to validate the positioning of comments about a statement

### ISSUE THREAD

**Issue by mrjoelkemp** [jscs-dev/node-jscs#651]
### validateCommentPosition

Type: `'String'`

Values:

* 'above'
* 'beside'

### Example

`validateCommentPosition: 'above'`

Valid:

```js
// This is a valid comment
1 + 1;
```

Invalid:
```js
1 + 1; // An invalid comment
```

`validateCommentPosition: 'beside'`

Valid:

```js
1 + 1; // A valid comment
```

Invalid:
```js
// This is an invalid comment
1 + 1;
```

If you'd like to support both styles, then don't supply a value to this rule.

**Comment by hzoo** [comment]
For this rule, can we do `file.iterateTokensByType('Line', function(comment) {` and then just check `comment.loc.start.column === 0` for above and `!== 0` for beside?

**Comment by mikesherov** [comment]
Well, not zero, but see if the comment is the firstTokenOnLine or not.

**Comment by hzoo** [comment]
oh ok `file.getFirstTokenOnLine` - what a nice helper

**Comment by TheSavior** [comment]
This would be awesome. :+1:

**Comment by GrayedFox** [comment]
:+1: yes would also like to regulate this through our team!

**Comment by markelog** [comment]
@GrayedFox would like to implement it?

**Comment by GrayedFox** [comment]
Yes I think so :) I know it's minor, but you can't beat consistency right?

**Comment by mrjoelkemp** [comment]
Just keep in mind that inline disabling of rules needs to still work. In other words, // jscs disable should still be valid above the line.

**Comment by mrjoelkemp** [comment]
Ping @GrayedFox. Still interested?

**Comment by GrayedFox** [comment]
Hey there - sorry for the lack of updates/communication. I am a bit swamped right now with work, and as a junior QA come dev, this would be a good learning curve for me but would likely take a while. Regrettably passing the buck :disappointed:

**Comment by bjdixon** [comment]
Hi, I'd like to implement this please.

**Comment by mrjoelkemp** [comment]
Go for it @bjdixon. We could use the help!
