### ISSUE TITLE
Current working directory is set to config path

### ISSUE THREAD

**Issue by Bondza** [jscs-dev/node-jscs#669]
In Checker.prototype.configure, cwd is set to config.configPath if it is set. This is then passed to excludeFiles, which is used to resolve the paths that should be excluded.

Therefore it is only possible to exclude paths that lie in the same directory as the configuration file or beneath it in the directory structure. Which in turn makes it impossible to exclude files from the paths specified to jscs. Is this the intended behaviour?

As far as I can see, there is no way I can share a common configuration file between projects like this. Or am I mistaken?

**Comment by zxqfox** [comment]
@markelog Since you already doing something with CLI can you try to make `--cwd` option?

```diff
diff --git a/bin/jscs b/bin/jscs
index 3537a9c..ad5f4ba 100755
--- a/bin/jscs
+++ b/bin/jscs
@@ -15,6 +15,7 @@ program
     .usage('[options] <file ...>')
     .description('A code style linter for programmatically enforcing your style guide.')
     .option('-c, --config [path]', 'configuration file path')
+    .option('--cwd <dir path>', 'will manually set the CWD')
     .option('--auto-configure [path]', 'auto-generate a JSCS configuration file')
     .option('-x, --fix', 'fix code style violations (applies to fixable violations)')
     .option('-e, --esnext', 'attempts to parse esnext code (currently es6)')
diff --git a/lib/cli.js b/lib/cli.js
index f86de75..a043836 100644
--- a/lib/cli.js
+++ b/lib/cli.js
@@ -35,7 +35,7 @@ module.exports = function(program) {
     });

     try {
-        config = configFile.load(program.config);
+        config = configFile.load(program.config, program.cwd);
     } catch (e) {
         console.error('Config source is corrupted -', e.toString());
         defer.reject(1);
```

**Comment by markelog** [comment]
I think it is an issue only in very rare conjunction and it we solve https://github.com/jscs-dev/node-jscs/issues/73 it will go away by itself.

I think we can close this one.

**Comment by zxqfox** [comment]
@markelog It won't because there are no chance to find up plugins and basic `.jscsrc` for global installations (sublime, idea, atom, etc.).

**Comment by zxqfox** [comment]
My bad. It will.

**Comment by aliosv** [comment]
Same problem, want to use config from inner folder(external lib).

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed
