### ISSUE TITLE
Illegal space before closing round bracket in regular expression with esnext option

### ISSUE THREAD

**Issue by ffesseler** [jscs-dev/node-jscs#685]
```js
expect($location.path()).toMatch(/home/);
```
leads to an *Illegal space before closing round bracket* error.

It only happens when using the esnext option

**Comment by danez** [comment]
The issue was fixed in https://github.com/ariya/esprima/commit/fc79b9d827e4c5549ed845e5ecb27f2014e764c0

But no new release yet and esprima-fb needs merging.

**Comment by mikesherov** [comment]
@danez fixing this now. Should be done shortly.

**Comment by ruimarinho** [comment]
@mikesherov that is awesome, I was looking forward for this fix. Any chance of bumping to 1.9.1?

**Comment by mikesherov** [comment]
We'll be releasing 1.10 shortly. Thanks for the patience!

**Comment by MoOx** [comment]
Just got this with 1.10.0

```
Illegal space before closing round bracket at ./src/components/iconsvg/index.js :
    35 |
    36 |  render() {
    37 |    if (!this.props.svg.trim().match(/^\s*</g)) {
----------------------------------------------^
    38 |      console.warn("Please use <IconSvg> with <svg> file")
    39 |    }

Illegal space before closing round bracket at ./src/components/iconsvg/index.js :
    35 |
    36 |  render() {
    37 |    if (!this.props.svg.trim().match(/^\s*</g)) {
-----------------------------------------------------^
    38 |      console.warn("Please use <IconSvg> with <svg> file")
    39 |    }
```

**Comment by mikesherov** [comment]
@MoOx are you sure you're using 1.10 and the --esnext option?

**Comment by MoOx** [comment]
Forget what I said, I werent using that. jsxcs is stuck with ~1.7 :(
Sorry!

**Comment by danez** [comment]
You don't need to use jsxcs for jsx files. We also have jsx files and use jscs with configuration to use espeima-fb. That works perfectly.

**Comment by MoOx** [comment]
I don't use .jsx extension & have errors on every jsx line :(

**Comment by hzoo** [comment]
```json
{
  "esnext": true,
  "esprima": "./node_modules/esprima-fb",
  "fileExtensions": [".js", ".jsx"],
}
```

is working for me (after running `npm install esprima-fb`)

**Comment by MoOx** [comment]
This config works for me. Thanks man.
