### ISSUE TITLE
New format attempt

### ISSUE THREAD

**Issue by markelog** [jscs-dev/node-jscs#698]
<b>WIP</b>

Related to https://github.com/jscs-dev/node-jscs/issues/136
This is what i got so far - https://gist.github.com/markelog/752e53faf9f27de4024d

/cc @mikesherov @mdevils @mrjoelkemp @nschonni

**Comment by hzoo** [comment]
For new/modified rules now, is it still

```
 * "disallowDanglingUnderscores": { allExcept: ["_exception"] }
```

because some rules like requireSpacesInsideParentheses are using

```
 * "requireSpacesInsideParentheses": {
 *     "all": true,
 *     "except": [ "{", "}" ]
 * }
```

**Comment by mikesherov** [comment]
Just wanted to drop a note that the "2-level" approach to configuration here means:

1. the way plugins and getOptionName work needs to change.
2. the way enable/disable comments works needs to change.

I'm not sure again as to the benefit of having 2 levels for rules. It introduces the question of what belongs in the top level vs. the bottom level.

If the options are all normalized, simplified (meaning combining beforeAndAfter and require/disallow) and some names shortened, 1 level looks fine too IMO:

```
"binarySpacing": "require",
"unarySpacing": { require: { allExcept: "++" } },
"curlyBraceBlocks": "require",
"curlyBraceNewlines": "require"
````

Just something to consider.

**Comment by markelog** [comment]
I think we're at the point of prototyping this thing, i'm sure will find more caveats along the way or possible improvements.

**Comment by mrjoelkemp** [comment]
A bit of discussion on this issue going on in Gitter: https://gitter.im/jscs-dev/node-jscs?at=55566279811d64626eebcb40. 

We're torn between forcing users to change their configuration in 2.0 versus having an internal conversion proxy to allow users to not have to change their config.

**Comment by markelog** [comment]
For this issue to resolve i think we need to:
- declaratively specify rule options #480, #895
- preserve back-compat - both old and new format should work
- create classification strategy of which rules should go to which block, like "block", "vars", etc; see the proposed format
- actually add new parsing for the new format
- rules clean-up, at least #853, #538 #1349

Only last one item is a breaking change.

**Comment by markelog** [comment]
In other words, is there any takers for the proposed items?

**Comment by mrjoelkemp** [comment]
Yes, I'm looking at #895.
