### ISSUE TITLE
Remove validateQuoteMarks and disallowMultipleLineBreaks from crockford.json presets

### ISSUE THREAD

**Issue by devdoc** [jscs-dev/node-jscs#718]
http://javascript.crockford.com/code.html does not make statements about the use of quote marks and actually seems to endorse the use of whitespace to improve readability. Crockford seems to use multiple line breaks himself (see e.g. the code for JSLint).

**Comment by markelog** [comment]
Fixed via https://github.com/jscs-dev/node-jscs/commit/5ccacb56491c3c93901c12d5a7f292e1de2f57ee
