### ISSUE TITLE
disallowCurlyBraces

### ISSUE THREAD

**Issue by donaldpipowitch** [jscs-dev/node-jscs#726]
It looks like I can't `disallowCurlyBraces`? I want to disallow it so switch/case looks like this:

````
switch(a) {
  case 'hello':
    break;
  default:
    break;
}
````

Instead of this:
````
switch(a) {
    case 'hello': {
      break;
    }
    default: {
      break;
    }
}
````
I've never saw someone use that last style.

**Comment by markelog** [comment]
Discussion moved to https://github.com/jscs-dev/node-jscs/issues/796

**Comment by danny-andrews** [comment]
https://github.com/jscs-dev/node-jscs/issues/726#issue-47036167 Does this rule work for this use-case? I wasn't able to get it to work for switch statements.
