### ISSUE TITLE
.jscsignore

### ISSUE THREAD

**Issue by zxqfox** [jscs-dev/node-jscs#73]
Please, we need it!

**Comment by yutin1987** [comment]
```{excludedFiles: '.jshintignore'}``` is a good idea.

**Comment by mikesherov** [comment]
@zxqfox would you like to tackle this for 1.12?

**Comment by zxqfox** [comment]
@mikesherov yep. I'll do it ;-)

@mdevils Please take a look here, really want to know your thoughts.

**Comment by masi** [comment]
I think support for .jscsignore is fine, but even better would be if I can name a ignore file. Either in the config or as CLI parameter. Then I could do:

jshint --exclude-path=myjsignore
jscs --exclude-path=myjsignore

a simple myjsignore could look like this:

**/*min.js
**/*minified.js
**/*packed.js

**Comment by zxqfox** [comment]
@masi Yup. But if you gonna use `.jshintignore` or `.gitignore` as `.jscsignore` you can get troubles with different formats.

Anyone against `--excludes-file` option name?

**Comment by mikesherov** [comment]
Yes, I'm against it for now. A symlink can be created at the os level to achieve the same goal without have to add another option to jscs.

**Comment by zxqfox** [comment]
@mikesherov I'm agree in common, but e.g. git on windows doesn't support symlinks.

**Comment by masi** [comment]
Different formats would indeed be troublesome. In my personal ideal world - :) - jshint and jscs are using the same format as git. But I'm fine with a shared format amongst the JS utilities.

**Comment by zxqfox** [comment]
@masi In ideal world — yes. I'm gonna use and suggest for jshint (ignore)[https://www.npmjs.com/package/ignore] package. Guys as jshint also going to a `.gitignore` format (https://github.com/jshint/jshint/issues/1917 and https://github.com/jshint/jshint/pull/1758#issuecomment-60785192) so I think it's a right way.

Thoughts?

**Comment by mrjoelkemp** [comment]
What's the status on this? I'm tempted to close it as `orphaned` unless there's a strong objection.

**Comment by zxqfox** [comment]
Waiting for #1150 to finish this.
Also there is #1159 — I think we should also change this logic in 2.0.

**Comment by mikesherov** [comment]
I still very much want this.

**Comment by mdevils** [comment]
I feel OK deprecating `exludeFiles` and implementing `jshintignore/gitignore`-compatible `.jscsignore` file.

**Comment by jwhitmarsh** [comment]
+1

**Comment by iamstarkov** [comment]
👍

**Comment by shawn-simon** [comment]
How is there no option to specify an ignore file...

**Comment by mikesherov** [comment]
@shawn-simon there is. It's called the `excludeFiles` option. This ticket is to move to a separate ignore file from the current mechanism.

**Comment by shawn-simon** [comment]
That's not a file, it's json. I would like to have all of the ignores in one place, since I'm using jshint as well. Also, for some reason excludeFiles is fired in relation to your current working directory, not the config file. At least it works though!

**Comment by markelog** [comment]
If anyone would help us with this ticket, it would be great

**Comment by jwhitmarsh** [comment]
I'd be interested in helping out with this.

**Comment by mrjoelkemp** [comment]
One idea for tackling this is to use the newline delimited contents of the jscsignore to populate the excludeFiles configuration array internally.

**Comment by mrjoelkemp** [comment]
@jwhitmarsh friendly ping. Any progress on this?

**Comment by ronkorving** [comment]
Would love this too!

**Comment by adambuczynski** [comment]
Was reading this and seeing how it was raised in 2014, really hoping that it would be in by now. Either a .jscsignore or to specify a path to the ignore file to use, so that .jshintignore can be recycled. Anyway, +1 from me for consistency with other libraries/tools.

**Comment by malandrew** [comment]
FWIW, I'm no longer +1 on this. I've completely switched over to eslint since it pretty much meets all the needs that jscs used to address.

**Comment by adambuczynski** [comment]
@malandrew Thanks for the info. I will look into it as well.

**Comment by indexzero** [comment]
@malandrew that passive aggressive behavior is not welcome here. @adambuczynski would love your contributions if you have time. The biggest win that `jscs` has over `eslint` is that the autofix support is much more robust right now. 

At GoDaddy we use both `eslint` and `jscs` together. `eslint` strictly for linting and `jscs` strictly for style. It is a very nice separation that I would recommend adopting. 

I am still very much +1 on this as it bit me recently.

**Comment by indexzero** [comment]
I put a $200 bounty on this issue. Lets do this folks!

**Comment by adambuczynski** [comment]
I used to think that it's a good thing to have them separate, but I'm not sure anymore. Especially since I find myself just merging the results of jshint and jscs in my gulp tasks anyway. I haven't yet tried the autofix feature, because I'm a bit paranoid about software making coding decisions for me, but if it's only style then perhaps I should give it a go.

**Comment by indexzero** [comment]
@adambuczynski exactly. I personally really only want autofix for style. Anything else does make me a little nervous.

**Comment by dsebastien** [comment]
+1

**Comment by nescalante** [comment]
+1, any updates on this one? [seems to be backed on bountysource](https://www.bountysource.com/issues/4706894-jscsignore/backers)

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed
