### ISSUE TITLE
wrong indent expected after function in condition

### ISSUE THREAD

**Issue by Soarez** [jscs-dev/node-jscs#736]
```javascript
var Checker = require('./lib/checker');

var checker = new Checker();
checker.registerDefaultRules();
checker.configure({ validateIndentation: 2 });

var errors = checker.checkString(
    'if ([ 1, 2, 3 ].some(function(n) {\n' +
    '  return n === 2;\n' +
    '}))\n' +
    '  console.log("-.-");\n' +
    '\n' +
    'console.log("done");'
);

console.log(errors.getErrorList());
```

results in:

```json
[ { rule: 'validateIndentation',
    message: 'Expected indentation of 2 characters',
    line: 6,
    column: 2 } ]
```

**Comment by cowwoc** [comment]
I am seeing the same thing (https://github.com/jscs-dev/node-jscs/issues/736#issuecomment-64961655) with JSCS 1.10.0 (the latest version as of this time).

**Comment by mikesherov** [comment]
@cowwoc have you tried master? Let me know if this is still an issue on master

**Comment by cowwoc** [comment]
@mikesherov I'm not very fluent with node. How do I get package.json to depend on a non-versioned version of jscs? Do I clone the project and reference the file path of entry point file? If so, what *is* the entry point file?

**Comment by hzoo** [comment]
Can checkout https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

if you have npm > 1.1.65
```
"jscs": "jscs-dev/node-jscs"
```

**Comment by mikesherov** [comment]
Confirmed this is still happening in master. I suppose that braceless, non single line control structures should make a fake indent... sigh :-\

**Comment by mikesherov** [comment]
Actually, it's just not going to check the indentation of the braceless else, same way it ignores indentation for all control structures with 1 child. Fix incoming.

**Comment by cowwoc** [comment]
Happy happy! Joy joy! :) Thanks.
