### ISSUE TITLE
Plugin API modification guesses

### ISSUE THREAD

**Issue by zxqfox** [jscs-dev/node-jscs#739]
Continue of dialog in #731 with @mdevils 

So, cases are:
- Allow modifying prototypes (or append helpers) to file and node objects;
- Allow modifying file/node on check by hooks (preparing files/nodes before checking);
- Think about nested option names (it's a real pain to make separated nested rules)

### Examples

Configuration:
```js
{
  "plugins": ["my-plugin"],
  "someRule": true, // trash in global scope?
  "nestedRulesInPluginNs": {
    "otherRule": true // nested rules?
  }
}
```

Plugin index:
```js
module.exports = function(conf) {
    conf.setPluginNamespace('nestedRulesInPluginNs'); // maybe like that?
    conf.registerRule(require('./rules/some-rule'));
    conf.registerRule(require('./rules/other-rule'));
    conf.registerNodeHelper('nodeHelper', function () { /* this = node; */ });
    conf.registerFileHelper('fileHelper', function () { /* this = file; */ });
};
```

Some rule:
```js
module.exports = function() {};
module.exports.prototype = {
  configure: function (options) {
    // asserts
  },
  getOptionName: function () {
    return 'someRule';
  },
  check: function(file, errors) {
    file.fileHelper(); // yay!
    file.iterate(function (node) {
      node.nodeHelper(); // yayayay!
    });
  }
};
```

Other rule:
```js
module.exports = function() {};
module.exports.prototype = {
  configure: function (options) {
    // asserts
  },
  getOptionName: function () {
    return 'otherRule'; // or nestedRulesInPluginNs.otherRule
  },
  check: function(file, errors) {
  }
};
```

--- 

Modification of files/nodes are very very useful for development rules which needs some additional calculation. For example, parsed comments in `jsdoc` plugin. Otherwise it's a real pain to share this data between separate rules.

Also there is no API for nested rules declaration. It means flat configuration list. It can be done by plugin namespaces or explicit declaration in `getOptionName` in rule name or in `getNamespace`. But there is the flip side: if your rule would be checked separately how to share some options between them?

**Comment by TheSavior** [comment]
I also want to throw in that there should be some sort of support for being able to test these custom plugins against the framework that we have for JSCS.

**Comment by hzoo** [comment]
Where are we with this?
