### ISSUE TITLE
Move traversing module (js-file) to its own npm-module

### ISSUE THREAD

**Issue by markelog** [jscs-dev/node-jscs#747]
`js-file` module is pretty powerful, it might be used in different projects and help others.

Just like [estraverse](https://github.com/Constellation/estraverse) or tools alike standalone we could do the same, but most (all?) of those tools use only AST, whereas we also use tokens and basically created methods that link AST with tokens, which mean you could do more, in some cases much more.

**Comment by hzoo** [comment]
Should we close this specific issue since we're talking about a CST now?

**Comment by mrjoelkemp** [comment]
Seems so. +1 to closing. Will let @markelog decide.
