### ISSUE TITLE
Illegal space before closing round bracket with ES6 template string

### ISSUE THREAD

**Issue by lencioni** [jscs-dev/node-jscs#748]
The following code:

```js
throw new Error(`foo ${'bar'}`);
```

leads to an `Illegal space before closing round bracket` error. It seems to only happen if there is interpolation in the template string.

**Comment by MoOx** [comment]
Getting the same issue (even with esprima-fb).

**Comment by mikesherov** [comment]
Template strings are not yet supported. Leaving this open until then.

**Comment by vtambourine** [comment]
I have the same annoying problem...

Is the source of the problem lies in esprima or in the jscs-rules?

**Comment by zxqfox** [comment]
@vtambourine Probably in both projects. But basically in esprima.

**Comment by lencioni** [comment]
[ESLint has a fork of Esprima](https://github.com/eslint/espree) that might be worth looking into.

**Comment by mikesherov** [comment]
Looks like harmony now supports this. Investigating soon.

**Comment by mikesherov** [comment]
Is due to this bug after investigating: https://code.google.com/p/esprima/issues/detail?id=632

**Comment by kristerkari** [comment]
@mikesherov ping

I see that nothing has happened here in a while, so what's the status of this bug? Is there anything that I could do to help it getting fixed? I'm using template strings a lot and this bug is annoying :)

**Comment by mikesherov** [comment]
@kristerkari, I've fixed this in Esprima. Just waiting to get it merged. This should be resolved in JSCS 1.12

**Comment by stefanpenner** [comment]
eta for 1.12?

**Comment by mrjoelkemp** [comment]
Scheduled for tomorrow.

**Comment by stefanpenner** [comment]
@mrjoelkemp <3

**Comment by ruimarinho** [comment]
Thank you @mikesherov :raised_hands:
