### ISSUE TITLE
requireSpaceAfterBinaryOperators: issue with location of error

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#756]
I think the spacing should change to the end of the token right?

![](http://i.imgur.com/JCHPFQ3.png)

I works for single character operators like `>` and `*` but not for `==` and `===`

https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/require-space-after-binary-operators.js#L85

Maybe it should be `var loc = part.loc.start;` -> `var loc = part.loc.end;`? Although i'm not sure since the `===` has it point to the middle character.

**Comment by hpshelton** [comment]
This seems to have been fixed by https://github.com/jscs-dev/node-jscs/commit/b5c6dad7daf393eb68727e0617c9141efe35189b on Nov 23. I'll add additional unit tests to prevent any future regressions here.
