### ISSUE TITLE
Extract JavaScript to validate from HTML files

### ISSUE THREAD

**Issue by aik099** [jscs-dev/node-jscs#764]
I saw an `--extract` option on JsHint (http://www.jshint.com/docs/cli/) that allow to extract JavaScript (what comes between `<script>` tags) from HTML pages. Would be great if JSCS would have similar option.

**Comment by lahmatiy** [comment]
Hi, all! I almost done on this feature.
But something strange with code coverage, looks like new test file doesn't apply. Please see PR https://github.com/jscs-dev/node-jscs/pull/1038.
Looking forward for feedback.

**Comment by mikesherov** [comment]
@lahmatiy, thanks for contributing! Your test file is named incorrectly. It should be `test/extract-js.js`. Our coverage tool only counts coverage on a file for the tests written for a file and does the matching by filename.

**Comment by lahmatiy** [comment]
@mikesherov Thanks for your explanations. I fixed tests. And looks everything fine now.
