### ISSUE TITLE
disallowSpaceAfterObjectKeys doesn't work with ES6 object shorthand

### ISSUE THREAD

**Issue by gustavohenke** [jscs-dev/node-jscs#772]
The rule `disallowSpaceAfterObjectKeys`, when used in combination with [ES6 object shorthands](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-object-initialiser), will produce errors.

Example code:
```js
return { foo };
```

_The spec URL was taken from [Traceur Compiler](/google/traceur-compiler/wiki/LanguageFeatures#object-initializer-shorthand) wiki._

**Comment by mikesherov** [comment]
It does parse @mrjoelkemp . The demo you linked to had an illegal return statement. Here's the updated link: http://esprima.googlecode.com/git-history/harmony/demo/parse.html?code=function%20hi()%20%7B%0A%09return%20%7B%20foo%20%7D%3B%0A%7D

**Comment by mikesherov** [comment]
https://github.com/jscs-dev/node-jscs/pull/992 ;-)
