### ISSUE TITLE
Invalid JSDoc param argument

### ISSUE THREAD

**Issue by mrjoelkemp** [jscs-dev/node-jscs#778]
```
~/D/node-precinct (sass ⚡) jscs -p google index.js
Invalid JSDoc @param argument name at index.js :
     8 |/**
     9 | * Finds the list of dependencies for the given file
    10 | * @param {String} file - path of the file whose dependencies to find
-----------^
    11 | * @param {String} [type] - The type of content being passed in. Useful if you want to use a non-js detective
    12 | * @return {String[]}


1 code style error found.
```

Will investigate the root cause of this. Might only be the `google` preset.

**Comment by zxqfox** [comment]
We also should think about merging different presets. It would helps a lot in many cases for plugins.

E.g. jscs provides a bunch of basic style rules, plugin provides their presets with plugin rules, for now you can't merge them (manually only). Related: #109

**Comment by mikesherov** [comment]
@zxqfox can you remove the rule from all presets, and mark it as deprecated in it's docs? We can move the multi preset discussion back to #109 where it belongs. Thanks!

**Comment by zxqfox** [comment]
@mikesherov I couldn't find deprecated rules section ;-( validateJSDoc rule is moved out of docs since jscs.info or even earlier.

**Comment by zxqfox** [comment]
I propose just move out usage of that rule by @mrjoelkemp's commit.

Also we can cleanup tests but imo that's not really important.

**Comment by markelog** [comment]
I remember de decided to do this in 2.0, did something change?

**Comment by zxqfox** [comment]
To be clear: we can change presets in 1.11, and drop these rules in 2.0 (as decided). #982

**Comment by markelog** [comment]
Sure we can, but should we, anyway, do not feel strongly about this.

Would need to create warnings for them though which is always a pain.

**Comment by zxqfox** [comment]
I've made a clear issue. Closing this.
