### ISSUE TITLE
requireTrailingCommaInExpandedLiterals?

### ISSUE THREAD

**Issue by mzgol** [jscs-dev/node-jscs#795]
A while ago I created a "plugin" for handling trailing commas in array/object literals:
https://www.npmjs.org/package/jscs-trailing-comma
It was way before plugins started to be supported by JSCS so it doesn't use the new interface yet.

I've noticed a core method now conflicts in the name with my own but my plugin exposes two additional classes of rules: `{require,disallow}TrailingCommaInCollapsedLiterals` and `{require,disallow}TrailingCommaInExpandedLiterals`. For example, in my projects I usually use:

```js
    "requireTrailingCommaInExpandedLiterals": true,
    "disallowTrailingCommaInCollapsedLiterals": true
```

This allows me to avoid having to write `{a: 2, b: 3,}` while still requiring trailing commas in "expanded" literals; see https://github.com/EE/jscs-trailing-comma#rationale for rationale and a detailed description of the distinction.

My question is: would you consider adding an option like that to the core `{require,disallow}TrailingComma` rules? I'd then be able to deprecate my plugin completely.

**Comment by mzgol** [comment]
> @mzgol that's a good rule, although I think it would be a bit more robust to say that collapsed is last element on same line as closing brace AND more than one element per line. Thoughts?

I thought about it a little more; by "more than one element per line" do you mean that all lines have more than one element? It might be surprising if you change the following code:
```js
var a = ['a', 'b',
    'c', 'd',
    'e', 'f',];
```
into:
```js
var a = ['a', 'b',
    'c', 'd',
    'd0',
    'e', 'f',];
```
and suddenly JSCS would complain about the trailing comma...

**Comment by mrjoelkemp** [comment]
This issue has been inactive for quite a while. Going to close as `orphaned`. Happy to reopen if anyone wants to submit a patch.
