### ISSUE TITLE
disallowCurlyBrace

### ISSUE THREAD

**Issue by mikesherov** [jscs-dev/node-jscs#796]
This replaces #126. Essentially, this rule will throw an error when a control structure has a block with a single statement inside. .e.g:

```
// valid
if (x===1) foo();
else bar();

// valid
if (x ===1) {
  foo();
  bar();
}
else baz();

// invalid
if (x===1) { foo(); }
else { bar(); }
```

**Comment by markelog** [comment]
> This replaces #126.

And #726

**Comment by markelog** [comment]
Associated PR https://github.com/jscs-dev/node-jscs/pull/880

**Comment by danny-andrews** [comment]
This doesn't work for me for switch statements.  
.jscsrc  
```json
{
  "disallowCurlyBraces": ["case", "default"]
}
```
example.js  
```javascript
switch(a) {
  case 1: {
    console.log('you got one');
  }
  default: {
    console.log('you got something other than one');
  }
}
```
This example passes with no errors from jscs.

**Comment by hzoo** [comment]
Looking at the [source](https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/disallow-curly-braces.js) - it was never implemented for case/default so they aren't valid options atm. If you want you can create a new issue to add them.

Although looking now they are valid in requireCurlyBraces (funny). If you want to make a PR for this go ahead! https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/require-curly-braces.js

**Comment by danny-andrews** [comment]
Yeah, that's what threw me off, haha. I'll take a look and see what I can do.
