### ISSUE TITLE
Autoconfiguration option

### ISSUE THREAD

**Issue by mikesherov** [jscs-dev/node-jscs#797]
JSCS should have a cli option called `--configure`. When ran from the root of your project, it will do the following:

1. ask you to specify the location of your javascript files. 
2. run each preset against your codebase.
3. output the number of violations from each preset with a link to the style guide.
4. ask you to choose a preset based on the output of 3.
5. go through the remaining violations, rule by rule. For each violation, it will ask: "Would you like to create an exception for this rule, or fix this issue?"
  1. for each "exception" created, it will nullfy that rule in .jscsrc.
  2. for each "fix this issue", in the future, will automatically fix it, but for now require you to fix it.
6. at the end, it will output a .jscsrc file for you to commit yourself.

Supercedes #341

**Comment by mrjoelkemp** [comment]
Finished the first iteration. It works, but needs code cleanup, tests, and documentation. I'll finish up those items to get the PR ready for review either tomorrow (Tuesday) or this weekend.

Here's what it looks like:

![screen shot 2015-01-13 at 1 00 00 am](https://cloud.githubusercontent.com/assets/865203/5716604/b65289fa-9abf-11e4-9724-80b18a79d45c.png)

Code is here: https://github.com/jscs-dev/node-jscs/pull/908

**Comment by markelog** [comment]
Looks good!

Maybe you could send PR now? Could be very well be a WIP.

**Comment by mrjoelkemp** [comment]
@markelog PR is here: https://github.com/jscs-dev/node-jscs/pull/908

**Comment by jzaefferer** [comment]
This looks like a good approach, I like the CLI previews, too. Regarding

> output the number of violations from each preset with a link to the style guide.

and

> A small reservation that I have is outputting a link to the style guide since that information is not a part of the preset's configuration and not readily available at runtime.

This could be addressed by adding a URL to each preset. I expect each of these presets to have a stable URL where the style guide is documented.

Could just add a `presetUrl` property at the start of each preset `json` file. Or `_presetReference` or some such, whatever avoids collisions with actual rules.
