### ISSUE TITLE
add rules to presets for major version bump

### ISSUE THREAD

**Issue by mikesherov** [jscs-dev/node-jscs#808]
This should be a running list of all rules that need to be added to presets.

`requireInitializedVariablesFirst`: airbnb, wikimedia.
`requireInitializedVariablesLast`: jquery

/cc @indexzero @Krinkle @markelog @mrjoelkemp

**Comment by craigjennings11** [comment]
For airbnb, I think `"disallowKeywordsOnNewLine": ["else"]` needs to be added (https://github.com/airbnb/javascript#blocks)

**Comment by markelog** [comment]
@craigjennings11 didn't notice this comment before, would you like to send us a PR?

**Comment by craigjennings11** [comment]
On it

**Comment by craigjennings11** [comment]
Addressed in #1333

**Comment by hzoo** [comment]
Did we already do these?

**Comment by markelog** [comment]
We doing that in general, but `requireInitializedVariablesFirst` is still required to be implemented, although since jquery code-style changed we no longer need `requireInitializedVariablesLast`

**Comment by hzoo** [comment]
We can just leave a note in the #807 issue that jquery requires the rule and close this?

**Comment by hzoo** [comment]
Closing this in favor of #807
