### ISSUE TITLE
requirePaddingNewlinesBeforeKeywords rule with switch statement

### ISSUE THREAD

**Issue by leigeber** [jscs-dev/node-jscs#810]
It would appear that the requirePaddingNewlinesBeforeKeywords does not consider a case inside a switch statement a block. We require a break before if statements but would not require one as the first line inside a case. Its pretty rare we would run across advanced logic in a case but though I would bring this up.

**Comment by hzoo** [comment]
Going to be closing older/inactive issues and labeling with `orphaned` to track anything we might want to reopen again later (if we want to add it again or something has a PR). Thanks
