### ISSUE TITLE
Allow differentiation of call expressions in the requireSpacesInsideParentheses rule

### ISSUE THREAD

**Issue by jamesallardice** [jscs-dev/node-jscs#812]
The style guide that I adhere to contains the following conventions:

```js
var x = getX(y, z); // No spaces inside call expression parens

if ( x ) {
  // Spaces inside the parens of control flow structures and function definitions
}
```

The `requireSpacesInsideParentheses` rule does not provide any mechanism for differentiating between these two cases. I think there's a few possible solutions:

 - A custom rule if this isn't something that would be widely useful
 - A modification to `requireSpacesInsideParentheses`. The rule already accepts an object so a property could be added to this. A set of values could also be added to the `except` array:

```js
"requireSpacesInsideParentheses": {
  "all": true,
  "except": [ "if", "while" /*...*/ ]
}
```

 - A new rule could be added

**Comment by hzoo** [comment]
Is this closed now?

**Comment by markelog** [comment]
No, that pr only for grouping parentheses

**Comment by hzoo** [comment]
Going to be closing older/inactive issues and labeling with `orphaned` to track anything we might want to reopen again later (if we want to add it again or something has a PR). Thanks :smiley: !
