### ISSUE TITLE
Turn off es3 by default

### ISSUE THREAD

**Issue by mikesherov** [jscs-dev/node-jscs#824]
The default behavior for JSCS currently assumes ES3 support. We should change the default to opt-in in 2.0 as this is a breaking change.

**Comment by adrianheine** [comment]
Is there currently any way to deactive es3 via cli?

**Comment by zxqfox** [comment]
:+1: 

@adrianheine Acually, there are 2 options: https://github.com/jscs-dev/node-jscs/blob/master/lib/js-file.js#L23-L24

ES5 is used by default, as I see.
Behaviour: https://github.com/jscs-dev/node-jscs/blob/master/test/specs/js-file.js#L835-L867

What we decide to do with the options? I don't see where they are documented ;-(

**Comment by markelog** [comment]
> ES5 is used by default, as I see.

Can we close this then?

**Comment by zxqfox** [comment]
> Can we close this then?

I think so. :+1: for closing as resolved or non-fixable.

**Comment by zxqfox** [comment]
/cc @mikesherov @mdevils

Polite ping.

**Comment by hzoo** [comment]
Is this the only thing left in terms of issues/prs for 2.0?

**Comment by mikesherov** [comment]
I thought that we still have some places where we assume es3, like allowing quoted object keys if the key is a reserved word. Is that not true?

**Comment by zxqfox** [comment]
I've found the reason of this issue. Gonna fix it. Looks like there will be some reworks in some rules also.

I hope we are ok with that because we gonna switch major version
![image](https://cloud.githubusercontent.com/assets/677518/8764728/14568dfe-2df4-11e5-84ea-5c3b15326713.png)
