### ISSUE TITLE
requirePaddingNewlinesBeforeKeywords with very small blocks

### ISSUE THREAD

**Issue by indexzero** [jscs-dev/node-jscs#826]
I do enjoy padding newlines before returns for large blocks, but for small blocks (say less than or equal to two lines) they are quite cumbersome.

e.g. 

``` js
try {
  fs.statSync(someFile);
  return true;
}
catch (ex) {
  return false;
}
```

**vs.**

``` js
try {
  fs.statSync(someFile);
  
  return true;
}
catch (ex) {
  return false;
}
```

I am proposing that this rule be made configurable to have a minimum size of a block before throwing an error. Thoughts?

**Comment by markelog** [comment]
@mikesherov, @mrjoelkemp thoughts?

**Comment by mrjoelkemp** [comment]
Sounds good. I assume this would be in the form of an object with a property called `minimumBlockSize`: `Number`. Is this the same as applying `true` or should we still allow the user to specify keywords? If we're still allowing specific keywords, then @markelog might have a better idea on how the config might possibly adhere to #698

**Comment by hzoo** [comment]
Going to be closing older/inactive issues and labeling with `orphaned` to track anything we might want to reopen again later (if we want to add it again or something has a PR). Thanks
