### ISSUE TITLE
Ignore/Except Quotes in requireSpacesInsideParentheses

### ISSUE THREAD

**Issue by kelvinlouis** [jscs-dev/node-jscs#836]
Is it possible to ignore quotes from requireSpacesInsideParentheses?
I'd like to cover this case (https://github.com/rwaldron/idiomatic.js/#type 2.C.1.3) 
```javascript
// Single argument string literal, no space
foo("bar");
```

This doesn't work:
```javascript
"requireSpacesInsideParentheses": {
 "all": true,
 "except": [ "{", "}", "\"" ]
},
```

Any ideas?

**Comment by markelog** [comment]
Reopening, since jquery code-style changed and doesn't need it anymore, but <a href="https://github.com/jscs-dev/node-jscs/issues/1065">incoming</a> `idiomatic` preset would require this feature.

/cc @hzoo

**Comment by hzoo** [comment]
How would we go about checking this?
The rule is using `value = nextToken.value`.
```js
foo("bar"); // value = "bar"
foo('bar'); // value = 'bar'
```
quote is single quote, double quote, es6 template
and then something like `if (nextToken.type === 'Literal' && value[0] === quote) { return; }`
