### ISSUE TITLE
exceptions for requireCapitalizedComments

### ISSUE THREAD

**Issue by alawatthe** [jscs-dev/node-jscs#837]
I like the ```requireCapitalizedComments``` rule, but I ran into the problem, that some tools like jshint or istanbul require their inline configuration to be lowercase.

For example:
```javascript
/* istanbul ignore else  */
if (foo.hasOwnProperty('bar')) {
    // do something
}
```
isn't working with the ```requireCapitalizedComments``` rule.

My suggestion:
```requireCapitalizedComments``` should accept an array of strings. These words can be exceptions to the upper case rule.

So with 
```
requireCapitalizedComments: ["globals", "istanbul", "jshint"]
```
the above example would work.

(The same could be done for ```disallowCapitalizedComments```, too.)

Any thoughts?

**Comment by zxqfox** [comment]
Dup of #1045

**Comment by mrjoelkemp** [comment]
Closing this one since discussion already started on the dupe.

**Comment by markelog** [comment]
Don't forget to add labels :-)
