### ISSUE TITLE
disallowOperatorBeforeLineBreak erroneously reporting objects?

### ISSUE THREAD

**Issue by Deathspike** [jscs-dev/node-jscs#845]
If `disallowOperatorBeforeLineBreak` is set to true, this will erroneously report the following code:

    'use strict';

    /**
     * Represents the route configuration.
     * @param {$RouteProvider} $routeProvider
     */
    function Route($routeProvider) {
      $routeProvider.when('/', {
        controller: 'TestController',
        templateUrl: 'views/test-view.html'
      }).otherwise({
        redirectTo: '/'
      });
    }

    module.exports = ['$routeProvider', Route];

With:

    Operator needs to either be on the same line or after a line break. at route.js:
         8 |  $routeProvider.when('/', {
         9 |    controller: 'TestController',
        10 |    templateUrl: 'views/test-view.html'
    ------------^
        11 |  }).otherwise({
        12 |    redirectTo: '/'

While according to the documentation, it should not apply here at all (JSCS 1.8.1)

**Comment by mzgol** [comment]
> In terms of short term I think maybe we should remove ',' from the defaults at least for this config variable and maybe others.

Any news about that? As it stands, the default value of this option is useless.

**Comment by izeau** [comment]
Workaround for the time being:

> `.jscsrc`

```
{
  // every operator but the comma (see https://github.com/jscs-dev/node-jscs/issues/845)
  "disallowOperatorBeforeLineBreak": ["=", "+=", "-=", "*=", "/=", "%=", "<<=", ">>=", ">>>=", "&=", "|=", "^=", "+", "-", "*", "/", "%", "<<", ">>", ">>>", "&", "|", "^", "&&", "||", "===", "==", ">=", "<=", "<", ">", "!=", "!=="]
}
```

**Comment by AaronGeorge** [comment]
Any news on this?

**Comment by markelog** [comment]
That would be a breaking change, so in 2.0, which should be released soon, would you mind sending pr for this?
