### ISSUE TITLE
Ability to specify custom nodes to the treeIterator for custom grammars

### ISSUE THREAD

**Issue by yannickcr** [jscs-dev/node-jscs#865]
Since 1.8.0 we can specify a custom esprima version via CLI or config and that's great :tada: 

But sadly when using custom esprima version we can also need to:
* specify potential unkown node types to estraverse in lib/tree-iterator.js (#830)
* pass some custom parameters to esprima. For example, if I want to use the new esprima fork [espree](https://github.com/eslint/espree) with some [ES6 features and/or JSX support](https://github.com/eslint/espree#usage).

Current implementation of the custom esprima option is very limited in term of configuration which limit us in term of alternatives for the current esprima parser.

Some solutions can be to:
* be aware of some esprima alternative and handle their custom node types and their options, but it limits JSCS to a whitelist of known alternatives.
* expose custom node types list and parser options in the configuration file/CLI, but it will make more difficult to use JSCS with a custom parser (more configuration to set up).
* both, handling of custom node types and options for known alternatives but allow the possibility to customize these parameters in configuration file/CLI if needed.
* any other solution ?

**Comment by yannickcr** [comment]
Thanks for your reply.

I understand your reluctance to set up some special cases for a very new parser like Espree.

As said, another solution could be to expose the esprima options in the config file. For example:

```json
"esprima": "espree",
"esprimaOptions": {
    "ecmaFeatures": {
        "regexYFlag": true,
        "regexUFlag": true,
        "binaryLiterals": true
    }
}
```
(and keep forcing `loc`, `range`, `comment`, `tokens` to `true` since jscs need them)

I could allow anyone to configure the parser the way he want, without relying on a module with the hardcoded features.

What's your thought about this ?

**Comment by mikesherov** [comment]
@yannickcr see #903 for controlling options

**Comment by yannickcr** [comment]
Great! Thanks.

**Comment by mikesherov** [comment]
Keeping this open though for ability to pass custom node types to tree iterators

**Comment by hzoo** [comment]
Going to be closing older/inactive issues and labeling with `orphaned` to track anything we might want to reopen again later. Thanks
