### ISSUE TITLE
API method for finding a reporter

### ISSUE THREAD

**Issue by sindresorhus** [jscs-dev/node-jscs#867]
So consumers doesn't have to reimplement it.

See: https://github.com/jscs-dev/gulp-jscs/pull/41#discussion_r22385643

**Comment by UltCombo** [comment]
Like `module.exports.reporter = getReporter;` ? That'd be the closest to gulp-jshint, I think.

**Comment by sindresorhus** [comment]
@UltCombo We're not going to directly re-export it as we need to handle the reporter initiation. But yeah. JSCS could expose a `getReporter` (clearer than `reporter`) function.

**Comment by UltCombo** [comment]
Oh yes, thought I was in the gulp-jscs when I suggested a `reporter` export. gulp-jscs exposing a `reporter` would be consistent with gulp-jshint then.

**Comment by markelog** [comment]
Check it out - https://github.com/jscs-dev/node-jscs/issues/867

**Comment by mikesherov** [comment]
ping @UltCombo and @sindresorhus . Does this PR address your needs?

**Comment by UltCombo** [comment]
I believe so. Thanks @markelog :smile: 
I most likely won't have much free time this week to try it out, so I'm not 100% sure.
