### ISSUE TITLE
Add link to the live gh-pages branch site in repo description

### ISSUE THREAD

**Issue by mrjoelkemp** [jscs-dev/node-jscs#872]
Not sure what the url is. Do we even maintain it?

/cc @mdevils

**Comment by hzoo** [comment]
can add `jscs.info` from #873 then right?

**Comment by mrjoelkemp** [comment]
Yes, but it has to be done by the repo owner. Specifically, I'm talking about this location next to the repo description: 

![image](https://cloud.githubusercontent.com/assets/865203/5600266/86d91dec-92a4-11e4-928a-c72d20501a64.png)

**Comment by hzoo** [comment]
Yeah sounds good

**Comment by mdevils** [comment]
Thank you! Added the link!
