### ISSUE TITLE
Provide a rule to require/disallow whitespace inside bracket notation accessors

### ISSUE THREAD

**Issue by jdforrester** [jscs-dev/node-jscs#875]
In line with disallow/requireSpacesInsideArrayBrackets, maybe something like "disallow/requireSpacesInsideAccessBrackets":

`disallowSpacesInsideAccessBrackets = true;`
```js
// VALID
foo[0];
// INVALID
foo[0 ];
foo[ 0];
foo[ 0 ];
```

`requireSpacesInsideAccessBrackets = true;`
```js
// VALID
foo[ 0 ];
// INVALID
foo[0];
foo[0 ];
foo[ 0];
```

**Comment by gero3** [comment]
I already have written such a rule that requires spaces.
[require-spaces-in-computed-memberExpression](https://github.com/gero3/node-jscs/blob/formatter/lib/rules/require-spaces-in-computed-memberExpression.js)

**Comment by jdforrester** [comment]
Awesome, thanks.

**Comment by zxqfox** [comment]
What about:
```
foo[/*baz*/ 1 ]
foo[ 1 /*baz*/]
```

**Comment by jdforrester** [comment]
I'd say that the comment should be considered content and so both those test cases would fail as I'd imagined it. Is there a wider setting to ignore comments for the purposes of whitespace validation? Should there be?

**Comment by shobhitg** [comment]
I just landed on this page because I wish JSCS to ignore everything inside Block Comments.
So IMO, there should be a wider setting to ignore comments or block comments.

**Comment by zxqfox** [comment]
Actually, for now these comments will be ignored because all rules works with tokens while esprima doesn't provide them in AST. It's a Parser API standard.

It's not a problem already since we have tools to work with these cases. We just need to decide what to do ;-)

**Comment by hzoo** [comment]
Going to be closing older/inactive issues and labeling with `orphaned` to track anything we might want to reopen again later (if we want to add it again or something has a PR). Thanks
