### ISSUE TITLE
Spurious issue running tests on travis.

### ISSUE THREAD

**Issue by ljharb** [jscs-dev/node-jscs#883]
A significant percentage of the time I run builds on `travis-ci`, `npm install` fails when trying to install `jscs` - specifically `esprima`.
```bash
npm ERR! EEXIST, symlink '../esprima/bin/esparse.js'
```

See https://travis-ci.org/paulmillr/es6-shim/jobs/45910645 for an example.

Do you have any idea what's causing this? When this happens, I can occasionally just rerun the build and it passes, but sometimes the build never passes.

**Comment by markelog** [comment]
This is probably npm issue, like - https://github.com/npm/npm/issues/6309 

We don't do anything special for esprima here.

**Comment by ljharb** [comment]
Turns out this is absolutely a `jscs` issue - `esprima` and `esprima-harmony-jscs` both publish a binary named `esparse`, and as such, are **incompatible** as sibling dependencies.

Unless one of them renames their binary, `jscs` must not depend directly on both.

/@markelog

**Comment by markelog** [comment]
We discussed this issue in length in here - https://github.com/jscs-dev/node-jscs/issues/787

Do you still see the errors?

**Comment by markelog** [comment]
Yeah, given discussion in <a href="https://github.com/npm/npm/issues/7130">here</a>. i'm reopening this.

/cc @Krinkle, @mikesherov

**Comment by ljharb** [comment]
Not as often as I used to, but yes, still occasionally.

**Comment by Krinkle** [comment]
Whether or not there is a bug in npm, the immediate cause is that node-jscs depends on https://www.npmjs.com/package/esprima and https://www.npmjs.com/package/esprima-harmony-jscs. Both of these export a `esparse` and `esvalidate` bin in package.json.

Can we remove it from esprima-harmony-jscs? Or give it a different name? I assume jscs isn't using the bin path because it would conflicting without knowing which one it is using.

**Comment by zxqfox** [comment]
@Krinkle :+1: for that.

Another solution is to have a proxy npm-package with esprima-harmony-jscs.

**Comment by markelog** [comment]
I don't see a reason why we still need a `esprima-harmony-jscs` it seems we can just update esprima to the latest 2.2 and let es6 be enabled by default.

@mikesherov ?

**Comment by zxqfox** [comment]
@markelog Yeah, I've tried Esprima 2.x with JSCS and it works well, but seems like we should inc major version.

**Comment by markelog** [comment]
Why

**Comment by zxqfox** [comment]
@markelog Because we can't guarantee work of plugins.

**Comment by markelog** [comment]
Why?

**Comment by mikesherov** [comment]
Our form of esprima-harmony supports more of es6, namely generators, for of, and a few others. Once ESPrima has full es6 support, we'll ditch our fork.

**Comment by markelog** [comment]
@mikesherov okay, so it seems after 2.3 we can ditch it, although we can update esprima to 2.2?

**Comment by markelog** [comment]
@Krinkle, @ljharb could use current master in your CI-runs to see if problem is resolved?

**Comment by ljharb** [comment]
That's a bit tricky - is it something that couldn't be released in a patch version?

**Comment by markelog** [comment]
Minor will be released very soon (hoping for monday) just wanted to be sure we all okay here, so we would need to release 1.13.1 or something.

It most certainly should be fixed, but i can't test it, can't reproduce it, so it shot in the dark

**Comment by Krinkle** [comment]
@markelog It's a race condition (maybe 1 in a 100). I can't easily test it. Additionally because we've got dozens of different repositories using jscs. However I'm quite certain that removing `bin` will resolve the conflict.

**Comment by Krinkle** [comment]
@markelog It's hard to be sure since it is a race condition. Initial testing shows the problem is solved. I can't be sure until it is released because we have many different projects each with their own `package.json` that specifies the version.

**Comment by ljharb** [comment]
Just to close the loop; this hasn't happened for me in months, so the problem is solved for me. Thanks!
