### ISSUE TITLE
disallowSpacesInsideParentheses throw error on valid regular expression.

### ISSUE THREAD

**Issue by mattma** [jscs-dev/node-jscs#884]
I am using latest `jscs` globally installed on my Mac.

```bash
 ➜ jscs --version                                                                                                        
1.9.0
```

I have this feature on `disallowSpacesInsideParentheses`. Not sure it is something to do with `esnext`, I read through the issue list and it may have something to do with it.

```js
{
  "esnext": true,
...
"disallowSpacesInsideParentheses": true
}
```

I execute the command `jscs test`, here is the result:

```bash
Illegal space before closing round bracket at test/errors/index.spec.js :
    49 |          err.should.be.an.instanceOf(Error);
    50 |          err.should.be.equal(toThrow);
    51 |          err.should.match(/test1/);
------------------------------------^
    52 |          done();
    53 |        });


1 code style error found.
```

I do not have any spaces inside the parentheses, and it should be valid the rules. Is this a bug or user error? Thanks

**Comment by mikesherov** [comment]
Thanks for contributing! As noted, this is a dupe.
