### ISSUE TITLE
Disallowing do..while on new line

### ISSUE THREAD

**Issue by gagle** [jscs-dev/node-jscs#885]
I would like to have this restriction:

```javascript
do {
  ...
} while (...);
```

The `while` used with `do` should be placed in the same line of the closing curly brace. However, this cannot be defined with the option `disallowKeywordsOnNewLine` because a single `while` would be marked as invalid.

```javascript
// This gives an error: Keyword 'while' should not be placed on a new line
while (...);
```

How can I require a do..while on the same line but allow single whiles on a new line?

**Comment by mikesherov** [comment]
@gagle thanks for contributing! We'll be looking into this shortly!
