### ISSUE TITLE
TypeError: Cannot read property 'loc' of undefined for disallowNewlineBeforeBlockStatements

### ISSUE THREAD

**Issue by tteltrab** [jscs-dev/node-jscs#887]
Specifically, JSCS exits with this error if you have a file which begins with a block statement.  Using jscs 1.9.0 on OSX.  Specifically, files beginning with "{" cause the issue as there doesn't exist a token before the openingBrace token and thus the prevToken variable is undefined, causing the error.

**Comment by markelog** [comment]
Thank you for the report, would you like to send us a pull request?

**Comment by markelog** [comment]
Went ahead on this one, would need to fix this asap

**Comment by tteltrab** [comment]
The pull request was #888, had it up for a day or so already.

**Comment by markelog** [comment]
Did a simplified version of it, but still merged yours, since it was better
