### ISSUE TITLE
Add ability to declare acceptable values for the rules

### ISSUE THREAD

**Issue by markelog** [jscs-dev/node-jscs#895]
Now this responsibility falls on the `configure` method, but it would much easier if this method would be replaced by some declaration like:

```js
values: [{
    type: "object",
    value: { 
        type: "string",
        value: "allExcept"
    }
}, {
    type: "boolean",
    value: true
}];
```

we couldn't fully dispose from the `configure` method, but it will simplify a lot of things

/cc @mdevils

**Comment by zxqfox** [comment]
It can be replaced with a `function({Conf} conf)` with some `conf.registerRuleValue` inside.

Also one rule could handle several rules and values. And also one rule could have aliases (for modern configuration).

But fully declarative version (yours) will also be good.

**Comment by mdevils** [comment]
As I can remember, @mikesherov wanted to do something about it.

**Comment by markelog** [comment]
> As I can remember, @mikesherov wanted to do something about it.

Yeah, i remember something like that, although no one responded when i repeatedly ask about this, hence the ticket

**Comment by mrjoelkemp** [comment]
Looks good and manageable. Nice work, Oleg.

Who will implement the validation using this? I can help port some rules
once the validator is in master.

We just have to make sure no rule currently overrides this.values in its
configure. If none do, the validator can just check for the existence of
values on a rule and run the validator then configure, or just run
configure. Hence, the validator can be shipped quickly without being used.

**Comment by markelog** [comment]
> Who will implement the validation using this?

Whoever is capable and have time to do this :-), after 1.10 my next item is jquery tasks, there is a lot them accumulated out there.

> We just have to make sure no rule currently overrides this.values

`configure` method usually set only private properties (style which @mdevils set long time ago, nice going btw :-) i.e. with "_" prefix, so we should be good there.

> Hence, the validator can be shipped quickly without being used.

That is my thought exactly.

**Comment by mikesherov** [comment]
I think I still have an open issue about this somewhere...

My thoughts were to make rule values declarative rather than having functions. This would also make documentation auto generate able.

**Comment by zxqfox** [comment]
We can try to use here https://github.com/molnarg/js-schema/ or analogue. But it's 24Kb. Probably we can find more lighten solution.

**Comment by hzoo** [comment]
Came across
- https://github.com/arasatasaygin/is.js
- https://github.com/philbooth/check-types.js
- https://facebook.github.io/react/docs/reusable-components.html#prop-validation - maybe even React.propTypes?

**Comment by hzoo** [comment]
Some ideas on a declarative format:

```js
values: [
    // true,
    // number,
    // string
    // one of the strings in an array
    // object with properties 'beforeOpeningRoundBrace' and 'beforeOpeningCurlyBrace' which are both true
];

values: [{
    type: "boolean",
    value: true
}, {
    type: "number" // maybe no value?
}, {
    type: "string"
}, {
    type: "string",
    value: ['a', 'b', 'c']
}, {
    type: "object",
    value: [ // not sure how this would work
        { 
            type: "string",
            value: "beforeOpeningCurlyBrace"
        },
        { 
            type: "string",
            value: "beforeOpeningRoundBrace"
        },
    ]
}, ];

// use constructor functions?
values: [
    true,
    Number,
    ['a', 'b', 'c'],
    {
        beforeOpeningCurlyBrace: [String] 
        beforeOpeningRoundBrace: [String] 
    }
];

// react type (namespaces to represent things)
values: [
    Types.true,
    Types.number,
    Types.oneOf(['a', 'b', 'c']),
    Types.object({
        beforeOpeningCurlyBrace: Types.arrayOf(Types.String)
        beforeOpeningRoundBrace: Types.arrayOf(Types.String)
    })
];
```

I like the 2nd one if something like that is possible.

**Comment by zxqfox** [comment]
Nice stuff. Thanks! ;-)

About 2nd one: https://github.com/molnarg/js-schema/ — 25Kb, can be used in browser. Is it fine for us?

**Comment by hzoo** [comment]
Looks like ESLint has an issue about notifying on config options using a declarative approach too! There's also https://github.com/mafintosh/is-my-json-valid and https://github.com/hapijs/joi.

**Comment by hzoo** [comment]
Do we know if we're going to use another tool to validate or make our own?

**Comment by mrjoelkemp** [comment]
Looking to use one of the suggested tools. The proposed schema would change
to fit the tool. Experimenting with the options for now.

**Comment by markelog** [comment]
What options do we have on the table?

**Comment by mrjoelkemp** [comment]
I've been looking at the ones suggested in this thread mostly. @hzoo's suggestion of https://github.com/mafintosh/is-my-json-valid feels like the best one so far. I'm in the middle of a prototype with it, so no guarantees that it'll work just yet.

**Comment by hzoo** [comment]
Yeah that's the one ESLint is planning on using as well - https://github.com/eslint/eslint/pull/2179
