### ISSUE TITLE
move esprima parsing to inside JsFile and out of StringChecker

### ISSUE THREAD

**Issue by mikesherov** [jscs-dev/node-jscs#901]
the `tree` variable is created in string checker by parsing the `str` variable. The `str` and `tree` variables are then passed to the `JsFile` constuctor. The tree is not used anywhere else.

We should just parse in the constructor of JsFile given the `str`. This will also help us avoid having to do `esprima.parse` directly in tests.

I don't think this need to move to 2.0 I don't imagine anyone is really using JsFile directly. Thoughts?

**Comment by hzoo** [comment]
This probably isn't as relevant anymore - especially after the cst changes right?

**Comment by hzoo** [comment]
Ok closing

**Comment by mdevils** [comment]
I have a prototype in `v3` where it was implemented, so feel free to close.
