### ISSUE TITLE
Ability to control the options passed to esprima.

### ISSUE THREAD

**Issue by cvrebert** [jscs-dev/node-jscs#903]
Esprima (at least for ES6) has a `tolerant` parser option that allows it to parse not-strictly-spec-compliant syntax. This is useful in some cases. For example, I only use ES6 in a transpiled-to-ES5 context, and ES6 only allows `import`s at the top level of a module, but the transpiler (6to5) doesn't have that restriction (because CommonJS's `require` has no such restriction). Allowing such imports makes conditional imports and imports with fallbacks if the module is unavailable, possible.
Thus, I'm requesting that JSCS add an option that controls Esprima's `tolerant` flag, so that JSCS can style check such ES6 code instead of immediately dying with a parsing error like it currently does.
(See also https://code.google.com/p/esprima/issues/detail?id=619)

**Comment by mikesherov** [comment]
Changed the title because people have asked to control other options as well.

**Comment by markelog** [comment]
> Changed the title because people have asked to control other options as well.

Is there related issues?

**Comment by mikesherov** [comment]
@markelog, yes, https://github.com/jscs-dev/node-jscs/issues/865 wants the ability to pass options when using Espree which has tons of options, each one enabling certain parts of es6 grammar.
