### ISSUE TITLE
Rule: require spaces in between for statement

### ISSUE THREAD

**Issue by gero3** [jscs-dev/node-jscs#912]
Requires spaces in between for statement.
 
  Type: `Boolean`
 
  Values: `true` to requires spaces in between for statement.
 
  #### Example
 
  ```js
  "requireSpacesInForStatement": true
  ```
 
  ##### Valid
 
  ```js
  for(var i = 0; i<l; i++) {
      x++;
  }
  ```
 
  ##### Invalid
 
  ```js
  for(var i = 0;i<l;i++) {
      x++;
  }
  ```
 
  ```js
  for(var i = 0; i<l;i++) {
      x++;
  }
  ```
 
  ```js
  for(var i = 0;i<l; i++) {
      x++;
  }
  ```

**Comment by dimafeldman** [comment]
Seems like this statement breaks it:

``` JavaScript
for (var i = 0; (!reachEnd && (i < elementsToMove)); i++) {
```

**Comment by hzoo** [comment]
Yeah it does - `for (var i = 0; !reachEnd && i < elementsToMove; i++) {`works though

**Comment by dimafeldman** [comment]
Thanks,
opened an issue: https://github.com/jscs-dev/node-jscs/issues/1332
