### ISSUE TITLE
Forbid usage of object

### ISSUE THREAD

**Issue by janbaer** [jscs-dev/node-jscs#918]
Is there a rule with that we can forbid the usage of some specific functions or objects like *console.log* ?

**Comment by alawatthe** [comment]
I think such a rule belongs more to a tool like eslint or jshint. jscs is about the format of the code.

If you are only concerned about *console*, there is a [rule in eslint](http://eslint.org/docs/rules/no-console.html) addressing your needs.

**Comment by mikesherov** [comment]
@janbaer thanks for contributing. @alawatthe is exactly correct, as JSCS is only concerned with style, and this is better suited for either JSHint or ESLint. Thanks again!

**Comment by janbaer** [comment]
Thanks for the answer. We're using currently jshint but it's not really extendable with custom rules. So we decide to use additionally **jscs** to have more flexibility with code checks in a semantic way and with formatting. There is a rule that can check for forbidden keywords like **debugger** in the production code . Why not extend the **jscs** to check also the usage of some functions. The **console** was just an example. Before some weeks I used the jasmine function **ddescribe** to just run a specific test. But I forgot to change it back to **describe**. So for some days our **ci** just executed one test. With a check with **jscs** for example in this wouldn't happen.

**Comment by alawatthe** [comment]
So I gave this a second thought. I think a rule like
```js
disallowVariableNames: ['temp', 'foo', 'bar', 'baz', 'asdf']
```
could make sense, as this is a stylistic choice about the code.
@janbaer This should fit your use case, too.

I am just not a too big fan of a rule like
```js
disallowUseOfObject: ['console']
```
Since it is impossible to completely prohibit the use of an object through static analysis.

@mikesherov should we reopen this issue?

**Comment by mrjoelkemp** [comment]
Duplicate of #41
