### ISSUE TITLE
Report which rule exactly fails

### ISSUE THREAD

**Issue by creynders** [jscs-dev/node-jscs#919]
Though some failure messages are quite clear, sometimes it's pretty hard to know what rule is failing, it would be a HUGE help if the reporter would prefix the failure message with the failing rule, e.g.:

```sh
Illegal space before "function" keyword at index.js :
```

I have no idea which rule disallows a space before "function" keywords, since there's a number of potential rules that apply (if you're pretty new to jscs) Is this due to some specific "function" rule? Or due to a "require space" rule? Or? (After some experimenting I found it's due to `disallowSpaceBeforeKeywords: true`)

It would be a lot easier if the reporter would dump:

```
disallowSpaceBeforeKeywords: Illegal space before "function" keyword at index.js :
```

This is especially useful, when you're still configuring jscs.

**Comment by mikesherov** [comment]
@creynders thanks for contributing! Yes, that's the `verbose` option, which will be the default in 2.0.

Thanks again!

**Comment by am11** [comment]
@mikesherov, in tslint, the object passed to the custom formatter has a `getRuleName()` (see their [verbose formatter example](https://github.com/palantir/tslint/blob/master/src/formatters/verboseFormatter.ts)). Would it be possible to have something similar in object passed to node-jscs custom reporter? This way we (the downstreamers) would be able to emit which rule has been violated.

Related: https://github.com/madskristensen/WebEssentials2013/issues/1717.

**Comment by mikesherov** [comment]
@am11, if I'm not mistaken, the error object already contains the rule name, which is passed to the custom reporter.

**Comment by creynders** [comment]
:facepalm: ah the `--verbose` flag, of course... 😊

**Comment by am11** [comment]
@mikesherov, thanks alot! Its being a while I am out of sync with node-jscs and web-essentials project (been busy with node-sass and other things).

I tried to debug it via web-essentials and apparently [out script](https://github.com/madskristensen/WebEssentials2013/blob/master/EditorExtensions/Resources/server/services/srv-jscs.js) is broken. My fork's master was 299 commits behind the current master. Seems like a lot has changed, which is exciting! :)

I changed [this](https://github.com/madskristensen/WebEssentials2013/blob/master/EditorExtensions/Resources/server/services/srv-jscs.js#L2) to `var jscs = require("jscs"),` and apparently vow ([here](https://github.com/madskristensen/WebEssentials2013/blob/master/EditorExtensions/Resources/server/services/srv-jscs.js#L63)) is terminating the script (and try-catch is not helping either). Will dig deeper. Any quick pointers would be much appreciated. :)
