### ISSUE TITLE
Rules for spaces inside various parens

### ISSUE THREAD

**Issue by jzaefferer** [jscs-dev/node-jscs#92]
In the [jQuery JavaScript style guide](http://contribute.jquery.org/style-guide/js/), whitespace is added inside various parens, round and square. A few samples:

```js
array = [ a, b ];
foo( options, object[ property ] );
```

For function calls, there are exceptions to this rule:

```js
// Function with a callback, object, or array as the sole argument:
// No space on either side of the argument
foo({
    a: "alpha",
    b: "beta"
});
 
// Function with a callback, object, or array as the first argument:
// No space before the first argument
foo(function() {
    // Do stuff
}, options );
 
// Function with a callback, object, or array as the last argument:
// No space after after the last argument
foo( data, function() {
    // Do stuff
});
```

I have no idea how much effort it is to write rules for this. Before I look into that, I'd like to hear from someone if this is reasonable and would be merged. Maybe some hints on how to implement it?

**Comment by mikesherov** [comment]
The saga of this issue has now been resolved by simplifying the jQuery style guide. I'm going to close this issue and file another one just for adding existing rules to the jQuery style guide.
