### ISSUE TITLE
requireDotNotation breaks for non-latin variable name

### ISSUE THREAD

**Issue by alawatthe** [jscs-dev/node-jscs#920]
Example (copy to the [demo](http://jscs.info/demo.html), jQuery preset)
```
obj["π"] = 1;
obj["test"] = 2;
```
The requireDotNotation error is only reported for the last line, but should also be reported for the first.

Reason for the bug is in
https://github.com/jscs-dev/node-jscs/blob/master/lib/utils.js#L66

The RegExp
```
/^[a-zA-Z_$][a-zA-Z0-9_$]*$/;
```
is not describing all possible JavaScript identifiers see [section 7.6 in the ES5 spec](http://es5.github.io/#x7.6).

**Comment by mathiasbynens** [comment]
Might be useful:
https://mathiasbynens.be/notes/javascript-properties
https://mathiasbynens.be/notes/javascript-identifiers
https://gist.github.com/mathiasbynens/6334847
