### ISSUE TITLE
JSCS package size has grown significantly since 1.9.0

### ISSUE THREAD

**Issue by akshayp** [jscs-dev/node-jscs#921]
unicode-6.3.0 was added as part of https://github.com/jscs-dev/node-jscs/pull/847 which is a massive dependency. With 1.8.1 the package was about `7.3Mb` but the newer versions are `127.1Mb`. Is it possible to use a more modular version that only pulls in the category L regexes?

**Comment by mikesherov** [comment]
@akshayp thanks for contributing! We'll look into this soon.

**Comment by mrjoelkemp** [comment]
Looking into it. cc @efolio and @alawatthe.

**Comment by mathiasbynens** [comment]
Quoting @alawatthe in <https://github.com/mathiasbynens/node-unicode-data/issues/14#issuecomment-69985628>:

> Is there any plan right now of publishing the categories (especially the different letter categories) as independent node modules?
>
>The problem of the unicode-data being to big came up in [issue #921](https://github.com/jscs-dev/node-jscs/issues/921) for jscs. It increased the size of jscs by a factor of 18...

For the use case in jscs, unicode-6.3.0 should be a `devDependency`. The regular expression for identifiers should be generated at build time (just once) and saved to a file. [Check out how Esprima handles it.](https://github.com/ariya/esprima/blob/master/tools/generate-identifier-regex.js)

(Btw, you may want to update to unicode-7.0.0.)

**Comment by alawatthe** [comment]
Thanks for your answer Mathias.
I basically used the esprima way when I wrote the code for the first time, but I somehow missed that the unicode-data should be a ```devDependency``` an not a ```dependency```. My bad :-/

This is also probably the reason, why we had the performance problems with regenerate in https://github.com/jscs-dev/node-jscs/pull/861.

I'll write some code for this later.

**Comment by mathiasbynens** [comment]
Awesome, thank you @alawatthe!

**Comment by markelog** [comment]
I'm planning to release 1.10 in couple hours, "127.1Mb" doesn't sit right with me, wouldn't even thought it would grow that much.

I'm gonna yank fix for #847 and wait for more intelligent approach. 

@mathiasbynens could you verify @alawatthe patch when it will come?

**Comment by markelog** [comment]
btw @mathiasbynens 

> For the use case in jscs, unicode-6.3.0 should really be a devDependency, not a dependency. The regular expression for identifiers should be generated at build time (just once) and saved to a file that is part of the npm-published tarball.

Would be cool for you to point this out in the docs, it seems as most popular use-case, when now i see only `npm install unicode-6.3.0 --save` there

**Comment by mikesherov** [comment]
> I'm gonna yank fix for #847 and wait for more intelligent approach.

This seems like the best approach. We'll add back in 1.10.1 :-)

**Comment by mathiasbynens** [comment]
@markelog 

> Would be cool for you to point this out in the docs, it seems as most popular use-case, when now i see only `npm install unicode-6.3.0 --save` there

Fair enough, I’ve changed `--save` to `--save-dev` and added another warning there. Thanks!

FWIW, this particular section was already in the docs, just below: https://github.com/mathiasbynens/unicode-7.0.0#regular-expressions

**Comment by mathiasbynens** [comment]
> @mathiasbynens could you verify @alawatthe patch when it will come?

Of course!

**Comment by mathiasbynens** [comment]
This is what I had in mind: #924.
