### ISSUE TITLE
requireSpacesInsideArrayBrackets erroring on object access with

### ISSUE THREAD

**Issue by tivac** [jscs-dev/node-jscs#923]
```js
// Super-contrived example
var a = { b : 1 },
    b = "b";
    
a[b] = 2;
```

In `jscs@1.10.0` on windows when `requireSpacesInsideArrayBrackets` is set to `"all"` this causes two errors.

```
Missing space after opening bracket at lib/jscs.js :
     2 |    b = "b";
     3 |
     4 |a[b] = 2;
----------^
     5 |
     6 |

Missing space before closing bracket at lib/jscs.js :
     2 |    b = "b";
     3 |
     4 |a[b] = 2;
-----------^
     5 |
     6 |
```

But this isn't an array, so why is a rule about array brackets catching it?

If this is a legit bug I'd be happy to send a PR w/ a failing test.

**Comment by tivac** [comment]
My .jscsrc file, in case it helps narrowing it down. Important to note: The bug repros with only the one rule applied though.

```json
{
    "disallowEmptyBlocks" : true,
    "disallowKeywordsOnNewLine" : [ "else" ],
    "disallowKeywords" : [ "with", "eval" ],
    "disallowMixedSpacesAndTabs" : true,
    "disallowMultipleLineBreaks" : true,
    "disallowMultipleLineStrings" : true,
    "disallowNewlineBeforeBlockStatements" : true,
    "disallowOperatorBeforeLineBreak" : [ "+", "." ],
    "disallowQuotedKeysInObjects" : "allButReserved",
    "disallowSpaceAfterKeywords" : [ "if", "for", "while", "do", "switch", "catch" ],
    "disallowSpaceAfterPrefixUnaryOperators" : true,
    "disallowSpaceBeforePostfixUnaryOperators" : true,
    "disallowSpacesInCallExpression" : true,
    "disallowSpacesInsideParentheses" : true,
    "disallowTrailingComma" : true,
    "disallowYodaConditions" : true,
    "requireBlocksOnNewline" : true,
    "requireCamelCaseOrUpperCaseIdentifiers" : true,
    "requireCapitalizedConstructors" : true,
    "requireCommaBeforeLineBreak" : true,
    "requireCurlyBraces" : true,
    "requireDotNotation" : true,
    "requireLineBreakAfterVariableAssignment" : true,
    "requireLineFeedAtFileEnd" : true,
    "requireMultipleVarDecl" : true,
    "requireOperatorBeforeLineBreak" : [ "?", "=", "+", "-", "/", "*", "==", "===", "!=", "!==", ">", ">=", "<", "<=", "\"" ],
    "requirePaddingNewlinesBeforeKeywords" : [ "do", "for", "if", "switch", "case", "try", "while", "return" ],
    "requirePaddingNewLinesInObjects" : true,
    "requireParenthesesAroundIIFE" : true,
    "requireSpaceAfterBinaryOperators" : true,
    "requireSpaceAfterLineComment" : true,
    "requireSpaceAfterObjectKeys" : true,
    "requireSpaceBeforeBinaryOperators" : true,
    "requireSpaceBeforeKeywords" : [ "else", "while", "catch" ],
    "requireSpaceBeforeObjectValues" : true,
    "requireSpaceBetweenArguments" : true,
    "requireSpacesInAnonymousFunctionExpression" : { "beforeOpeningCurlyBrace" : true },
    "requireSpacesInConditionalExpression" : true,
    "requireSpacesInForStatement" : true,
    "requireSpacesInFunction" : { "beforeOpeningCurlyBrace" : true },
    "requireSpacesInFunctionExpression" : { "beforeOpeningCurlyBrace" : true },
    "requireSpacesInsideArrayBrackets" : "all",
    "requireSpacesInsideObjectBrackets" : "all",
    "safeContextKeyword" : [ "self" ],
    "validateIndentation" : 4,
    "validateLineBreaks" : "LF",
    "validateParameterSeparator" : ", ",
    "validateQuoteMarks" : "\"",
    
    
    "excludeFiles": [
        "node_modules/**",
        "coverage/**"
    ],

    "additionalRules": []
}
```

**Comment by markelog** [comment]
That was intentional, `ArrayBrackets` reference to square brackets, probably need to rename this rule.

@mikesherov, @mdevils am i wrong here?

**Comment by zxqfox** [comment]
Didn't we decided to use `bracket` notation for `[]`, `brace` for `()` and `curly` for `{}` ?

**Comment by markelog** [comment]
No, see - http://en.wikipedia.org/wiki/Bracket

**Comment by zxqfox** [comment]
Oh right, thanks. So `brace` for `{}` and `parens` for `()`.

**Comment by mikesherov** [comment]
You're right, @markelog in terms of it being intentional.

But did the rule only deal with arrays before? If so, we likely need to revert it and introduce requireSpacesInBrackets.

**Comment by markelog** [comment]
Yes, but this rule previously would catch only array declarations through literals.

For this:
```js
x = [ 1 ]
x[0]
```

didn't catch it, rule that would distinguish object and array accessors would be hard to do and i think it pretty much weird, if someone would need one but not the either. 

It seems name part `ArrayBracket` was just specifying the type of bracket not implying it could be used with arrays only.

Besides, objects with brackets accessor context are commonly referred as "associated arrays", for example - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Property_Accessors

**Comment by mikesherov** [comment]
@markelog, that makes sense. Perhaps we should then add a duplicated rule that drops the `array` part of the name, and remove/mark-as-deprecated the docs for the one with array in the name?

**Comment by tivac** [comment]
I would never consider using brackets to access object properties as being "array brackets" (clearly, because I filed a bug on it). You could think of an object as an associative array, but it isn't an array, and those brackets aren't array brackets.

If this behavior is intentional I hope the rule gets renamed.

**Comment by zxqfox** [comment]
Feels like 
```
    "requireSpacesInsideArrayBrackets" : "all",
    "requireSpacesInsideObjectBrackets" : "all",
```
are not about property accessors. Can we make a different rule for `x[y]` ?

**Comment by noseglid** [comment]
+1.

I'd really want to be able (e.g. enforce) my code like this:

```javascript
var a = [ 1 ];
console.log(a[0]);
```

**Comment by ilkkao** [comment]
My app build started to fail because this today. My config is like @zxqfox comment and code like @noseglid comment, :+1: for separating rules.

**Comment by mikesherov** [comment]
Just to be clear here. You want to separate array definition spacing from array or object access spacing, right?

Because we can possibly do that, but we can't distinguish array access from object access.

**Comment by noseglid** [comment]
Yes, exactly as you described it. No need to distinguish between different subscripts (array or object).

**Comment by markelog** [comment]
Sounds like we should add new rule(s) and revert recent changes for `requireSpacesInsideArrayBrackets`.

I wouldn't want to do this until 1.11 (although we can, according to our semver policy), since this rule used in couple of presets and current behaviour seems as more preferred one.

**Comment by noseglid** [comment]
One could argue that 1.10 broke compatibility  since it's now enforcing something it did not previously. (e.g. `a[0]`). It's not a huge issue though. I've temporarily disabled this rule in my projects so commits may or may not follow the convention now. I'll just clean them up once the rule is available.

**Comment by mikesherov** [comment]
@markelog, let's revert for 1.10.1 and then reintroduce the brackets rule under the new "array-less" name in 1.11.0?

**Comment by markelog** [comment]
These changes has fixed three issues and introduced new values, which with this tactic, should be re-implemented, that would be a pain, current behaviour, as i can judge, is needed for 7 presets. 

Whereas this issue is presented only for custom made configs. 
Whereas it's a matter of opinion if these cases should be catched or not.

Because of these reasons, it's easy and more subtle to revert in 1.11, this version could be released right after https://github.com/jscs-dev/node-jscs/issues/797, which, i hope, shouldn't take that long.

/cc @mrjoelkemp

**Comment by mikesherov** [comment]
@markelog, just so we're clear. In 1.11 you're going to do what exactly?

By revert, you mean return this rule to what it was doing (1.9) and introduce a new rule that does the current (1.10) behavior?

**Comment by markelog** [comment]
> By revert, you mean return this rule to what it was doing (1.9)

Yep

> and introduce a new rule that does the current (1.10) behavior?

Yep and, in the presets, replace old rules with new ones. Although if we will not re-implemented newly added options that might be considered as feature regression, so i'd need to check how hard it is.

**Comment by mikesherov** [comment]
> Although if we will not re-implemented newly added options that might be considered as feature regression, so i'd need to check how hard it is.

Do whatever is easiest here :-).

**Comment by gonsfx** [comment]
+1 for rules to enforce spaces here
```javascript
var a = [ 0 ];
```

while disallowing them here
```javascript
console.log(a[0]);
```

**Comment by joshcarr** [comment]
+1 for rules to enforce spaces here
```javascript
var a = [ 0 ];
```
while disallowing them here
```javascript
console.log(a[0]);
```

**Comment by markelog** [comment]
> +1

https://twitter.com/rwaldron/status/557629305552134145 ... just kidding :-), although it was already stated that we would do our best to bring this back in the next version, unless you wanna help?

**Comment by mikesherov** [comment]
Locking this issue to prevent more "me toos!" As @markelog mentioned, the best way to see this work done is to submit a PR at this point!
