### ISSUE TITLE
Add Rule disallowConditionalExpression

### ISSUE THREAD

**Issue by micnic** [jscs-dev/node-jscs#925]
I really hate `a ? b : c`, would it be possible to add a rule to disallow conditional expression?

**Comment by mocheng** [comment]
+1

It would be better to customize it.
`a ? b : c` sometimes is OK. But, nested conditional expression is hard to read. e.g. ` a ? b : c ? d : e`

**Comment by mikesherov** [comment]
@micnic, thanks for contributing! It's pretty easy to add this rule if it's a simple disallow, but then we'll start get requests to only disallow nested, etc.

It'd be fairly easy to write your own custom rule for this until we see more demand for this feature, btw.

**Comment by micnic** [comment]
@mikesherov , I'll try to come up with a PR later (if none does it  earlier) with an custom configuration for this rule, I just started using jscs, and I like it, have to check how to add new rules and set their configuration.

**Comment by GerHobbelt** [comment]
There are two different uses for `?:`: as a conditional *statement*, e.g.

```
cond1 ? a() : b();
cond2 ? y = 1 : y = f(x);
```

and as a conditional *expression*, e.g.

```
x = cond1 ? a() : b();
y = cond2 ? 1 : f(x);
if (cond3 ? a() : b()) { c(); }
```

(Note the different ways `y` is assigned a value conditionally in both examples.)

If possible, I'ld like to disallow the use as conditional *statement*, while any use as conditional (right hand) *expression* is fine with me. I don't know if the JSCS parser is smart enough to identify both uses, but if it is... ;-)

**Comment by zxqfox** [comment]
> I don't know if the JSCS parser is smart enough to identify both uses, but if it is... ;-)

Yep. It's pretty easy to do for your samples ;-) We need more cases!

**Comment by hzoo** [comment]
You should be able to use http://jscs.info/rule/disallowNodeTypes.html with `ConditionalExpression` for this.

Unless we want a separate rule for this I think we can close?

**Comment by hzoo** [comment]
Going to close this in favor of using `"disallowNodeTypes": ["ConditionalExpression"]`. If someone wants to make a new rule/PR we can open again.

**Comment by GerHobbelt** [comment]
Hm, sorry to be a party pooper but upon closer inspection of Esprima again, that one doesn't see the difference between the two use cases I listed above: it only has the `ConditionalExpression` token, not any `ConditionalStatement` token, so the check whether its use case 1 or 2 requires some more logic to inspect the Esprima output AST.

Anyway, not a high priority for me right now as I don't into use case 1 very often but it would be nice when we get the ability to weed those out.

**Comment by hzoo** [comment]
Oh I see. That specific case is pretty different.

There could be another rule for that - I guess you can just check if the `node.parent.type === 'ExpressionStatement'` and iterating over all `ConditionalExpression`. People are always free to implement it themselves (as their own separate rule or a PR).

**Comment by GerHobbelt** [comment]
Good enough for me right now. Let's keep this one closed and when I feel
the need that last bit should be enough hint to arrive at a working
solution then. Right now I have to pick my battles and this one is not top
priority today.

Thanks for the idea.

**Comment by hzoo** [comment]
Some more help would be looking at the AST for the different types of snippets you want to test for (although you may need to look for more - and unit tests can help with that). You can paste it into http://astexplorer.net/

```js
a ? 1 : 0

var a = a ? 1 : 0
```

**Comment by GerHobbelt** [comment]
Super! Didn't know about astexplorer.net: very nice :-)

For future reference, the `?:` constructs I inspected there:

```
var x = 1;

var y = x ? 1 : 2;

y = x ? 3 : 4;

x ? log() : print();

var z = x ? log() : print();

if (x ? checkA() : checkB()) {
  z = 5;
}

(x ? log : print)();
```

where the 4th and 7th line are undesirable (my preferred styleguide), while
the others are more or less okay -- RL code situations like these often are
way more complicated so it's hard to draw a clear and obvious line there.
Lines 4 is always a no-good in my book, while line 7 is *very* frowned upon
(I can see the appeal to write something like that at some point). The
other lines are good to average pass. Nothing a machine can decide to fail
with certainty.

Anyway, astexplorer.net shows that I'ld need to check the parent of the
`ConditionalExpression` node to catch these: if the *immediate parent* is
either an `ExpressionStatement` (line 4) or a `CallExpression` (line 7)
then the custom check should trigger a reject report.

---

A bit of googling to see where I'ld have to go next leads to these:

- https://github.com/jscs-dev/node-jscs/wiki/Plugin-API
- https://github.com/jscs-dev/jscs-jsdoc

after hitting
https://github.com/jscs-dev/node-jscs/issues/321

When I work on this I'll have to check (no pun intended ;-) ) if the
`.check(node)` plugin API method is fed AST nodes like that -- I assume it
is, but haven't dug into the code there yet.



Met vriendelijke groeten / Best regards,

Ger Hobbelt

--------------------------------------------------
web:    http://www.hobbelt.com/
        http://www.hebbut.net/
mail:   ger@hobbelt.com
mobile: +31-6-11 120 978
--------------------------------------------------
