### ISSUE TITLE
Add rule maxParameterNumber

### ISSUE THREAD

**Issue by mocheng** [jscs-dev/node-jscs#926]
Based on current jscs infrastructure, is it possible to detect function declared parameter number?

If possible, we can add one rule to limit too-many-parameter issue.

**Comment by mikesherov** [comment]
This is the maxParams rule is JSHint and is not a "style" thing but rather a program correctness and best practice thing, which we decided a long time ago not to pursue. Closing for now,but thanks again for the suggestion!

**Comment by alawatthe** [comment]
There are rules in jshint and eslint for this:
http://eslint.org/docs/rules/max-params.html
http://jshint.com/docs/options/#maxparams

**Comment by mocheng** [comment]
@mikesherov  @alawatthe  thanks for your direction.
