### ISSUE TITLE
Change in behavior for requireSpaceBeforeBlockStatements

### ISSUE THREAD

**Issue by jaswilli** [jscs-dev/node-jscs#927]
After #904 this rule now errors if there are multiple spaces before the block statement's opening curly brace:

`.jscsrc`:
```
{
  "requireSpaceBeforeBlockStatements": true
}
```

Test case:
```
if (true)  {
  console.log('hi');
}
```

Output:
```
Missing space before opening curly brace for block expressions at test.js :
     1 |if (true)  {
-----------------^
     2 |  console.log('hi');
     3 |}


1 code style error found.
```

**Comment by mikesherov** [comment]
Thanks for contributing! This behavior is intended. It allows a single space, or many spaces if the curly is on a different line.

Are you just reporting that the behavior changed, or did you actually want to have the 2 spaces there? If so, I don't think we'll be adding an option for that any time soon if ever.

**Comment by jaswilli** [comment]
Hi @mikesherov,

No, being notified that there are multiple spaces is actually a good thing :smile:.  My only issue is that the rule that's doing it is `requireSpaceBeforeBlockStatements`, which reads as though "space" is required, not "one and only one space."

Anyway, that confusion aside, I have no real complain as the change in behavior works for my case.  I just raised the issue in case it was not intended or desired.

**Comment by zxqfox** [comment]
I'm not sure if we need ability to enforce 2 or more spaces here. That's strange. But anyway it's pretty easy to implement.

@jaswilli Does you need 2 or more spaces? or just any count more than zero?

**Comment by jaswilli** [comment]
@zxqfox 

I don't need two spaces.  I was just surprised after upgrading that this rule produced an error on multiple spaces.

I agree that it's probably an extreme edge case to want two or more spaces before an opening block.  I just raised this issue in case the change in behavior was accidental and not desired--personally, I'm perfectly happy to have JSCS throw an error in this case.

**Comment by jaswilli** [comment]
> Probably we should fix an error message here.

Yeah, that was the source of confusion.  I saw the error about missing a space, glanced at the code snippet and thought, "Wait, there is a space... oh, it's not missing a space, it has multiple spaces."

**Comment by zxqfox** [comment]
@jaswilli Yeah, we definitely should fix a message. Thanks again!

**Comment by mikesherov** [comment]
@zxqfox, can you whip up a patch for the error message?

**Comment by zxqfox** [comment]
@mikesherov Done ;-)

**Comment by hawkrives** [comment]
Is there a way we could have a rule for requiring at *least* one space, instead of enforcing *exactly* one?

My case: I'm using multiple spaces to line up function bodies.

```js
changeName(studentId, ...args)          { this._change(studentId, 'changeName',          ...args) },
changeCreditsNeeded(studentId, ...args) { this._change(studentId, 'changeCreditsNeeded', ...args) }
```

**Comment by mikesherov** [comment]
@hawkrives file a new bug for that please! /cc @mdevils we need to think about assertion framework allowing 0, 1, >0.

**Comment by zxqfox** [comment]
@mikesherov Just about >0. For now there are 2 methods: `whitespaceBetween` and `noWhitespaceBetween`.

**Comment by hawkrives** [comment]
@mikesherov thanks, filed #936.
