### ISSUE TITLE
Throw error when esnext found in JSCS config file

### ISSUE THREAD

**Issue by cvrebert** [jscs-dev/node-jscs#932]
So, it turns out that putting `"esnext": true` in `.jscsrc` unfortunately does nothing; that option has to be specified at a higher level (e.g. Grunt). Given that, perhaps an error could be thrown when `esnext` is found in the config file, explicitly stating that it cannot be set via the config file? Makes it easier for the user to discover their mistake.

**Comment by markelog** [comment]
It does nothing? http://jscs.info/overview.html#esnext

/cc @mikesherov

**Comment by mikesherov** [comment]
@cvrebert, what version of JSCS are you using? Specifying in jscsrc should work...

What happens when you have `esnext` in your `.jscsrc` and run `jscs` from the command line and not via the grunt plugin?

**Comment by cvrebert** [comment]
Looks like I was on crack when filing this, as I couldn't repro when trying to put together a nice testcase. My apologies for the trouble!
