### ISSUE TITLE
maximumLineLength not applies for generator function

### ISSUE THREAD

**Issue by tunnckoCore** [jscs-dev/node-jscs#934]
I catch this problem in my middleware [koa-better-body/index.js#L117](https://github.com/tunnckoCore/koa-better-body/blob/master/index.js#L117)
Line 117 is 81-82 chars long, my jscs config is 80, but its not throw error.

```bash
jshint index.js && jscs index.js --esnext
```

**Comment by alawatthe** [comment]
By my count, the line is 80 characters long. So everything is fine I guess...?

**Comment by tunnckoCore** [comment]
Hmmm. Interesting. SublimeText3 shows 81 - mm yea cursor is on 81st column, lol

Sorry, lol, my fault. I guess too much vacantion. :D
