### ISSUE TITLE
Allow requireSpaceBeforeBlockStatements to say "at least 1 space"

### ISSUE THREAD

**Issue by hawkrives** [jscs-dev/node-jscs#936]
v0.11.0 changed `requireSpaceBeforeBlockStatements` to throw an error if you have more than one space before the opening brace. Before 0.11, it would only throw if you had zero spaces.

Could you add a rule for requiring *at least* one space, instead of enforcing *exactly* one?

(Essentially, I'd like some way of opting in to what the rule used to do.)

My use-case: I'm using multiple spaces to line up function bodies.

```js
changeName(studentId, ...args)          { this._change(studentId, 'changeName',          ...args) },
changeCreditsNeeded(studentId, ...args) { this._change(studentId, 'changeCreditsNeeded', ...args) }
```

**Comment by hzoo** [comment]
looks like another use-case is if there is a comment (rare) in between

```js
function asdf() /* comment */ {
```

The single space option for all these kinds of rules should be opt-in right? Since we updated the rule, which would throw more errors. Although for this rule it's rare to want more than 1 space..

**Comment by mikesherov** [comment]
@hzoo this has really nothing to do with comments between and more to do with alignment, like:

```
function asdf() { something(); }
function as()    { something(); }
````

**Comment by hzoo** [comment]
This would be a simple change now: `exactly: 1` to `atLeast: 1`?

**Comment by mikesherov** [comment]
Correct.

**Comment by micky2be** [comment]
Arg, I need that fix :(

**Comment by zappan** [comment]
+1
