### ISSUE TITLE
How to disable disallowSpacesInFunctionExpression

### ISSUE THREAD

**Issue by Nolski** [jscs-dev/node-jscs#946]
Hi,

I am using jscs and I want to disable `disallowSpacesInFunctionExpression` which is being used by my preset. The issue is I can't set any of it's children properties to false and I can't set it an empty object. If I set it to null nothing seems to change.

**Comment by hzoo** [comment]
Do you also need to require spaces? You should be able to just null it.

```
{
  "preset": "airbnb",
  "disallowSpacesInFunctionExpression": null
}
```
or
```
{
  "preset": "airbnb",
  "disallowSpacesInFunctionExpression": null,
  "requireSpacesInFunctionExpression": {
    "beforeOpeningRoundBrace": true
  }
}
```

**Comment by Nolski** [comment]
Ah, my mistake. I was a bit confused about the null property disabling a rule and having to explicitly set the `require` or `disallow` value depending if you want a specific rule or not.
