### ISSUE TITLE
`export default` breaks disallowSpacesInsideParentheses

### ISSUE THREAD

**Issue by elidupuis** [jscs-dev/node-jscs#947]
I have `disallowSpacesInsideParentheses` set to true and I'm getting this error:

```
Illegal space after opening round bracket at filename.js :
     6 |export default function startApp(attrs) {
-----------------------------------------^
```

I've even remove all other rules to confirm there wasn't anything conflicting. Thoughts?

**Comment by elidupuis** [comment]
Upon further inspection, this *is* only the case when `esnext: true`.

**Comment by zxqfox** [comment]
@elidupuis Definitely it is only about esnext. Feels like there are a lot of bugs in es6 parsing logic. ;-(

**Comment by ozten** [comment]
this is `export default` specifically. Removing default "fixes" the bug (but will break your single function module).

Minimal test case:

    export default function() {

    }

    $ jscs --esnext -c js/.jscsrc js/foo.js
    Illegal space after opening round bracket at js/foo.js :
     1 |export default function() {
       --------------------------------^
     2 |
     3 |}

    1 code style error found.

**Comment by mikesherov** [comment]
I have a patch https://github.com/jscs-dev/node-jscs/pull/990 but also files bug with esprima: https://code.google.com/p/esprima/issues/detail?id=631
