### ISSUE TITLE
Allow non-top-level ES6 `import` declarations

### ISSUE THREAD

**Issue by cvrebert** [jscs-dev/node-jscs#952]
See #903 for rationale. #944 makes it possible to use Esprima-harmony's `tolerant` mode which allows such `import`s to parse, but it does still report them as an error. However, this error is very specific and thus amenable to being specifically ignored.
JSCS ought to ignore this particular "error" since it's a semantic/correctness issue rather than a stylistic issue.

**Comment by markelog** [comment]
Allowing `import` to be everywhere sounds like side-effect of transpiling, otherwise it seems weird for ES6 to forbid it but for transpiler to allow it. 

Why is that? Could you provide links to relevant topics?

**Comment by cvrebert** [comment]
Well, yes, the transpiler can be permissive like this because the CJS module system (and probably UMD too) don't impose any such constraint, and those are what it uses when transpiling to ES5.

**Comment by mikesherov** [comment]
Thanks again!

**Comment by cvrebert** [comment]
Thanks! I look forward to re-enabling the next release of JSCS on my ES6 project :smile:
