### ISSUE TITLE
Ability to import external .jscsrc

### ISSUE THREAD

**Issue by phanect** [jscs-dev/node-jscs#955]
In my corporate project, I'm trying to separate lint files including .jscsrc (.jscs.json) to another repository: https://github.com/growaspeople/coding-standards/tree/master/javascript
In the project repository, I want to put .jscsrc/.jscs.json under project root and load configuration from above `coding-standards` repository.

```javascript
{
	"import": "https://github.com/growaspeople/coding-standards/blob/master/javascript/.jscs.json",
	"excludeFiles": ["db/**", "log/**"] // Configuration only applied for the project
}
```

Hopefully I want to set URL to `import` path, not only local path, but even it only supports local path, it is still useful. (I install `coding-standards` repository as npm module and refer .jshintrc in node_modules dir for JSHint, which already support include function.)

JSCS already supports `additionalRules` option, but it doesn't accept .jscsrc.

**Comment by zxqfox** [comment]
You can try to use `plugins` + `preset` for that purpose.

You would need to make some `index.js` with registering your corporate preset, and then just load it with `plugins`.

See also plugins API: https://github.com/jscs-dev/node-jscs/wiki/Plugin-API
And example: https://github.com/zxqfox/jscs-bem

**Comment by mikesherov** [comment]
Also note that we'll eventually have `excludeFiles` available via `.jscsignore` so that you'll be able to specify excludes separately. At that point, there's no need for an `import` directive.

I don't see us implementing this in the future so I'm going to close this for now. Feel free to respond and disagree.

**Comment by markelog** [comment]
And if https://github.com/jscs-dev/node-jscs/issues/109 will goes through, it would be even simpler to share your presets.

**Comment by phanect** [comment]
Thanks. I will try creating plugin.

However, it is a little bit tough to create a plugin. If import is implemented, it is much easier to separate .jscsrc to another repo.

**Comment by markelog** [comment]
@phanect our thoughts exactly, but i as mentioned, #109 might resolve "too hard" problem, allowing you to do what you ask but with `preset` property.

**Comment by phanect** [comment]
@markelog Oh, sorry, I misunderstood discussion in #109.
OK, then this issue is duplicate of #109.
