### ISSUE TITLE
jscs violates the Rule of Silence

### ISSUE THREAD

**Issue by feross** [jscs-dev/node-jscs#962]
When `jscs` finds no errors it prints:

```bash
No code style errors found.
```

This violates the Rule of Silence:

> The rule of silence, also referred to as the silence is golden rule, is an important part of the Unix philosophy that states that when a program has nothing surprising, interesting or useful to say, it should say nothing. It means that well-behaved programs should treat their users' attention and concentration as being valuable and thus perform their tasks as unobtrusively as possible. That is, silence in itself is a virtue. (http://www.linfo.org/rule_of_silence.html)

What would you say to a PR that made `jscs` silent by default?

**Comment by markelog** [comment]
Yeah!
