### ISSUE TITLE
Switch indentation bug with "disallowSemicolons"

### ISSUE THREAD

**Issue by feross** [jscs-dev/node-jscs#964]
With this config:

```json
{
  "disallowSemicolons": true,
  "validateIndentation": 2
}
```

And this correct code:

```js
function a (x) {
  switch (x) {
    case 1:
      return 1
    default:
      return 2
  }
}
```

The following errors are produced:

```
t.js:5:6: Expected indentation of 6 characters
t.js:6:8: Expected indentation of 8 characters
t.js:7:6: Expected indentation of 6 characters
```

This is a bug.

**Comment by mikesherov** [comment]
Can you try this on master? I'm having trouble reproing and I landed a bunch of fixes last week. Thanks!

**Comment by feross** [comment]
Just confirmed the issue exists on master.

**Comment by feross** [comment]
```bash
$ cat code
function a (x) {
  switch (x) {
    case 1:
      return 1
    default:
      return 2
  }
}
cat config
{
  "disallowSemicolons": true,
  "validateIndentation": 2
}
./bin/jscs code --config config
Expected indentation of 6 characters at code :
     3 |    case 1:
     4 |      return 1
     5 |    default:
--------------^
     6 |      return 2
     7 |  }

Expected indentation of 8 characters at code :
     4 |      return 1
     5 |    default:
     6 |      return 2
----------------^
     7 |  }
     8 |}

Expected indentation of 6 characters at code :
     5 |    default:
     6 |      return 2
     7 |  }
--------------^
     8 |}
     9 |


3 code style errors found.
```

**Comment by mikesherov** [comment]
And if you use semicolons? Still busted?

**Comment by feross** [comment]
With semicolons there are no errors found.

**Comment by mikesherov** [comment]
Thanks! This fix needs to get merged into the master Esprima: https://github.com/jquery/esprima/pull/272/files#diff-7c9336e4324ea31118ce749be055b6a3R2221

**Comment by feross** [comment]
@mikesherov Wow, that commit was merged 6 months ago but it hasn't landed in a stable version of esprima yet. I just left a comment asking when it will be merged. https://github.com/jquery/esprima/pull/272#issuecomment-71915861

**Comment by mikesherov** [comment]
This has been merged to master, so the next release of Esprima, which should be soon, will have it, and JSCS will have it right after that.

**Comment by feross** [comment]
Excellent!
