### ISSUE TITLE
Parsing Error with async/await

### ISSUE THREAD

**Issue by pjako** [jscs-dev/node-jscs#969]
jscs parser does not understand code like this:
```javascript
async function foo() {
return 0;
}
await foo;
```
It results in a parsing error for both.

**Comment by mikesherov** [comment]
@pjako thanks for contributing! `async` and `await` aren't even in ES6! JSCS uses Esprima for parsing, so if you can find a fork of esprima or perhaps espree that parses async and await, JSCS will work with it. For now though, I'm going to close this as there's nothing inside of JSCS to do to fix this.
