### ISSUE TITLE
Document how to explicitly disable rules

### ISSUE THREAD

**Issue by cowwoc** [jscs-dev/node-jscs#971]
Following up on https://github.com/jscs-dev/node-jscs/issues/287, please add a paragraph to the top of http://jscs.info/rules.html mentioning that we can disable rules by either omitting them from the configuration, or setting their value to null.

I am particularly interested in the latter (specifying a `null` value) because I want to be able to differentiate between new rules that get added over time versus rules I've already reviewed and decided to disable.

**Comment by hzoo** [comment]
There is a small note about it in http://jscs.info/overview.html#preset but maybe it should be added to rule s as well?

**Comment by mikesherov** [comment]
Yes, add it to error suppression as well.
