### ISSUE TITLE
Cannot read property 'value' of undefined in requireSpaceBetweenArguments rule

### ISSUE THREAD

**Issue by cowwoc** [jscs-dev/node-jscs#973]
Setting `requireSpaceBetweenArguments: true` triggers the following runtime failure:

```
TypeError: Cannot read property 'value' of undefined
    at C:\Users\Gili\Documents\gulp-jscs\node_modules\jscs\lib\rules\require-space-between-arguments.js:58:36
    at Array.forEach (native)
    at C:\Users\Gili\Documents\gulp-jscs\node_modules\jscs\lib\rules\require-space-between-arguments.js:54:28
    at Array.forEach (native)
    at Object.JsFile.iterateNodesByType (C:\Users\Gili\Documents\gulp-jscs\node_modules\jscs\lib\js-file.js:364:42)
    at Object.module.exports.check (C:\Users\Gili\Documents\gulp-jscs\node_modules\jscs\lib\rules\require-space-between-arguments.js:52:14)
    at null.<anonymous> (C:\Users\Gili\Documents\gulp-jscs\node_modules\jscs\lib\string-checker.js:157:22)
    at Array.forEach (native)
    at StringChecker.checkString (C:\Users\Gili\Documents\gulp-jscs\node_modules\jscs\lib\string-checker.js:155:35)
    at DestroyableTransform.through.obj.emit.gutil.PluginError.showStack [as _transform] (C:\Users\Gili\Documents\gulp-jscs\index.js:53:34)
```

**Comment by zxqfox** [comment]
/cc @markelog 

https://github.com/jscs-dev/node-jscs/blob/master/lib%2Frules%2Frequire-space-between-arguments.js#L56

**Comment by markelog** [comment]
@cowwoc would you mind posting the code that triggers this?

**Comment by cowwoc** [comment]
@markelog Due to the beauty of gulp streams (sarcasm) I have no idea which file is responsible for triggering this error. I will investigate and get back to you.

**Comment by zxqfox** [comment]
@cowwoc You can try to run jscs manually with your config to separate paths deeper and deeper until error happens on concrete file.

**Comment by cowwoc** [comment]
@markelog Out of curiosity, is there a way for jscs to wrap exceptions thrown by rules and add the path that triggered the problem? This seems like something we should have anyway...

**Comment by markelog** [comment]
Yeah, it might be a good idea, although it rarely happens

**Comment by cowwoc** [comment]
Here is the offending file: https://gist.github.com/cowwoc/fabfd4bff45c677362ed

**Comment by mikesherov** [comment]
@cowwoc can you reduce that at all? I can't repro this using master.

**Comment by mikesherov** [comment]
@cowwoc ping

**Comment by cowwoc** [comment]
@mikesherov Sorry about that. I have not forgotten. My codebase is not in a good place (it no longer builds). As soon as I get this straightened out I'll try to produce a minimal testcase for you. Feel free to ping me again if you don't hear from me within a week.

**Comment by cowwoc** [comment]
I can no longer reproduce this problem. Closing for now.
