### ISSUE TITLE
require new line after var declaration, var assignation

### ISSUE THREAD

**Issue by bjrmatos** [jscs-dev/node-jscs#974]
How to make this?

Valid:

```js
var some;

awesomeMethod();

// or 

var some = 1;

awesomeMethod();
```

Invalid:

```js
var some;
awesomeMethod();

// or

var some = 1;
awesomeMethod();
```

**Comment by mikesherov** [comment]
This doesn't exist yet, but would be called `requirePaddingNewLinesAfterVariableDeclarations`

**Comment by mikesherov** [comment]
Thanks for contributing the suggestion @bjrmatos

**Comment by bjrmatos** [comment]
Awesome!! Thanks for your feedback.

**Comment by mchandleraz** [comment]
Is this not the same result as require-padding-newline-after-variable-declaration ?

**Comment by hzoo** [comment]
Seems like http://jscs.info/rule/requirePaddingNewLineAfterVariableDeclaration covers it although maybe there should be some more examples
