### ISSUE TITLE
google preset shouldn't have disallowMultipleVarDecl

### ISSUE THREAD

**Issue by dbrinegar** [jscs-dev/node-jscs#984]
I was surprised to see this warning when checking out jscs, and don't think it should be part of the google preset although hey I could be wrong.

reasons:

1. gjslint does not check for this condition and is happy with multiple var decl
2. Google style guide doesn't seem to have a rule on this one way or the other
3. angular.js source has multiple var decls everywhere

Suggest removing the disallowMultipleVarDecl config line to make this preset more permissive.  Happy to learn why not, as well.

**Comment by zxqfox** [comment]
You can see that there is [.jscs.json in angular.js repo](https://github.com/angular/angular.js/blob/master/.jscs.json) and it doesn't use google preset.

cc @hzoo 

Agreed that [google styleguide](https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml#var) doesn't tell us how many `var`s we should use in a scope. It just tell us to use it.

It was added in https://github.com/jscs-dev/node-jscs/commit/ce6c5593c0d0c76b5d5d07f5b5f6315294c6536e

cc @mrjoelkemp

**Comment by markelog** [comment]
Code styles, usually, are not as precise are jscs rules, so more often then not, preset rules are based on code examples:

http://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml#eval__
http://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml#Array_and_Object_literals

It seems we're in line here.

**Comment by zxqfox** [comment]
These code examples uses multiple `var`s to declare variables. Isn't it? It's more like we need `requireMultipleVarDecl: true` in google preset.

**Comment by markelog** [comment]
No, see the docs for those rules and feel free to create a ticket for their rename.

Also don't forget to add labels for the issues.

**Comment by zxqfox** [comment]
Omg, this happens again!

**Comment by markelog** [comment]
@dbrinegar are satisfied with explanation?

**Comment by dbrinegar** [comment]
Sure understood that this is an interpretation of the guide.  While the style guide examples have places that do use one var per decl, I don't think they are documenting that as a requirement.  You can do that, or you can string them together, there's no point of view in the style guide or the body of code following this style guide as far as I can see.  Lots of instances both ways.

Real issue: I was hoping preset=google to be something like a gjslint replacement, but on comparing a few of the gjslint test cases it looks like the gap is pretty wide.  Maybe a note in the docs "this is our interpretation of the style guide and not meant to be compatible with gjslint"  would clarify that for others.

**Comment by zxqfox** [comment]
> While the style guide examples have places that do use one var per decl

Are you sure about that? I didn't find a place with that.

**Comment by dbrinegar** [comment]
@zxqfox click the expander arrow buttons to see the code samples.  I think they wrote the examples this way because it was more succinct.  Using one var per decl is obviously allowed, my point is that it isn't a rule to use it only this way.

**Comment by zxqfox** [comment]
@dbrinegar I see a lot of code like this.

![image](https://cloud.githubusercontent.com/assets/677518/5994515/4905c10e-aa88-11e4-9c7c-aadaf3067b69.png)

Just to be clear. Am I right that you talking about allowing this in google preset?
```
var one,
    two = 2,
    three;
```

I'm not against removing this rule from preset but attached examples tells us to declarate variables separately so we should think twice before doing it.

**Comment by mrjoelkemp** [comment]
As a heavy user of this preset and due to no clear standard, I'd like to keep it in and folks can override/nullify the rule if they choose. 

This is also the first request to remove the rule from the preset. Given that the google preset is out second most popular preset (according to github traffic), let's keep things as is to see if this issue comes up again.

**Comment by mrjoelkemp** [comment]
Thanks for contributing @dbrinegar. Nullifying the rule should solve your problem.

**Comment by markelog** [comment]
> Maybe a note in the docs "this is our interpretation of the style guide and not meant to be compatible with gjslint"

Maybe it is other way around? Maybe we just better then gjslint? :-) 

I'm kidding of course, but do think its one sided opinion, jscs have a lot of rules, therefore has more features, maybe gjslint devs just didn't had a chance to implement such check?

**Comment by markelog** [comment]
@cramforce could help us out here?

**Comment by cramforce** [comment]
In Google code reviews var a, b, c; is typically not very appreciated :)

I personally consider gjslint as more of a recommendation since it tends to have false positives.

**Comment by dbrinegar** [comment]
Cool, thanks @cramforce for the clarification.

So while gjslint is stricter in some ways, jscs preset=google is stricter in other ways, such as multi var decl.  Got it!

**Comment by rubennorte** [comment]
Sorry guys for bringing this up again, but I think you should reconsider the usage of `disallowMultipleVarDecl` in this case. When we choose the Google code style we write code that fits the rules that are specified in its official documentation. For all other undocumented cases it's assumed that we can freely choose the way we want to solve them (being consistent in the project scope). If the "google" preset doesn't take this into account people may think the linter isn't working the way it should. Also, people who have been a long time adhering to the guide may be frustrated about it telling their code is wrong.

If you think Google style guide is too ambiguous about some things, you better create a new style guide called "google-strict" or similar. IMO applying arbitrary rules on top of the guide is a mistake and I think the "google" preset should adhere only to the official documentation.

Thanks for considering.

**Comment by hzoo** [comment]
You can always just add to your `.jscsrc` file (if you didn't already do that) since everyone has their own changes to make if the preset doesn't change or won't change soon.
```js
{
	"preset": "google",
	"disallowMultipleVarDecl": null
}
```

**Comment by rubennorte** [comment]
Thanks @hzoo, I know that but that's not the point. The point is: why should I overwrite a rule that is not in the style guide of the preset I'm using? Who and why said the google style guide doesn't allow multiple var declarations when in fact they are present in the official documentation?

**Comment by hzoo** [comment]
Oh ok different issue (more of a practical thing). I don't seem to see any multiple var dec in the style guide - https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml right? It is true it doesn't mention it but I don't see var a, b, c

**Comment by rubennorte** [comment]
Yeah, that's it and now I can't find any either... I'd swear I saw examples in there, but it must have been a long day for me, sorry.
