### ISSUE TITLE
Add option to enforce variable declaration at the top of declaring scope

### ISSUE THREAD

**Issue by Druotic** [jscs-dev/node-jscs#99]
In short, the option would require that all variable declarations be made at the top of their declaring scope -- where a JS interpreter would "hoist" them.  

Previously, I had proposed this idea and implemented it for JSHint, but JSHint is moving away from styling entirely in V3.0, so it was not accepted.  Unlike JSHint, JSCS seems like the perfect place for this sort of feature!

Rather than duplicating the detailed explanation/examples, see the issue jshint/jshint#1263 and pull request jshint/jshint#1283 for additional info and previous discussions.

This will be my first contribution to jscs, so it might take me a bit to port it over.  Hopefully it won't be very different/difficult.

**Comment by markelog** [comment]
This issue has been open more than a month without supported PR for it. 

Unfortunately, we don't have the resources to implement rules that could not be included in any of the supported [presets](https://github.com/jscs-dev/node-jscs/tree/master/presets) (if it could be, please point that out).

However, if you or anybody else submit PR for it, we will gladly consider it.

**Comment by Krinkle** [comment]
@markelog This would be a rule to enable in the wikimedia preset. We currently enforce this rule by convention only. Would be great to have it be enforced by JSCS.

**Comment by ava-dylang** [comment]
:+1: To quote my colleges "How is this not supported yet". I guess people who write multiple var declarations don't overlap that much with people who like to use linters, or write linters anyway. Anyways glad I found *something, anything* on this topic.

**Comment by oredi** [comment]
Any preference for the rule name, I will try to take a look into this.
If anyone has any idea about an existing rule that can act as a start it will be a time saver.
Or else I would dig into the existing rules for implementation.

**Comment by oredi** [comment]
Think I found the requireMultipleVarDecl that might be applicable for this. I am thinking about names like requireVarDeclAtTop with the only option value of true unless someone else has better suggestions.

**Comment by mrjoelkemp** [comment]
requireVarDeclFirst sounds closer to the rule's logic.

**Comment by markelog** [comment]
Check this out - https://github.com/jscs-dev/node-jscs/issues/807

**Comment by oredi** [comment]
@mrjoelkemp  and @markelog  Thanks I will use that and and look into that sample implementation.
