### ISSUE TITLE
Add jscs-jsdoc and cover the core with comments

### ISSUE THREAD

**Issue by zxqfox** [jscs-dev/node-jscs#994]
Ref https://github.com/jscs-dev/node-jscs/pull/908#discussion_r24061948

**Comment by zxqfox** [comment]
Houston, `jscs-jsdoc` has a `peerDependency` of `jscs` itself. Should I make a symlink in `node_modules`? Is there a more elegant solution?

**Comment by mrjoelkemp** [comment]
Not sure, honestly. @sindresorhus might know.

**Comment by sindresorhus** [comment]
Don't use `peerDependencies`. They're to be deprecated.

**Comment by zxqfox** [comment]
@sindresorhus Yes sir! ;-( But what to use for plugins? (Please don't tell me that "plugins are deprecated" ;-)

**Comment by zxqfox** [comment]
https://docs.npmjs.com/cli/dedupe ? Not sure that it's a right way to do it.

**Comment by sindresorhus** [comment]
I don't know what the officially recommended solution is, just that `peerDependencies` is not the solution to anything. Dedupe is a good candidate. npm 3.0, which I think is shipping in the near time, is going to dedupe by default on install, which will make deduping a lot more useful.

**Comment by zxqfox** [comment]
@sindresorhus Great news everyone! Thanks, it can really help with plugins. Looks like a real solution.

**Comment by markelog** [comment]
So what's with this one?

**Comment by zxqfox** [comment]
Looking for a time to get it done. ;-(
