### ISSUE TITLE
JSDoc rest params

### ISSUE THREAD

**Issue by Shuhrat** [jscs-dev/node-jscs#998]
Sorry, if I duplicated existing issue. I didn't search.
It seems to be jscs does not know anything about rest parameters
```
@param {...number}
```
Just copy-pasted from http://usejsdoc.org/tags-param.html
```js
/**
 * Returns the sum of all numbers passed to the function.
 * @param {...number} num - A positive or negative number.
 */
function sum(num) {
    var i = 0, n = arguments.length, t = 0;
    for (; i < n; i++) {
        t += arguments[i];
    }
    return t;
}
```

**Comment by mikesherov** [comment]
@Shuhrat, thanks for contributing! The validateJSDoc rule is no longer supported. We suggest you check out the ecellrnt jscs-jsdoc plugin, and file bugs there if it's still an issue. Thanks again!

**Comment by zxqfox** [comment]
@Shuhrat Just fyi: this case already handled correctly by plugin. Thanks!
